### ISSUE TITLE
Merge lexical entries, merge suggestions error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#1104]
Users report errors when attempting to merge lexical entries and get merge suggestions in https://lingvodoc.ispras.ru/dictionary/7476/2/perspective/8015/2/edit:
![image](https://github.com/ispras/lingvodoc-react/assets/2802467/8963a274-64bf-48d2-ac99-3e544c1699be)
![image](https://github.com/ispras/lingvodoc-react/assets/2802467/19c3f10c-3fa7-4d43-9852-1e902ca10e3e)

Looks like the problem is at the https://github.com/ispras/lingvodoc/blob/heavy_refactor/lingvodoc/views/v2/merge.py#L528, when we are checking perspective permissions via requesting the refactored out route 'perspective_roles'.

We should rewrite permission check function `check_user_merge_permissions()` to use better more modern ACL mechanisms, e.g. by using `acl_check_if()` method of the request context (see query.py) or by using direct ACL check via `acl_check_direct()` from acl.py.

**Comment by vmonakhov** [comment]
Solved using direct ACL check via check_direct() from acl.py.
