### ISSUE TITLE
Select another language - Menu is not updated.

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#116]
1. Open http://lingvodoc.ispras.ru/ 
Result: English is a default language
2. In main menu click Languages(English) and from the appeared menu select Russian.
![image](https://user-images.githubusercontent.com/59951991/72502970-ac248a80-384b-11ea-8ea6-a8a1b6c4f7b4.png)
Expected: Menu is updated (all menus are in Russian)
Actual: Menu is still in English
Workaround: Reload the page (e.g. by pressing F5)

**Comment by jandrew44** [comment]
General problem with translations refresh when language is being changed has been fixed already.
However, there are still several issues with top level sub menus.

The following translatable strings exists but does not have the corresponding gists:
1) Import Dialeqt dictionary
2) Storage
3) Organizations

Also in the gist "User account activation / deactivation" spaces should be removed around '/'.
It should be "User account activation/deactivation".

**Comment by nadezhday** [comment]
We have a separate defect for User account activation/deactivation localization.
https://github.com/ispras/lingvodoc-react/issues/496
The rest menus are translated.
Closing.

**Comment by vmonakhov** [comment]
Covered in selenium tests
