### ISSUE TITLE
Dialogs and menus localization

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#120]
Open http://lingvodoc.ispras.ru/map_search
Switch between English and Russian languages and verify menus and dialogs.
Problem: We have problem with localization of dialogs and menus.

Within this issue we need to fix the following:
1) Top Menu and its submenus
Expected: all menus and submenus (Maps, Dashboard etc) should have correct localization
Actual: It is a mix of English and Russian words
![image](https://user-images.githubusercontent.com/59951991/72528616-9085a800-387c-11ea-95f3-eca4476dfbe8.png)

2) Maps->Search
![image](https://user-images.githubusercontent.com/59951991/72529031-78625880-387d-11ea-95bd-16cb6834d665.png)
![image](https://user-images.githubusercontent.com/59951991/72529128-ac3d7e00-387d-11ea-8d80-efd5b0f37ff9.png)

3) Dashboard->Create corpus
![image](https://user-images.githubusercontent.com/59951991/72529303-15bd8c80-387e-11ea-88d3-f46a421b2105.png)

4) Dashboard->dictionaries
![image](https://user-images.githubusercontent.com/59951991/72529432-6208cc80-387e-11ea-9365-9e138764c033.png)

5) Open initial page
![image](https://user-images.githubusercontent.com/59951991/72529529-8b295d00-387e-11ea-9107-0a99ad21a73e.png)

6) Lexical view
![image](https://user-images.githubusercontent.com/59951991/72529652-c7f55400-387e-11ea-9049-d3c9525543e9.png)

**Comment by al-indigo** [comment]
@jandrew44 check please this too; it's almost the same as #116

**Comment by jandrew44** [comment]
1) Described in the separate issue #116 
2) Looks like a lot of stuff were not localized on the search page.
@al-indigo do you know if Tomsk team is working on the search page now?
I can do the localization but merge conflicts are possible in this case.
3) Some localization should be added here.
However I noticed that sometimes the word 'corpus' is used for 'корпус' and sometimes it is 'corpora'.
I think one alternative should be used everywhere.
@al-indigo what is the best one?
4) Fix on frontend side is required
5) Fix on frontend side is required
6) Fix on frontend side is required

**Comment by nataliauvarova** [comment]
Localization for  "User account activation/deactivation" will be done in the task: https://github.com/ispras/lingvodoc-react/issues/496
other Fixed.

**Comment by nadezhday** [comment]
Looks excellent.

**Comment by vmonakhov** [comment]
Covered in tests/test_localization.py
