### ISSUE TITLE
Highlighting disappears in a couple of seconds

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#121]
1) Open http://lingvodoc.ispras.ru/
2) In select language type: Čerköq
3) Enter 
Result:
(a) language is found and it is highlighting.
![image](https://user-images.githubusercontent.com/59951991/72530645-d6446f80-3880-11ea-8748-f4c5087687db.png)
(b) in a second or two highlighing disappears.
![image](https://user-images.githubusercontent.com/59951991/72530721-0724a480-3881-11ea-8180-3d4d917c3ace.png)

It would be nice to leave the highlighting. Usability problem.

**Comment by al-indigo** [comment]
In this case that was the desired behaviour (the prototype for this feature had eternal highlighting and users asked to drop it)

**Comment by nadezhday** [comment]
OK. We can close this issue.
