### ISSUE TITLE
Context commands are not visible in the end of page

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#123]
-Open http://lingvodoc.ispras.ru/
-In select language type: Ket
-Enter
-click on View to expand context menu

Expected: context menu is visible
![image](https://user-images.githubusercontent.com/59951991/72532175-f9245300-3883-11ea-85ba-a5afdcf3096f.png)

Actual: context menu is partly visible:
![image](https://user-images.githubusercontent.com/59951991/72532048-bb272f00-3883-11ea-9c71-4a9d820e23f8.png)

Workaround: you need to use mouse scroll to get full context commands.

**Comment by al-indigo** [comment]
@jandrew44 look at it please. If needed, ask @alexlag for help; I just don't understand the way to fix it

**Comment by jandrew44** [comment]
It is semantic-ui-react issue that was fixed in version 0.81.1.
However upgrading to this version may introduce some regressions.
At least I noticed changes in position of modal dialogs(no more centered).

**Comment by jandrew44** [comment]
semantic-ui-react has been upgraded to the latest version, it has fixed the issue.
In order to do it I had to upgrade react to the version 16.3.
UI regression testing is required.

**Comment by nadezhday** [comment]
The problem with context command is fixed.

**Comment by vmonakhov** [comment]
Covered with tests/test_db_dictionaries_all.py
