### ISSUE TITLE
Unauthorized users can see any tools for editing table entries 

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#124]
-Open lingvodoc
-Search for: Ket
-click View->Lexical view
-Activate Publish column
Expected: The user is unauthorized. He should not see any options/checkboxes/buttons [Add/Delete/Edit etc]
Actual: Checkboxes, [Add+, Edit, Delete] buttons are present on the page. 
![image](https://user-images.githubusercontent.com/59951991/72589136-63340b00-390b-11ea-9b9c-087616a2ed78.png)
-Activate Edit column
Problem: edit/delete/[+] buttons are available for unauthorized user.
![image](https://user-images.githubusercontent.com/59951991/72589355-113fb500-390c-11ea-840c-c7fb020a9755.png)

**Comment by al-indigo** [comment]
Yes, that bothered us *A LOT*. Andrew was the only one who hasn't tried to fix it yet; look through it please

**Comment by jandrew44** [comment]
Well, the fix seems to be easy.
I guess unauthorized user is not supposed to see the 'Edit', 'Publish' and 'Merge suggestions' menu items, right?
For read-only purposes 'View' and 'View published' should be used.
So it is enough to hide it for unauthorized user.
Not sure about menu items in the 'Tools' menu, are there any options that should be available for authorized users only?
@al-indigo FYI

**Comment by myrix** [comment]
Re: 'Tools', TLDR: everything should be available for unauthorized.

In 'Tools' everything except 'Cognate suggestions' and 'Cognate multi-language suggestions' is read-only, just as 'View' and 'View published'.

In suggestions some parts are read-only, some would be not, so it still should be visible for unauthorized, non-read-only parts I would hide when interface for suggestions acceptance would be finished.

**Comment by jandrew44** [comment]
'Edit' and 'Publish' items are not available for unauthorized users anymore.

**Comment by nadezhday** [comment]
Verified.

**Comment by nadezhday** [comment]
covered in selenium tests

**Comment by nadezhday** [comment]
Additional issue is created; https://github.com/ispras/lingvodoc-react/issues/181 

Lexical Entries roles and properties commands should be unavailable for unauthorized users.
