### ISSUE TITLE
Add, Remove, Merge buttons should be inactive/hidden for unathorized users

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#126]
-Open lingvodoc
-Do not login
Open http://lingvodoc.ispras.ru/dictionary/2639/4263/perspective/2639/4267/edit
Check several entries (by clicking on checkboxes)
Expected: 
1) These checkboxes should not be available for unathorized users.
2) Add/Remove/Merge lexical entries buttons should be hidden or inactive.
Actual:
Unathorized users can select table entries and click Add/Remove/Merge lexical entries buttons.
![image](https://user-images.githubusercontent.com/59951991/72591856-50710480-3912-11ea-88df-33c6f5bf6788.png)

**Comment by jandrew44** [comment]
Fixed indirectly by the fix for the issue #124.
'Edit' menu item is not available for unauthorized users anymore.

**Comment by nadezhday** [comment]
Verified.

**Comment by nadezhday** [comment]
Covered in selenium tests
