### ISSUE TITLE
Table header and buttons should be available on the top after scrolling 

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#127]
-Open http://lingvodoc.ispras.ru/dictionary/2639/4263/perspective/2639/4267/edit
Result:
Header of the table/ buttons are visible - OK
![image](https://user-images.githubusercontent.com/59951991/72592646-0be66880-3914-11ea-8ac1-9551426a9b7c.png)

-Scroll down the page.
Expected: Header of the table/ buttons should be visible.
Actual: 
![image](https://user-images.githubusercontent.com/59951991/72592734-451ed880-3914-11ea-8412-e0a3f4d85cb3.png)

**Comment by al-indigo** [comment]
good idea, just forgot about it

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Header is not visible after scrolling. NOK

Reopening.

![image](https://user-images.githubusercontent.com/59951991/143188555-e0235f3b-87d6-48a9-aae0-a7f8b8b602e3.png)

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Verified

**Comment by vmonakhov** [comment]
Covered in tests/test_dictionaries.py
