### ISSUE TITLE
Use Go back while dialog is opened ->Table is not updated

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#129]
-Open http://lingvodoc.ispras.ru/dictionary/284/4/perspective/284/5/view
-click View contributions
Result: table shows 2 empty entries.
![image](https://user-images.githubusercontent.com/59951991/72608140-1d8b3880-3933-11ea-8dab-de4d4b27595a.png)

-Open a dialog (e.g. click Lexical Entries-> Lexical Entries roles)
![image](https://user-images.githubusercontent.com/59951991/72608390-9e4a3480-3933-11ea-8dcb-ec3865a7bc31.png)

-click Go Back (user wants to close this dialog, he cannot see Close button and presses Go Back)

Problem: As you can see from the screenshot another column of the table is selected:
 
![image](https://user-images.githubusercontent.com/59951991/72608546-f7b26380-3933-11ea-94c4-82c19f3c5c0e.png)

-close  Lexical Entries roles

Problem: The table has View published column selected. It is not updated (it shows 2 empty entries - data for View contributions column)
![image](https://user-images.githubusercontent.com/59951991/72608787-9212a700-3934-11ea-9b0b-048bf135a866.png)

Workaround: you need to click View published header in order to see the correct data.

**Comment by al-indigo** [comment]
needs investigation; really don't even have a clue why this may happen

**Comment by jandrew44** [comment]
It is not a bug.
Modal dialogs does not block browser controls.
So it is still possible for user to press the 'back' button and it will work.
In this case "View published" was the previous page in the history.

**Comment by jandrew44** [comment]
Works as designed.

**Comment by nadezhday** [comment]
Verified. Nothing to test. WAD.
