### ISSUE TITLE
Implement possibility to close Tasks right panel without clicking Tasks menu

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#130]
- open http://lingvodoc.ispras.ru
- click Tasks menu
![image](https://user-images.githubusercontent.com/59951991/72610394-4661fc80-3938-11ea-86d4-5319b4d49667.png)

-just imagine you have forgotten that you clicked Task menu to open Tasks panel.
Problem: the only way to close this Tasks panel is to click Tasks menu. 
It would be nice to implement extra functionality for closing this panel (e.g. [x] or [>>]).

**Comment by jandrew44** [comment]
'>>' icon has been added to the sidebar.

**Comment by nadezhday** [comment]
Verified. Works fine.

**Comment by nadezhday** [comment]
Covered in automatic selenium tests.
