### ISSUE TITLE
Add Build version information

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#132]
It would be nice to have build number information.
Can we implement Info-> Version command or something?

**Comment by al-indigo** [comment]
yes, that's great idea. Maybe it should be displayed in the footer? @myrix what do you think?

**Comment by myrix** [comment]
Maybe footer at the main page, and from menu Info -> Version page / modal dialog?

If include this info, then what exactly?

Latest commit date for frontend and backend?

We don't have any up-to-date version info in tags, `git tag` for backend:

```
0.81
1.0
2.0-alpha
v2.0
v2.1
v2.1.1
```

`git-tag` for frontend gives a long list of automatic untagged release tags:

```
untagged-028d645c91abd8332b6f
untagged-02a17a29c6f632ee2c05
...
```

**Comment by myrix** [comment]
Based on discussion we should have following version info:

For frontend, build datetime, build number, commit identifier and commit datetime.

For backend, commit identifier and commit datetime.

**Comment by myrix** [comment]
Version info can be seen in Info -> Version menu:
![image](https://user-images.githubusercontent.com/2802467/79680596-0867c380-821a-11ea-864f-6a0c945f3cc6.png)

For backend version info contains latest Git version tag and commit info, including commit datetime.

For frontend version info contains Git version tag and commit info, Travis build number, Travis build branch and build configuration type (server / proxy / desktop).

**Comment by nadezhday** [comment]
verified.

**Comment by nadezhday** [comment]
Version submenu is covered in selenium test
