### ISSUE TITLE
Syntax error in the message

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#136]
- open http://lingvodoc.ispras.ru/map_search
- click Search button

Problem: Search finds 370 resuls.
Correct the word: resul**t**s
![image](https://user-images.githubusercontent.com/59951991/72614338-1704bd00-3943-11ea-9913-27ebff497516.png)

**Comment by jandrew44** [comment]
Fixed.

**Comment by nadezhday** [comment]
Verified. Selenium test is updated.
