### ISSUE TITLE
Crash: TypeError: "a is undefined"

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#137]
Major problem.

- open test-lingvodoc
- sign in 
- select UserName->Requests
Problem: Crash. Menu disapeared.

Console data:
TypeError: "a is undefined"
    T Requests.js:39
    React 10
    forceRenderChildren react-apollo.browser.umd.js:529
    e react-apollo.browser.umd.js:504
    d Observable.js:126
    h Observable.js:161
    value Observable.js:215
    next ObservableQuery.js:328
    next ObservableQuery.js:328
    queryListenerForObserver QueryManager.js:419
    broadcastQueries QueryManager.js:710
    broadcastQueries QueryManager.js:709
    broadcastQueries QueryManager.js:704
    next QueryManager.js:761
    d Observable.js:126
    h Observable.js:161
    value Observable.js:215
    next dedupLink.js:60
    next dedupLink.js:60
    d Observable.js:126
    h Observable.js:161
    value Observable.js:215
    next index.js:37
    d Observable.js:126
    h Observable.js:161
    value Observable.js:215
    l index.js:91

**Comment by al-indigo** [comment]
need investigation

**Comment by jandrew44** [comment]
I could not reproduce it.

**Comment by nadezhday** [comment]
I cannot reproduce it any more. Closing.
Covered in selenium tests.
