### ISSUE TITLE
Move Browser... functionality on the top of the page

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#138]
- open test-lingvodoc
- sign in 
- select UserName->My files
Problem: 
Browse... button is located on the bottom of the page. 
![image](https://user-images.githubusercontent.com/59951991/72618698-b67a7d80-394c-11ea-81eb-86b5850de883.png)
We need to move "Browse... file selection" on the top of the page, so user will see this functionality.
![image](https://user-images.githubusercontent.com/59951991/72618874-27ba3080-394d-11ea-8bf7-998240dfb21e.png)

**Comment by jandrew44** [comment]
Done.
Also I have made the 'Upload' button more noticeable and enabled when some file is selected only.

**Comment by nadezhday** [comment]
Verified. 
Browse on the top, Upload is available after selecting a file.

**Comment by nadezhday** [comment]
Covered  in selenium test
