### ISSUE TITLE
Implement search on the top of My files table to improve usability

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#139]
-Open lingvodoc
-sign in
-User->My files
Result: the table with files.
It would be nice to implement search functionality (search filed on the top) on My files page.

**Comment by jandrew44** [comment]
Search field has been added.

**Comment by nadezhday** [comment]
Verification:
Search works fine (Name column).

**Comment by nadezhday** [comment]
Covered in selenium test.
