### ISSUE TITLE
Exception. Sign In does not work after My files + Sign Out  

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#140]
-Open test-Lingvodoc
-sign In
- User->My files
-Sign Out
-Sign In
Expected: User can login.
Actual: Dialog Please sign in is still opened and "in process" decoralor is visible. This process never ends.
![image](https://user-images.githubusercontent.com/59951991/72701915-fc5c5f00-3b61-11ea-8227-11233e6fd62d.png)

Console reports the following error:
uncaught at c at c 
 at r 
 at a 
 at i 
 e@http://83.149.198.62/assets/vendor.fee91c2e.js:1:680976
next@http://83.149.198.62/assets/vendor.fee91c2e.js:1:5079937
d@http://83.149.198.62/assets/vendor.fee91c2e.js:1:5053930
h@http://83.149.198.62/assets/vendor.fee91c2e.js:1:5054323
value@http://83.149.198.62/assets/vendor.fee91c2e.js:1:5055342
next/<@http://83.149.198.62/assets/vendor.fee91c2e.js:1:5082893
next@http://83.149.198.62/assets/vendor.fee91c2e.js:1:5082866
d@http://83.149.198.62/assets/vendor.fee91c2e.js:1:5053930
h@http://83.149.198.62/assets/vendor.fee91c2e.js:1:5054323
value@http://83.149.198.62/assets/vendor.fee91c2e.js:1:5055342
next@http://83.149.198.62/assets/vendor.fee91c2e.js:1:5118622
d@http://83.149.198.62/assets/vendor.fee91c2e.js:1:5053930
h@http://83.149.198.62/assets/vendor.fee91c2e.js:1:5054323
value@http://83.149.198.62/assets/vendor.fee91c2e.js:1:5055342
l/</</<@http://83.149.198.62/assets/vendor.fee91c2e.js:1:5115682
raven.js:55:31
    b raven.js:55
    Redux 19

**Comment by al-indigo** [comment]
needs investigation

**Comment by IgorBMSTU** [comment]
That`s true. Please note that there is no "sign in" request in debug toolbar. It looks like a problem on the frontend side

**Comment by jandrew44** [comment]
Sign out navigates to the root page now.
There is no problem with subsequent login anymore.

**Comment by nadezhday** [comment]
The problem is fixed. 
Selenium tests will be updated due to changed functionality.
