### ISSUE TITLE
Search: Implement progress bar

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#143]
-Open http://lingvodoc.ispras.ru/map_search
-Do not sign in
-Search for adoptions
-AND block (Phonemic transcription): ei
![image](https://user-images.githubusercontent.com/59951991/72711727-a647e580-3b7a-11ea-942e-94a24f3e2cc7.png)

-Press Search.
![image](https://user-images.githubusercontent.com/59951991/72712163-8a910f00-3b7b-11ea-9175-f9c8cf735e8e.png)

Problem: The search process can take time.
How long should our users wait?
We need to introduce Progress bar for search process.

**Comment by al-indigo** [comment]
It's not possible actually since search query is sync by its nature and is made with single request. Also it seems to be a bad idea to make async handlers for search operations

The solution is caching for search, work in progress

**Comment by nadezhday** [comment]
OK. We can close this issue.
