### ISSUE TITLE
Add/Delete functionality in Lexical Entries roles dialog

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#152]
-Open test-lingvodoc  /dictionary/2774/31/perspective/2774/35/view
-Sign in as Admin.
-Select LexicalEntries->Lexical Entries roles... command.
In the dialog click dropdown menu and select any user.
Problem: User is added to the Roles table immediately.  There is not button Add in the table (to confirm add operation). You cannot delete just added name from the role table. 

For developers: if we have the same problem with other dialogs fix the problem in all dialogs and add information in this case for testers to verify.

**Comment by nadezhday** [comment]
Workaround: To delete a user from the role list you need to deselect all options.

**Comment by al-indigo** [comment]
@alexlag Maybe you remember how it was done? Seems to be easy one to fix

**Comment by jandrew44** [comment]
It is possible to remove a user from the table but you have to switch off all roles in this case.
It is very inconvenient.

**Comment by jandrew44** [comment]
Add/delete buttons has been added.

**Comment by nadezhday** [comment]
Verification: 
![image](https://user-images.githubusercontent.com/59951991/77721785-e3a67480-6ffc-11ea-87f7-a6d6985b6efe.png)

Add/Delete functionality works. - OK

**Comment by nadezhday** [comment]
Covered in selenium test
