### ISSUE TITLE
Improve top menu to support Different desktops

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#156]
-Open lingvodoc
-set desktop size (1024x720) or use mouse scroll.
Problem: Help button is not visible on the page.
Improve top menu.
![image](https://user-images.githubusercontent.com/59951991/72990745-c4734700-3e01-11ea-9363-7a641f5e1290.png)

**Comment by nadezhday** [comment]
1) Redesign menu
2) Language (Russian(Русский)) - we can use flag.
3) User - we can implement Icon with first letters (Name Surname = NS)

**Comment by al-indigo** [comment]
redesign first, yes (and wait for Tomsk changes since they touch that part too). Not assigning yet

**Comment by nadezhday** [comment]
This issue was fixed by @Dina936 and @nataliauvarova.
Closing.

**Comment by vmonakhov** [comment]
UI is much different now, but the issue is covered in tests/test_top_menu.py
