### ISSUE TITLE
Dictionary blobs metadata inconsistency

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#159]
Dictionary 69/4, blobs metadata:

`{"blobs": [{"client_id": 238, "object_id": 3}, {"client_id": 238, "object_id": 2}, {"client_id": 238, "object_id": 1}]}`

DB has no blob 238/1.

How to reproduce the error in the interface:

Open search http://lingvodoc.ispras.ru/map_search, search field "Phonemic transcription" with string "ʨajç əløm" as 'Full string'.

Select dictionary marker on the map, dictionary blobs modal dialog opens and then error message "GraphQL error: UserBlobs was not found" appears.

Client 238 has exactly three blobs, 238/2, 238/3 и 238/4.

Looks like `object_id` values in the metadata are for some reason just shifted by 1.

**Comment by vmonakhov** [comment]
Actually when a new `object_id` is calculated, the current counter is increased firstly and only then the increased counter will be taken as a result. So the minimal `object_id` value is '2'

**Comment by vmonakhov** [comment]
- reproduced the issue on my own local Lingvodoc with fresh backend
- then re-added the same files (Tuba-phon.pdf and Tuba-morph.pdf) to the same dictionary (69/4)
- tried to reproduce again -> no any error

Closed as repaired

**Comment by myrix** [comment]
It looks like the errors were introduced by a faulty implementation, which since long been fixed, long ago. The introduced errors (not so large in number, admittedly) were not fixed or not all of them were fixed, some small number remain.

We'll try fixing remaining errors by directly modifying DB.

Getting dictionaries with dangling references in 'blobs' metadata info:
```sql
with

dictionary_blob as (

  select
    D.client_id,
    D.object_id,
    D.created_at,
    D.additional_metadata -> 'authors',
    B.client_id as blob_cid,
    B.object_id as blob_oid
    
  from
    dictionary D,
    jsonb_to_recordset(D.additional_metadata -> 'blobs') as B (client_id bigint, object_id bigint)
    
  where
    D.additional_metadata ? 'blobs'),

dictionary_id as (
  
  select
    D.client_id,
    D.object_id

  from
    dictionary_blob D

  left join
    userblobs B
    
  on
    B.client_id = D.blob_cid and
    B.object_id = D.blob_oid
    
  where
    B.client_id is null
  
  group by
    D.client_id,
    D.object_id)

select
  D.client_id,
  D.object_id,
  D.created_at,
  D.additional_metadata -> 'authors',
  D.additional_metadata -> 'blobs'

from
  dictionary D,
  dictionary_id I

where
  D.client_id = I.client_id and
  D.object_id = I.object_id;
```

**Comment by myrix** [comment]
Fixed with a DB mutation, see https://github.com/ispras/lingvodoc/commit/3dd12956740545e47fd273d8dee1dc82491ba66a.

While can't guarantee that all inconsistencies which were introduced are fixed (e.g. for dictionary 407/4 it's possible metadata blob link 511/2 should actually be 511/3), but at least now there are no dangling links in dictionary blob metadata and there should be no errors like this.
