### ISSUE TITLE
Update data on language selection

### ISSUE THREAD

**Issue by alexlag** [ispras/lingvodoc-react#16]
Most of the data should be re-queried when user select another language

**Comment by alexlag** [comment]
As I want to access Apollo client from saga, I added it to redux-store. That's a bit hacky.

**Comment by nadezhday** [comment]
@alexlag, please add steps for verification.

**Comment by al-indigo** [comment]
Actually this is a clone of #116

**Comment by nadezhday** [comment]
Verified. 
Closed as duplicate of https://github.com/ispras/lingvodoc-react/issues/116 - Select another language - Menu is not updated. #116

**Comment by vmonakhov** [comment]
Covered in selenium tests
