### ISSUE TITLE
Dialog cannot be closed 

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#161]
-Open http://lingvodoc.ispras.ru/dictionary/671/15154/perspective/748/553/view, -filter search "три человека", field "Praat markup", button "download" near button "View".
![image](https://user-images.githubusercontent.com/59951991/73427267-74d3d480-4347-11ea-9f88-e3550942f8b6.png)
Result: 
![image](https://user-images.githubusercontent.com/59951991/73427304-8a48fe80-4347-11ea-87ed-39695905e660.png)
-Try to close it (Esc, clicking outside, etc).
Problem: it is not possible. - NOK

**Comment by myrix** [comment]
That's actually not a dialog, it's a direct link to the image, and browser just displays the image, see address bar.

Not a bug.

**Comment by nadezhday** [comment]
The only way to close this image is to use "Go back" but the user will get in unsorted table, so will have to search  "три человека" again.
Minor issue.

**Comment by nadezhday** [comment]
Can we make it as dialog that can be closed without Go back?

**Comment by al-indigo** [comment]
It's funny, but I agree with both of you:
1. Nadya is right since it's not convenient to use
2. Ivan is right because it's really not controllable behaviour - all download actions in the same windows lead to such behaviour and it's very hard to fix

But there is an easy way to fix both problems. Since it's a separate action for explicit download and not view, I suppose it would be correct to use [download attribute](https://www.w3schools.com/tags/att_a_download.asp)

**Comment by myrix** [comment]
NOTE: due to same-origin policy (see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a, https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) can only be tested on the production site http://lingvodoc.ispras.ru.

**Comment by nadezhday** [comment]
The problem is reproduced. 
http://83.149.198.62/dictionary/671/15154/perspective/748/553/view
Column Praat click on Download.

![image](https://user-images.githubusercontent.com/59951991/73442826-93959380-4366-11ea-8b96-24d8881f7fb0.png)
Expected: Opening dialog should appear.

Note: if you click Download button in Sound of paradigmatic column.
You will get Save dialog.
![image](https://user-images.githubusercontent.com/59951991/73443021-f5ee9400-4366-11ea-9576-8a96cc177464.png)

If I use http://lingvodoc.ispras.ru/dictionary/671/15154/perspective/748/553/view then everything works as expected (Opening dialog appears)
![image](https://user-images.githubusercontent.com/59951991/73443208-4d8cff80-4367-11ea-978a-4951d1cdb370.png)
