### ISSUE TITLE
Broken link routing on the main page

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#169]
With interface as of 8d708e6122ce0ec38e19eaa7e6adc604e74ed992 user clicks on a dictionary perspective link, address in the address bar changes, browser does not go to the selected link:
![image](https://user-images.githubusercontent.com/2802467/74099342-88472280-4b33-11ea-9c18-ada7aea6ce67.png)
![image](https://user-images.githubusercontent.com/2802467/74099348-a1e86a00-4b33-11ea-9ac9-693c3ca9d814.png)

The same with dashboard links, e.g. dictionary import:
![image](https://user-images.githubusercontent.com/2802467/74099358-cf351800-4b33-11ea-98b9-4492c8f8ffa3.png)
![image](https://user-images.githubusercontent.com/2802467/74099368-e6740580-4b33-11ea-94cc-24784cec8266.png)

**Comment by myrix** [comment]
Fixed, dictionary and dashboard links on the main page work.

**Comment by nadezhday** [comment]
Verified.
Scenario1:
-Open testlingvo
-click view->lexical 
Expected: page with lexical entries is opened
Scenario2:
Dashboard->Import dialeqt dictionary
Expected: Import dialeqt dictionary page is opened 
Both scenarios works fine.

**Comment by nadezhday** [comment]
Covered in selenium tests.
