### ISSUE TITLE
Accepting cognate suggestions

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#171]
Currently user can request and receive cognate suggestions for words of a perspective among the words of perspective's language group and, if required, other language groups, see perspective view -> tools -> "Cognate suggestions", "Cognate multi-language suggestions".

User should be able to accept, fully or partially, received cognate suggestions without manually searching for and connecting to each of suggested cognate words.

**Comment by myrix** [comment]
Simple interface implemented.

Authorized users can receive and accept cognate suggestions by using Tools -> "Cognate suggestions", "Cognate multi-language suggestions" in perspective view.
![image](https://user-images.githubusercontent.com/2802467/74139135-e5aaa480-4c03-11ea-899c-128e6cb8e43c.png)

After computing cognate suggestions as usual user is presented with a suggestion acceptance interface:
![image](https://user-images.githubusercontent.com/2802467/74139519-93b64e80-4c04-11ea-856f-db5dafa5a7ed.png)

Interface lists words or word groups of the source perspective (1) and standalone words (2) and already connected word groups (3) suggested as possible cognates.

Words are listed as their transcriptions and meanings.

User can select any subset of suggested cognates; if at least one suggestion is selected, user can accept the suggestion and connect source perspective word to all selected cognate suggestions via 'Connect' button:
![image](https://user-images.githubusercontent.com/2802467/74140291-de849600-4c05-11ea-9e77-5e12be610502.png)

**Comment by nadezhday** [comment]
Open http://83.149.198.62/dictionary/2639/4263/perspective/2639/4267/view
Tools-> Cognate suggestions
Result: Error
Loading forever.
![image](https://user-images.githubusercontent.com/59951991/74217302-1e0bba80-4cb8-11ea-8f14-27a90819642d.png)

Reopening.

**Comment by myrix** [comment]
> Reopening.

The error is fixed by #179.

**Comment by nadezhday** [comment]
Verification:
Open http://83.149.198.62/dictionary/657/3/perspective/657/4/view
Tools->Cognate suggestions
press Compute button
![image](https://user-images.githubusercontent.com/59951991/74305658-9d10f980-4d71-11ea-9179-68e4ec06a9b2.png)

**Comment by nadezhday** [comment]
+ Verified with Tools->Cognate multi-language suggestions

**Comment by nadezhday** [comment]
Covered in selenium tests
