### ISSUE TITLE
Localization problem - search, edit profile, create corpus 

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#173]
Open test-lingvodoc
Select Russian language
We still have problems with localization:
Scenario 1:
Login +  Edit profile
![image](https://user-images.githubusercontent.com/59951991/74147255-ea775480-4c13-11ea-89b8-ec64a43ff328.png)

Scenario 2:
Карты-> Поиск

![image](https://user-images.githubusercontent.com/59951991/74148750-35df3200-4c17-11ea-92d1-2fffe58baf23.png)

Scenario 3:
Панель управления-> Создать корпус

![image](https://user-images.githubusercontent.com/59951991/74148879-86568f80-4c17-11ea-92c4-140a4c366a8a.png)

**Comment by nataliauvarova** [comment]
Done (all 3 points)

**Comment by nadezhday** [comment]
Scenario 1: OK
![image](https://user-images.githubusercontent.com/59951991/154426351-3c33854b-bdfc-4537-814b-be6280aa38bb.png)

Scenario 2: OK
![image](https://user-images.githubusercontent.com/59951991/154426661-7667ece7-d02d-47b7-8ea1-3246621fd86c.png)

Scenario 3 (only the first page): OK
![image](https://user-images.githubusercontent.com/59951991/154426910-ef6e09c7-f692-4134-96b7-988e073b6a2b.png)

Separate defect will be created for Loading.....

**Comment by vmonakhov** [comment]
Covered in tests/test_localization.py
For /map_search: "These phrases are not translated: {'Leaflet', 'OpenStreetMap'}"
