### ISSUE TITLE
Localization problem: Tools context commands

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#174]
Open test-lingvodoc
search for: Ket
View->lexical
click Tools
Switch to Russian language
Problem:
Several context commands are not translated.
![image](https://user-images.githubusercontent.com/59951991/74151406-2f53b900-4c1d-11ea-9b5c-af543681af5a.png)

**Comment by jandrew44** [comment]
Translation gists are missing for these entries.

**Comment by nadezhday** [comment]
@jandrew44 Can we add them?

**Comment by nadezhday** [comment]
Almost all commands have been translated. Separate defect were created for the left ones.
Closing.

**Comment by nadezhday** [comment]
Fixed indirectly
