### ISSUE TITLE
 Map is not visible (grey)

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#175]
Open testlingvodoc/map
Problem: most of the map is not visible (grey).
This is a regression.
![image](https://user-images.githubusercontent.com/59951991/74152183-d127d580-4c1e-11ea-8cf9-efaf587d0d64.png)

**Comment by nadezhday** [comment]
Verified.

**Comment by vmonakhov** [comment]
For testing every piece of the map (its file) can be ping with curl, if this is really important.

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_maps.py
