### ISSUE TITLE
Improving cognate suggestions acceptance

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#177]
User should be able deselect source perspective words and connect only suggested cognate words and word groups.
![image](https://user-images.githubusercontent.com/2802467/74212478-771e2300-4ca5-11ea-9031-18c7366f31d9.png)

Accepted suggestions should not just vanish and instead should be marked as accepted for the user to see.

Total counts of accepted and not accepted suggestions should be displayed.

After some words or word groups are connected when a suggestion is accepted, there is no guarantee that other suggestions containing these words or word groups remain valid; such suggestions should be marked as invalid and user should not be able to accept them.

**Comment by myrix** [comment]
User is able to deselect source perspective words:
![image](https://user-images.githubusercontent.com/2802467/74212697-83ef4680-4ca6-11ea-83ed-c5e37c1032b0.png)

Accepted suggestions are marked as such:
![image](https://user-images.githubusercontent.com/2802467/74212718-a1241500-4ca6-11ea-9be3-568dee8e3e56.png)

We show how many suggestions were accepted and how many are not:
![image](https://user-images.githubusercontent.com/2802467/74212743-cd3f9600-4ca6-11ea-9181-853a5301e6ec.png)

Invalidated suggestions are marked as such:
![image](https://user-images.githubusercontent.com/2802467/74212789-07a93300-4ca7-11ea-980b-65c03ac0ee41.png)

**Comment by nadezhday** [comment]
Verification:
http://83.149.198.62/dictionary/657/3/perspective/657/4/view
-Tools->Cognate suggestions
-press Compute button
-deselect checkbox for anɕər ʽпередний зуб (у хищников)ʼ (Dictionary of Yukonda dialect of Mansi - Lexical Entries)
Verify: 
39 suggestions
38 left
1 connected - OK
-Click Connect for aol ʽодин (первый) вариант 2ʼ (Dictionary of Yukonda dialect of Mansi - Lexical Entries)
Verify: 
1) Connected  - OK
2) Invalidated 
Another suggestion was accepted, source perspective word and/or one of suggested cognate words or cognate groups have been connected 
for el’mel’- ʽуходить (убираться)ʼ (Dictionary of Yukonda dialect of Mansi - Lexical Entries) - OK
3) 
39 suggestions
35 left
2 connected
2 invalidated

**Comment by nadezhday** [comment]
Verified. No errors.
![image](https://user-images.githubusercontent.com/59951991/74307467-74d7c980-4d76-11ea-8b8d-4a3a93f01d80.png)

**Comment by nadezhday** [comment]
Covered in selenium tests
