### ISSUE TITLE
Cognate suggestions initialization error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#179]
Open http://83.149.198.62/dictionary/2639/4263/perspective/2639/4267/view
Tools-> Cognate suggestions
Result: Error
Loading forever.
![image](https://user-images.githubusercontent.com/59951991/74217302-1e0bba80-4cb8-11ea-8f14-27a90819642d.png)

Reopening.

_Originally posted by @nadezhday in https://github.com/ispras/lingvodoc-react/issues/171#issuecomment-584505365_

**Comment by myrix** [comment]
Fixed, at http://83.149.198.62/dictionary/2639/4263/perspective/2639/4267/view Tools -> Cognate acoustic analysis, Cognate analysis, Cognate multi-language reconstruction, Cognate multi-language suggesions, Cognate reconstruction, Cognate suggestions open and initialize succesfully.

**Comment by nadezhday** [comment]
Verified. Works fine. No errors.

**Comment by nadezhday** [comment]
Covered in selenium tests
