### ISSUE TITLE
Lexical Entries roles and properties commands should be unavailable for unauthorized users.

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#181]
Do not sign in.
Open http://83.149.198.62/dictionary/482/4/perspective/482/5/view
click on Lexical Entries drop down menu.
'Lexical Entries' roles...
'Lexical Entries' properties...
![image](https://user-images.githubusercontent.com/59951991/74236775-039b0680-4ce3-11ea-8be4-9e794c67d9b0.png)

Note: Lexical Entries statistics... should be available for all users.

The same problem Paradigms

**Comment by jandrew44** [comment]
Done.

**Comment by nadezhday** [comment]
Verified both with Lexical Entries and Paradigms.

**Comment by nadezhday** [comment]
Covered in selenium test (lexical entries)
