### ISSUE TITLE
Cognate suggestions computation errors

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#182]
Open http://lingvodoc.ispras.ru/dictionary/1106/7053/perspective/1106/7054/view, Tools -> Cognate suggestions, deselect "Match translations", click "Compute" button:
![image](https://user-images.githubusercontent.com/2802467/74275972-ee939700-4d25-11ea-828d-0e086948ba9d.png)

Open http://lingvodoc.ispras.ru/dictionary/2059/5674/perspective/2059/5675/view, Tools -> Cognate suggestions, click "Compute" button:
![image](https://user-images.githubusercontent.com/2802467/74276105-269ada00-4d26-11ea-9a82-da220a8538a1.png)

**Comment by myrix** [comment]
Fixed.

**Comment by nadezhday** [comment]
Verified. No errors.
![image](https://user-images.githubusercontent.com/59951991/74307510-9a64d300-4d76-11ea-985e-17a29301ff0e.png)

**Comment by nadezhday** [comment]
Covered in selenium tests
