### ISSUE TITLE
Accept all selected cognate suggestions

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#183]
User should be able to accept all selected cognate suggestions at once, without accepting them one by one.

A simple 'Connect all selected' button should suffice.

**Comment by myrix** [comment]
Implemented:
![image](https://user-images.githubusercontent.com/2802467/74293783-db47f200-4d4c-11ea-9eaa-82c4dcf3ae35.png)

When the 'accept all selected' action is initiated, user is provided with dynamically updated info:
![image](https://user-images.githubusercontent.com/2802467/74293818-ff0b3800-4d4c-11ea-8c25-1e6b3fef8270.png)

**Comment by nadezhday** [comment]
Verified.
dynamically updated info - OK
Result: 
0 left
31 connected
8 invalidated

**Comment by nadezhday** [comment]
Covered in test_cognate_multi_suggestions.py
