### ISSUE TITLE
Cognate multi-language suggestion computation error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#185]
Open http://lingvodoc.ispras.ru/dictionary/654/3/perspective/654/4/view, Tools -> Cognate multi-language suggestions, click "Compute" button:
![image](https://user-images.githubusercontent.com/2802467/74429428-feb58e80-4e6b-11ea-8056-c2779a71983c.png)

**Comment by myrix** [comment]
Fixed, "Cognate multi-language suggestions" at http://lingvodoc.ispras.ru/dictionary/654/3/perspective/654/4/view compute ok.

**Comment by nadezhday** [comment]
Tested both in test-lingvodoc and ispras.lingvodoc.
Works fine.

**Comment by nadezhday** [comment]
Covered in selenium tests
