### ISSUE TITLE
Sign out: List with dictionaries disappears

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#187]
Open test-lingvodoc
Sign In
Result: you can see lingvodoc start page.
![image](https://user-images.githubusercontent.com/59951991/75848834-5f454500-5df4-11ea-8c37-17b009c26e39.png)

Sign Out
Expected: page is reloaded and then you will see lingvodoc start page with dictionaries.
Problem: It looks like that page is not reloaded. The list of dictionaries disappears. 
User cannot use lingvodoc.
![image](https://user-images.githubusercontent.com/59951991/75848863-7ab05000-5df4-11ea-898f-30cc751e5d19.png)

Workaround: reload page.
The problem was caught by automatic test (test_view_paradigms.py)

**Comment by jandrew44** [comment]
Fixed.

**Comment by nadezhday** [comment]
Works fine.
