### ISSUE TITLE
Clicking on Sign in dialog led to appearing Context menu with Sign In command

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#188]
Open test-lingvodoc
Click User->Sign In
![image](https://user-images.githubusercontent.com/59951991/75876658-2a061a80-5e27-11ea-8598-160e3d352ac6.png)

Click on Sing in dialog.
Problem: Context menus appear. 
![image](https://user-images.githubusercontent.com/59951991/75876803-6df91f80-5e27-11ea-88b2-73deacef0a30.png)

Close sign in dialog
Problem: Context menu is still visible.
![image](https://user-images.githubusercontent.com/59951991/75876903-9d0f9100-5e27-11ea-81c2-bf7b9eb5b24d.png)

**Comment by jandrew44** [comment]
It is semantic-ui-react regression.
https://github.com/Semantic-Org/Semantic-UI-React/issues/3174

**Comment by jandrew44** [comment]
It was not fixed for a long time.
So for now I have downgraded semantic ui version to 0.81.3 where it works ok.

**Comment by nadezhday** [comment]
Works fine.

**Comment by vmonakhov** [comment]
Now this issue is not actual for testing because the 'sign in/out' context menu does not exist any more.
