### ISSUE TITLE
Change language: Reload page is needed to see correct data on the page.

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#189]
1) Open test-lingvodoc
Result: menu, language names and dictionaries are in English
![image](https://user-images.githubusercontent.com/59951991/75949709-21a9f000-5eb8-11ea-897a-6e9eedb46cc0.png)

2) Select Russian language
Expected: menu, language names and dictionaries are in Russian
Actual: 
menu - OK
language names - still in English - NOK
dictionaries are are in Russian - OK
![image](https://user-images.githubusercontent.com/59951991/75949949-df34e300-5eb8-11ea-9276-ea18c0880f6f.png)

Workaround: refresh page
![image](https://user-images.githubusercontent.com/59951991/75950008-0db2be00-5eb9-11ea-87d0-b35b0f150bc2.png)

**Comment by jandrew44** [comment]
Fixed.

**Comment by nadezhday** [comment]
Verified.

**Comment by nadezhday** [comment]
Covered in selenium test.
