### ISSUE TITLE
Two submenus can be opened

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#190]
Open test-lingvodoc
1. Click on any top menu item to open submenus (e.g Languages).
![image](https://user-images.githubusercontent.com/59951991/76067888-34e4ba80-5fa1-11ea-82d1-7ad684ab97c5.png)

2. Click on Lingvodoc 3.0
Result: page is refreshed but submenu (with Langauages list) is still available.
3. Click on User
Problem: Two submenus can be seen (both for Languages and User)
![image](https://user-images.githubusercontent.com/59951991/76067845-1bdc0980-5fa1-11ea-91d7-55135f47e641.png)

Note: sometimes this problem is not reproduced. Repeat the above steps several times and you will get it.

**Comment by nadezhday** [comment]
The problem is easy to reproduce:
Open test-lingvo-doc
Click on Maps menu, 
click on Info menu.
Problem: two submenus are present on the page.
![image](https://user-images.githubusercontent.com/59951991/76383866-3ed63700-636e-11ea-9364-16b44c5aebf5.png)

This is a regression.

**Comment by jandrew44** [comment]
Fixed.

**Comment by nadezhday** [comment]
Works fine.

**Comment by nadezhday** [comment]
Covered in selenium test
