### ISSUE TITLE
Show begin and end dates for grants

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#191]
Open http://lingvodoc.ispras.ru/grants, grants' begin & end dates are not shown:
![image](https://user-images.githubusercontent.com/2802467/76296202-e566fd00-62c6-11ea-9a90-8f0d90ce140d.png)

Valid begin & end dates should be shown, just like at the previous version at http://old.lingvodoc.at.ispras.ru/#/grants:
![image](https://user-images.githubusercontent.com/2802467/76296470-3c6cd200-62c7-11ea-83e9-de38ed7bc46a.png)

**Comment by myrix** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/2802467/76298826-1ea16c00-62cb-11ea-9606-83a627c439d3.png)

**Comment by nadezhday** [comment]
Verified.

**Comment by nadezhday** [comment]
Covered in selenium test
