### ISSUE TITLE
Improvements in My Files -> file type selection functionality

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#194]
open test-lingvodoc
sign in
select UserName->My files
Select any txt file (Option PDF file is ON by default)

Problems: 
1) txt file is uploaded, it has pdf type. 
![image](https://user-images.githubusercontent.com/59951991/76592940-dfab2a80-6505-11ea-973b-0a0b06239f9f.png)

Should we have a check what file is loaded?
The same problem with .doc files.

2) We can upload .exe files.

Files:
[english_txt.txt](https://github.com/ispras/lingvodoc-react/files/4328041/english_txt.txt)

**Comment by jandrew44** [comment]
MIME types has been added to the file input.
However note that at least Windows allows to reset file category in the dialog and select any file anyway.

**Comment by nadezhday** [comment]
Looks OK. Verified
