### ISSUE TITLE
Uploaded file cannot be opened.

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#195]
sign in.
select UserName->My files.
Select any txt file (Option PDF file is ON by default).

[english_txt.txt](https://github.com/ispras/lingvodoc-react/files/4328054/english_txt.txt)
Upload.
Click on the uploaded file.
Expected: txt is opened.
Actual: File cannot be opened.
 
![image](https://user-images.githubusercontent.com/59951991/76593606-dde26680-6507-11ea-88e6-c5012b2c5a42.png)

Maybe extra steps are required?

**Comment by myrix** [comment]
Defect of the sandbox testing stand site, relevant section of the docker.ini from centos@83.149.198.62:/home/centos/lingvodoc/docker/docker.ini:
```
[backend:storage]
# disk or openstack
type = disk
path = /tmp/
prefix = http://localhost/
static_route = objects/
```
Going to try to change it to http://83.149.198.62/.

**Comment by myrix** [comment]
Ok, now the links are ok, like http://83.149.198.62/objects/userblobs/pdf/2978/2/test.txt, but files are not accessible, nginx returns 404.

So probably should look into nginx configuration, somebody should do it.

**Comment by myrix** [comment]
Fixed, file opens ok after upload.

Please note that for this to work on staging test stand, every time before test stand server restart configuration file ~/lingvodoc/docker/docker.ini has to be replaced by file ~/staging_docker.ini.

**Comment by nadezhday** [comment]
@academic-sakharov Andrey, do we need any modifications in out selenium test env?

**Comment by nadezhday** [comment]
Verification: scenario from description works fine.

**Comment by academic-sakharov** [comment]
> @academic-sakharov Andrey, do we need any modifications in out selenium test env?

Yes, I've added a command to copy file ~/staging_docker.ini to ~/lingvodoc/docker/docker.ini before docker restart.

**Comment by vmonakhov** [comment]
Covered in tests/test_my_files.py
