### ISSUE TITLE
My files: translate "Обзор", "Файл не выбран"

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#196]
Login
Open My files (User->My files)
![изображение](https://user-images.githubusercontent.com/59951991/76602191-79c99d80-651b-11ea-9834-8da9cf68f1b9.png)

Expected: Browse, File is not selected
Actual: Обзор, Файл не выбран.

**Comment by jandrew44** [comment]
I have done the necessary work on the frontend side.
Translation gists "Browse" and "No file seleted" should be added.
After that translations can be performed.

**Comment by nadezhday** [comment]
Testing: Both selenium tests have been updated according changed functionality.

Note: In order to close this case this functionality should work in Russian.

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/153334888-29740f97-1b0d-4666-9931-b67871ec780f.png)
The left Localization problem.

**Comment by nataliauvarova** [comment]
Done

**Comment by nadezhday** [comment]
Verified

![image](https://user-images.githubusercontent.com/59951991/154200200-93817ef8-2e26-4e50-b01c-3275215b2efa.png)

**Comment by nadezhday** [comment]
I am not sure if we need to translate values in the table. Let us wait for users response.
![image](https://user-images.githubusercontent.com/59951991/154200478-9ea730c4-eead-4ad0-97f2-dfe33d3a896e.png)
