### ISSUE TITLE
Timestamp errors and inconsistencies

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#197]
`created_at` fields of various objects are stored in the DB as UTC timestamps without timezone; when used in the code, they are incorrectly interpreted as if they were local time timestamps, see https://github.com/ispras/lingvodoc/blame/a9c668086b7e9da6677312aed7ffe45511c0d7f8/lingvodoc/models.py#L234 and https://docs.python.org/3.6/library/datetime.html#datetime.datetime.timestamp.

Among other things, this would cause `created_at` timestamps to be incorrectly displayed when requested by the frontend. E.g.:
```
curl 'http://lingvodoc.ispras.ru/api/graphql' -H 'content-type: application/json' --data '{"operationName": "entity", "variables": {"id": [743, 2]},"query": "query entity($id: LingvodocID!) { entity(id: $id) { id created_at } } "}' && printf "\n"
{"data": {"entity": {"id": [743, 2], "created_at": 1485417619}}}
```
```
select created_at, extract(epoch from created_at)
from public.entity
where client_id = 743 and object_id = 2;
         created_at         |    date_part     
----------------------------+------------------
 2017-01-26 11:00:19.409524 | 1485428419.40952
(1 row)
```
`created_at` value of the entity [743, 2] a frontend instance would get would be lower then the actual value stored in the DB.

`created_at` fields should be correctly interpreted as UTC timestamps, for reasons of consistency and simplicity and because it's the correct choice to provide timestamps to frontend instances regardless of their local timezones.

`deleted_at` fields in the ObjectTOC metadata are set up incorrectly due to the same reason; this leads to an inconsistency where time of deletion of an object, specified by its `deleted_at` timestamp, may actually be earlier then time of its creation, specified by its `created_at` timestamp. E.g. for entities:
```
select count(*)
from public.entity E, objecttoc O
where
  E.client_id = O.client_id and E.object_id = O.object_id and
  O.additional_metadata is not null and
  (select max((value ->> 'deleted_at') :: float) from jsonb_each(O.additional_metadata)) < extract(epoch from E.created_at);
 count 
-------
   983
(1 row)
```
```
select
  E.content,
  E.created_at,
  extract(epoch from E.created_at),
  (jsonb_each(O.additional_metadata)).value -> 'deleted_at',
  ((jsonb_each(O.additional_metadata)).value ->> 'deleted_at') :: float - extract(epoch from E.created_at)
from
  public.entity E, objecttoc O
where
  E.client_id = 2361 and E.object_id = 43246 and
  E.client_id = O.client_id and E.object_id = O.object_id;
 content |         created_at         |   date_part    |  ?column?  |     ?column?      
---------+----------------------------+----------------+------------+-------------------
 *ǯube-  | 2019-12-25 19:15:19.950999 | 1577301319.951 | 1577290521 | -10798.9509990215
(1 row)
```
Entity '*ǯube-' [2361, 43246] has deletion time almost 3 hours earlier then creation time.

`deleted_at` times should be set up correctly; existing `deleted_at` times should be corrected if possible.

**Comment by myrix** [comment]
Fixed.

`created_at` timestamps are correctly interpreted and served to the frontend as proper Unix timestamps:
```
curl 'http://lingvodoc.ispras.ru/api/graphql' -H 'content-type: application/json' --data '{"operationName": "entity", "variables": {"id": [743, 2]}, "query": "query entity($id: LingvodocID!) { entity(id: $id) { id created_at } } "}' && printf "\n"
{"data": {"entity": {"id": [743, 2], "created_at": 1485428419.409524}}}
```

Also, timestamps are no longer rounded to whole seconds, microsecond precision of timestamp initialization and timestamp DB storage is conserved.

`deleted_at` ObjectTOC metadata values are now initialized correctly; existing `deleted_at` values were adjusted:
```
curl 'http://lingvodoc.ispras.ru/api/graphql' -H 'content-type: application/json' --data '{"operationName": "entity", "variables": {"id": [2361, 43246]}, "query": "query entity($id: LingvodocID!) { entity(id: $id) { id created_at deleted_at } } "}' && printf "\n"
{"data": {"entity": {"id": [2361, 43246], "created_at": 1577301319.950999, "deleted_at": 1577301321.0}}}
```

Adjustment was also run at proxy server http://lingvodoc.tsu.ru, no `deleted_at` metadata timestamps were found and consequently no were adjusted.

Also, as illustrated by `curl` example just above, a new `deleted_at` GraphQL interface field was implemented for entities, lexical entries, perspectives, dictionaries and languages.

If the object does not have `deleted_at` metadata, `null` is returned:
```
curl 'http://lingvodoc.ispras.ru/api/graphql' -H 'content-type: application/json' --data '{"operationName": "dictionary", "variables": {"id": [657, 3]}, "query": "query dictionary($id: LingvodocID!) { dictionary(id: $id) { id deleted_at } } "}' && printf "\n"
{"data": {"dictionary": {"id": [657, 3], "deleted_at": null}}}
```

**Comment by nadezhday** [comment]
How can we verify this case? Do we have any specific scenarios/steps we can be perform in order to say that this case is really fixed?
@myrix

**Comment by myrix** [comment]
@nadezhday 
We can check by running following shell commands:
```
curl 'http://lingvodoc.ispras.ru/api/graphql' -H 'content-type: application/json' --data '{"operationName": "entity", "variables": {"id": [743, 2]}, "query": "query entity($id: LingvodocID!) { entity(id: $id) { created_at } } "}' --silent | python -c "import json; import sys; assert json.load(sys.stdin)['data']['entity']['created_at'] == 1485428419.409524"
```
```
curl 'http://lingvodoc.ispras.ru/api/graphql' -H 'content-type: application/json' --data '{"operationName": "entity", "variables": {"id": [2361, 43246]}, "query": "query entity($id: LingvodocID!) { entity(id: $id) { created_at deleted_at } } "}' --silent | python -c "import json; import sys; entity = json.load(sys.stdin)['data']['entity']; assert entity['deleted_at'] >= entity['created_at']"
```
They should run succesfully, i.e. their return codes should be 0. Both require curl and python installed.

But probably we should establish some testing infrastructure for backend, and then create tests for this in this infrastructure.

**Comment by nadezhday** [comment]
Works. 
1) 
$ curl 'http://lingvodoc.ispras.ru/api/graphql' -H 'content-type: application/json' --data '{"operationName": "entity", "variables": {"id": [743, 2]},"query": "query entity($id: LingvodocID!) { entity(id: $id) { id created_at } } "}' && printf "\n"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   211  100    71  100   140    628   1238 --:--:-- --:--:-- --:--:--  1867{"data": {"entity": {"id": [743, 2], "created_at": 1485428419.409524}}}

2)
curl 'http://lingvodoc.ispras.ru/api/graphql' -H 'content-type: application/json' --data '{"operationName": "dictionary", "variables": {"id": [657, 3]}, "query": "query dictionary($id: LingvodocID!) { dictionary(id: $id) { id deleted_at } } "}' && printf "\n"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   215  100    62  100   153    462   1141 --:--:-- --:--:-- --:--:--  1592{"data": {"dictionary": {"id": [657, 3], "deleted_at": null}}}

3) 
curl 'http://lingvodoc.ispras.ru/api/graphql' -H 'content-type: application/json' --data '{"operationName": "entity", "variables": {"id": [743, 2]}, "query": "query entity($id: LingvodocID!) { entity(id: $id) { id created_at } } "}' && printf "\n"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   212  100    71  100   141    622   1236 --:--:-- --:--:-- --:--:--  1859{"data": {"entity": {"id": [743, 2], "created_at": 1485428419.409524}}}
