### ISSUE TITLE
Last modification time GraphQL interface for dictionaries and perspectives

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#198]
There should be a GraphQL interface for getting last modification time of dictionaries and perspectives.

Last modification time of a dictionary is defined as latest time of creation or deletion of the dictionary and all its perspectives, lexical entries and entities.

Last modification time of a perspective is defined as latest time of creation or deletion of the perspective and all its lexical entries and entities.

**Comment by myrix** [comment]
Implemented the interface as `last_modified_at` GraphQL field:
```
curl 'http://lingvodoc.ispras.ru/api/graphql' -H 'content-type: application/json' --data '{"operationName": "dictionary", "variables": {"id": [657, 3]}, "query": "query dictionary($id: LingvodocID!) { dictionary(id: $id) { id last_modified_at } } "}' && printf "\n"
{"data": {"dictionary": {"id": [657, 3], "last_modified_at": 1584010752.043628}}}
```
```
curl 'http://lingvodoc.ispras.ru/api/graphql' -H 'content-type: application/json' --data '{"operationName": "perspective", "variables": {"id": [330, 4]}, "query": "query perspective($id: LingvodocID!) { perspective(id: $id) { id last_modified_at } } "}' && printf "\n"
{"data": {"perspective": {"id": [330, 4], "last_modified_at": 1582290429.665542}}}
```

**Comment by nadezhday** [comment]
works fine.
$ curl 'http://lingvodoc.ispras.ru/api/graphql' -H 'content-type: application/json' --data '{"operationName": "dictionary", "variables": {"id": [657, 3]}, "query": "query dictionary($id: LingvodocID!) { dictionary(id: $id) { id last_modified_at } } "}' && printf "\n"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   240  100    81  100   159    167    328 --:--:-- --:--:-- --:--:--   494{"data": {"dictionary": {"id": [657, 3], "last_modified_at": 1584010752.043628}}}

$ curl 'http://lingvodoc.ispras.ru/api/graphql' -H 'content-type: application/json' --data '{"operationName": "perspective", "variables": {"id": [330, 4]}, "query": "query perspective($id: LingvodocID!) { perspective(id: $id) { id last_modified_at } } "}' && printf "\n"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   244  100    82  100   162    414    818 --:--:-- --:--:-- --:--:--  1232{"data": {"perspective": {"id": [330, 4], "last_modified_at": 1582290429.665542}}}
