### ISSUE TITLE
Improvements for Show statistics dialog.

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#199]
/dictionary/2774/31/perspective/2774/35/view
Open dialog for showing statistics (Select Lexical Entries->Lexical Entries statistics... command)
Result: Dialog is opened.
![image](https://user-images.githubusercontent.com/59951991/76926538-b287bf00-68ed-11ea-8b74-cd83607dd36b.png)

Problems: 
1)Dialog has Cancel button.
Would it better to rename it to Close?
2) Dialog should have title.

**Comment by jandrew44** [comment]
Header has been added.
Button has been renamed.

**Comment by nadezhday** [comment]
Verified.
![image](https://user-images.githubusercontent.com/59951991/77502291-83cc9400-6e6b-11ea-92ab-a9255811fad7.png)

**Comment by nadezhday** [comment]
Covered in selenium test
