### ISSUE TITLE
Sometime Lexical Entries command is not available.

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#200]
Open test - Lingvodoc
Ctrl+F: Dictionary of Forest dialect of Enets language (1970) 
View->Lexical
Problem: Sometimes this line is not available. It is kind of hidden. Lexical Entries command is not accessible.
Here is a screenshot how it looks like:
![image](https://user-images.githubusercontent.com/59951991/76948893-c72d7c80-6918-11ea-9ac9-e7bbf03dff0e.png)

Workaround: reload the page http://83.149.198.62/dictionary/482/4/perspective/482/5/view
![image](https://user-images.githubusercontent.com/59951991/76949426-939f2200-6919-11ea-84a2-2d6db7cbea9e.png)

**Comment by jandrew44** [comment]
Could not reproduce.
Tried both Chrome and Firefox.

**Comment by nadezhday** [comment]
I am not able to reproduce this problem now.
BUT I saw this problem before several times. 
It happens occasionally.
It looks like that this line becomes hidden by top menu somehow.
![image](https://user-images.githubusercontent.com/59951991/77145704-5910c300-6a9a-11ea-9eba-b0fecd566d7d.png)

**Comment by myrix** [comment]
You can semi-hide it by slightly scrolling the page lower, e.g. by slightly adjusting page's scrolling slider at the right side of the window:
![image](https://user-images.githubusercontent.com/2802467/77158792-114b6500-6ab5-11ea-8170-66e5c72bc209.png)

If the page window is too short, slider also becomes short and can be hidden by the top menu completely, giving illusion that the page is not scrolled at all, meanwhile perspective's header is still half-hidden:
![image](https://user-images.githubusercontent.com/2802467/77158919-5374a680-6ab5-11ea-956e-e200a7eb2fff.png)

Maybe that's it?

In that case though 'Lexical entries' menu is still accessible, you can click on it even though it's the half-hidden, its command menu will still appear:
![image](https://user-images.githubusercontent.com/2802467/77159117-ca11a400-6ab5-11ea-985a-b35afd76b0bd.png)

**Comment by jandrew44** [comment]
@nadezhday please check Ivan's guess next time it will happen.

**Comment by jandrew44** [comment]
I guess it is not reproducible anymore.

**Comment by nadezhday** [comment]
Verified.

**Comment by vmonakhov** [comment]
Covered in tests/test_dictionaries.py
