### ISSUE TITLE
LexicalEntries->Lexical Entries roles... command: Empty dialog 

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#202]
Found problem from #151 Unhandled exception: Handle lexical Entries command for signed user

Steps to reproduce:
Here is the scenario to reproduce the exception:
Open http://83.149.198.62/dictionary/2774/31/perspective/2774/35/view
-Sign in.
-Select LexicalEntries->Lexical Entries roles... command
-Select LexicalEntries->Lexical Entries roles... command 
Problem: Empty dialog appears.
![image](https://user-images.githubusercontent.com/59951991/77143525-8d818080-6a94-11ea-83f2-eacfd2cb314d.png)

**Comment by jandrew44** [comment]
The reason is query 'PerspectiveRoles' produces error when called first time only.
All subsequent calls to this query does not have any reply from the backend.
Should be fixed on the backend side.
@myrix FYI.

**Comment by jandrew44** [comment]
Looks like it was fixed indirectly.

**Comment by vmonakhov** [comment]
Already covered in selenium tests
