### ISSUE TITLE
Role dialog: After option modification columns become reordered.

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#204]
-Open test-lingvodoc /dictionary/2774/31/perspective/2774/35/view
-Sign in as Admin.
-Select LexicalEntries->Lexical Entries roles... command.
Result:
User1 (Абубакирова Лидия Фатиховна) - 1 column
User2 (Анна Владимировна Дыбо) - 2 column
![image](https://user-images.githubusercontent.com/59951991/77722109-db9b0480-6ffd-11ea-84c2-4aac34a9e591.png)

Modify the first option for the person in the first column (User1).
Expected: Columns should be sorted (by name?). If we change options for the user it does not mean that we need to move user around the table.
Problem: After option modification columns become reordered.
User2 (Анна Владимировна Дыбо) - 1 column
User1 (Абубакирова Лидия Фатиховна) - 2 column
![image](https://user-images.githubusercontent.com/59951991/77722590-32550e00-6fff-11ea-97c7-4234ad8d6890.png)

**Comment by jandrew44** [comment]
Fixed.

**Comment by nadezhday** [comment]
Verified
Covered in tests\test_view_lexical_roles_edit.py
