### ISSUE TITLE
Add title for Roles dialog

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#206]
Login as Admin
In Lexical view click Lexical Entries roles... 
![image](https://user-images.githubusercontent.com/59951991/77736699-b5855c80-701d-11ea-97be-cf67469d46b5.png)

Can we add title for Roles dialog like we did for Show statistics?

**Comment by nadezhday** [comment]
Can we also implement dialog title for Lexical Entries->Properties...?

**Comment by jandrew44** [comment]
Done.

**Comment by nadezhday** [comment]
Verified. Titles are added.
![image](https://user-images.githubusercontent.com/59951991/78212436-64abb300-74b8-11ea-89a1-e493ecdf8606.png)

**Comment by nadezhday** [comment]
Covered in selenium test (test_view_lexical_roles.py)

Selenium test (test_view_lexical_statist.py) failed because of this fix. 
So it was updated.
