### ISSUE TITLE
Phonemic analysis tabulation size

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#208]
Mikhail Oslon reported that tabulation size of phonemic analysis results is too large.

Proper way of displaying phonemic analysis results according to him:
![image](https://user-images.githubusercontent.com/2802467/77794526-1c862e00-707d-11ea-8832-9709358ad319.png)

Current way of displaying, with too large tab size:
![image](https://user-images.githubusercontent.com/2802467/77794726-6a029b00-707d-11ea-973e-f0eb9340bfbd.png)

Tab size in phonemic analysis results should be reduced.

**Comment by myrix** [comment]
With tab size of 3 looks ok:
![image](https://user-images.githubusercontent.com/2802467/77796220-ed24f080-707f-11ea-816c-1a435aa924fa.png)

**Comment by nadezhday** [comment]
Verification:
Open a dictionary (e.g /dictionary/482/4/perspective/482/5/view), Tools -> Phonemic analysis
Click Compute.

Result: Tabulation looks ok now.  - OK.
![image](https://user-images.githubusercontent.com/59951991/77988947-28484d80-7326-11ea-8fe5-955bc76dd4d8.png)

We can close this issue.


A new issue is created: https://github.com/ispras/lingvodoc-react/issues/211 Access to horizontal scrollbar in dialogs. Improve dialog layout.

**Comment by nadezhday** [comment]
Covered in selenium test.
