### ISSUE TITLE
Select user field in the Role dialog

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#210]
The left issue from https://github.com/ispras/lingvodoc-react/issues/207 Problems with select user field in Role dialog

1)Login as admin.
2) Open /dictionary/482/4/perspective/482/5/view
3)Open Lexical Entries>Roles...
Result: "Select user" can be seen in the select user field. - OK 
![image](https://user-images.githubusercontent.com/59951991/77987060-7444c380-7321-11ea-8767-331c7d99bb90.png)

4)click Remove user.
Expected: "Select user" should be in the select user field. 
Actual: "Select user" is not in the select user field. - NOK
Note: After performing this scenario several times I noticed that sometimes  "Select user" is missing or name of just removed user appears in the select user field. 
![image](https://user-images.githubusercontent.com/59951991/77987565-dbaf4300-7322-11ea-9041-2bb6dbdc3a31.png)
![image](https://user-images.githubusercontent.com/59951991/77987592-eec21300-7322-11ea-9a01-4595c4c18953.png)

5) Click on select user field.
Result: "Пчелинцев" is not selected - OK
![image](https://user-images.githubusercontent.com/59951991/77987758-5710f480-7323-11ea-9e0d-32618c490f1f.png)
6)  click somewhere else 
Expected: Select user field should have "Select user" text.
Actual: Пчелинцев is selected.
![image](https://user-images.githubusercontent.com/59951991/77987876-abb46f80-7323-11ea-862f-e7e5e09e4292.png)

7) Also then you see "select user" text, click on drop down menu and do NOT select any user but press Enter. Пчелинцев is selected.  - NOK

**Comment by jandrew44** [comment]
Could not reproduce 4 and 6.
Regarding point 7 I think it is the correct behavior.

**Comment by nadezhday** [comment]
Interesting. I am not able to reproduce this behavior anymore. Stability problem?
We can close this case for now. 
In future we can always reopen it.

**Comment by jandrew44** [comment]
Perhaps it was just an old build.
