### ISSUE TITLE
Access to horizontal scrollbar in dialogs. Improve dialog layout.

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#211]
1) Open a dictionary (e.g /dictionary/482/4/perspective/482/5/view), Tools -> Phonemic analysis
2) Click Compute.
Result: the Phonemic analysis dialog appears.
3) Start scrolling down (use vertical scrollbar of Phonemic analysis dialog). 
![image](https://user-images.githubusercontent.com/59951991/77990339-bc67e400-7329-11ea-901c-98459dd0d63d.png)

Problems: 
1) You cannot see the end of text for very long values.
2) The horizontal scrollbar of Phonemic analysis dialog  is not reachable.  
![image](https://user-images.githubusercontent.com/59951991/77990927-42385f00-732b-11ea-9aff-965dd8ccd3ee.png)

Workaround: In order to get access to horizontal scrollbar of Phonemic analysis dialog you need to use vertical scrollbar of main page.  - NOK.
![image](https://user-images.githubusercontent.com/59951991/77991193-dd313900-732b-11ea-8770-3a958c15b352.png)

 
Can we make the dialogs user-friendly? 
This is an enhancement. If we have the same problem with other dialogs please fix them too.

**Comment by jandrew44** [comment]
Dialog has been improved.

**Comment by nadezhday** [comment]
The problem is fixed. Verified.
