### ISSUE TITLE
Convert to dictionary fails with autoclosing dialog window

### ISSUE THREAD

**Issue by al-indigo** [ispras/lingvodoc-react#214]
Dictionary creation from the corpus seems to fail on js side (but I can not trace what's happening at all).

How to reproduce:
1. Login with admin rights to have access to this corpus
2. Go to http://lingvodoc.ispras.ru/dictionary/2993/5/perspective/2993/8/edit
3. Click on markup view button (button with class "table icon")
4. Click the button "Convert to dictionary"
5. Select a language (or create a translation, but it's easier to select any parent language)
6. You will be dropped back to the dictionary silently without any error

Expected behaviour: after step 5. you should be able to fill the second obligatory field (translation or parent language) and unlock the button "convert" which should lead you to backend call.

![image](https://user-images.githubusercontent.com/1831193/78461270-31437100-76d0-11ea-9207-48fb53b48355.png)

**Comment by jandrew44** [comment]
Fixed.
However note that both actions(select language and add translation) are required in order to convert it(in the default 'create dictionary' mode).

**Comment by nadezhday** [comment]
@jandrew44 is it possible to verify this case on our test lingvodoc server?
Should I use specific dictionary? Can I use http://83.149.198.62/dictionary/2866/5/perspective/2866/9/edit ?

for example:
Login as admin
http://83.149.198.62/dictionary/2866/5/perspective/2866/9/edit
Click on markup view button (button with class "table icon")
Click the button "Convert to dictionary"
Select Language, add Translation (Test123_...)
![изображение](https://user-images.githubusercontent.com/59951991/78528859-11ec3700-77e9-11ea-9cff-61057f2c4022.png)

Click on Convert once.
Result: Task view has 1 task.

**Comment by nadezhday** [comment]
Verified.

**Comment by pavel-ho** [comment]
Covered in Selenium tests

**Comment by nadezhday** [comment]
Also can be used for testing

http://83.149.198.62/corpora_all самый первый "Glossed corpus of Gospel from st. Mark, translated in Tver karelian language, 1820" http://83.149.198.62/dictionary/3148/22166/perspective/3148/22169/edit.
