### ISSUE TITLE
Merge error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#216]
http://lingvodoc.ispras.ru/dictionary/2969/4/perspective/2969/5/merge
![image](https://user-images.githubusercontent.com/2802467/78517565-67631c80-77c6-11ea-9ecc-0ef39e3c4370.png)

**Comment by myrix** [comment]
Fixed.

Open http://83.149.198.62/dictionary/2969/4/perspective/2969/5/merge, click 'View suggestions' button, wait for suggestions to load, then click 'Select all on current page' button, then click 'Merge group' button of the first ('#0') suggestion group, 'Merged successfully' message appears:
![image](https://user-images.githubusercontent.com/2802467/79928325-4dbf0780-844b-11ea-9a95-00bedb20b565.png)

The same when clicking 'Merge group' button of the second suggestion group.

**Comment by nadezhday** [comment]
Verified. This particular scenario works fine.

**Comment by vmonakhov** [comment]
Covered in selenium tests
