### ISSUE TITLE
Remove dictionary: TranslationGist object has no attribute "parent_client_id"

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#217]
Login as admin
http://83.149.198.62/dictionary/2866/5/perspective/2866/9/edit
Click on markup view button (button with class "table icon")
Click the button "Convert to dictionary"
Select Language, add Translation (Test123_...)
![изображение](https://user-images.githubusercontent.com/59951991/78528278-afdf0200-77e7-11ea-8ab4-f47780338ba0.png)
Click on Convert once. 
Result: Task view has 1 task.

Try Remove dictionary:
Open http://83.149.198.62/dashboard/dictionaries
From drop-down menu select remove dictionary
Problem: Dictionary is not removed. Error.
![изображение](https://user-images.githubusercontent.com/59951991/78528155-668eb280-77e7-11ea-9c66-a709b4a60f9c.png)

**Comment by myrix** [comment]
Fixed, dictionaries are removed ok.

**Comment by nadezhday** [comment]
Verified.

**Comment by pavel-ho** [comment]
Covered in Selenium tests
