### ISSUE TITLE
Linking dictionaries to organizations

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#220]
It should be possible to link dictionaries to organizations, similar to how dictionaries can be linked to grants.

Single dictionary can be linked to multiple organizations.

User should be able to create a request to link a dictionary to an organization it is not already linked to; organization's administrators should be able to approve or reject such a request.

**Comment by myrix** [comment]
Request to link a dictionary to an organization can be created via dictionary's organizations dialog.

The dialog is accessible through dictionary's options in the dashboard and in perspective views:
![image](https://user-images.githubusercontent.com/2802467/79288380-3b831d80-7ecf-11ea-9b24-387121a5a5b4.png)
![image](https://user-images.githubusercontent.com/2802467/79288386-42aa2b80-7ecf-11ea-989b-af7b9e523647.png)

Dialog shows organizations the dictionary is linked to and all non-linked organizations, which are available for linking:
![image](https://user-images.githubusercontent.com/2802467/79288480-88ff8a80-7ecf-11ea-834f-529eb32a4f89.png)

To create a request to link the dictionary to an organization available for linking, click "Request link" button. Upon creation of the request user receives corresponding message:
![image](https://user-images.githubusercontent.com/2802467/79288832-746fc200-7ed0-11ea-8061-12cbea1a65c1.png)

The request will be sent to the organization administrators, or to the system's administrator user if the organization does not have any admins. Users the request was sent to can accept or reject the request on the "Requests" system page:
![image](https://user-images.githubusercontent.com/2802467/79289045-f829ae80-7ed0-11ea-851c-d554f84ef7ef.png)
![image](https://user-images.githubusercontent.com/2802467/79289059-fd86f900-7ed0-11ea-8c87-f4f14094833a.png)

If request is accepted, dictionary becomes linked to the organization, and the linking is shown in the dictionary's organizations dialog:
![image](https://user-images.githubusercontent.com/2802467/79289303-8e5dd480-7ed1-11ea-8e73-7e67ace1bdb7.png)

**Comment by nadezhday** [comment]
Verified.

Additional issues are created:
https://github.com/ispras/lingvodoc-react/issues/221 Remove link from dictionary to Organization
https://github.com/ispras/lingvodoc-react/issues/222 Message for user that Link to Organization is created.
https://github.com/ispras/lingvodoc-react/issues/223 Refresh is needed to see the accepted Link to organization

**Comment by nadezhday** [comment]
Covered in selenium tests
