### ISSUE TITLE
Message for user that Link to Organization is created. 

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#222]
#220 - Linking dictionaries to organizations

1) Login as admin
2) Dashboard + Dictionaries
3) Click any dictionary, select Organizations...
4) Click "request link" 
5) Administrator+ Requests.
6) Click Accept.
Result: Request disappeared.

We need to add a message to inform our user that Link has been created.

**Comment by myrix** [comment]
Added request acceptance message:
![image](https://user-images.githubusercontent.com/2802467/79330854-e40e9d00-7f22-11ea-8fc2-022fd732beaf.png)

**Comment by nadezhday** [comment]
Verified.
Well done.

**Comment by nadezhday** [comment]
When we click the Reject button we will get a message that Request accepted successfully.
A separate issue is created:
https://github.com/ispras/lingvodoc-react/issues/225 Reject -> message 'Request accepted successfully' is reported

**Comment by nadezhday** [comment]
covered in selenium test
