### ISSUE TITLE
Refresh is needed to see the accepted Link to organization

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#223]
#220 - Linking dictionaries to organizations

1) Login as admin
2) Dashboard + Dictionaries
3) Click any dictionary, select Organizations...
4) Click "request link"
5) Administrator+ Requests.
6) Click Accept.
7) Dashboard + Dictionaries
8) Click the dictionary, select Organizations...
Expected: Linked Organizations is NOT none.
Actual: Linked Organizations is none.

Workaround: Press Refresh to see the accepted Link to organization.

**Comment by nadezhday** [comment]
For testers: Should be covered in selenium test.

**Comment by myrix** [comment]
Fixed.

**Comment by nadezhday** [comment]
Verified.
Works fine.

**Comment by nadezhday** [comment]
Covered in selenium test
