### ISSUE TITLE
Search backend error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#224]
Open Map -> Search http://lingvodoc.ispras.ru/map_search, Select languages leaving only Khanty, search string "кожа", select Export to XLSX:
![image](https://user-images.githubusercontent.com/2802467/79807274-154bfa80-8373-11ea-8f0f-0a5166eed3bc.png)

The same without selecting only Khanty:
![image](https://user-images.githubusercontent.com/2802467/79807292-209f2600-8373-11ea-8b5f-aaf3b3e68993.png)

**Comment by myrix** [comment]
Fixed.

**Comment by nadezhday** [comment]
Verification:
Left the following languages:
![image](https://user-images.githubusercontent.com/59951991/79835076-c3c55f00-83b6-11ea-95db-430c781bab0a.png)
Кожа
Export to XLSL option is ON
click the 'XLSX-exported search results' link
Result: no errors.

**Comment by pavel-ho** [comment]
Covered in Selenuim tests
