### ISSUE TITLE
Reject -> message 'Request accepted successfully' is reported

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#225]
Login as admin
Dashboard + Dictionaries
Click any dictionary, select Organizations...
Click "request link"
Administrator+ Requests.
Click Reject.

Problem: the message 'Request accepted successfully' is reported.

I guess we need another message in this case.

![image](https://user-images.githubusercontent.com/59951991/79828976-9ffc1c00-83aa-11ea-8c47-4c2a192097b6.png)

**Comment by myrix** [comment]
Fixed to 'Request rejected successfully' on reject:
![image](https://user-images.githubusercontent.com/2802467/79830917-1569eb80-83af-11ea-85b1-20ad2f55aab3.png)

**Comment by nadezhday** [comment]
Verified.

**Comment by nadezhday** [comment]
Covered in selenium test
