### ISSUE TITLE
Perspective publish entities error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#227]
Open http://lingvodoc.ispras.ru/dictionary/2969/4/perspective/2969/5/publish, click 'Publish Entities' button.

Expected behaviour: 'Publish Entities' dialog appears.

What we have:
![image](https://user-images.githubusercontent.com/2802467/80055679-f001ec80-852a-11ea-90b6-734983296064.png)

**Comment by myrix** [comment]
Fixed, 'Publish Entities' dialog opens ok.

**Comment by nadezhday** [comment]
verified with 
http://83.149.198.62/dictionary/2969/4/perspective/2969/5/publish 

Publish Entities dialog appear. No errors.

**Comment by nadezhday** [comment]
Covered in selenium test
