### ISSUE TITLE
Implement result message for Publish Entities operation

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#228]
Open: http://83.149.198.62/dictionary/2969/4/perspective/2969/5/publish

Click Publish Entities button.

Select user.
 Click Publish.
![image](https://user-images.githubusercontent.com/59951991/80063284-40cf1080-853e-11ea-90ed-9a686438602b.png)

Problem: There is no response for this operation. Was it published? 
Can we implement any message that indicates that operation was Successful (or publish operation Failed).

If you press Refresh you will see Nothing to publish. But it does not mean that the previous  operation was successful.

**Comment by myrix** [comment]
Added successful update message:
![image](https://user-images.githubusercontent.com/2802467/80309029-e2728e00-87da-11ea-897c-d766c025a27b.png)

**Comment by nadezhday** [comment]
Verified.

**Comment by nadezhday** [comment]
Covered in selenium test

**Comment by pavel-ho** [comment]
It looks like Selenium tests found a regression.
http://83.149.198.62/dictionary/2969/4/perspective/2969/5/publish
click on "Галатия" 
click Publish entities and there is message appear
updated 0 entities.
![228](https://user-images.githubusercontent.com/67796013/90361903-fe3ec000-e067-11ea-83fb-bac13f5fb896.png)

(test_view_lexical_publish.test_lex_publish_entities)

**Comment by myrix** [comment]
Does not reproduce:
![image](https://user-images.githubusercontent.com/2802467/90368411-a48fc300-e072-11ea-9e94-4c8e5a888d82.png)
![image](https://user-images.githubusercontent.com/2802467/90368417-a78ab380-e072-11ea-9bce-80eaee4b14a0.png)

Same with 'Meaning' field and 1 or 2 entities. 

Probably requires some specific circumstances occurring during testing, need more info.

**Comment by pavel-ho** [comment]
may be in Telegram it is easier to communicate? @myrix

**Comment by nadezhday** [comment]
Actually I can also reproduce the problem.
Video:
[2020-08-17_0results.zip](https://github.com/ispras/lingvodoc-react/files/5083048/2020-08-17_0results.zip)

**Comment by myrix** [comment]
How to reproduce with certainty.

Start from lingvodoc-2020-04-28.16-51.sql.xz DB state, logged in as administrator, edit Uralic > Udmurt > Dictionary of the Written Monument "Life of St. Theodore: In the Votyak Language of the Elabuga Dialect" (1913) > Lexical Entries (/dictionary/2969/4/perspective/2969/5/edit), search for "Галатия", merge these two entries:
![image](https://user-images.githubusercontent.com/2802467/90460914-a0fd4a00-e10d-11ea-8124-54fbeb06f757.png)

Go to 'Publish' tab, unpublish 'Phonemic transcription' and 'Meaning' entities, open 'Publish Entities' dialog:
![image](https://user-images.githubusercontent.com/2802467/90460992-d30eac00-e10d-11ea-8930-3b13e252d75f.png)

Select user, click 'Publish All', you'll get message 'Updated 0 entities.':
![image](https://user-images.githubusercontent.com/2802467/90461021-e28df500-e10d-11ea-880f-d9f63f99f65f.png)

**Comment by myrix** [comment]
Fixed, now works ok:
![image](https://user-images.githubusercontent.com/2802467/90461236-71027680-e10e-11ea-8426-d6674579611a.png)

**Comment by nadezhday** [comment]
Backend:2.1.1+1285-d77f3515-2020.10.28-19:17+modified-2020.10.30-04:30
Frontend:35b1abfb-401-staging-server

The problem is reproduced again.
login as admin
http://83.149.198.62/dictionary/2969/4/perspective/2969/5/publish
Unselect Галатия 
Publish Entities
Select Базенова 
Click Publish

Here is the screenshot (if you press Publish 2, you will get message published 0) - NOK
![image](https://user-images.githubusercontent.com/59951991/97688323-09bc5780-1aab-11eb-8f15-a11e51706dbb.png)

**Comment by myrix** [comment]
Regression caused by faulty recent backend merge, fixed.

**Comment by nadezhday** [comment]
Verified.
Selenium test - PASS
