### ISSUE TITLE
Merge frontend/backend error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#229]
Open http://83.149.198.62/dictionary/2969/4/perspective/2969/5/merge while signed in as Administrator, compute merge suggestions with following settings:
![image](https://user-images.githubusercontent.com/2802467/80072971-a677c880-854f-11ea-9ca7-a2500ffb27b5.png)

Merge first ('#0') group by checking both its words and clicking 'Merge group button':
![image](https://user-images.githubusercontent.com/2802467/80072768-60bb0000-854f-11ea-930b-e868aeee8984.png)
Then merge the second group the same way:
![image](https://user-images.githubusercontent.com/2802467/80072780-63b5f080-854f-11ea-854e-1ea4b741bc69.png)

Go to page 2 via half-hidden pagination ribbon at the bottom of the window, merge first then second groups on the 2nd page:
![image](https://user-images.githubusercontent.com/2802467/80072922-92cc6200-854f-11ea-946e-1ab5cb12d26c.png)

**Comment by myrix** [comment]
Found some backend bugs, reworked frontend merge suggestions interface, the error is fixed and hopefully no new bugs were introduced.

Testing on http://83.149.198.62/dictionary/2969/4/perspective/2969/5/merge, with field selection, "Word", levenshtein 1.0, see page 4 group 36.

New interface provides 'Select all group entries' checkbox:
![image](https://user-images.githubusercontent.com/2802467/80860823-fbfc5580-8c72-11ea-952e-1a65d261193c.png)

When lexical entries are selected, entries from other groups containing selected entries also become available for selection, while these other groups are temporarily disabled:
![image](https://user-images.githubusercontent.com/2802467/80860982-39adae00-8c74-11ea-9719-a58f5ee1f855.png)

Groups with at least two selected entries can be merged by clicking on the 'Merge group' button:
![image](https://user-images.githubusercontent.com/2802467/80861124-2a7b3000-8c75-11ea-897a-2cad7c40247f.png)
Merged groups are indicated as such, merged entries become unavailable for selection in other groups:
![image](https://user-images.githubusercontent.com/2802467/80861127-2f3fe400-8c75-11ea-86a2-ee671a14287f.png)

Groups with no available entries left are disabled altogether:
![image](https://user-images.githubusercontent.com/2802467/80861131-323ad480-8c75-11ea-9475-ea2ed3462564.png)

**Comment by nadezhday** [comment]
Testing: No errors. Verified. If needed separate issues will be created.

**Comment by pavel-ho** [comment]
Covered in selenium tests
