### ISSUE TITLE
Remove link to OLD lingvodoc

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#230]
Remove link to OLD lingvodoc.

**Comment by nadezhday** [comment]
1) text Старая версия системы доступна по адресу: with link 
is removed from lingvodoc page. - OK

2) http://old.lingvodoc.at.ispras.ru/#/ is still available. Is it OK?

**Comment by nadezhday** [comment]
Removed selenium tests for OLD lingvodoc functionality

**Comment by jandrew44** [comment]
For now we remove the link only.

**Comment by nadezhday** [comment]
verified.
