### ISSUE TITLE
Corpus to dictionary conversion error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#232]
User reports corpus with sound -> dictionary convertion error at http://lingvodoc.ispras.ru/dictionary/3021/71/perspective/3021/75/edit:
![image](https://user-images.githubusercontent.com/2802467/80556423-326c7300-89dc-11ea-99da-753e9f3e0258.png)
(from user-supplied [Приложение.pdf](https://github.com/ispras/lingvodoc-react/files/4549573/default.pdf)).

Failed to reproduce at http://83.149.198.62/dictionary/3021/71/perspective/3021/75/edit, which uses docker backend, reproduced something, not exactly the error seen in the user's screenshot, locally with backend as `pserve development.ini` in a virtual environment. Differences in installed Python / package versions?

**Comment by myrix** [comment]
Fixed reproduced problem, tested conversion on one of the sound / markup corpus files at http://lingvodoc.ispras.ru/dictionary/3021/71/perspective/3021/75/edit, no errors, corpus converted ok.

Notified the user, we'll see if the conversion is really fixed.

**Comment by nadezhday** [comment]
Steps to reproduce:
http://lingvodoc.ispras.ru/dictionary/3021/71/perspective/3021/75/edit
Click on table icon
![image](https://user-images.githubusercontent.com/59951991/80561733-1376dc80-89ee-11ea-8cc5-1069697127cc.png)
Click on Convert to dictionary...
add
select language
Click Convert

**Comment by nadezhday** [comment]
Verification was performed by developer.

**Comment by vmonakhov** [comment]
Covered in tests/test_corpus_convertion.py
