### ISSUE TITLE
Columns are not created for the default perspective of a newly created corpus

### ISSUE THREAD

**Issue by jandrew44** [ispras/lingvodoc-react#233]
Create a new corpus using the corpus creation wizard.
As a result you will get corpus with perspective containing no columns.

**Comment by jandrew44** [comment]
Fixed.

**Comment by nadezhday** [comment]
Verified.
Corpus is created. We have the following columns: Sound, Markup and Comment

![изображение](https://user-images.githubusercontent.com/59951991/81256864-6d088800-903a-11ea-9918-19d5cb134357.png)

**Comment by vmonakhov** [comment]
Covered in tests/test_dashboard_create_corpus.py
