### ISSUE TITLE
Cognate suggestions interface improvement

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#236]
http://83.149.198.62/dictionary/654/3/perspective/654/4/view, Tools -> Cognate suggestions, deselect option 'Only for orphans', Compute.

In some suggestions there are groups which contain the source word, e.g.:
![image](https://user-images.githubusercontent.com/2802467/81830373-a4000180-9544-11ea-9bc8-081fe656e4c6.png)

Such suggested groups are redundant, as when words are connected, their groups, if they belong to any, are connected as well; so, such groups should not be suggested for connection.

However, we shouldn't hide from the user that the source word belongs to a group, so while such groups are not to be suggested, they still should be shown together with the source word.

Sometimes such groups are the only suggested connections for the source word, e.g.:
![image](https://user-images.githubusercontent.com/2802467/81831107-9f881880-9545-11ea-9501-ce0b12912fcb.png)

In such cases, when the source words' groups are filtered out, there are no suggestions left, and such suggestions should be removed entirely.

**Comment by myrix** [comment]
Implemented.

Groups containing source words are shown with them:
![image](https://user-images.githubusercontent.com/2802467/81843754-b97e2700-9556-11ea-88f3-57754e20fa2d.png)

Suggestions with only such groups are filtered out:
![image](https://user-images.githubusercontent.com/2802467/81843798-cc90f700-9556-11ea-9cd3-9a9f3dfecd43.png)

**Comment by nadezhday** [comment]
Verified.

**Comment by nadezhday** [comment]
covered in selenium test
