### ISSUE TITLE
Cognate multi-language suggestions error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#237]
http://lingvodoc.ispras.ru/dictionary/524/4/perspective/524/5/view as Administrator, Tools -> Cognate multi-language suggestions, Add language "Udmurt", turn off option "Only for orphans", Compute:
![image](https://user-images.githubusercontent.com/2802467/81896559-84f18600-95bd-11ea-8316-6136f6062c25.png)

Reproducible at http://83.149.198.62/dictionary/524/4/perspective/524/5/view with the same steps:
![image](https://user-images.githubusercontent.com/2802467/81896670-c41fd700-95bd-11ea-83c0-8bc1968a4002.png)

**Comment by myrix** [comment]
Traced source of the problem to the unexpected output from liboslon.so, new liboslon.so version https://github.com/ispras/lingvodoc-ext-oslon/commit/51a9b51b98288ad1f0b1fd859bf8cc72f5798a87 fixes the problem.

Updated to the latest liboslon.so version, error is no more, Komi-Udmurt multi-language suggestions work ok now.

**Comment by nadezhday** [comment]
Verified (http://83.149.198.62/dictionary/524/4/perspective/524/5/view). Compute successful.

**Comment by pavel-ho** [comment]
Covered in selenium test
