### ISSUE TITLE
http://lingvodoc.ispras.ru 502 Bad Gateway 

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#238]
Open http://lingvodoc.ispras.ru/

Problem: 
![image](https://user-images.githubusercontent.com/59951991/83101750-b5f0b100-a0bb-11ea-8a5c-75a44ffae287.png)

The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.

**Comment by al-indigo** [comment]
Shared storage RAID has fallen in degraded state; self-healing is in progress; lingvodoc is available (but very slow).

**Comment by nadezhday** [comment]
Works.
