### ISSUE TITLE
Etymological distance plot malfunction

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#239]
Tools -> Cognate analysis, etymological distance plot, legend covers all of the plot or a significant part of it:

http://lingvodoc.ispras.ru/dictionary/2059/6648/perspective/2059/6649/edit
<img width="640" alt="image" src="https://user-images.githubusercontent.com/2802467/83367256-4f6dda80-a3bc-11ea-9f3b-7f8baeee1d04.png">

http://lingvodoc.ispras.ru/dictionary/2059/5674/perspective/2059/5675/view
<img width="640" alt="image" src="https://user-images.githubusercontent.com/2802467/83367281-6c0a1280-a3bc-11ea-8ccb-ed6f029a1093.png">

Legend should not overlap the plot.

**Comment by myrix** [comment]
Fixed, height of the plot is adjusted based on the number of dictionaries.

http://lingvodoc.ispras.ru/dictionary/2059/6648/perspective/2059/6649/view, Tools, Cognate analysis:
![image](https://user-images.githubusercontent.com/2802467/83405655-a6ec6480-a415-11ea-8f10-aca2263f7f1c.png)

http://lingvodoc.ispras.ru/dictionary/2059/5674/perspective/2059/5675/view:
![image](https://user-images.githubusercontent.com/2802467/83405693-bf5c7f00-a415-11ea-8da5-39fd16422c71.png)

**Comment by nadezhday** [comment]
Verified with all above links (except http://lingvodoc.ispras.ru/dictionary/2059/6648/perspective/2059/6649/edit (no rights to do it)). 
Works fine.

**Comment by vmonakhov** [comment]
Covered in tests/test_cognate_analysis.py
