### ISSUE TITLE
Undo remove dictionary / perspective

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#240]
It should be possible to undo removal of dictionaries and perspectives performed from Dashboard -> Dictionaries.

**Comment by myrix** [comment]
Implemented.

Testing on sandbox, logged in as Administrator, Dashboard -> Dictionaries, http://83.149.198.62/dashboard/dictionaries.

Dictionary "Dictionary of Central Krasnoslobodskoy dialect of the Moksha language (vil. New Sindorovo recorded from V. I. Grishun'a)", perspective "Lexical Entries", id 2998/3362 (extracted from view link http://83.149.198.62/dictionary/2998/3361/perspective/2998/3362/view), remove it:
![image](https://user-images.githubusercontent.com/2802467/83759042-a3f2ad80-a67b-11ea-939e-8acf510596f9.png)
![image](https://user-images.githubusercontent.com/2802467/83759048-a6550780-a67b-11ea-8307-bd1759187192.png)

Undoing the removal by executing `undelete_perspective(id: [2998, 3362])` backend GraphQL query with proper authentication, e.g. with:
```
curl 'http://83.149.198.62/api/graphql' -H 'content-type: application/json' -H 'Cookie: locale_id=2; auth_tkt=587a704b7bad5eff2bf9f5c6d5955a50e7d4462e1b11f785a586412cc2a1badfd6e009e64cf90ed8314d53ee75202f6f9b132ff05453be59a776a63988ec5c2f5ed859fd3024!userid_type:int; client_id=3024' --data-raw '{"variables":{"id":[2998,3362]},"query":"mutation undelete($id: LingvodocID!) { undelete_perspective(id: $id) { triumph }}"}'
```
Refresh http://83.149.198.62/dashboard/dictionaries, perspective is back:
![image](https://user-images.githubusercontent.com/2802467/83759579-6c383580-a67c-11ea-86b0-9bfe03bc2e41.png)

Remove the dictionary:
![image](https://user-images.githubusercontent.com/2802467/83759675-912ca880-a67c-11ea-8914-a421d4820670.png)
![image](https://user-images.githubusercontent.com/2802467/83759745-b28d9480-a67c-11ea-8b13-4cb337fd59ea.png)

Restore it using its id 2998/3361 (see the perspective link above):
```
curl 'http://83.149.198.62/api/graphql' -H 'content-type: application/json' -H 'Cookie: locale_id=2; auth_tkt=587a704b7bad5eff2bf9f5c6d5955a50e7d4462e1b11f785a586412cc2a1badfd6e009e64cf90ed8314d53ee75202f6f9b132ff05453be59a776a63988ec5c2f5ed859fd3024!userid_type:int; client_id=3024' --data-raw '{"variables":{"id":[2998,3361]},"query":"mutation undelete($id: LingvodocID!) { undelete_dictionary(id: $id) { triumph }}"}'
```
It's back after page refresh:
![image](https://user-images.githubusercontent.com/2802467/83760073-1adc7600-a67d-11ea-8115-6e52ef34b497.png)

**Comment by nadezhday** [comment]
Created separate enhancement: https://github.com/ispras/lingvodoc-react/issues/251 UI for undo remove dictionary/perspective operation

**Comment by pavel-ho** [comment]
verified:

delete Lexical Entries perspective from 
http://83.149.198.62/dashboard/dictionaries

"Dictionary of Central Krasnoslobodskoy dialect of the Moksha language (vil. New Sindorovo recorded from V. I. Grishun'a)"


curl http://83.149.198.62/api/signin -H "content-type: application/json" --data-raw "{\"login\":\"type_login_here",\"password\":\"type_pass_here\"}" -c tmp_file_name

get string from tmp_file_name after auth_tkt

curl "http://83.149.198.62/api/graphql" -H "content-type: application/json" -H "Cookie: locale_id=2; PASTE_AUTH_TKT_HERE; client_id=3024" --data-raw "{\"variables\":{\"id\":[2998,3362]},\"query\":\"mutation undelete($id: LingvodocID!) { undelete_perspective(id: $id) { triumph }}\"}"

refresh page http://83.149.198.62/dashboard/dictionaries
Perspective appear

The same way for the dictionary (
remove dictionary,
curl 'http://83.149.198.62/api/graphql' -H 'content-type: application/json' -H 'Cookie: locale_id=2; auth_tkt=587a704b7bad5eff2bf9f5c6d5955a50e7d4462e1b11f785a586412cc2a1badfd6e009e64cf90ed8314d53ee75202f6f9b132ff05453be59a776a63988ec5c2f5ed859fd3024!userid_type:int; client_id=3024' --data-raw '{"variables":{"id":[2998,3361]},"query":"mutation undelete($id: LingvodocID!) { undelete_dictionary(id: $id) { triumph }}"}'
)

**Comment by pavel-ho** [comment]
covered in tests (Selenium + curl)
