### ISSUE TITLE
Remove access to deleted perspectives through direct links

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#242]
Open http://83.149.198.62/dashboard/dictionaries signed in as administrator, dictionary "Dictionary of Central Krasnoslobodskoy dialect of the Moksha language (vil. New Sindorovo recorded from V. I. Grishun'a)", Lexical Entries perspective link http://83.149.198.62/dictionary/2998/3361/perspective/2998/3362/view.

Remove this perspective:
![image](https://user-images.githubusercontent.com/2802467/83421165-4fa7bd80-a430-11ea-8a2c-30a541d94c0a.png)

Open link http://83.149.198.62/dictionary/2998/3361/perspective/2998/3362/view, can view and edit lexical entries, can view perspective statistics, view and edit its properties except for 'transcription rules':
![image](https://user-images.githubusercontent.com/2802467/83421503-e07e9900-a430-11ea-8092-d3c87a22753f.png)

The same with the normal user, if the user has corresponding permissions.

Deleted perspectives should not be accessible.

The same with not deleted perspectives of deleted dictionaries, e.g. perspective Paradigms of the aforementioned dictionary, link http://83.149.198.62/dictionary/2998/3361/perspective/2998/3363/view.

Remove this dictionary from the Dashboard -> Dictionaries page:
![image](https://user-images.githubusercontent.com/2802467/83422031-9c3fc880-a431-11ea-8911-d56b35d79219.png)

Link http://83.149.198.62/dictionary/2998/3361/perspective/2998/3363/view is accessible, can view and edit Paradigms perspective's lexical entries, statistics and properties.

Perspectives of deleted dictionaries should not be accessible.

**Comment by jandrew44** [comment]
@myrix what query/field frontend should request in order to know if dictionary/perspective was deleted?
If it is a regression, what was the correct frontend behavior for this case?

**Comment by myrix** [comment]
> @myrix what query/field frontend should request in order to know if dictionary/perspective was deleted? If it is a regression, what was the correct frontend behavior for this case?

Field `marked_for_deletion` for both for dictionary/perspective. Also, perspective is considered deleted even if just it's parent dictionary is deleted, and it itself is not.

Correct behaviour should probably be show something like 'This perspective is deleted' instead of the content.

If we have only perspective id, we can check deletion status of it and of its dictionary with following query:
```
query ($id: LingvodocID!) {
  perspective(id: $id) {
    id
    marked_for_deletion
    tree {
      id
      marked_for_deletion
    }
  }
}
```
`tree` field would be a list, with 2nd item being the perspective's dictionary.

Actually, we should probably also check if parent language/languages are deleted also, so we can check by using query
```
query ($id: LingvodocID!) {
  perspective(id: $id) {
    id
    tree {
      id
      marked_for_deletion
    }
  }
}
```
and consider perspective's content deleted and not to be shown if any of the `marked_for_deletion` fields in the `tree` list is true.

**Comment by jandrew44** [comment]
"This entity was deleted" - this message will be displayed when trying to open deleted perspective via direct link.

**Comment by nadezhday** [comment]
Verified.
![image](https://user-images.githubusercontent.com/59951991/160340564-95d738b4-679c-41a9-9329-d69cb7c49795.png)

**Comment by vmonakhov** [comment]
Covered in tests/test_dictionaries.py
