### ISSUE TITLE
Cognate analysis color highlighting

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#244]
Cognate analysis results exported in .xlsx files should be partially highlighted, see [example.xlsx](https://github.com/ispras/lingvodoc-react/files/4748597/example.xlsx).

Cells with '[u]—[u]—[u]—[u]—[u]—[u]—[u]—[u]—[u]—[u]'-like strings should be highlighted yellow:
![image](https://user-images.githubusercontent.com/2802467/84079785-cc640a00-a9e3-11ea-8458-6f855e69a422.png)

Rows with the same strings spread out among cells should also be yellow-highlighted:
![image](https://user-images.githubusercontent.com/2802467/84079896-fcaba880-a9e3-11ea-9ead-a7bc85e17f24.png)

Transcription-translation groups with parenthesized transcriptions should be emphasized gray:
![image](https://user-images.githubusercontent.com/2802467/84080133-64fa8a00-a9e4-11ea-8149-bcb8b2620828.png)

**Comment by myrix** [comment]
Implemented.

Can't test on sandbox http://83.149.198.62/ while generated file links are broken.

Verification on http://lingvodoc.ispras.ru/dictionary/654/3/perspective/654/4/view: Tools -> Cognate analysis, Compute, open "XLSX-exported analysis results" link, highlighted as required.

**Comment by nadezhday** [comment]
Verified with http://lingvodoc.ispras.ru/dictionary/654/3/perspective/654/4/view
