### ISSUE TITLE
basic_search() GraphQL API optimization

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#245]
GraphQL API basic_search() is used for finding lexical entries for group link, and for sufficiently non-specific searches it is too slow.

E.g. open http://83.149.198.62/dictionary/92/4/perspective/92/5/edit signed in as administrator, 'Cognates' button for the first lexical entry, 'Add connection' tab pane, search for 'pere', it is noticeably slow. Search for 'per', it takes more than a minute to finish.

This is not so big of a problem, because search for entries to link is usually performed with a specific entry in mind and the search string is specific enough, but optimizing it can still be useful, especially for debugging.

**Comment by myrix** [comment]
Optimized by moving all filtering to the PostgreSQL side.

In the example search for 'pere' is faster, and for 'per' is much faster, finishing in just a several seconds.

**Comment by nadezhday** [comment]
Works fine. It takes approx 4 sec to get results for 'per'.

**Comment by vmonakhov** [comment]
Covered in tests/test_view_lexical_03.py
