### ISSUE TITLE
Grouping tag modal display bug

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#246]
Open http://83.149.198.62/dictionary/92/4/perspective/92/5/edit signed in as administrator as a new page so that the interface is just loaded. Click button 'Cognates' of the first lexical entry it is present for, 'No entries' is displayed:
![image](https://user-images.githubusercontent.com/2802467/84190540-c7649080-aa9f-11ea-9cd2-f79fff19ba07.png)
![image](https://user-images.githubusercontent.com/2802467/84191304-faf3ea80-aaa0-11ea-9b52-29ce801f14c6.png)

Close grouping tag dialog by clicking 'Cancel', open it again through the same 'Cognates' button, data is displayed properly:
![image](https://user-images.githubusercontent.com/2802467/84191420-21b22100-aaa1-11ea-8c75-66a9f87f2ae9.png)

Then open lexical entries dialog by clicking the first lexical entries link, then close the dialog by clicking 'Cancel', again no data is displayed:
![image](https://user-images.githubusercontent.com/2802467/84191555-50c89280-aaa1-11ea-81d0-38505ab8a666.png)
![image](https://user-images.githubusercontent.com/2802467/84191597-6342cc00-aaa1-11ea-8059-30637b3a3d4e.png)
![image](https://user-images.githubusercontent.com/2802467/84191636-75bd0580-aaa1-11ea-8de7-ab6eae66455b.png)

Data should be displayed properly both on the first opening of the grouping tag dialog and after closing of the lexical entries dialog.

**Comment by myrix** [comment]
Fixed, grouping tag data is properly displayed on the first opening and is still displayed after opening and closing lexical entries dialog.

**Comment by nadezhday** [comment]
We can close this issue. Scenario works.

If needed separate defects will be created.

**Comment by pavel-ho** [comment]
Covered in selenium test
