### ISSUE TITLE
Group linking / perspective view bug

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#247]
Open http://83.149.198.62/dictionary/92/4/perspective/92/5/edit signed in as administrator, search for "perV", click 'Cognates' button, 'Add connection' tab pane, search for "perV", open 'Lexical Entries' dialog, scroll all the way to the right, click the first 'Connect' button, the dialog becomes empty:
![image](https://user-images.githubusercontent.com/2802467/84226171-c1939d00-aae9-11ea-9eff-cfd7cc5b5dbc.png)
![image](https://user-images.githubusercontent.com/2802467/84226175-c3f5f700-aae9-11ea-9421-60354b53b39c.png)
![image](https://user-images.githubusercontent.com/2802467/84226180-c6585100-aae9-11ea-9242-b85a8c982a38.png)
![image](https://user-images.githubusercontent.com/2802467/84226189-c8221480-aae9-11ea-87f4-9be86ee6fbb7.png)

Cancel 'Lexical Entries' and 'Grouping tag' dialogs, perspective view is hang up in a loading state:
![image](https://user-images.githubusercontent.com/2802467/84226239-ee47b480-aae9-11ea-9435-1de26fa2a2c6.png)

Probably related to #246.

**Comment by myrix** [comment]
Fixed.

Now 'Lexical Entries' dialog does not become empty after connect:
![image](https://user-images.githubusercontent.com/2802467/84234121-50a9b080-aafc-11ea-977e-33a2567d23b2.png)

And, if after that we close 'Lexical Entries' and 'Grouping tag' dialogs, the perspective view is as it should be:
![image](https://user-images.githubusercontent.com/2802467/84234268-936b8880-aafc-11ea-94ea-59b14e6e4c51.png)

**Comment by nadezhday** [comment]
@myrix? I can not see Lexical Entries link. Bug?
![image](https://user-images.githubusercontent.com/59951991/84619785-d358b400-aede-11ea-8494-0904aa65068e.png)

**Comment by nadezhday** [comment]
Verified. Scenario works fine. 
Separate defect is created 
https://github.com/ispras/lingvodoc-react/issues/250 Default value in the Search field includes space.

**Comment by pavel-ho** [comment]
I am writing automate tests in selenus.
What is described in this issue is somehow unstable reproduced.
This morning I checked - it was reproduced, but in the evening - it is no longer reproduced.
When I signed in as administrator, search for "perV", click 'Cognates' button, 'Add connection' tab pane, search for "perV", then 'Lexical Entries' dialog does not appear, only 'starling_source: 2 result(s)'
This image appears:

**Comment by pavel-ho** [comment]
![cannot_repro](https://user-images.githubusercontent.com/67796013/86950105-612f6400-c158-11ea-8774-9ac06e3e5021.png)

**Comment by pavel-ho** [comment]
Or it doesn’t matter, and you can click on "starling_source: 2 result(s)" ?

**Comment by myrix** [comment]
Perhaps, the DB state is changed? When clicking on 'Connect' button in 'Lexical entries' dialog a connection is established, and the entries which have been connected no longer appear in the results of the search for new entries to connect.

Try to re-initialize DB.

**Comment by vmonakhov** [comment]
Covered in tests/test_view_lexical_03.py
