### ISSUE TITLE
Group link search backend error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#248]
http://83.149.198.62/dictionary/743/127938/perspective/743/127939/edit logged in as Норманская Юлия Викторовна, first 'Cognates' button, 'Add connection' tab pane, search with default search string:
![image](https://user-images.githubusercontent.com/2802467/84564881-cff1eb00-ad6d-11ea-9bdb-d05aa34ed00e.png)

**Comment by myrix** [comment]
Fixed, now works as expected:
![image](https://user-images.githubusercontent.com/2802467/84565071-56f39300-ad6f-11ea-8e98-043ed3bceaf9.png)

**Comment by nadezhday** [comment]
Works. Verified.
After clicking Add connection window is empty for several seconds. It gives impression that something is wrong. Search field appears later. 
I would recommend to add process icon (similar) to indicate that tab is opening and information is loading.
 @myrix Is it possible to do? If 'yes' than I cancreate a separate enhancement.

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/84620185-f172e400-aedf-11ea-8c07-282c0486f7f8.png)

**Comment by pavel-ho** [comment]
Covered in selenium test
