### ISSUE TITLE
Perspective view: faulty perspective properties dialog

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#249]
Open http://83.149.198.62/dictionary/2969/4/perspective/2969/5/view logged in as administrator, try opening 'Lexical Entries' perspective properties:
![image](https://user-images.githubusercontent.com/2802467/84587329-f1fb7400-ae26-11ea-9aa4-2ce61bc11354.png)

Nothing happens, no dialog appears.

**Comment by myrix** [comment]
Fixed, now dialog opens alright:
![image](https://user-images.githubusercontent.com/2802467/84587799-fd509e80-ae2a-11ea-8477-a07b14daef33.png)

**Comment by nadezhday** [comment]
Works fine. Verified.

**Comment by pavel-ho** [comment]
@nadezhday,
there is a typo in the pop-up window:
![l](https://user-images.githubusercontent.com/67796013/86481898-8b001980-bd59-11ea-85dd-c3834913347f.png)

**Comment by myrix** [comment]
Re: 'propeties' typo, fixed:
![image](https://user-images.githubusercontent.com/2802467/86501597-f9b59500-bda2-11ea-87b2-5e0b6a517f87.png)

**Comment by pavel-ho** [comment]
Covered in selenium test
