### ISSUE TITLE
Default value in the Search field includes space.

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#250]
Open http://83.149.198.62/dictionary/92/4/perspective/92/5/edit signed in as administrator, search for "perV", click 'Cognates' button, 'Add connection' tab pane, 
Problem: search field has a default value. This value includes space. 
Search field: "perV "

Why do we have this space. It should be deleted. Or our search should ignore this space.
Important to fix.

**Comment by myrix** [comment]
Fixed.

Investigation showed that the space comes from the entity value (in this case,  "Proto-form" field text entity) "*perV " which happens to be used for search value initialization.

To reduce unnecessary surpriseness, any text entity value used for search value initialization is now whitespace-trimmed at both beginning and end.

Now in the example search field is initialiazed to "*perV", without space:
![image](https://user-images.githubusercontent.com/2802467/84632712-fa6faf80-aef7-11ea-8324-0fc019ea3d56.png)

**Comment by nadezhday** [comment]
Chrome: Works fine.

**Comment by nadezhday** [comment]
Problem to verify in **Firefox**:
![image](https://user-images.githubusercontent.com/59951991/85976255-ceb5f480-b9e2-11ea-8333-fe4fbd2fd94d.png)

Page is not fully visible.
@myrix, do you have the same problem? Or is it only my env issue?

**Comment by pavel-ho** [comment]
Verified for search for "perV"
On my computer on Chrome and Firefox it works fine

**Comment by pavel-ho** [comment]
Covered in Selenium tests
