### ISSUE TITLE
UI for undo remove dictionary/perspective operation

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#251]
Scenario can be taken from https://github.com/ispras/lingvodoc-react/issues/240 Undo remove dictionary / perspective
Users should not know about backend commands. 
They should be able to perform undo remove dictionary/perspective operation via our web UI.
Can we implement such functionality?

**Comment by jandrew44** [comment]
Closing since it is just a part of the large enhancement #410.

**Comment by nadezhday** [comment]
Nothing to verify
