### ISSUE TITLE
Dialeqt converter seems to skip audiofiles

### ISSUE THREAD

**Issue by al-indigo** [ispras/lingvodoc-react#252]
It seems that under some conditions lingvodoc convertor uploads only the first sound assigned to lexical entry.

Ivan has example of such a dictionary; can't put in public. The affected dictionary is here: http://lingvodoc.ispras.ru/dictionary/3020/8471/perspective/3020/8472/edit

**Comment by myrix** [comment]
Fixed.

Investigation have shown that the problem arises for words having more than one sound recording without associated markup; affected dictionaries can be fixed by updating from source Dialeqt dictionary in a standard way.

Tested locally.

**Comment by pavel-ho** [comment]
Can I check this on http://83.149.198.62 ?

**Comment by myrix** [comment]
Only if you can find a suitable already uploaded Dialeqt dictionary file to convert; I don't know if there are any such on http://83.149.198.62/. I doublt it, otherwise this bug would have been discovered earlier.

**Comment by nadezhday** [comment]
Tested on http://lingvodoc.ispras.ru/dictionary/3020/8471/perspective/3020/8472/edit
Login as admin
Open  http://lingvodoc.ispras.ru/dictionary/3020/8471/perspective/3020/8472/edit
Tools-> sound and markup
Result: .zip file is generated.(more then 1 wav in the zip)  -OK
