### ISSUE TITLE
Corpus converter enhancement

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#258]
When converting markup corpora to dictionaries, words and transcriptions that now go only to the 'Paradigms' perspective should also go to the 'Lexical entries' perspective, appropriately grouped by meanings and without duplicates, case-insensitive.

**Comment by myrix** [comment]
Implemented, tested locally.

**Comment by pavel-ho** [comment]
@myrix, 
I'm going to write automated test for this.
How do I reproduce this issue?

**Comment by myrix** [comment]
@pavel-ho 

> @myrix,
> I'm going to write automated test for this.
> How do I reproduce this issue?

Open http://83.149.198.62/dictionary/914/4/perspective/914/7/view signed in as administrator, open markup viewer,
![image](https://user-images.githubusercontent.com/2802467/88894797-28fbdc80-d251-11ea-96c4-ef19a0114506.png)
launch dictionary convertion,
![image](https://user-images.githubusercontent.com/2802467/88894824-33b67180-d251-11ea-9b09-b8306a2265d4.png)
wait for it to finish,
![image](https://user-images.githubusercontent.com/2802467/88894835-39ac5280-d251-11ea-96dc-c56a8823bb80.png)
got to the main page, find newly created dictionary, open its 'Lexical entries' perspective,
![image](https://user-images.githubusercontent.com/2802467/88894879-4630ab00-d251-11ea-9803-a39ebd18f676.png)
go to 'Edit' tab, perspective has words and transcriptions:
![image](https://user-images.githubusercontent.com/2802467/88894997-55175d80-d251-11ea-808d-f0f35dbe2ab7.png)

Issue is in the backend and it is not so simple to express it in interface interactions; it should be tested where it is, in the backend, but as of now there is no backend testing framework.

As far as I know, current policy for such issues is that it is sufficient to test them locally in development environment; so if the testing scenario too complex, you can probably skip it for automated testing.

**Comment by pavel-ho** [comment]
OK, Thanks!

**Comment by pavel-ho** [comment]
Verified. Covered in Selenium tests.
