### ISSUE TITLE
Phonological statistical distance error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#259]
Open http://83.149.198.62/dictionary/1393/29131/perspective/1393/29132/view, Tools -> Phonological statistical distance,
![image](https://user-images.githubusercontent.com/2802467/88938256-d7be0e00-d28d-11ea-8427-0f735dafff93.png)
click 'Create' immediately,
![image](https://user-images.githubusercontent.com/2802467/88938309-ec020b00-d28d-11ea-9699-a38aef5a24ee.png)
open tasks, wait, newly created phonological statistical distance task finishes with error:
![image](https://user-images.githubusercontent.com/2802467/88938381-fd4b1780-d28d-11ea-91ea-333934c92a12.png)

**Comment by myrix** [comment]
Fixed, now task finishes successfully:
![image](https://user-images.githubusercontent.com/2802467/88940041-f1f8eb80-d28f-11ea-9b55-1a9b2686567e.png)

**Comment by pavel-ho** [comment]
Verified. Covered in Selenium tests.
