### ISSUE TITLE
Cognate suggestions pagination

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#267]
For some large enough dictionary groups (e.g. http://lingvodoc.ispras.ru/dictionary/3151/24308/perspective/3151/24309/view) cognate suggestions won't render due to the large number of resulting suggestions.

We should try to limit number of suggestions displayed simultaneously, probably by using pagination.

**Comment by myrix** [comment]
Implemented suggestions pagination, now 'Cognate suggestions' works even for large dictionary groups.

**Comment by nadezhday** [comment]
Pagination is implemented.

**Comment by nadezhday** [comment]
Covered in selenium test.
