### ISSUE TITLE
Cognate analysis: It is not possible to see ЭТИМОЛОГИЧЕСКИЙ АНАЛИЗ

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#268]
Selenium test (test_cognate_analysis.py) - FAILED.

Steps: 
Open lexical view for 'Dictionary of Izhma dialect of Komi-Zyrian language' dictionary
http://83.149.198.62/dictionary/1389/6/perspective/1389/7/view
Tools->Cognate analysis.
Compute.

Expected: ЭТИМОЛОГИЧЕСКИЙ АНАЛИЗ
Actual: Skipping text output, loo long.

It is not a problem to update test case, BUT it looks like that this functionality should be improved.
Right now the user cannot see any text output. How can he do it?
What should the user do to see 'ЭТИМОЛОГИЧЕСКИЙ АНАЛИЗ'?
If we have introduced pagination then our user should see the link/button. By clicking on it the user will get all information.

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/91796055-f8300e00-ec27-11ea-87c5-c0294a7cc4ac.png)

**Comment by myrix** [comment]
Should be fixed, checked at http://lingvodoc.ispras.ru/dictionary/1389/6/perspective/1389/7/view.

**Comment by nadezhday** [comment]
Test - PASS
Verified.
