### ISSUE TITLE
Cognate multi-language analysis

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#269]
Users need to be able to perform joint cognate analysis on dictionaries from multiple base languages; we should implement 'Cognate multi-language analysis' tool, just as there is 'Cognate multi-language suggestions' for 'Cognate suggestions'.

**Comment by myrix** [comment]
Implemented as Tools -> Cognate multi-language analysis.

Tested at http://83.149.198.62/dictionary/657/3/perspective/657/4/view, select 'Khanty' as additional language, Compute, computes ok.

**Comment by nadezhday** [comment]
Scenario works fine. Verified.

**Comment by nadezhday** [comment]
Covered in selenium test.
