### ISSUE TITLE
Invoking Compute command for Unauthorized user

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#270]
Do not login.
Open (e.g. http://lingvodoc.ispras.ru/dictionary/3151/24308/perspective/3151/24309/view)
Tools-> cognate suggestions 
Compute.

It takes a lot of time to finish Compute operation.

The problem is that unauthorized user will  also wait for a long time but in the end he will see  the following message:
![image](https://user-images.githubusercontent.com/59951991/91843405-5f68b500-ec5e-11ea-9944-81cd6a0ba51b.png)

5193 suggestions
Unauthorized user 
Only authorized users can create new cognate connections based on cognate suggestions.
Skipping text output, too long.

Questions: can we improve this functionality?
1) can we check if user is authorized immediately after pressing Compute?  Should we show the message that User is Unauthorized and if he wants to see the results he needs to login (at once after pressing Compute)?

**Comment by myrix** [comment]
Now warning message is shown immediately, before computation:
![image](https://user-images.githubusercontent.com/2802467/91863093-6819b500-ec77-11ea-958b-6b43fd57064e.png)

**Comment by nadezhday** [comment]
Message is reported: 
'Unauthorized user 
Only authorized users can create new cognate connections based on cognate suggestions.'

We can close this case.


Separate defect is created for active Compute button:
#273 Disable Compute button for unauthorized user

**Comment by nadezhday** [comment]
Covered in selenium test
