### ISSUE TITLE
Cognate suggestions: Pagination bar in the end of page

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#271]
1)login as admin
2)Open http://83.149.198.62/dictionary/1393/19108/perspective/1393/19109/view
3)Tools-> cognate suggestions

4)Compute.

Result: pagination bar is present on the top - OK
![image](https://user-images.githubusercontent.com/59951991/91845736-5bd72d00-ec62-11ea-9306-9bc1677cbb8a.png)

5)Scroll down the page 

Problem: There is no pagination bar in the end of page. Usability problem.
It would be good to have this pagination bar in the end of page. We should not ask user to go to the top in order to select another page.
![image](https://user-images.githubusercontent.com/59951991/91845696-4235e580-ec62-11ea-984b-0f3f91603c43.png)

**Comment by myrix** [comment]
Pagination bar is at the bottom of suggestions, before textual output:
![image](https://user-images.githubusercontent.com/2802467/91852263-41548200-ec69-11ea-9213-d13dd0393867.png)

I believe this location is better; @nadezhday what do you think?

**Comment by nadezhday** [comment]
Yes. it is the right one (location) @myrix 
And as I can see it has been implemented.

I will reject the case as invalid.

**Comment by nadezhday** [comment]
Covered in selenium test.
