### ISSUE TITLE
Cognate multi-language reconstruction->Compute: Failed to compute cognate analysis!

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#272]
login as admin
Open http://83.149.198.62/dictionary/1393/19108/perspective/1393/19109/view
Tools -> Cognate multi-language reconstruction
Compute

Problem: Failed to compute cognate analysis!
![image](https://user-images.githubusercontent.com/59951991/91848612-6cd46e00-ec63-11ea-80e2-a3f8cbd0f6ea.png)

Console:
Error: Network error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    e ApolloError.js:37
    error QueryManager.js:212
    d Observable.js:130
    h Observable.js:161
    value Observable.js:220
    error index.js:55
    d Observable.js:130
    h Observable.js:161
    value Observable.js:220
    l index.js:98
    promise callback*l/</< index.js:94
    t Observable.js:179
    value Observable.js:258
    o index.js:19
    t Observable.js:179
    value Observable.js:258
    mutate QueryManager.js:183
    mutate QueryManager.js:124
    mutate ApolloClient.js:98
    dataForChildViaMutation react-apollo.browser.umd.js:544
    value index.js:1002
    Lodash 4
    e Button.js:103
    React 12
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
    d raven.js:393
raven.js:55:31

**Comment by myrix** [comment]
Traced problem to Mikhail Oslon's analysis library, contacted him.

**Comment by myrix** [comment]
The problem in the library is fixed, now computes ok:
![image](https://user-images.githubusercontent.com/2802467/91913969-a935b780-ecbf-11ea-8d8c-ed9faffff066.png)

But, during discussion with Mikhail it was determined that multi-language cognate reconstruction for only 1 language should be disallowed as it is meaningful only with at least 2 languages.

We should implement such check.

**Comment by myrix** [comment]
Implemented check, tested on http://83.149.198.62/dictionary/1393/19108/perspective/1393/19109/view logged in as administrator.

Tools -> Cognate multi-language reconstruction, warning message, Compute button is disabled:
![image](https://user-images.githubusercontent.com/2802467/91917122-ba82c200-ecc7-11ea-998a-23b75c9caea3.png)

Select another language, e.g. Khanty, no message, Compute button is enabled:
![image](https://user-images.githubusercontent.com/2802467/91917170-dab28100-ecc7-11ea-9b71-757d26a19850.png)

Remove a language, e.g. the first one, Moksha, again message is shown and Compute is disabled:
![image](https://user-images.githubusercontent.com/2802467/91917223-0170b780-ecc8-11ea-8e66-a119de7ea8e5.png)

**Comment by nadezhday** [comment]
Verified. Works fine.

**Comment by nadezhday** [comment]
Covered in selenium tests
