### ISSUE TITLE
'Save dictionary' enhancement

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#274]
Cognates should be saved with titles of dictionaries they reside in, with dictionary title, transcriptions and translations in separate cells.

Dictionaries with cognates but without appropriate pairs of transcription and translation fields should be listed separately.

Cognates without transcriptions should be highlighted via color.

**Comment by myrix** [comment]
Implemented.

Tested on http://lingvodoc.ispras.ru/dictionary/1106/7053/perspective/1106/7054/view logged in as administrator, 'Dictionary of Livvik dialect in Finland' dropdown menu, 'Save dictionary ...', 'Save all' button, close dialog, wait until dictionary saving task is complete, resulting XLSX URL works, dictionary data is saved as required.

**Comment by nadezhday** [comment]
Verification:
1) Open http://83.149.198.62/
2) Find Dictionary of Livvik dialect in Finland
![image](https://user-images.githubusercontent.com/59951991/92465675-90edfd00-f1d7-11ea-8f33-6d03070e9bf5.png)
3) Save dictionary...

Verify that dialog appears
![image](https://user-images.githubusercontent.com/59951991/92465889-ed511c80-f1d7-11ea-9f84-e26dab95468b.png)

Problem 1: It would be nice to modify dialog location (move it to the right)

4) Click Save all.

Problem 2: I have forgotten to login.  That is why I got Error. It would be nice to be more specific in error message (e.g. You should login) 
![image](https://user-images.githubusercontent.com/59951991/92466220-75372680-f1d8-11ea-838b-f62db97ae5a3.png)

5) Login as admin
6) Repeat steps 3 and 4

Problem 3: After clicking Save all nothing is going on. User cannot see Tasks(n).
We need to inform user that Save is started and User should close this dialog himself.

7) close Save dialog
8) Open Tasks and click xlsx file

Problem 4:  Unable to connect
![image](https://user-images.githubusercontent.com/59951991/92467132-c267c800-f1d9-11ea-9bdb-d077151e4295.png)

**Comment by nadezhday** [comment]
Partly covered in selenium test.
