### ISSUE TITLE
Phonetic proximity on the map

### ISSUE THREAD

**Issue by elmedweb** [ispras/lingvodoc-react#275]
Add a new tab to the NavBar to display phonetic  proximity between dictionaries

Add a new tab “Distance map”.

![Screenshot from 2020-08-14 10-36-52](https://user-images.githubusercontent.com/40824202/92435274-1ec3eb00-f1cc-11ea-945d-98455a269fca.png)

Add restrictions when selecting a dictionary. 
1. The dictionary must have coordinates 
2. Dictionary must have lexical entries

![Screenshot from 2020-08-14 10-42-21](https://user-images.githubusercontent.com/40824202/92435312-37340580-f1cc-11ea-9515-bd2c1ae47359.png)

It should be possible to add dictionaries from other groups

![Screenshot from 2020-08-14 10-46-33](https://user-images.githubusercontent.com/40824202/92435326-43b85e00-f1cc-11ea-9027-d037c6498d53.png)

Warning should be displayed at 0 distance

![Screenshot from 2020-08-14 11-02-32](https://user-images.githubusercontent.com/40824202/92435336-503cb680-f1cc-11ea-803e-909f4d782109.png)

If there is a phonetic proximity between languages, a map with the name of the dictionary and its distance should be displayed. The relationship with the d dictionaries should be displayed in color around the dictionary.

![Screenshot from 2020-08-14 11-03-40](https://user-images.githubusercontent.com/40824202/92435365-5af74b80-f1cc-11ea-882c-b4c7a2459d7a.png)

**Comment by nadezhday** [comment]
Please provide any real example where we can verify found dictionaries with color around the dictionary.

**Comment by nadezhday** [comment]
Additional steps for verification:
Open http://83.149.198.62/distance_map
Find Dictionary of Yukonda dialect of Mansi
Select dictionary

Add dictionaries of other language groups
1 line) Uralic
2 line) Mansi
3 line) Wester dialect

Select checkboxes for all found dictionaries
![image](https://user-images.githubusercontent.com/59951991/93335855-b4482600-f82f-11ea-8621-93123c82d82e.png)

Problem: selection disappears from Uralic, Mansi tabs. It is not good.  
![image](https://user-images.githubusercontent.com/59951991/93336183-1739bd00-f830-11ea-994d-d5ff8d3eca23.png)

Next

![image](https://user-images.githubusercontent.com/59951991/93335323-ec029e00-f82e-11ea-92be-e2b082fb7458.png)

**Comment by nadezhday** [comment]
@elmedweb FYI

Created defects:
1) https://github.com/ispras/lingvodoc-react/issues/289 -Support 'Phonetic proximity on the map' for Russian language

2) https://github.com/ispras/lingvodoc-react/issues/290 -'Select dictionary' command is missing if Russian language is chosen

**Comment by nadezhday** [comment]
Scenario 2: 
![image](https://user-images.githubusercontent.com/59951991/93432835-be6d3180-f8ce-11ea-9805-7da38a0420cf.png)

Result: Found something. 
![image](https://user-images.githubusercontent.com/59951991/93432932-d80e7900-f8ce-11ea-970a-4af2c23b0c80.png)

Problem:
There are no titles for dots on the map. Nothing. How our users will understand it.

I do not know if we have a separate defect for this. It is better to have duplicate then to have nothing.
A separate defect for this problem: https://github.com/ispras/lingvodoc-react/issues/292 - Distance map: Dots on the Map do not have any titles.

**Comment by nadezhday** [comment]
More problems: 
https://github.com/ispras/lingvodoc-react/issues/293 - Back button will redirect user on initial page instead of getting to the page with Next button

**Comment by nadezhday** [comment]
https://github.com/ispras/lingvodoc-react/issues/295 - Distance map: select dictionary -> TypeError: J.children is undefined. Top menu disappears. #295

**Comment by nadezhday** [comment]
We can close this issue.
Problems were reported in the separated issues.
