### ISSUE TITLE
Error message should inform user to login if he wants to save dictionary

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#278]
Problem found during #274 verification.

1) Open http://83.149.198.62/
2) Find Dictionary of Livvik dialect in Finland

![image](https://user-images.githubusercontent.com/59951991/92468738-5044b280-f1dc-11ea-8a10-d280243f6859.png)

3) Save dictionary...

Result: dialog appears.

4) Click Save all.

Problem : I have forgotten to login. That is why I got Error. It would be nice to be more specific in error message (e.g. You should login)
![image](https://user-images.githubusercontent.com/59951991/92468894-926df400-f1dc-11ea-849d-aa12f43774c4.png)

**Comment by myrix** [comment]
Anonymous users should also be able to save and download dictionaries.

Fixed, now even if not signed in a user can launch saving dictionary task, wait for the task to complete and download saved dictionary info:
![image](https://user-images.githubusercontent.com/2802467/93045501-0b979c00-f660-11ea-996c-e74c1ce7781e.png)
![image](https://user-images.githubusercontent.com/2802467/93045556-21a55c80-f660-11ea-9ddb-5ec741eee3c2.png)

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/93060166-70f88680-f67a-11ea-9069-f8c6bd81d0cd.png)
1) unsigned
-save all
-save all with Save sound recordings option ON
-Save only published


Problem: Open Tasks. If I want to terminate saving process How do you know which one should be closed. All of them are named "Saving dictionary" 

I am not sure that this is important. Do we need to create a separate enhancement for this? @myrix what do you think?

**Comment by myrix** [comment]
I guess it would be more convenient; so, a separate enhancement issue should be opened.

**Comment by nadezhday** [comment]
covered in selenium tests
