### ISSUE TITLE
Indication that Save dictionary task is started

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#279]
Problem found during #274 verification.

Login as admin
1) Open http://83.149.198.62/
2) Find Dictionary of Livvik dialect in Finland

![image](https://user-images.githubusercontent.com/59951991/92469293-41123480-f1dd-11ea-8c76-fd2eeb9439b0.png)

3) Save dictionary...

Result: dialog appears.

4) Click Save all.
Problem: After clicking Save all nothing is going on. User cannot see Tasks(n+1).
We need to inform user that Save is started and User should close this dialog himself.

**Comment by myrix** [comment]
Now task launch is indicated via message:
![image](https://user-images.githubusercontent.com/2802467/93045727-a1cbc200-f660-11ea-89f1-0d253f129469.png)

**Comment by nadezhday** [comment]
Verified.
Indication is present.

**Comment by nadezhday** [comment]
covered in selenium tests
