### ISSUE TITLE
Generated xlsx file cannot be opened

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#280]
Problem found during #274 verification.

Login as admin

1) Open http://83.149.198.62/
2) Find Dictionary of Livvik dialect in Finland

![image](https://user-images.githubusercontent.com/59951991/92469635-d3b2d380-f1dd-11ea-98f9-43148f97a8e7.png)

3) Save dictionary...

Result: dialog appears.

4) Click Save all.

5) Close dialog
6) Open Tasks and click xlsx file

Problem: Unable to connect
![image](https://user-images.githubusercontent.com/59951991/92469941-5a67b080-f1de-11ea-865b-1fee6119c456.png)

**Comment by myrix** [comment]
Test stand configuration issue, see #195.

Test stand administrator should properly configure it and additionally ensure that configuration is stable across git pulls and docker / test stand restarts.

**Comment by myrix** [comment]
Fixed, now downloads fine.

Also please see additional details about staging test stand config in https://github.com/ispras/lingvodoc-react/issues/195#issuecomment-691808150.

**Comment by nadezhday** [comment]
Verified.
Files can be opened.
