### ISSUE TITLE
Cognate multi-language analysis: no distance matrices, no distance figures

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#281]
Open http://lingvodoc.ispras.ru/dictionary/657/3/perspective/657/4/view, Tools -> Cognate multi-language analysis, select 'Khanty' as additional language, Compute, no distance matrices in XLSX-export and no distance figures in results.

**Comment by myrix** [comment]
Fixed, now matrices are included in the XLSX file and figures are displayed.

**Comment by nadezhday** [comment]
Scenario from description works fine.
![image](https://user-images.githubusercontent.com/59951991/92554253-8ed67d80-f26d-11ea-808b-e51d9d991bf7.png)

**Comment by nadezhday** [comment]
Added more verification points in selenium multi-language tests.
