### ISSUE TITLE
'Save dictionary' with sounds option

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#282]
User should be able to specify that the XLSX file containing saved dictionary info has to include local links to sound files referenced by saved lexical entries; in that case these files should be bundled together with the XLSX file in an archive.

**Comment by myrix** [comment]
Implemented, to save dictionary with sound click 'Save sound recordings' checkbox before launching saving dictionary task, e.g. with http://83.149.198.62/dictionary/1106/7053/perspective/1106/7054/view:
![image](https://user-images.githubusercontent.com/2802467/93046059-8f05bd00-f661-11ea-92fa-99839500c817.png)

Archive with sound files and XLSX containing dictionary data can be downloaded after the task is finished:
![image](https://user-images.githubusercontent.com/2802467/93047245-bad67200-f664-11ea-99d5-877f0e000f63.png)

**Comment by nadezhday** [comment]
Verified.
zip file with wav files is generated and can be opened.

**Comment by nadezhday** [comment]
covered in selenium tests
