### ISSUE TITLE
Dictionary metadata

### ISSUE THREAD

**Issue by elmedweb** [ispras/lingvodoc-react#283]
Add the following required fields to the metadata population interface (in the Dictionary Creation Wizard):

- Interrogator
- Processing 
- Informant
- Type of discourse
- Type of speech
- Speech genre
- The theme of the text 

Currently, the editor works with metadata of dictionaries and enclosures. Since additional meta-information in dictionaries and enclosures differs, the meta-information input interface for dictionaries and enclosures must be separated.
The current metadata edit page looks like this:
![image](https://user-images.githubusercontent.com/40824202/93117105-81dfe100-f6e8-11ea-936e-7cf185ad0812.png)
The metadata population interface should look like this:
![image](https://user-images.githubusercontent.com/40824202/93117146-94f2b100-f6e8-11ea-9da7-3946af954c35.png)

**Comment by nadezhday** [comment]
https://github.com/ispras/lingvodoc-react/issues/305 Create Dictionary: Not possible to select any option Экспедиция or Архив

**Comment by nadezhday** [comment]
Backend:

2.1.1+1228-bcdde400-2020.09.14-05:34+modified-2020.09.17-15:15

Frontend:

0.0.1+251-955990e3-347-staging-server

![image](https://user-images.githubusercontent.com/59951991/93580732-d913d900-f9a8-11ea-8a3b-d946ceb66f5a.png)

**Comment by nadezhday** [comment]
Stop testing. Waiting.

**Comment by nadezhday** [comment]
Backend:
2.1.1+1228-bcdde400-2020.09.14-05:34+modified-2020.09.19-16:18

Frontend:
0.0.1+327-2b3a7a88-369-staging-server

Fields can be verified:
![image](https://user-images.githubusercontent.com/59951991/93739688-8da03b80-fbf1-11ea-8f5e-38de408112fc.png)

OK

Separate defect is created: https://github.com/ispras/lingvodoc-react/issues/314 - Properties are empty for newly created dictionary with new metadata

**Comment by nadezhday** [comment]
We can close this case.

**Comment by nadezhday** [comment]
Covered in selenium test
test_dashboard_create_dictionary.py
