### ISSUE TITLE
Corpus metadata

### ISSUE THREAD

**Issue by elmedweb** [ispras/lingvodoc-react#284]
1)Add the following required fields to the metadata population interface (in the New Enclosures Wizard):

- Title of the work 
- Genre
- Time of writing 
- Quantitative characteristic
- Bibliographic data of the source
- Translator
- Bibliographic data of the translation

Currently, the editor works with metadata of dictionaries and enclosures. Since additional meta-information in dictionaries and enclosures differs, the meta-information input interface for dictionaries and enclosures must be separated.
The current chassis metadata page looks like this:
![image](https://user-images.githubusercontent.com/40824202/93117565-3c6fe380-f6e9-11ea-968b-076b858137d0.png)
The metadata population interface should look like this:
![Screenshot from 2020-09-15 00-21-17](https://user-images.githubusercontent.com/40824202/93117722-780aad80-f6e9-11ea-9b78-52e39d7f5ae1.png)
2)It is necessary to implement a mechanism for placing a dictionary label on a map using the names of settlements.
![image](https://user-images.githubusercontent.com/40824202/93117766-85c03300-f6e9-11ea-93a1-27e7be326f0a.png)
The user calls a window with a map from the interface for editing the meta-information of the case and there selects a settlement on the map. This geolocation is included in the case/dictionary meta-information.

**Comment by nadezhday** [comment]
Backend:

2.1.1+1228-bcdde400-2020.09.14-05:34+modified-2020.09.17-15:15

Frontend:

0.0.1+251-955990e3-347-staging-server

Scenario:
Dashboard->create corpus.

Problem: The old interface

![image](https://user-images.githubusercontent.com/59951991/93582215-d1edca80-f9aa-11ea-8cf4-420431966c25.png)

**Comment by nadezhday** [comment]
Backend:

2.1.1+1228-bcdde400-2020.09.14-05:34+modified-2020.09.19-16:18

Frontend:

0.0.1+327-2b3a7a88-369-staging-server

Corpus metadata feature is present in the build.
![image](https://user-images.githubusercontent.com/59951991/93735051-419aca00-fbe4-11ea-87d3-4c2c2a1ea899.png)

**Comment by nadezhday** [comment]
We can close this case. A separate defect was created #315

**Comment by nadezhday** [comment]
covered in test_dashboard_create_corpus.py
