### ISSUE TITLE
Support 'Phonetic proximity on the map' for Russian language

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#289]
Issue is found during testing https://github.com/ispras/lingvodoc-react/issues/275 Phonetic proximity on the map 

-Open http://83.149.198.62/ 
-Switch to Russian language
- select Карты->Distance map  
Problem 1: Translatе 'Distance map' menu into Russian
Problem 2: Translate 'Select a dictionary for analysis'
Problem 3: Translate 'No coordinate data' and 'Lexical entries no found'.  

Problem 4: Probably text 'Lexical entries no found' should be renamed in 'Lexical entries not found'

![image](https://user-images.githubusercontent.com/59951991/93423267-40089380-f8be-11ea-9e32-cdd3ad1598c4.png)

**Comment by nataliauvarova** [comment]
«Lexical entries not found» and «No coordinate data» were deleted in
https://github.com/ispras/lingvodoc-react/issues/322

other is fixed

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/153997351-5355dfac-9359-4923-b9ed-dc26c6310251.png)

![image](https://user-images.githubusercontent.com/59951991/153997384-fe5c233c-32bc-444c-aaed-33fb22ebb238.png)

**Comment by nadezhday** [comment]
Separate defect is created https://github.com/ispras/lingvodoc-react/issues/616 Distance map: localization
