### ISSUE TITLE
'Select dictionary' command is missing if Russian language is chosen

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#290]
Issue is found during testing #275 Phonetic proximity on the map

-Open http://83.149.198.62/
-Switch to Russian language
- select Карты->Distance map
Problem: Select dictionary command is missing.
User cannot work with 'Phonetic proximity on the map' functionality in Russian version of Lingvodoc.
+Do not forget to translate 'Select dictionary' it into Russian.

![image](https://user-images.githubusercontent.com/59951991/93423997-d6898480-f8bf-11ea-9bf1-d9982a026c20.png)

**Comment by nadezhday** [comment]
Backend:

2.1.1+1228-bcdde400-2020.09.14-05:34+modified-2020.09.19-16:18

Frontend:

0.0.1+327-2b3a7a88-369-staging-server

The problem is reproduced:
![image](https://user-images.githubusercontent.com/59951991/93735678-6d1eb400-fbe6-11ea-8338-9d9d0de9d623.png)

**Comment by nadezhday** [comment]
Backend:
2.1.1+1232-b95b85a9-2020.09.21-06:37+modified-2020.09.21-16:35
Frontend:
06faa11a-371-staging-server

Verified: Translated. Works ok.
![image](https://user-images.githubusercontent.com/59951991/93854729-f1dd0100-fcbe-11ea-8309-827e97fec405.png)

Results are the same in both versions - OK
![image](https://user-images.githubusercontent.com/59951991/93855302-f3f38f80-fcbf-11ea-9851-234b1a6da656.png)
![image](https://user-images.githubusercontent.com/59951991/93855349-0241ab80-fcc0-11ea-9094-09e04ecab657.png)

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_distance_map.py
