### ISSUE TITLE
After clicking LingvoDoc 3.0 link we should see the dictionary list from the top.

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#291]
Our selenium test found a regression.
Expected:
After clicking LingvoDoc 3.0 link we should see the dictionary list from the top.
![image](https://user-images.githubusercontent.com/59951991/93428957-09844600-f8c9-11ea-8122-f818d1120f9c.png)

Actual:
But we cannot see the top of the list.  We can see the end of the list.
![image](https://user-images.githubusercontent.com/59951991/93428809-c4f8aa80-f8c8-11ea-884a-2d1dd088b72f.png)

Steps to reproduce (video) can be taken from https://github.com/ispras/lingvodoc-react/issues/286 - Empty screen after performing corpus conversion and clicking LingvoDoc 3.0 link

**Comment by nadezhday** [comment]
@elmedweb what is the status of this issue?

**Comment by elmedweb** [comment]
Additional clarification of the problem is needed. The video shows the old appearance of the site and when you click on the link, you return to the tree. You are now returning to the panels. Unable to play error

**Comment by nadezhday** [comment]
Testing: it looks like that this problem is fixed. I cannot reproduce it anymore.
Closing.
@elmedweb FYI

**Comment by nadezhday** [comment]
Fixed indirectly.
