### ISSUE TITLE
Back button will redirect user on initial page instead of getting to the page with Next button

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#293]
Issue is found during testing #275 Phonetic proximity on the map

1)Open http://83.149.198.62/distance_map
2)Find Dictionary Upper Pelym dialect of Mansi language, author priest K.Slovcov, 1905 (Ю.В.Норманская)
    click Select dictionary
![image](https://user-images.githubusercontent.com/59951991/93435488-3426cc80-f8d2-11ea-81d7-9982a8799d7f.png)

 3)Add dictionaries of other language groups
 -Uralic, Mansi, Easten
 -select option ON for dictionary Dictionary of Yukonda dialect of Mansi
 4)Click Next
![image](https://user-images.githubusercontent.com/59951991/93435745-88ca4780-f8d2-11ea-9d19-b445f23d9bbb.png)

5)Click Back.

Expected: We should get to previous page with Next button. Where we can select another dictionary.
![image](https://user-images.githubusercontent.com/59951991/93435861-adbeba80-f8d2-11ea-9b28-25abeb13ae85.png)

Actual: After clicking Back we are on initial page. Why should we repeat steps 2-4 one more time. Not good.  
![image](https://user-images.githubusercontent.com/59951991/93435697-78b26800-f8d2-11ea-88c3-67535a3bbcf9.png)

**Comment by nadezhday** [comment]
We have:
1) Back, Next on first page.
![image](https://user-images.githubusercontent.com/59951991/96591870-6a4fd580-12f0-11eb-8b5c-c4e682b70948.png)
2) Return to tree, Back 
![image](https://user-images.githubusercontent.com/59951991/96592045-a2efaf00-12f0-11eb-8e41-707dcdb9a7ef.png)

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_distance_map.py
