### ISSUE TITLE
Rename submenues from 'Import dialect' and 'Import' to 'Import Dialect dictionary' and 'Import Startling dictionaries'

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#304]
Open http://83.149.198.62/dashboardRoute
![image](https://user-images.githubusercontent.com/59951991/93570670-06a65580-f99c-11ea-91ed-4b2f14510122.png)

Problem: there are 'Import dialect' and 'Import' submenus.

Should these commands be renamed to 'Import Dialect dictionary' and 'Import Startling dictionaries'?

So we should have the same names in Dashboard top menu and New designed menu

**Comment by elmedweb** [comment]
'Import Dialect dictionary' or 'Import Dialeqt dictionary'. There's no typo?

**Comment by myrix** [comment]
'Import Dialeqt dictionary', Dialeqt is a name for a standalone desktop program that was before Lingvodoc.

**Comment by nadezhday** [comment]
Backend:
2.1.1+1232-b95b85a9-2020.09.21-06:37+modified-2020.09.21-11:56
Frontend:
0.0.1+327-2b3a7a88-369-staging-server

Verified. 
![image](https://user-images.githubusercontent.com/59951991/93767351-96f4cc80-fc20-11ea-9cd5-d8fc498afac4.png)

**Comment by nadezhday** [comment]
Covered in selenium test
