### ISSUE TITLE
Create Dictionary: Not possible to select any option Экспедиция or Архив

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#305]
Open 
http://83.149.198.62/dashboard/create_dictionary
Try to select any option Экспедиция or Архив
![image](https://user-images.githubusercontent.com/59951991/93578993-a0730000-f9a6-11ea-9a58-134921eb327b.png)

Problem: it is not possible to select any option.

Switch in English.
Repeat steps.
What option is ON by default?
![image](https://user-images.githubusercontent.com/59951991/93579274-f5af1180-f9a6-11ea-99e2-bb245c78da46.png)

**Comment by nadezhday** [comment]
https://github.com/ispras/lingvodoc-react/issues/283

**Comment by nadezhday** [comment]
Backend:
2.1.1+1232-b95b85a9-2020.09.21-06:37+modified-2020.09.21-16:35
Frontend:
06faa11a-371-staging-server
1) In English version default is Expedition - OK

2) The problem with switching option is still reproduced in Russian version. Video attached.
[Russian_Options_video.zip](https://github.com/ispras/lingvodoc-react/files/5259840/Russian_Options_video.zip)

**Comment by jandrew44** [comment]
Fixed.

**Comment by nadezhday** [comment]
Verified.
