### ISSUE TITLE
Bulk cognate disconnects from Xlsx

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#313]
It should be possible to parse modified Xlsx files with highlighted non-valid cognates and disconnect such cognates.

Xlsx example: [Dictionary of Middle-Ob dialect Mansi - 2020.09.09.xlsx](https://github.com/ispras/lingvodoc-react/files/5253684/Dictionary.of.Middle-Ob.dialect.Mansi.-.2020.09.09.xlsx)

**Comment by myrix** [comment]
Implemented, only administrator can perform such bulk disconnects.

Tested locally via:
```
curl 'http://localhost:6543/graphql' \
  -H 'Cookie: locale_id=2; auth_tkt=28247d2cbbcd64d146dd1e5503880fe10e8e9f31b17a77e76f118ad36870b4d653abfce7665f25adc6b387a8e056051850ce2c2412eb8139c807ffcf4bab72ec5f677c373206!userid_type:int; client_id=3206' \
  -H 'Content-Type: multipart/form-data' \
  -F operations='{ "query": "mutation XlsxBulkDisconnect($xlsx_file: Upload) { xlsx_bulk_disconnect(xlsx_file: $xlsx_file) { entry_info_count skip_count group_count disconnect_count triumph } }", "variables": { "xlsx_file": null } }' \
  -F map='{ "0": ["variables.xlsx_file"] }' \
  -F 0=@"./Dictionary of Middle-Ob dialect Mansi - 2020.09.09.xlsx"
```

To test elsewhere, modify appropriately with required URL and 'auth_tkt' and 'client_id' administrator login cookies.

**Comment by yesandv** [comment]
Is it possible to test this using the UI?

**Comment by myrix** [comment]
> Is it possible to test this using the UI?

No, it's not in the interface.

**Comment by nadezhday** [comment]
Test: Added curl command in ToDo list. 
Closing without verification.
