### ISSUE TITLE
Properties are empty for newly created dictionary with new metadata

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#314]
Problem found during verification of https://github.com/ispras/lingvodoc-react/issues/283 Dictionary metadata

Backend:
2.1.1+1228-bcdde400-2020.09.14-05:34+modified-2020.09.19-16:18
Frontend:
0.0.1+327-2b3a7a88-369-staging-server

Create dictionary with new metadata (e.g. like shown in the screenshot)
![image](https://user-images.githubusercontent.com/59951991/93739688-8da03b80-fbf1-11ea-8f5e-38de408112fc.png)

Open it.
Invoke 'dictionary name' properties
![image](https://user-images.githubusercontent.com/59951991/93740269-d3a9cf00-fbf2-11ea-8f6a-1ac2687ed14e.png)

Expected: you can see field are filled in.
Actual: Filed are empty.
![image](https://user-images.githubusercontent.com/59951991/93740346-f63be800-fbf2-11ea-88d1-867a6c359cb8.png)

**Comment by nadezhday** [comment]
Modify the fields and try to Save.
It is not possible.
![image](https://user-images.githubusercontent.com/59951991/93740991-436c8980-fbf4-11ea-9f28-45e56b1fcf71.png)

**Comment by nadezhday** [comment]
Also the Map should have the mark 'Moscow'.

**Comment by jandrew44** [comment]
Fixed.

**Comment by nadezhday** [comment]
Functionality works. So we can close this case.

However, usability is not good. So menu Save buttons. We have separate defect for this problem.
