### ISSUE TITLE
Map on Full screen

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#321]
Comments from Y.V. Normanskaya:

Maps: we should have maps full screen.
![image](https://user-images.githubusercontent.com/59951991/93846639-4bd4cb00-fcad-11ea-8ac9-93be39ddd0bb.png)

**Comment by nadezhday** [comment]
http://83.149.198.62/map
![image](https://user-images.githubusercontent.com/59951991/93967259-7d15cf80-fd6f-11ea-901c-22526ef807b0.png)

From testing point of view Full screen is not fixed. 
Request to look at the result (map) is sent to Y.V. Normanskaya.
Let us see.

**Comment by nadezhday** [comment]
Comment from N.V. Normanskaya:
It would be good to expand the map to the bottom.

**Comment by nadezhday** [comment]
Verified. OK.

**Comment by nadezhday** [comment]
looks good.
![image](https://user-images.githubusercontent.com/59951991/94411858-be4c1c00-0181-11eb-982e-fb1c2ee9c7d4.png)

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_maps.py
