### ISSUE TITLE
Connect all selected operation takes too much time and it is impossible to sign out

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#327]
Selenium test FAILed test_cognate_multi_suggestions.py

The problem is reproduce manually.
Steps to reproduce:
login as Julia
Open Dictionary of Yukonda dialect of Mansi
Tools->Cognate multi_language suggestions
Compute
Connect all
! Do not wait until all items are connected.
Close dialog
Click Lingvodoc 3.0 link
Try to logout (Julia->logout)
Problem: it is not possible to logout. And sometimes DB crashes.

**Comment by nadezhday** [comment]
More testing.

http://83.149.198.62/dictionary/657/3/perspective/657/4/view

![image](https://user-images.githubusercontent.com/59951991/94006466-8d966c00-fda8-11ea-86f8-32c34e36f9b7.png)
Result: it takes about 7 mins to complete Connecting operation.

Is this expected result?

In our test we do not wait for the end of operation and closing dialog. Then we try to logout. As a result we can experience the problem with logout.

**Comment by myrix** [comment]
No, 7 minutes is not an expected result. Implies problem with the server / DB performance, or at least server / DB overload.

**Comment by myrix** [comment]
Locally I takes about half a minute for me, the problem obviously with test stand DB / server setup, probably with DB performance.

**Comment by nadezhday** [comment]
Now it takes about 8 mins to finish this operation.
It takes less then 1:30 to fix almost all connections.

We have problem with one connection 'берег'.

Here is the process:
(1) after 1min30sec: 
1 left
30 connecting
4 invalidated

(2) after fixing 'берег':
0 left
31 connected
5 invalidated

Question: After solving the last left issue we have +1 in connected and +1 in invalidated.
How this can be? It is very strange! 
Can we solve this problem on our test machine?

In addition DB crashed once during performing this test.

**Comment by nadezhday** [comment]
http://jenkins.zeus.intra.ispras.ru/job/test_lingvodoc_frontend/lastCompletedBuild/testReport/chrome/junit/
I have increased timeout up to 600.
And as I can see it does not help. 
Test Failed again. 
@academic-sakharov, @myrix please help.
Is it a bug in lingvodoc? Is it a BD problem? Is it an env problem?
I have noticed that performance becomes worse and worse.

**Comment by myrix** [comment]
Seems like this is a bad 'Connect all selected' example, I would surmise that this combination of suggestions leads to connecting large number of groups together, overloading server.

'Connect all selected' was never intended to be used with raw suggestions, only after user reviewed them and left only meaningful ones; that's why this button is at the bottom. I would suggest to disable this suggestions test until suitable test case is found for the current DB dump.

**Comment by nadezhday** [comment]
The scenario was taken from https://github.com/ispras/lingvodoc-react/issues/183 Accept all selected cognate suggestions
Before it took less then 450sec, 
Now sometimes it takes more then 600 sec. 

Today http://jenkins.zeus.intra.ispras.ru/job/test_lingvodoc_frontend/314/ test (test_cognate_multi_suggestions.py) - PASS

**Comment by myrix** [comment]
Test DB state changed, affecting execution of the test case.

**Comment by nadezhday** [comment]
Let's use another dictionary in our test.
Dictionary Upper Pelym dialect of Mansi language, author priest K.Slovcov,  1905
The result of Connect all is:
0 left
25 connected
3 invalidated

At least it does not take to much time.

**Comment by nadezhday** [comment]
Test passed.
Closing.
