### ISSUE TITLE
Performance problem: Saving dictionary (with sound)

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#329]
Selenium test test_save_dictionary.py - FAIL

Problem: 
Before: It took less then 350 sec to generate .zip file.
Now: I takes about 650 sec to generate this .zip file.

The performance is not good. 

Steps to reproduce:
Open http://83.149.198.62/dictionary/1106/7053/perspective/1106/7054/view
![image](https://user-images.githubusercontent.com/59951991/93969129-d3850d00-fd73-11ea-8a03-0abf3cabe96e.png)

![image](https://user-images.githubusercontent.com/59951991/93969616-fbc13b80-fd74-11ea-9f61-6f7550ea52f8.png)

The problem should be investigated.

If this performance is ok, then I will increase wait in selenium test.

**Comment by myrix** [comment]
Performance depends on many thing, including number of sound files referenced by the dictionary, memory and disk performance, connection to the big file storage server, and, in the case of the test stand, performance of the connection to the main server where sound files are stored.

So 650 sec is still good; actually, as the time can vary from time to time, it is better to not wait a specified time, but to wait until the task is 'Finished'. But also of course it should be noted that this time increase can also be an indication of issues with some of the aforementioned performance items.

**Comment by nadezhday** [comment]
Updated test: Increased wait for .zip appearance.
