### ISSUE TITLE
Functionality Select dictionary does not work. Uncaught  Exception ​ columnNumber: 0

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#339]
Backend:

2.1.1+1233-cf4fa323-2020.09.23-13:39+modified-2020.09.27-21:19

Frontend:

486a6f9f-390-staging-server

Watch the attached video.
[2020-09-28 08-09-22.zip](https://github.com/ispras/lingvodoc-react/files/5290024/2020-09-28.08-09-22.zip)

Testing:
The behaviour is changed. Menu does not disappear.  However, after clicking Select dictionary button we still get the exception.  
So this defect is not fixed. 
Expected result is to get dialog where we can select dictionaries.

We have exception:
Uncaught 
Exception
​
columnNumber: 0
​
data: null
​
filename: "https://cdn.ravenjs.com/3.18.1/raven.min.js"
​
lineNumber: 2
​
message: ""
​
name: "NS_ERROR_ILLEGAL_VALUE"
​
result: 2147942487
​
stack: "B/</<@https://cdn.ravenjs.com/3.18.1/raven.min.js:2:13630\nP/<@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:731226\nn@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:537724\nP@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:731138\ne/r.handleClick@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:825450\ni@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1223725\no@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1223808\na@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1223863\ns@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1224027\nat@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1233875\not@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1233719\nst@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1234065\ndt@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1235271\nMo@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1338647\nw@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1226501\nCt@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1239129\nLt@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1238691\ne.unstable_runWithPriority@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1344355\nqe@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1248643\n_@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1338501\nAt@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1238505\nd@https://cdn.ravenjs.com/3.18.1/raven.min.js:2:6483\nEventListener.handleEvent*b/</<@https://cdn.ravenjs.com/3.18.1/raven.min.js:2:11053\nOt@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1238426\nSt@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1238228\nht@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1235579\njt@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1240211\nvr@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1277416\nni@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1295523\nei@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1295412\nJr@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1295265\nqr@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1292235\nFr@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1288973\nAi@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1305943\nRi/<@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1307096\nGr@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1292676\nRi@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1307082\ne.render@http://83.149.198.62/assets/vendor.7b32b7b0.js:1:1339902\ni@http://83.149.198.62/assets/client.8a197688.js:1:62118\n1281@http://83.149.198.62/assets/client.8a197688.js:1:63484\nn@http://83.149.198.62/assets/manifest.68b22dda.js:1:101\n1081@http://83.149.198.62/assets/client.8a197688.js:1:62058\nn@http://83.149.198.62/assets/manifest.68b22dda.js:1:101\nwindow.webpackJsonp@http://83.149.198.62/assets/manifest.68b22dda.js:1:418\n@http://83.149.198.62/assets/client.8a197688.js:1:13\n"
​
<prototype>: ExceptionPrototype { toString: toString(), name: Getter, message: Getter, … }

**Comment by elmedweb** [comment]
Error cannot be repeated, details required 

[simplescreenrecorder-2020-09-28_16.36.37.zip](https://github.com/ispras/lingvodoc-react/files/5291331/simplescreenrecorder-2020-09-28_16.36.37.zip)

**Comment by nadezhday** [comment]
It looks like that you are using Chrome.
More testing: The problem is specific for Firefox.

**Comment by nadezhday** [comment]
@elmedweb, What is the status of this issue?
This issue is still reproduced (Firefox specific).

**Comment by nadezhday** [comment]
The problem is not reproduced in Firefox anymore. Verified.
Tested in Chrome - OK
Closing.
