### ISSUE TITLE
Experimental design

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#341]
Екатерина, [25.09.20 05:18]
[In reply to Юлия Викторовна Норманская]
Как вариант, можем предложить сделать небольшой редизайн как показано на картинке. Или, если вам этот вариант не подойдет, присылайте картинки для текущего дизайна, мы их поставим.

Екатерина, [25.09.20 05:19]
![image](https://user-images.githubusercontent.com/2802467/94420015-38819e00-018c-11eb-89a8-21309ebf0ccc.png)

Юлия Викторовна Норманская, [25.09.20 12:53]
Мне кажется, что такой дизайн, да, более академичный.

**Comment by nadezhday** [comment]
Comment from N.V. Normanskaya:
Я не могу сказать нравится, но лучше, мне кажется, чем прошлый вариант. Но если есть ещё варианты, буду рада посмотреть

**Comment by nadezhday** [comment]
Design is not good.
![изображение](https://user-images.githubusercontent.com/59951991/94512872-e3926600-0225-11eb-9151-70f0389924e2.png)
 
Impossible to see anything.
![изображение](https://user-images.githubusercontent.com/59951991/94512918-fc028080-0225-11eb-90f7-d642eecc1355.png)

![изображение](https://user-images.githubusercontent.com/59951991/94512927-091f6f80-0226-11eb-8f34-6a6964bd6b72.png)

![изображение](https://user-images.githubusercontent.com/59951991/94513140-9a8ee180-0226-11eb-8f04-86c56556879e.png)

Reopening case.

**Comment by nadezhday** [comment]
![изображение](https://user-images.githubusercontent.com/59951991/94513313-11c47580-0227-11eb-867d-1d1690c61a93.png)

**Comment by nadezhday** [comment]
@elmedweb What is the status?

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/94774359-6a7e4480-03c6-11eb-8da6-c28b8687ad29.png)
Almost impossible to see anything.

**Comment by nadezhday** [comment]
Link to Figma prototype can be found here: https://confluence.ispras.ru/pages/viewpage.action?pageId=31950164

**Comment by 7kingdom** [comment]
> 
> 
> Екатерина, [25.09.20 05:18]
> [In reply to Юлия Викторовна Норманская]
> Как вариант, можем предложить сделать небольшой редизайн как показано на картинке. Или, если вам этот вариант не подойдет, присылайте картинки для текущего дизайна, мы их поставим.
> 
> Екатерина, [25.09.20 05:19]
> ![image](https://user-images.githubusercontent.com/2802467/94420015-38819e00-018c-11eb-89a8-21309ebf0ccc.png)
> 
> Юлия Викторовна Норманская, [25.09.20 12:53]
> Мне кажется, что такой дизайн, да, более академичный.

**Comment by nadezhday** [comment]
This issue can be closed. @Dina936 and @nataliauvarova are working with a new design implementation.
