### ISSUE TITLE
Support English version for List of grants

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#343]
Left issue from https://github.com/ispras/lingvodoc-react/issues/318 Authors -> List of grants

http://83.149.198.62/authorsRoute
List of grants
All 6 topics (copy the list from here: http://lingvodoc.ispras.ru/)  should be in English.

![изображение](https://user-images.githubusercontent.com/59951991/94513911-94016980-0228-11eb-822c-4b3d31beaa4d.png)

**Comment by nadezhday** [comment]
1) Text (list of grants) in English
![image](https://user-images.githubusercontent.com/59951991/97271733-fe1a2800-1841-11eb-999a-e57ccf99af16.png)

2) Text in Russian
![image](https://user-images.githubusercontent.com/59951991/97271838-26098b80-1842-11eb-8564-b3a8c39a5359.png)


3) Unfortunately I experienced a problem:
List with grants was missing. 
After refreshing page it appears again.
A separate defect will be created.

@elmedweb FYI

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/97272229-a62ff100-1842-11eb-932e-0cabf5dc88f6.png)

**Comment by nadezhday** [comment]
Sometimes you can see Russian text in English version
![image](https://user-images.githubusercontent.com/59951991/97275262-c497eb80-1846-11eb-9de3-4e349f8a6eed.png)

**Comment by vmonakhov** [comment]
Covered in tests/test_localization.py
