### ISSUE TITLE
Change the location ofLanguages submenu. Move it under the icon. 

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#345]
http://83.149.198.62/toolsRoute

Problem: Languages is located on top of the icon.
![изображение](https://user-images.githubusercontent.com/59951991/94532944-2b75b500-0247-11eb-90cb-6316f211e89f.png)

**Comment by al-indigo** [comment]
@nadezhday testing if you see notification

**Comment by nadezhday** [comment]
Fixed. Verified. Closing.
![image](https://user-images.githubusercontent.com/59951991/97262265-90fe9680-1831-11eb-9758-9d61e95e73c9.png)
