### ISSUE TITLE
Dedoc project support added into odt corpus parser

### ISSUE THREAD

**Issue by ankan2013** [ispras/lingvodoc-react#346]
A pull request (https://github.com/ispras/lingvodoc/pull/1268) was made to add a new feature: document structure extracting from an odt document. A parser sends a post request to a remote server with dedoc project deployed and gets an html with headers and paragraphs as the responce. The url of this server is specified in 'dedoc_url' parameter in docker.ini configuration file.

**Comment by jandrew44** [comment]
Not sure why this task was created.
It describes a part of backend implementation related to the corpora text markup.
Can be closed.

**Comment by nadezhday** [comment]
Closing without verification
