### ISSUE TITLE
Create corpus: pressing ENTER in the fields initiates opening Select settlement dialog

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#351]
Dashboard->create Corpus
select language
next
Put cursor in the field Title of the work (the problem is also reproduced for other fields)
click ENTER
![image](https://user-images.githubusercontent.com/59951991/94789232-5560e000-03dd-11eb-93f1-a22e831d75f3.png)

Problem: dialog Select settlement is opened.
![image](https://user-images.githubusercontent.com/59951991/94789620-cc967400-03dd-11eb-9fdb-144ab12a5dec.png)

@elmedweb

**Comment by nadezhday** [comment]
Corpus metadata #284

**Comment by jandrew44** [comment]
Fixed.

**Comment by nadezhday** [comment]
Create Corpus dialog - OK
Verified.

**Comment by vmonakhov** [comment]
Covered in tests/test_dashboard_create_corpus.py
