### ISSUE TITLE
Parser optimization

### ISSUE THREAD

**Issue by ankan2013** [ispras/lingvodoc-react#352]
As it wasn't done here before, I should give a brief description of how parsing system works.

The idea (as well as a use case) of parsing is in following:
1. A user uploads a linguistic corpus in .odt format (further new formats support may be added) into a field of a perspective, which is suitable for loading documents, for example, Markup field .
2. A user preses a button near loaded document (looks somehow like "power on"), selects a suitable parser from the list of them and launches the process of parsing.
3. After a page update and that task finishing, new result appears as a "child" of loaded document in the same field.
4. By clicking the button near the new result (looks like a four-cell table), a window with text from the document appears, where words for which the parser made some possible results are highlited with red background colour.
5. By clicking at a highlighted word, possible results appear at the left side of the dialog window, and user can select one of those variants using a checkbox.
6. Also user can select some text and make his own result for this word (selection).
7. After confirmation of result selections/result inputs confirmed words become highlighted with green background colour.

The back-end implementation lays in following:
1. There are two new models in models.py: Parser and ParserResult, which are mapped to database tables with same names. The field "method" in Parser table is the same as the name of the corresponding method in utils/parser.py file. New parsers should be added manually by back-end developers.
2. There are some queries for implementing the interface for front-end developers: "parsers" for resolving all parsers in the system, "parser_results"  for resolving all results for an entity, "parser_result" for resolving a specific, parser result, "execute_parser" for launching parser for an entity, "update_parser_result" for modifying a result (mostly for changing and adding a colour highlighting for a word) and "delete_parser_result".
3. "execute_parser" query starts a celery task "async_create_parser_result" from utils/creation.py (though it is possible to start a synchronous parsing by passing async=False with execute_parser query).
4. This task loads a content by the link in the entity's content and saves it into a temporary file. Then it calls a suitable method for parsing fom utils/parser.py with that file passed as a parameter. This method returns an html with the result, which is been then saved in the database.

The idea of a function timarkh_udm, which implements support of the timarkh's parser for udmurtian language in Lingvodoc lays in following:
1. Pure text string is been loaded from source odt document and tokenized, then a .csv file with the list of words frequences is been built, which is been passed to timakh's parser main function (timarkh_udm) with two filenames of temporary files created before - one for saving parsed data, another for saving unparsed words.
2. A query with the source odt is been sent to the server with Dedoc project deployed. The url of this server should present in the config for docker-compose (docker.ini) as dedoc_url parameter. The response is an html with headers in paragraphs.
3. The parsed data is been remade into a dictionary: keys are parsed words, values are dictionaries with keys - linguistic attributes and values - the values of those attributes.
4. Then the result is been constructed by wrapping those words in text that are in the dictionary which was built at the previous step in tags. The wrap seems like <span class=unverifired id={unique id}> <span class=result id={unique id}> {JSON} </span>... <span class=result id={unique_id}> {JSON} </span> WORD </span>. (unverified and verified classes are for colour highlight).

The point of this very issue is just in slight changing of result constructing process.

How it was: words from dictionary (built at step 3) were been firstly searched in the html from Dedoc and wrapped into harsh symbolic sequences, then the html was been splitted by left border of those wraps and then the result was constructed from elements from splitted list; those elements which had right border sequence were modified into an html wrap (from step 4) before appending to result string. This strange idea was to avoid a problem: when I tried to replace all occurences of each word to html wraps using regex, some replaces could wrap in tags words contained in a wrap of another wrap: for example, there is a word 'кикые' and it's wrap contains 'lex': 'кикы', so while wrapping all 'кикы' occurences, wraps of 'кикые' become incorrect.

How it is: instead of wrapping each word into harsh symbolic sequences (and wasting memory and time for lots of text copying as each string modification means its copying), a list of matches is been built bu using re.findall(). Match is a dictionary with keys: element, starting index of an occurence and ending index of an occurence. This dictionary is then been sorted by increasing of starting indices. Then in a loop result is been constructed by adding, firstly, a piece of text between the end of previous match and the start of the current match, and, secondly, a wrap for a word between the start and the end of a current match. 

The link to pull request is here: https://github.com/ispras/lingvodoc/pull/1268

**Comment by nadezhday** [comment]
I have asked steps for verification and I did not get them. So performing free testing:
Scenario:
Open http://83.149.198.62/dictionary/2684/5/perspective/2718/123/view
Click four-cell table icon.
![image](https://user-images.githubusercontent.com/59951991/95167041-9b3fee80-07b7-11eb-9449-27aa3620b630.png)

Result: Unnamed dialog appears.
Do nothing. Wait a little bit.  
![image](https://user-images.githubusercontent.com/59951991/95167178-d93d1280-07b7-11eb-8b53-b500aa242639.png)
Then in FF you can see the following message: a web page is slowing down your browser. What would you like to do?

**Comment by nadezhday** [comment]
Try to close this dialog.
It is not possible!
![image](https://user-images.githubusercontent.com/59951991/95168538-1efada80-07ba-11eb-9721-19aecbf854e6.png)

**Comment by nadezhday** [comment]
Separate defects were created: 
https://github.com/ispras/lingvodoc-react/issues/353 Improve dialog that appears after clicking a four-cell table
https://github.com/ispras/lingvodoc-react/issues/354 Clicking on zoom-slider in dialog that appeared after clicking a four-cell table: Uncaught TypeError: this.buffer is undefined

**Comment by nadezhday** [comment]
"By clicking the button near the new result (looks like a four-cell table), a window with text from the document appears, where words for which the parser made some possible results are highlited with red background colour."

Question: What corpora should I use to see red background color? 
![image](https://user-images.githubusercontent.com/59951991/95172581-30df7c00-07c0-11eb-8750-a4adf40b0e8a.png)

**Comment by nadezhday** [comment]
Comment from  @ankan2013. Functionality has not been merged in master yet.

Waiting  with testing.

**Comment by jandrew44** [comment]
This task is related to the corpora text markup functionality that was deployed in production about 1,5 years ago.
Can be closed.

**Comment by nadezhday** [comment]
Closing without verification
