### ISSUE TITLE
Improve performance for loading page with dictionaries

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#355]
Open http://lingvodoc.ispras.ru/LanguagesDatabasesRoute
Click on Dictionaries.
Problem: we can see the following empty "loading" page for about 10 sec
Comments from Y.V.Normanskaya: it took 5 min to load the page. Our ministers got negative impression... 

![image](https://user-images.githubusercontent.com/59951991/95189225-42cc1980-07d6-11eb-904b-e1ade5ff8a1b.png)

Can we improve this functionality?

**Comment by jandrew44** [comment]
Improved by the #720 enhancement.

**Comment by nadezhday** [comment]
Verified

**Comment by nadezhday** [comment]
Should be covered in selenium.
