### ISSUE TITLE
Disable all dictionaries by default in Map-distance dialog

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#362]
http://83.149.198.62/distance_map
Find Dictionary of Komi-Yazva language (Р.И.Идрисов), 
Select dictionaries.
Expand the appeared tree.

Problem: all checkboxes are selected. 
![image](https://user-images.githubusercontent.com/59951991/96675265-3b2e7800-1373-11eb-8de0-f5dc378fc9e5.png)

The user will have to press Uncheck all button and then select what he wants.
So I suggest to uncheck all these checkboxes by default.

@elmedweb

**Comment by nadezhday** [comment]
More testing:
If we do not uncheck all and press Next 
we will get  Exception
Uncaught (in promise) Error: Network error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    e ApolloError.js:37
    error QueryManager.js:212
    d Observable.js:130
    h Observable.js:161
    value Observable.js:220
    error index.js:55
    d Observable.js:130
    h Observable.js:161
    value Observable.js:220
    l index.js:98
    promise callback*l/</< index.js:94
    t Observable.js:179
    value Observable.js:258
    o index.js:19
    t Observable.js:179
    value Observable.js:258
    mutate QueryManager.js:183
    mutate QueryManager.js:124
    mutate ApolloClient.js:98
    dataForChildViaMutation react-apollo.browser.umd.js:544
    e getDistancePerspectives.js:106
    r runtime.js:65
    u runtime.js:299
    e runtime.js:117
    i client.92f90fe3.js:32424
    i client.92f90fe3.js:32424
    i client.92f90fe3.js:32424
    d getDistancePerspectives.js:5
    e map.js:141
    r runtime.js:65
    u runtime.js:299
    e runtime.js:117
    i client.92f90fe3.js:32109
    i client.92f90fe3.js:32109
    i client.92f90fe3.js:32109
    e client.92f90fe3.js:32350
    value map.js:109
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 5
    d raven.js:393
    b raven.js:1046
    React 15
    i index.js:66
    1282 index.js:80
    Webpack 5
ApolloError.js:37
    i client.92f90fe3.js:32109
    i client.92f90fe3.js:32109
    (Async: promise callback)
    i client.92f90fe3.js:32109
    i client.92f90fe3.js:32109
    i client.92f90fe3.js:32109
    e client.92f90fe3.js:32350
    value map.js:109
    React 2
    oi self-hosted:1265
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
    qr self-hosted:1208
    Ke React
    unstable_runWithPriority scheduler.production.min.js:19
    React 5
    bind_applyFunctionN self-hosted:1359
    At self-hosted:1322
    d raven.js:393
    (Async: EventListener.handleEvent)
    b raven.js:1046
    React 15
    i index.js:66
    1282 index.js:80
    Webpack 5

And never ending progress on the page.
![image](https://user-images.githubusercontent.com/59951991/96678376-3b7e4180-137a-11eb-8afb-ac22d5ef8178.png)

**Comment by nadezhday** [comment]
Testing: all checkboxes are OFF by default - OK

We can close this issue.

The scenario with all checkboxes are ON and clicking Next is reported as separate defect: https://github.com/ispras/lingvodoc-react/issues/374 - Distance map: check all -> Response: 502 Bad Gateway

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_distance_map.py
