### ISSUE TITLE
Distance map: Make working area for language selection bigger.

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#363]
http://83.149.198.62/distance_map
Find Dictionary of Komi-Yazva language (Р.И.Идрисов),
Select dictionaries.
Try to expand the tree and select dictionaries.

Problem: We need to have more working area for dictionaries. And should use almost all screen (Just leave Back and Next buttons on the bottom)
![image](https://user-images.githubusercontent.com/59951991/96675689-20103800-1374-11eb-92f9-ca766a8fc8a2.png)

**Comment by nadezhday** [comment]
@elmedweb  FYI

**Comment by myrix** [comment]
Fixed by (probably) https://github.com/ispras/lingvodoc-react/commit/eb88def4a0cad4b6bb19867261488d2eddbef932 and later changes.
