### ISSUE TITLE
Sometimes list of grant is missing on Grants page.

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#366]
The problem found during verification of https://github.com/ispras/lingvodoc-react/issues/343 
![image](https://user-images.githubusercontent.com/59951991/97272377-df686100-1842-11eb-9f10-703ac8750de2.png)

Steps to reproduce: 
I cannot provide exact steps to reproduce right now.

@elmedweb FYI

**Comment by nadezhday** [comment]
Sometimes you can see Russian text in English version and varsa versa
![image](https://user-images.githubusercontent.com/59951991/97275051-83074080-1846-11eb-87e0-f44d2a73b918.png)

**Comment by elmedweb** [comment]
You need more details to play the error. Unable to play it
![Screenshot from 2020-10-30 20-02-43](https://user-images.githubusercontent.com/40824202/97708353-41e38a80-1aeb-11eb-8727-fa9fb0dd0258.png)

**Comment by nadezhday** [comment]
It looks like we have the same problem with Version
![image](https://user-images.githubusercontent.com/59951991/97953583-0a5a3400-1db2-11eb-97f6-dcd86b118096.png)

Backend is empty.

**Comment by nadezhday** [comment]
Do we have any timeout for getting Backend Version info?
The separate defect for Empty backend version is created (with exact steps to reproduce): https://github.com/ispras/lingvodoc-react/issues/377 - Backend version becomes empty after switching languages

**Comment by nadezhday** [comment]
Do we have any timeout for getting Grants list info? 
There were similar steps for getting empty Grants list.
Reproduced:
![image](https://user-images.githubusercontent.com/59951991/97954596-0845a480-1db5-11eb-9f24-a4c474dc6464.png)

**Comment by nadezhday** [comment]
[2020-11-03 09-15-15_grants_problem.zip](https://github.com/ispras/lingvodoc-react/files/5479512/2020-11-03.09-15-15_grants_problem.zip)

From the attached video you can see that sometimes the list appears with a delay.
The approx steps to reproduce.
1) open main page (by clicking Lingvodoc.3.0)
2) change to Russian language
3) Open Grants menu
Sometimes we do not see the list of grants

**Comment by nadezhday** [comment]
The problem is reproduced in 
Backend:2.1.1+1302-3bf1c138-2020.12.02-02:39+modified-2020.12.14-21:46
Frontend:36e52e00-410-staging-server

**Comment by nadezhday** [comment]
I have not seen this problem resently. Closing as fixed indirectly.
