### ISSUE TITLE
Align text Backed and Frontend in versions page to the left

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#367]
Open http://83.149.198.62/version_route

![image](https://user-images.githubusercontent.com/59951991/97290635-e058bd00-1859-11eb-914c-4124e5b94e70.png)

Will it be better to have backend and frontend aligned to the left  
![image](https://user-images.githubusercontent.com/59951991/97291102-83a9d200-185a-11eb-915d-14d84b20e900.png)

Now it does not look nice.

@elmedweb  FYI

**Comment by nadezhday** [comment]
Right now we have the following:
![image](https://user-images.githubusercontent.com/59951991/97839539-6e69f300-1cf3-11eb-9314-fd924c15bfa6.png)

Can we move Frontend to the left?
@elmedweb

**Comment by nadezhday** [comment]
It looks like that we have fixed this problem. Should we close it?
![image](https://user-images.githubusercontent.com/59951991/138858416-b45c23f5-e45f-4c75-ad66-14580ac3fe7d.png)

**Comment by Dina936** [comment]
@nadezhday yes, we close
