### ISSUE TITLE
Odt corpus parser added (New feature)

### ISSUE THREAD

**Issue by IgorBMSTU** [ispras/lingvodoc-react#369]
Text markup + Proposed variants

**Comment by nadezhday** [comment]
Is this functionality fixed? 
Is it ready for verification? It is still in Open state.
What steps should be performed to verify this issue?

**Comment by jandrew44** [comment]
It is related to the corpus markup feature.
Was implemented a long time ago.

**Comment by nadezhday** [comment]
Closed without verification
