### ISSUE TITLE
Open lexical view for dictionary: Unhandled error GraphQL error: Cannot query field "is_subject_for_parsing" on type "Entity"

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#371]
Selenium test failed: test_view_lexical.py
Steps to reproduce:
Login as julianor
Open http://83.149.198.62/dashboard/dictionaries_all
Find 'Dictionary of Forest dialect of Enets language (1970)'
Click view ->Lexical Entries

The same problem with 'Dictionary of Yukonda dialect of Mansi'

![изображение](https://user-images.githubusercontent.com/59951991/97536632-82011b00-19ce-11eb-9371-380538ec74c8.png)

Unhandled error GraphQL error: Cannot query field "is_subject_for_parsing" on type "Entity". e@http://83.149.198.62/assets/vendor.cd496b26.js:1:703740
_</t.prototype.queryListenerForObserver/<@http://83.149.198.62/assets/vendor.cd496b26.js:1:5254819
_</t.prototype.broadcastQueries/</<@http://83.149.198.62/assets/vendor.cd496b26.js:1:5261240
_</t.prototype.broadcastQueries/<@http://83.149.198.62/assets/vendor.cd496b26.js:1:5261219
_</t.prototype.broadcastQueries@http://83.149.198.62/assets/vendor.cd496b26.js:1:5261126
next@http://83.149.198.62/assets/vendor.cd496b26.js:1:5262299
d@http://83.149.198.62/assets/vendor.cd496b26.js:1:5236346
h@http://83.149.198.62/assets/vendor.cd496b26.js:1:5236739
value@http://83.149.198.62/assets/vendor.cd496b26.js:1:5237758
next/<@http://83.149.198.62/assets/vendor.cd496b26.js:1:5265312
next@http://83.149.198.62/assets/vendor.cd496b26.js:1:5265285
d@http://83.149.198.62/assets/vendor.cd496b26.js:1:5236346
h@http://83.149.198.62/assets/vendor.cd496b26.js:1:5236739
value@http://83.149.198.62/assets/vendor.cd496b26.js:1:5237758
next@http://83.149.198.62/assets/vendor.cd496b26.js:1:5301063
d@http://83.149.198.62/assets/vendor.cd496b26.js:1:5236346
h@http://83.149.198.62/assets/vendor.cd496b26.js:1:5236739
value@http://83.149.198.62/assets/vendor.cd496b26.js:1:5237758
l/</</<@http://83.149.198.62/assets/vendor.cd496b26.js:1:5298123
promise callback*l/</<@http://83.149.198.62/assets/vendor.cd496b26.js:1:5298104
t@http://83.149.198.62/assets/vendor.cd496b26.js:1:5237411
value@http://83.149.198.62/assets/vendor.cd496b26.js:1:5238388
o/</<@http://83.149.198.62/assets/vendor.cd496b26.js:1:5300855
t@http://83.149.198.62/assets/vendor.cd496b26.js:1:5237411
value@http://83.149.198.62/assets/vendor.cd496b26.js:1:5238388
o</e.prototype.request/l<@http://83.149.198.62/assets/vendor.cd496b26.js:1:5265211
t@http://83.149.198.62/assets/vendor.cd496b26.js:1:5237411
value@http://83.149.198.62/assets/vendor.cd496b26.js:1:5238388
_</t.prototype.fetchRequest/<@http://83.149.198.62/assets/vendor.cd496b26.js:1:5261980
_</t.prototype.fetchRequest@http://83.149.198.62/assets/vendor.cd496b26.js:1:5261888
_</t.prototype.fetchQuery@http://83.149.198.62/assets/vendor.cd496b26.js:1:5253773
_</t.prototype.startQuery@http://83.149.198.62/assets/vendor.cd496b26.js:1:5259379
f</e.prototype.setUpQuery@http://83.149.198.62/assets/vendor.cd496b26.js:1:697823
f</e.prototype.onSubscribe@http://83.149.198.62/assets/vendor.cd496b26.js:1:697043
e/a<@http://83.149.198.62/assets/vendor.cd496b26.js:1:691472
t@http://83.149.198.62/assets/vendor.cd496b26.js:1:5237411
value@http://83.149.198.62/assets/vendor.cd496b26.js:1:5238388
i/a</l.prototype.subscribeToQuery@http://83.149.198.62/assets/vendor.cd496b26.js:1:70975
i/a</l.prototype.componentDidMount@http://83.149.198.62/assets/vendor.cd496b26.js:1:66965
Tr@http://83.149.198.62/assets/vendor.cd496b26.js:1:1284211
oi@http://83.149.198.62/assets/vendor.cd496b26.js:1:1301612
e.unstable_runWithPriority@http://83.149.198.62/assets/vendor.cd496b26.js:1:1346282
qe@http://83.149.198.62/assets/vendor.cd496b26.js:1:1250570
ii@http://83.149.198.62/assets/vendor.cd496b26.js:1:1298270
qr@http://83.149.198.62/assets/vendor.cd496b26.js:1:1294362
Ke/<@http://83.149.198.62/assets/vendor.cd496b26.js:1:1250860
e.unstable_runWithPriority@http://83.149.198.62/assets/vendor.cd496b26.js:1:1346282
qe@http://83.149.198.62/assets/vendor.cd496b26.js:1:1250570
Ke@http://83.149.198.62/assets/vendor.cd496b26.js:1:1250808
Ge@http://83.149.198.62/assets/vendor.cd496b26.js:1:1250741
Fr@http://83.149.198.62/assets/vendor.cd496b26.js:1:1290922
enqueueForceUpdate@http://83.149.198.62/assets/vendor.cd496b26.js:1:1330429
i.prototype.forceUpdate@http://83.149.198.62/assets/vendor.cd496b26.js:1:1222662
i/a</l.prototype.forceRenderChildren@http://83.149.198.62/assets/vendor.cd496b26.js:1:71317
e@http://83.149.198.62/assets/vendor.cd496b26.js:1:70828
d@http://83.149.198.62/assets/vendor.cd496b26.js:1:5236346
h@http://83.149.198.62/assets/vendor.cd496b26.js:1:5236739
value@http://83.149.198.62/assets/vendor.cd496b26.js:1:5237758
next/<@http://83.149.198.62/assets/vendor.cd496b26.js:1:697699
next@http://83.149.198.62/assets/vendor.cd496b26.js:1:697662
_</t.prototype.queryListenerForObserver/<@http://83.149.198.62/assets/vendor.cd496b26.js:1:5255863
_</t.prototype.broadcastQueries/</<@http://83.149.198.62/assets/vendor.cd496b26.js:1:5261240
_</t.prototype.broadcastQueries/<@http://83.149.198.62/assets/vendor.cd496b26.js:1:5261219
_</t.prototype.broadcastQueries@http://83.149.198.62/assets/vendor.cd496b26.js:1:5261126
next@http://83.149.198.62/assets/vendor.cd496b26.js:1:5262299
d@http://83.149.198.62/assets/vendor.cd496b26.js:1:5236346
h@http://83.149.198.62/assets/vendor.cd496b26.js:1:5236739
value@http://83.149.198.62/assets/vendor.cd496b26.js:1:5237758
next/<@http://83.149.198.62/assets/vendor.cd496b26.js:1:5265312
next@http://83.149.198.62/assets/vendor.cd496b26.js:1:5265285
d@http://83.149.198.62/assets/vendor.cd496b26.js:1:5236346
h@http://83.149.198.62/assets/vendor.cd496b26.js:1:5236739
value@http://83.149.198.62/assets/vendor.cd496b26.js:1:5237758
next@http://83.149.198.62/assets/vendor.cd496b26.js:1:5301063
d@http://83.149.198.62/assets/vendor.cd496b26.js:1:5236346
h@http://83.149.198.62/assets/vendor.cd496b26.js:1:5236739
value@http://83.149.198.62/assets/vendor.cd496b26.js:1:5237758
l/</</<@http://83.149.198.62/assets/vendor.cd496b26.js:1:5298123
promise callback*l/</<@http://83.149.198.62/assets/vendor.cd496b26.js:1:5298104
t@http://83.149.198.62/assets/vendor.cd496b26.js:1:5237411
value@http://83.149.198.62/assets/vendor.cd496b26.js:1:5238388
o/</<@http://83.149.198.62/assets/vendor.cd496b26.js:1:5300855
t@http://83.149.198.62/assets/vendor.cd496b26.js:1:5237411
value@http://83.149.198.62/assets/vendor.cd496b26.js:1:5238388
o</e.prototype.request/l<@http://83.149.198.62/assets/vendor.cd496b26.js:1:5265211
t@http://83.149.198.62/assets/vendor.cd496b26.js:1:5237411
value@http://83.149.198.62/assets/vendor.cd496b26.js:1:5238388
_</t.prototype.fetchRequest/<@http://83.149.198.62/assets/vendor.cd496b26.js:1:5261980
_</t.prototype.fetchRequest@http://83.149.198.62/assets/vendor.cd496b26.js:1:5261888
_</t.prototype.fetchQuery@http://83.149.198.62/assets/vendor.cd496b26.js:1:5253773
_</t.prototype.startQuery@http://83.149.198.62/assets/vendor.cd496b26.js:1:5259379
f</e.prototype.setUpQuery@http://83.149.198.62/assets/vendor.cd496b26.js:1:697823
f</e.prototype.onSubscribe@http://83.149.198.62/assets/vendor.cd496b26.js:1:697043
e/a<@http://83.149.198.62/assets/vendor.cd496b26.js:1:691472
t@http://83.149.198.62/assets/vendor.cd496b26.js:1:5237411
value@http://83.149.198.62/assets/vendor.cd496b26.js:1:5238388
i/a</l.prototype.subscribeToQuery@http://83.149.198.62/assets/vendor.cd496b26.js:1:70975
i/a</l.prototype.componentDidMount@http://83.149.198.62/assets/vendor.cd496b26.js:1:66965
Tr@http://83.149.198.62/assets/vendor.cd496b26.js:1:1284211
oi@http://83.149.198.62/assets/vendor.cd496b26.js:1:1301612
e.unstable_runWithPriority@http://83.149.198.62/assets/vendor.cd496b26.js:1:1346282
qe@http://83.149.198.62/assets/vendor.cd496b26.js:1:1250570
ii@http://83.149.198.62/assets/vendor.cd496b26.js:1:1298270
qr@http://83.149.198.62/assets/vendor.cd496b26.js:1:1294362
Ke/<@http://83.149.198.62/assets/vendor.cd496b26.js:1:1250860
e.unstable_runWithPriority@http://83.149.198.62/assets/vendor.cd496b26.js:1:1346282
raven.js:55:31
    b raven.js:55
    error ObservableQuery.js:295
    d Observable.js:130
    f Observable.js:112
    h Observable.js:156
    l Observable.js:67
    (Async: promise callback)
    l Observable.js:65
    h Observable.js:155
    value Observable.js:220
    onSubscribe ObservableQuery.js:302
    a ObservableQuery.js:43
    t Observable.js:179
    value Observable.js:258
    recycle react-apollo.browser.umd.js:38
    componentWillUnmount react-apollo.browser.umd.js:344
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    unlisten Router.js:70
    n createTransitionManager.js:54
    notifyListeners createTransitionManager.js:73
    notifyListeners createTransitionManager.js:72
    k createBrowserHistory.js:95
    O createBrowserHistory.js:120
    n createTransitionManager.js:44
    O createBrowserHistory.js:118
    M createBrowserHistory.js:102
    d raven.js:393
    (Async: EventListener.handleEvent)
    b raven.js:1046
    addEventListener DOMUtils.js:7
    N createBrowserHistory.js:248
    Y createBrowserHistory.js:282
    componentWillMount Redux
    React 12
    i index.js:66
    1284 index.js:80
    Webpack 5

**Comment by myrix** [comment]
No error with latest backend version.

**Comment by nadezhday** [comment]
Works fine.
