### ISSUE TITLE
Can't change dictionary name

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#378]
Open http://83.149.198.62/dictionary/1393/29131/perspective/1393/29132/view logged in as julianor, open dictionary properties, try to change both english name translation entries to something new, e.g. 'abc', one of the translation updates does not finish properly, 'Update' button remains active.
![image](https://user-images.githubusercontent.com/2802467/98452605-ec9a1f80-2161-11eb-9af5-bd69dd5cc7a8.png)
![image](https://user-images.githubusercontent.com/2802467/98452609-ef951000-2161-11eb-993c-ce66820dde7a.png)
![image](https://user-images.githubusercontent.com/2802467/98452610-f15ed380-2161-11eb-88b9-f8b13fabedff.png)

Close and open properties again, one of the translations is unchanged:
![image](https://user-images.githubusercontent.com/2802467/98452614-03d90d00-2162-11eb-88c4-eae2208469df.png)

**Comment by myrix** [comment]
Fixed, now can change both translations successfully.

**Comment by nadezhday** [comment]
Well, this functionality works. Dictionary name can be updated. OK.
We can verify this issue.

BUT
One more problem: After closing dialog you have to press F5 to see the changed name:
![image](https://user-images.githubusercontent.com/59951991/98513692-50fbd280-2279-11eb-888b-40f841b5f02f.png)
@myrix  should I create a separate defect for found issue? Will it be fixed?

**Comment by myrix** [comment]
> @myrix should I create a separate defect for found issue? Will it be fixed?

Yeah, I think it needs separate issue.
