### ISSUE TITLE
Updated Dictionary name: Refresh page is required to see the changes

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#379]
problem is found during testing https://github.com/ispras/lingvodoc-react/issues/378

Open http://83.149.198.62/dictionary/1393/29131/perspective/1393/29132/view logged in as julianor, open dictionary properties, try to change both english name translation entries to something new, e.g. 'abc', 
Click Update 
Click Update
![image](https://user-images.githubusercontent.com/59951991/98517112-7a6b2d00-227e-11eb-91eb-57381cf6ac6b.png)

Close dialog.
Problem: Name of dictionary is not changed
![image](https://user-images.githubusercontent.com/59951991/98517275-b3a39d00-227e-11eb-8cd7-b1df87cf46d5.png)

Workaround: You need to press F5 to see it.

**Comment by jandrew44** [comment]
Fixed.

**Comment by vmonakhov** [comment]
Duplicate of #825. Covered in tesst/test_dictionaries.py
