### ISSUE TITLE
Correct import of Excel-exported CSVs in 'Import Starling dictionaries'

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#381]
Users need to import dictionaries from Excel-exported CSVs, e.g. [ненецкий 1.csv.zip](https://github.com/ispras/lingvodoc-react/files/5610517/1.csv.zip), just like it is possible to import dictionaries from Starling-exported CSVs.

Right now such CSVs do not parse correctly, and obviously dictionary import from them does not work:
![image](https://user-images.githubusercontent.com/2802467/100514806-afd1af00-3188-11eb-90f9-909141d03bea.png)

**Comment by myrix** [comment]
Implemented, now such files can be imported as dictionaries through 'Import Starling dictionaries'.

E.g. unzip and import [ненецкий 1.csv.zip](https://github.com/ispras/lingvodoc-react/files/5610517/1.csv.zip) through 'My files' as a 'Starling'-type file, and import dictionary from it through 'Import Starling dictionaries' as follows:
![image](https://user-images.githubusercontent.com/2802467/100514933-bd3b6900-3189-11eb-920c-19c55f07b3e3.png)
![image](https://user-images.githubusercontent.com/2802467/100514935-c3c9e080-3189-11eb-99dc-55ee4129dce3.png)
![image](https://user-images.githubusercontent.com/2802467/100514937-c62c3a80-3189-11eb-98d3-ae13a3be6fd8.png)

Import works, resulting dictionary:
![image](https://user-images.githubusercontent.com/2802467/100514944-cdebdf00-3189-11eb-9178-3b8011f52621.png)

**Comment by nadezhday** [comment]
1) 
Backend:2.1.1+1302-3bf1c138-2020.12.02-02:39+modified-2020.12.08-02:31
Frontend:0db6a820-407-staging-server

http://83.149.198.62/import

![image](https://user-images.githubusercontent.com/59951991/101444385-6f182980-3930-11eb-9c74-f1382f4357e3.png)

NOK

2) I do not know if I can test this functionality on http://lingvodoc.ispras.ru/files

Waiting for the last version to be uploaded on  http://83.149.198.62/

**Comment by myrix** [comment]
Backend:2.1.1+1302-3bf1c138-2020.12.02-02:39+modified-2020.12.08-07:05
Frontend:7f885369-408-staging-server

Uploads ok, both as a standard user:
![image](https://user-images.githubusercontent.com/2802467/101489111-87f4ff00-3971-11eb-8139-d11fcfdc0ddf.png)
And as admin:
![image](https://user-images.githubusercontent.com/2802467/101489125-8f1c0d00-3971-11eb-849e-b3127c4cdec3.png)

Maybe page should be refreshed for the file to become visible? Also CSV files should be uploaded as 'Starling'-type:
![image](https://user-images.githubusercontent.com/2802467/101489535-22554280-3972-11eb-860e-27ee2125c5eb.png)
![image](https://user-images.githubusercontent.com/2802467/101489567-2b461400-3972-11eb-85d6-10ee087640ff.png)

**Comment by nadezhday** [comment]
Verification:
Both for admin and user - OK

**Comment by nadezhday** [comment]
For found problems separate defects will be created
1) Sometimes Refresh is needed (at least for non-admin user) before you can see csv file
![image](https://user-images.githubusercontent.com/59951991/101725533-e4ffca80-3ac1-11eb-8f1f-3e6a2e551585.png)
https://github.com/ispras/lingvodoc-react/issues/385  Import starling dictionaries: Sometimes Refresh page is needed to see uploaded file

2) https://github.com/ispras/lingvodoc-react/issues/384 Import starling dictionaries: Disable button Submit until user selects important options in Language section
