### ISSUE TITLE
Perspective view: sort alphabetically by 'Meaning' by default

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#383]
Open http://lingvodoc.ispras.ru/dictionary/3442/9575/perspective/3442/9576/edit, lexical entries are not sorted by default:
![image](https://user-images.githubusercontent.com/2802467/101428944-d1fac800-3912-11eb-9356-21b00d311625.png)

It would be better if they are sorted alphabetically by field 'Meaning', if it's present.

**Comment by myrix** [comment]
Implemented, opening the same perspective now:
![image](https://user-images.githubusercontent.com/2802467/101429121-37e74f80-3913-11eb-8b54-14c8b325e489.png)

**Comment by nadezhday** [comment]
Backend:2.1.1+1302-3bf1c138-2020.12.02-02:39
Frontend:7f885369-408-staging-server
http://lingvodoc.ispras.ru/dictionary/3442/9575/perspective/3442/9576/edit
![image](https://user-images.githubusercontent.com/59951991/101443096-ab965600-392d-11eb-91bb-4b646c1ed6b4.png)

Well done.
Verified.

**Comment by nadezhday** [comment]
@myrix what should we do with Meaning->Glossing? Should it be sorted alphabetically? If 'Yes' I will create a separate issue.
1) 
http://83.149.198.62/dictionary/1024/40/perspective/1024/45/edit
![image](https://user-images.githubusercontent.com/59951991/101442366-44c46d00-392c-11eb-9f18-7cccef00f9eb.png)

2) Should our sorting work in this case?
http://83.149.198.62/dictionary/2654/9320/perspective/2654/9324/view
![image](https://user-images.githubusercontent.com/59951991/101442646-cb794a00-392c-11eb-996c-dcda6a8b9757.png)

![image](https://user-images.githubusercontent.com/59951991/101442713-ee0b6300-392c-11eb-9041-0376391a15ee.png)

**Comment by nadezhday** [comment]
my last comment is not valid.
http://83.149.198.62/version_route
Backend:2.1.1+1302-3bf1c138-2020.12.02-02:39+modified-2020.12.08-02:31
Frontend:0db6a820-407-staging-server

**Comment by myrix** [comment]
> @myrix what should we do with Meaning->Glossing? Should it be sorted alphabetically? If 'Yes' I will create a separate issue.

As far as I understand, as Glossing is a subordinate field, it should not influence sorting, entries should only be sorted by Meaning; current implementation should do exactly that, so separate issue is not required.

**Comment by nadezhday** [comment]
Backend:2.1.1+1302-3bf1c138-2020.12.02-02:39+modified-2020.12.09-03:22
Frontend:7f885369-408-staging-server

Verified. All scenario work fine.

**Comment by nadezhday** [comment]
Selenium tests are updated.
