### ISSUE TITLE
Import starling dictionaries: Disable button Submit until user selects important options in Language section

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#384]
Problem found during verification https://github.com/ispras/lingvodoc-react/issues/381
Steps can be found in #381.
Login as julianor
Select My files
select file ненецкий 1.csv
Choose from down menu option 'Starling'
Upload
[ненецкий 1.zip](https://github.com/ispras/lingvodoc-react/files/5670573/1.zip)
Dashboard->Import Starling dictionaries
Click 'Base blob'
![image](https://user-images.githubusercontent.com/59951991/101727519-aff57700-3ac5-11eb-8b70-f5616814af2e.png)

Problem: can we rename it somehow? What does this mean?
Select ненецкий 1.csv
![image](https://user-images.githubusercontent.com/59951991/101727563-c3a0dd80-3ac5-11eb-8b44-491b11bbdb6b.png)

Next step
Next
In Language section enter translations and click SUBMIT

Problem: If you do not select parent language you will get exception in console.
![image](https://user-images.githubusercontent.com/59951991/101727856-55a8e600-3ac6-11eb-916c-2560bf787ba0.png)

If something important is not selected (in this case Parent Language) we should not make our buttons available (Submit).
![image](https://user-images.githubusercontent.com/59951991/101728020-af111500-3ac6-11eb-89dc-a98bb0224d31.png)

If we cannot disable Submit It would be nice to add at least notification for user: Select Parent language.

Uncaught TypeError: n is undefined
    r api.js:54
    o api.js:64
    Immutable 5
    o api.js:63
    value index.js:148
    Lodash 4
    e Button.js:103
    React 12
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
    d raven.js:393
    b raven.js:1046
    React 15
    i index.js:66
    1284 index.js:80
    Webpack 5

**Comment by myrix** [comment]
Implemented.

Go to step 3 of Starling dictionary import e.g. by following steps in #397. Until parent language is selected for each base CSV, 'Submit' button is absent and a corresponding message is displayed instead:
![image](https://user-images.githubusercontent.com/2802467/107549111-7c77bb80-6be0-11eb-9d2d-4ce6270892f9.png)

Select any parent language by clicking on the 'Select Parent Language' button, message disappears and 'Submit' button appears:
![image](https://user-images.githubusercontent.com/2802467/107549356-c496de00-6be0-11eb-82e5-9498ddd0f358.png)

**Comment by yesandv** [comment]
Verified.

![384-Disable-Submit-Button](https://user-images.githubusercontent.com/73657817/108485815-60de7600-72ae-11eb-95de-0557ddd3e21f.png)

**Comment by vmonakhov** [comment]
If no any title is set Submit pressing leads to GraphQL error
![2023-04-07_17-09-19 (2)](https://user-images.githubusercontent.com/18721530/230623812-6f5238a4-d7e6-4007-b3b3-fcde4087f5b6.png)

**Comment by myrix** [comment]
Fixed.

Backend now handles no translations alright, and frontend does not allow to submit until all languages have at least one non-empty translation:
![image](https://user-images.githubusercontent.com/2802467/230650030-5a6dac6a-9052-49db-a813-61f583f8f160.png)

**Comment by vmonakhov** [comment]
Covered in tests/test_import_starling_dict_02.py
