### ISSUE TITLE
Import starling dictionaries: Sometimes Refresh page is needed to see uploaded file

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#385]
Problem found during verification #381
Steps can be found in #381.
Login as julianor
Select My files
select file ненецкий 1.csv
Choose from down menu option 'Starling'
Upload
ненецкий 1.zip
Dashboard->Import Starling dictionaries
Click 'Base blob'

Problem: Sometimes you do not see the file that was uploaded
Workaround: you have to press F5

Expected: User should not refresh page. He should find this uploaded file immediately.

**Comment by myrix** [comment]
Fixed.

Go to Starling dictionary import either through /import suburl or through home page -> Dashboard -> Import Starling dictionaries, note files available for import, e.g.:
![image](https://user-images.githubusercontent.com/2802467/107552475-a03d0080-6be4-11eb-9321-fcbb2339a933.png)

Go to 'My files' through user menu,
![image](https://user-images.githubusercontent.com/2802467/107552525-ad59ef80-6be4-11eb-8340-97bd6e2e34fe.png)
upload a suitable file, e.g. unpacked [ненецкий 1 (1).csv.zip](https://github.com/ispras/lingvodoc-react/files/5960449/1.1.csv.zip) as a Starling-type file by first selecting the file and then selecting its type (order of selection matters!) and then clicking 'Upload' button:
![image](https://user-images.githubusercontent.com/2802467/107552796-06c21e80-6be5-11eb-988d-9e7fa01ea690.png)

Wait for upload to finish,
![image](https://user-images.githubusercontent.com/2802467/107552873-1e010c00-6be5-11eb-8531-f7314d55b5a0.png)
then go back to Starling dictionary import through 'Go back one page' browser navigation or through upper left corner Lingvodoc 3.0 -> Dashboard -> Import Starling dictionaries, uploaded file is available for import without page refresh:
![image](https://user-images.githubusercontent.com/2802467/107553143-746e4a80-6be5-11eb-94b3-e07ee8f0b045.png)

**Comment by yesandv** [comment]
Verified.

**Comment by vmonakhov** [comment]
Covered in selenium
