### ISSUE TITLE
'Cognate ...' tools accessible only to the administrator

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#387]
As of now, all 'Cognate ...' tools ---
![image](https://user-images.githubusercontent.com/2802467/102242907-a035c280-3f0b-11eb-8648-2b49b0fca379.png)
--- should be accessible only to the administrator.

**Comment by myrix** [comment]
Implemented, now non-administrator users do not have access to 'Cognate ...' tools:
![image](https://user-images.githubusercontent.com/2802467/102247846-8d25f100-3f11-11eb-82b9-12ba137a3f8a.png)

If non-administrator user tries to use 'Cognate ...' tools API directly, they will receive an error.

Administrator has access to the tools:
![image](https://user-images.githubusercontent.com/2802467/102247968-b5155480-3f11-11eb-9ca8-b7471c1aafa1.png)

For administrator these tools work as usual.

**Comment by nadezhday** [comment]
Covered in selenium test (test_cognate_analysis.py)
Other tests were updated (login as admin)
Remove test for #270 (not needed)
