### ISSUE TITLE
Let all users to use Distance map

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#388]
https://github.com/ispras/lingvodoc-react/issues/387:

Backend:2.1.1+1304-cd1256e1-2020.12.15-17:07+modified-2020.12.16-05:23
Frontend:6506ba70-411-staging-server

Selenium test detected a regression.
test_tools_distance_map.py - FAIL

Steps to reproduce:
Login as julianor
Tools->Distance map

Find 'Dictionary Upper Pelym dialect of Mansi language, author priest K.Slovcov,  1905' and click Select dictionary button.
![image](https://user-images.githubusercontent.com/59951991/102448049-51d70f80-4042-11eb-90c0-9ba52ffe6eab.png)

 Expand Uralic, Mansi, Western dialect nodes

Select checkbox for Dictionary of Mansi language, compiled by archpriest Simeon Cherkalov (Solikamsk city, 1783)

![image](https://user-images.githubusercontent.com/59951991/102448165-a11d4000-4042-11eb-9d04-99bca2a06f1d.png)

Click Next

Expected: Dots on the map
Actual: 
GraphQL error: Only administrator can pefrorm cognate analysis.
![image](https://user-images.githubusercontent.com/59951991/102448616-957e4900-4043-11eb-90dc-81584dbae973.png)

Workaround: you need to login as admin.

**Comment by nadezhday** [comment]
Created extra test: distance map for admin.
To be sure that this functionality works for admin user.

**Comment by myrix** [comment]
For the time being Distance map functionality would be available only for the administrator.

Tools page, not logged in:
![image](https://user-images.githubusercontent.com/2802467/103214972-07e40880-4923-11eb-9b61-d946293c142f.png)

The same when logged in as a standard user.

Tools page, logged as admin:
![image](https://user-images.githubusercontent.com/2802467/103214985-19c5ab80-4923-11eb-9484-e3940dae6da3.png)

Manually going to /distance_map, not logged in:
![image](https://user-images.githubusercontent.com/2802467/103215046-411c7880-4923-11eb-854e-ede25e138fdd.png)

The same when logged in as a standard user.

Manually going to /distance_map/selected_languages and /distance_map/selected_languages/map without proper actions at /distance_map results in redirect to /distance_map, as expected.

For admin /distance_map works as usual.

**Comment by nadezhday** [comment]
Verified. Works as described.
Selenium test updated. PASS.

**Comment by vmonakhov** [comment]
Now the tool is available for any registered (signed in) user.  In Tools section the corresponding label is hidden if you are not signed in. In this case the link /distance_map follows to info message: "Please sign in. Only registered users can work with distance map." Works as expected. Selenium test updated.
