### ISSUE TITLE
Hidden perspectives should not be accessible to unrelated users

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#389]
If the perspective is hidden, i.e. if its or its' parent dictionary status is 'Hidden', it should only be accessible to a user if it is present in the Dashboard -> Dictionaries -> Available dictionaries for that user.

E.g. http://83.149.198.62/dictionary/1574/274855/perspective/1574/274858/view should not be accessible to 'julianor' user, but should be accessible to 'modis' user.

**Comment by myrix** [comment]
Implemented:
![image](https://user-images.githubusercontent.com/2802467/102713118-dcd03800-42d6-11eb-9aca-678893dd1728.png)
![image](https://user-images.githubusercontent.com/2802467/102713137-f96c7000-42d6-11eb-8dfb-8768847e11c5.png)

**Comment by nadezhday** [comment]
Login as admin:
![image](https://user-images.githubusercontent.com/59951991/102738432-2b271a80-435b-11eb-9107-a20e4b692125.png)


Login as Julia
http://83.149.198.62/dictionary/1574/274855/perspective/1574/274858/view
Result: Perspective is hidden and you don't have permissions to access it. - OK

Questions:
1) Phonemic analysis:
![image](https://user-images.githubusercontent.com/59951991/102737746-4db83400-4359-11eb-9248-8838d03f17a5.png)

2) Statistic:
![image](https://user-images.githubusercontent.com/59951991/102737885-a7206300-4359-11eb-99cb-edf2be4fdfc9.png)
Statistic is not empty. Is this OK?

3) Phonological statistical distance computation process is started, no errors. 
@myrix, Is this expected?
![image](https://user-images.githubusercontent.com/59951991/102738028-fc5c7480-4359-11eb-9276-28869b86b929.png)
![image](https://user-images.githubusercontent.com/59951991/102738100-2f066d00-435a-11eb-8c9a-27fb62a08066.png)

4) Files generated (phonology compilation, sound and markup) are empty.
Note: If we login as administrator files are also empty. 
If user does not have any rights, should we allow to generated anything?

**Comment by myrix** [comment]
Based on discussion with @al-indigo Oleg Borisenko, hidden perspectives should not reveal anything to unauthorized users; reopening.

**Comment by myrix** [comment]
Implemented:
![image](https://user-images.githubusercontent.com/2802467/102775088-3e5ada00-439d-11eb-9462-1f7d7a9f2496.png)

**Comment by nadezhday** [comment]
Verified.
Tools, statistics etc are not available for user without permission.
![image](https://user-images.githubusercontent.com/59951991/102846878-398c3980-4422-11eb-89c5-399b50f63dff.png)

**Comment by nadezhday** [comment]
Covered in selenium test_view_lexical.py
