### ISSUE TITLE
Perspective view: sorting by column indication & unsetting

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#390]
User should be able to see by which fields lexical entries are sorted, and to unset sorting.

**Comment by myrix** [comment]
Implemented.

Current sort order is indicated by a modified direction icon:
![image](https://user-images.githubusercontent.com/2802467/103136636-1cca5d00-46d3-11eb-883a-8c877b5d9cf9.png)

Clicking on it unsets sorting, making lexical entries appear in initial server-supplied order:
![image](https://user-images.githubusercontent.com/2802467/103136654-39ff2b80-46d3-11eb-9229-1ccd55c64616.png)

**Comment by nadezhday** [comment]
http://83.149.198.62/dictionary/3066/11/perspective/3066/14/view

1) Initial: Meaning is sorted - anc  - OK
![image](https://user-images.githubusercontent.com/59951991/103188335-0c83cf00-48d9-11eb-9231-2536a00b1aa7.png)

2) Click anc direction icon one more time
Result: Unsorted
![Uploading image.png…]()

3) Click desc direction icon.
Result: Meaning is sorted by desc.

4) Click desc direction icon one more time.
Result: Meaning is unsorted.

5) Tested sorting in other columns.

Summary:
Functionality works. And we can close this case.

However, it is implemented in a specific way. User has to get used to this implementation (turning ON/OFF sorting by clicking on different icons). 
Recommendation: User should have possibility to change order by simple click on the header of the column. 
User should not click on small direction icons. It is unusual and inconvenient.

@myrix Should we create enhancement for improving this sorting feature? Or should we leave it as it is?

**Comment by nadezhday** [comment]
Or should we reopen this enhancement?

Note: selenium test test_view_lexical.test_order_meaning_01 - FAILed
If we leave this implementation as it is the test should be updated.

**Comment by nadezhday** [comment]
selenium test updated.

**Comment by myrix** [comment]
Reopening for enhancement of simple clicking on column's header.

**Comment by myrix** [comment]
Implemented.

Clicking on column's header results in following:

1. If the entries are not sorted by the column, sorting changes to sort by the column ascending.
2. If the entries are sorted by the column ascending, sorting changes to sort by the column descending.
3. If the entries are sorted by the column descending, sorting unsets and entries are shown in initial server-defined order.

**Comment by nadezhday** [comment]
Functionality works fine. It is better now.
BUT we still have a problem:
Now the user should know where to click (he has to click on the word in the column header to change the ordering)

It would be better to allow user clicking on the header to initiate reordering.
![image](https://user-images.githubusercontent.com/59951991/103260901-6f946500-49b0-11eb-8e68-5192f7fa87ad.png)

@myrix what do you think? Can we improve this?

**Comment by myrix** [comment]
> It would be better to allow user clicking on the header to initiate reordering.

Will see if it's possible.

**Comment by myrix** [comment]
Implemented.

**Comment by nadezhday** [comment]
Works. - OK
Note: that ordering is saved. 
F5 returns us to the initial state (Meaning - asc).

Selenium tests will be updated.
