### ISSUE TITLE
Dictionary / corpus search optimization

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#391]
We should try to optimize dictionary & corpus search http://lingvodoc.ispras.ru/map_search, as in particular it is quite slow for searches with a large number of selected languages and dictionaries / corpora.

**Comment by myrix** [comment]
Optimized search by moving as much as possible of filtering and collation to the DB side, achieved noticeable improvement.

Open http://lingvodoc.ispras.ru/map_search logged in as administrator, wait for all search data to load:
![image](https://user-images.githubusercontent.com/2802467/103727855-742ece00-4fed-11eb-975b-cdcac27bc217.png)

Search settings: field "Word", string "abc", as substring, additional OR-block, field "Word", string "def", as substring, do not change anything else:
![image](https://user-images.githubusercontent.com/2802467/103727928-9a546e00-4fed-11eb-80a8-96a2ca49dfa1.png)

Before optimization this search request timings, with page reloading between tries, measured 17.73 s, 17.84 s, 17.75 s, after optimization — 6.76 s, 6.74 s, 6.77 s, quite better.

**Comment by nadezhday** [comment]
Works fine. Verified.

**Comment by vmonakhov** [comment]
Updated selenium tests
