### ISSUE TITLE
Map search links

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#393]
User should be able to get a link to an instance of map search http://lingvodoc.ispras.ru/map_search, such that opening it shows map search page with the same search instance.

**Comment by myrix** [comment]
Implemented.

Go to /map_search, get results of your search by clicking on 'Search' as usual,
![image](https://user-images.githubusercontent.com/2802467/104148515-9ce70700-53e3-11eb-9b32-da64f0866e63.png)
wait for search results to load, now you can click on 'Get link to search results',
![image](https://user-images.githubusercontent.com/2802467/104148564-c869f180-53e3-11eb-9096-5eda6de6cf2f.png)
after clicking on it you will get a link to the search,
![image](https://user-images.githubusercontent.com/2802467/104148592-eafc0a80-53e3-11eb-92d1-ce1f9c2ca8f5.png)
opening it will open this search again.

NOTE: to test this on test stand http://83.149.198.62/ its DB dump should be updated to one after today 08:00 MSK, otherwise there will be discrepancies with DB schema.

**Comment by nadezhday** [comment]
Open  http://83.149.198.62/map_search
Search for: abc
![image](https://user-images.githubusercontent.com/59951991/104270779-5d372280-54aa-11eb-9f84-d610f3e346af.png)


Click Search
Result: Found 2 results - OK
![image](https://user-images.githubusercontent.com/59951991/104270887-9ec7cd80-54aa-11eb-9f9e-b809b812ea0a.png)

Click Get link to search results

Problem: Failed to get search link  - NOK (I guess this is the problem that was mentioned in NOTE)
![image](https://user-images.githubusercontent.com/59951991/104270399-7db2ad00-54a9-11eb-8c67-fea8da6a8084.png)

Exception:
Error: GraphQL error: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: relation "unstructured_data" does not exist
LINE 3: FROM unstructured_data) AS anon_1
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/api/lingvodoc/schema/query.py", line 9075, in mutate
    id_str = NewUnstructuredData.get_random_unstructured_data_id()
  File "/api/lingvodoc/schema/query.py", line 8990, in get_random_unstructured_data_id
    id_count = DBSession.query(dbUnstructuredData).count()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 3029, in count
    return self.from_self(col).scalar()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2783, in scalar
    ret = self.one()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2754, in one
    ret = self.one_or_none()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2724, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2795, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 2818, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "unstructured_data" does not exist
LINE 3: FROM unstructured_data) AS anon_1
             ^
 [SQL: 'SELECT count(*) AS count_1 \nFROM (SELECT unstructured_data.additional_metadata AS unstructured_data_additional_metadata, unstructured_data.created_at AS unstructured_data_created_at, unstructured_data.id AS unstructured_data_id, unstructured_data.client_id AS unstructured_data_client_id, unstructured_data.data AS unstructured_data_data \nFROM unstructured_data) AS anon_1']
    e ApolloError.js:37
    next QueryManager.js:186
    d Observable.js:126
    h Observable.js:161
    value Observable.js:215
    next index.js:37
    d Observable.js:126
    h Observable.js:161
    value Observable.js:215
    l index.js:91
    
    
@myrix  This is an enhancement. Let us perform more testing (if needed separate defects will be created):
 1) Try to search abc_2 in the same Search1 tab.
 Click search.
 Problems: 
 (a) Failed to get search link, please contact adiministrators. message is still present. - NOK
 (b) Incorrect "adiministrators" -> "administrators"

2) Use several Search tabs
![image](https://user-images.githubusercontent.com/59951991/104272619-983b5500-54ae-11eb-94fc-ba8a036014f7.png)
Problem: "Failed to get search link, please contact adiministrators." Failed search message in Search2 tab also appears in Search1 tab.
How many links should we have? 1 for all searches?

3) If search result is 0 we still have Link to search result. Is this OK?  In my opinion it is OK.
![image](https://user-images.githubusercontent.com/59951991/104271293-99b74e00-54ab-11eb-9f99-c626d5114cd4.png)

--------------
Testing http://lingvodoc.ispras.ru/map_search
![image](https://user-images.githubusercontent.com/59951991/104273301-b35a9480-54af-11eb-8b8f-5a467fb9a0b1.png)
Click this link.
Result: http://lingvodoc.ispras.ru/map_search/ is changed to  http://lingvodoc.ispras.ru/map_search/xUx08
How should it work? Should we open another tab in the browser?
What is the core of clicking on this link and geting the same page in the same tab?
I guess that user wants to copy this link and send it to another person (share the search results).   
Maybe it is better to do it like this:
1) User clicks the link it is copied in the cliboard and user gets the message that url was copied. User can paste this URL in the mail or somewhere else.

**Comment by nadezhday** [comment]
@academic-sakharov Andrey? Could you please help to make this functionality work on  http://83.149.198.62/ 

NOTE: to test this on test stand http://83.149.198.62/ its DB dump should be updated to one after today 08:00 MSK, otherwise there will be discrepancies with DB schema.

**Comment by myrix** [comment]
> Problem: Failed to get search link - NOK (I guess this is the problem that was mentioned in NOTE)

Correct, DB dump needs to be configured properly.

> Click this link.
> Result: http://lingvodoc.ispras.ru/map_search/ is changed to http://lingvodoc.ispras.ru/map_search/xUx08
> How should it work? Should we open another tab in the browser?
> What is the core of clicking on this link and geting the same page in the same tab?
> I guess that user wants to copy this link and send it to another person (share the search results).
> Maybe it is better to do it like this:
> 
>     1. User clicks the link it is copied in the cliboard and user gets the message that url was copied. User can paste this URL in the mail or somewhere else.

Yeah, just a link to send to somebody else or save somewhere to open later, without need to input all search configurations.

Don't think it's necessary to copy link to clipboard, standard browser context menu functionality (right click on the link to open context menu, "Copy link location" or some such) suffices.

Edit:

> How many links should we have? 1 for all searches?

Correct, 1 link for all search tabs.

**Comment by nadezhday** [comment]
Backend:2.1.1+1310-1bd4d3e0-2021.01.11-04:34+modified-2021.01.12-06:36
Frontend:499f692b-419-staging-server:

(b) Incorrect "adiministrators" -> "administrators"  - Failed to get search link, please contact administrators.  - Fixed - OK

**Comment by nadezhday** [comment]
For tester: Partly covered in test_tools_search.py test.
TBD: Test link after problem with  http://83.149.198.62/ is fixed

**Comment by myrix** [comment]
After discussion with @nadezhday and getting reports from users, it appears that indeed it should be possible to get links even to empty search results.

Even if it shows "Found 0 results on map", it should be possible to get link to the search.

**Comment by myrix** [comment]
Implemented.

**Comment by academic-sakharov** [comment]
> @academic-sakharov Andrey? Could you please help to make this functionality work on http://83.149.198.62/
> 
> NOTE: to test this on test stand http://83.149.198.62/ its DB dump should be updated to one after today 08:00 MSK, otherwise there will be discrepancies with DB schema.

Done. DB dump has been replaced with the latest one: lingvodoc-2021-01-13.16-51.sql

**Comment by nadezhday** [comment]
Covered in selenium test. PASS.
