### ISSUE TITLE
Map search colors in fixed order

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#394]
Go to http://83.149.198.62/map_search, add some search tabs, each search is labeled with a different color:
![image](https://user-images.githubusercontent.com/2802467/104330075-b335b580-54fe-11eb-95a3-845e2e155e03.png)

Reload the page, do the same, now colors are different:
![image](https://user-images.githubusercontent.com/2802467/104330135-bd57b400-54fe-11eb-8fdd-be0bd195b56a.png)

Current user experience shows that such randomization is inadvisable, search colors should always go in the same fixed order.

**Comment by myrix** [comment]
Implemented.

**Comment by nadezhday** [comment]
Verified.
The order:
1) 
![image](https://user-images.githubusercontent.com/59951991/104988856-3177e780-5a2a-11eb-9481-c5a31f174a2d.png)
2)
![image](https://user-images.githubusercontent.com/59951991/104988903-4fdde300-5a2a-11eb-8c38-1e8cc245e590.png)

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_search_03.py
