### ISSUE TITLE
Get link to search results: Map should contain markers for all searches

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#395]
Left issue from https://github.com/ispras/lingvodoc-react/issues/393
Open Search1, perform search of something (321) - 1 match
![image](https://user-images.githubusercontent.com/59951991/104889419-43508080-597f-11eb-874f-55c0ed8ac512.png)

Open Search2, search something else (123) - 4 matches
![image](https://user-images.githubusercontent.com/59951991/104889306-11d7b500-597f-11eb-9817-d7b17c321a28.png)

Result: map contains results from both Search1 and Search2 - 5 matches
![image](https://user-images.githubusercontent.com/59951991/104890075-1a7cbb00-5980-11eb-9d8f-7ac9ae6291d8.png)

Click Get link to search results.
Click the generated link.

Expected: The opened new page should contain markers for both searches (Search1 and Search2)
Actual: Only 1 marker is present on the map. You have to click Search2 tab to see more markers. 
![image](https://user-images.githubusercontent.com/59951991/104890175-3da76a80-5980-11eb-99d6-453a893959c2.png)

**Comment by myrix** [comment]
Fixed, after search results are fully loaded, map shows markers of all searches.

**Comment by nadezhday** [comment]
Verified.

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_search_03.py
