### ISSUE TITLE
Corpus parser fixed

### ISSUE THREAD

**Issue by ankan2013** [ispras/lingvodoc-react#396]
A pull request (ispras/lingvodoc#1287) was made to fix some bugs in corpus parser's work:
1. lowering case in some sentences' first letters
2. missing some words that are starting with a capital letter in the result of a parser's work (the change is that a word frequencies dictionary for a parser is now been built by counting occurencies non-case-sensitively)
3. fixed empty result of parsing in cases when a parser had not any presumptions about a corpus
4. fixed losing the piece of text in a parser result after the last presumption
5. fixed proceeding single capital characters in source text two times (which caused some situations like turning A in a source text to AA in a result) and digits - three times (e.g. 9 -> 999)
No changes in the user interface were made.
In terms of the source code, the only file was modified - lingvodoc/utils/doc_parser.py

Use cases to check the correctness:
1-2, 4 5: upload file
[3_Ожын кыдан.docx](https://github.com/ispras/lingvodoc-react/files/5906096/3_.docx)
The expected result is
[expected.txt](https://github.com/ispras/lingvodoc-react/files/5906366/expected.txt)
(renamed from .html to .txt to upload here)
Visually, it should be like
![expected](https://user-images.githubusercontent.com/45983282/106510650-48b1dd00-64e0-11eb-90fa-21354ec877ca.png)

3: upload pure latin characters document 
[British Colonial Empire.docx](https://github.com/ispras/lingvodoc-react/files/5906375/British.Colonial.Empire.docx)
The result text should be the same as the source text:
[expected_3.txt](https://github.com/ispras/lingvodoc-react/files/5906411/expected_3.txt)

**Comment by nadezhday** [comment]
Steps to reproduce (from @myrix ):
-Open http://83.149.198.62/dictionary/3235/4/perspective/3235/7/edit as Admin, 
-Add lexical entry
![image](https://user-images.githubusercontent.com/59951991/106558605-18485e00-6535-11eb-827f-5ea92e842d01.png)
- In a new entry click + in Markup column
![image](https://user-images.githubusercontent.com/59951991/106558704-3ada7700-6535-11eb-9949-9d24fa850f37.png)
-Upload file
![image](https://user-images.githubusercontent.com/59951991/106558801-69f0e880-6535-11eb-9f5c-52789baf9de2.png)

-Open parser dialog
![image](https://user-images.githubusercontent.com/59951991/106558815-77a66e00-6535-11eb-8537-a87bbb651614.png)

-Select Udmurt
![image](https://user-images.githubusercontent.com/59951991/106558858-8a20a780-6535-11eb-8a48-882f2ddca4a0.png)

- wait a little bit

![image](https://user-images.githubusercontent.com/59951991/106558917-a7ee0c80-6535-11eb-9b56-dfc764c33e00.png)

- Refresh page
- Open markup dialog
 
![image](https://user-images.githubusercontent.com/59951991/106558999-cf44d980-6535-11eb-8c7d-756757d5391e.png)
-Compare results
![image](https://user-images.githubusercontent.com/59951991/106558979-c6540800-6535-11eb-9d8c-db4033499102.png)

**Comment by nadezhday** [comment]
1) Result - ОК

![image](https://user-images.githubusercontent.com/59951991/106559747-eb954600-6536-11eb-864d-6f00a3ed59f9.png)

2) Result 2:
![image](https://user-images.githubusercontent.com/59951991/106560225-b76e5500-6537-11eb-9378-523a58362282.png)

This issue can be Verified. 
@ankan2013 Please close this issue and I will verify it.
