### ISSUE TITLE
Import Starling dictionaries: 'Next Step' disabling not working

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#397]
Go to http://83.149.198.62/import logged in as admin, select any CSV, e.g. "ненецкий 1.csv". When no Starling columns for CSV are selected, the "Next Step" button is not supposed to be visible, yet it is:
![image](https://user-images.githubusercontent.com/2802467/107525013-74f7e880-6bc7-11eb-8203-bd544ec0d87a.png)

This sometimes leads to user confusion and should be fixed.

**Comment by myrix** [comment]
Fixed.

Open Import Starling dictionaries as above, select any CSV, when no columns are selected 'Next Step' button is absent, and a corresponding message is displayed instead:
![image](https://user-images.githubusercontent.com/2802467/107548041-3837eb80-6bdf-11eb-82dd-212b84d6a47b.png)

Select one of the columns by clicking on it and selecting 'Keep', message disappears and 'Next Step' button appears:
![image](https://user-images.githubusercontent.com/2802467/107548128-569de700-6bdf-11eb-8bc6-f3d769a314fa.png)

Go to the next step by clicking the button, at the second step until all columns are mapped 'Next Step' button is absent, and a corresponding message is displayed instead:
![image](https://user-images.githubusercontent.com/2802467/107548357-96fd6500-6bdf-11eb-9481-5315b613d29e.png)

Select for each Starling column a Lingvodoc field type by clicking on corresponding 'Field Type' button and selecting any available Lingvodoc field, message disappears and 'Next Step' button appears:
![image](https://user-images.githubusercontent.com/2802467/107548651-f8253880-6bdf-11eb-8433-5d9056e1dcda.png)

**Comment by yesandv** [comment]
Verified.

![897-Next-Step-1](https://user-images.githubusercontent.com/73657817/108486411-1c070f00-72af-11eb-99b4-f7511d66b911.png)
![897-Next-Step-2](https://user-images.githubusercontent.com/73657817/108486418-1d383c00-72af-11eb-888a-1533b6731a7d.png)

**Comment by vmonakhov** [comment]
Covered in tests/test_import_starling_dict_01.py
