### ISSUE TITLE
Docx corpus import: not all data is processed

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#398]
Transformation of .docx corpus [Маркешта Святой Іôванӷели (2).docx](https://github.com/ispras/lingvodoc-react/files/5966316/o.2.docx) to standard .eaf 5-tier corpus format (command-line `python -m lingvodoc.scripts.docx_import import "Маркешта Святой Іôванӷели (2).docx" --eaf-file "Маркешта Святой Іôванӷели (2).eaf" --check-file "Маркешта Святой Іôванӷели (2).txt"`) does not process all data in the .docx file, most of the data at the end of the file is silently skipped.

**Comment by myrix** [comment]
The problem is in the external python-docx package, rather then trying to fix it, it is more convenient in such cases to use a workaround.

If after conversion resulting .eaf file does not contain all data from the .docx file, user should try conversion with additional option --all-tables (e.g. `python -m lingvodoc.scripts.docx_import import "Маркешта Святой Іôванӷели (2).docx" --eaf-file "Маркешта Святой Іôванӷели (2).eaf" --check-file "Маркешта Святой Іôванӷели (2).txt" --all-tables` in this case).

Workaround implemented, tested locally.

**Comment by nadezhday** [comment]
Closing without verification.

**Comment by yesandv** [comment]
Verified.
