### ISSUE TITLE
Corpus parser fixed

### ISSUE THREAD

**Issue by ankan2013** [ispras/lingvodoc-react#399]
А new pull request (https://github.com/ispras/lingvodoc/pull/1290) was made to treat two words written with "-" as a single word due to specific rules in Meadow Mari language. 
Steps to reproduce:
-Open http://83.149.198.62/dictionary/3235/4/perspective/3235/7/edit as Admin,
-Add lexical entry
![image](https://user-images.githubusercontent.com/45983282/108445562-a75fb080-726d-11eb-94a9-04d22d1b1038.png)
In a new entry click + in Markup column
![image](https://user-images.githubusercontent.com/45983282/108445606-ba728080-726d-11eb-9adb-5954339ee4ba.png)
Upload file
![image](https://user-images.githubusercontent.com/45983282/108445626-c0686180-726d-11eb-9861-125ed3b26d41.png)
The file is below.
[Таргылтыш.docx](https://github.com/ispras/lingvodoc-react/files/6007105/default.docx)
Open parser dialog
![image](https://user-images.githubusercontent.com/45983282/108445824-20f79e80-726e-11eb-94da-24d7fec9b9c1.png)
Select Meadow Mari
![Screenshot from 2021-02-19 04-52-27](https://user-images.githubusercontent.com/45983282/108445930-513f3d00-726e-11eb-8c54-77f8700aed60.png)
wait a little bit
![Screenshot from 2021-02-19 04-53-26](https://user-images.githubusercontent.com/45983282/108446006-759b1980-726e-11eb-86b2-ef4f8986bba9.png)
Refresh page
Open markup dialog
![image](https://user-images.githubusercontent.com/45983282/108446035-82b80880-726e-11eb-9290-ccff57579fe1.png)
Result OK:
![Screenshot from 2021-02-19 04-55-21](https://user-images.githubusercontent.com/45983282/108446158-c0b52c80-726e-11eb-80fe-92a90182d500.png)
![Screenshot from 2021-02-19 04-55-36](https://user-images.githubusercontent.com/45983282/108446163-c1e65980-726e-11eb-8dc1-b6d910022369.png)
(These words are highlighted in the result)

**Comment by jandrew44** [comment]
Was merged a long time ago.

**Comment by nadezhday** [comment]
Verified

parser can be opened - OK
![image](https://user-images.githubusercontent.com/59951991/170468483-14ba9efb-970e-4fbf-8765-1070128121b0.png)
