### ISSUE TITLE
INEL corpora EXMARaLDA .exb -> Lingvodoc 5-tier ELAN .eaf converter

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#400]
We need to convert as much as possible info from [INEL](https://www.slm.uni-hamburg.de/inel.html) [Dolgan](https://corpora.uni-hamburg.de/hzsk/en/islandora/object/spoken-corpus:dolgan-1.0), [Kamas](https://corpora.uni-hamburg.de/hzsk/en/islandora/object/spoken-corpus:kamas-1.0) and [Selkup ](https://corpora.uni-hamburg.de/hzsk/en/islandora/object/spoken-corpus:selkup-1.0) corpora, stored in EXMARaLDA .exb format, to our 5-tier ELAN .eaf corpora format.

So, we should implement a converter.

**Comment by myrix** [comment]
Implemented.

Conversion should be performed in the environment with installed backend. To perform the convertion, download corpora files [dolgan-corpus.zip](https://corpora.uni-hamburg.de/hzsk/de/islandora/object/file:dolgan-1.0_INEL_Dolgan_Corpus_1.0_ZIP_Archive/datastream/ZIP/dolgan-corpus.zip), [kamas.zip](https://corpora.uni-hamburg.de:8443/fedora/objects/file:kamas-1.0_zip/datastreams/ZIP/content) (as kamas.zip), [selkup.zip](https://corpora.uni-hamburg.de/hzsk/de/islandora/object/file:selkup-1.0_zip_audio/datastream/ZIP/zip_audio.zip) (as selkup.zip) and use following commands:
```
python -m lingvodoc.scripts.exmaralda_to_eaf convert_corpus <path_to_downloads>/dolgan-corpus.zip <path_to_dolgan_dir>
python -m lingvodoc.scripts.exmaralda_to_eaf convert_corpus <path_to_downloads>/kamas.zip <path_to_kamas_dir>
python -m lingvodoc.scripts.exmaralda_to_eaf convert_corpus <path_to_downloads>/selkup.zip <path_to_selkup_dir>
```

Tested locally.

**Comment by nadezhday** [comment]
Closing without verification.
