### ISSUE TITLE
Licenses for dictionaries and corpora

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#403]
When creating dictionaries, either anew or by importing Dialeqt / Starling / CSV data, user should be able to specify a license for the dictionary being created. The same when creating a corpus.

Also, when dictionary is created from a 5-tier EAF markup in a corpus, it should inherit license of the corpus.

For now the set of possible licenses is fixed, user should be able select one of the following licenses:
1. Proprietary license
2. [Creative Commons Attribution 4.0](https://creativecommons.org/licenses/by/4.0/legalcode) license
3. [Creative Commons Attribution-ShareAlike 4.0](https://creativecommons.org/licenses/by-sa/4.0/legalcode) license
4. [Creative Commons Attribution-NonCommercial-ShareAlike 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode) license

**Comment by myrix** [comment]
Implemented.

Any dictionary / corpus without explicitly specified license, including all already existing ones, is displayed as having a proprietary license.

### New dictionary / corpus

When creating a new dictionary, at the second step "Dictionary names and metadata" user can also specify a license for a new dictionary.

E.g. go to new dictionary creation (home page -> Dashboard -> Create dictionary), at first step choose any language, e.g. Uralic, select a license at the second step:
![image](https://user-images.githubusercontent.com/2802467/109088402-63165980-7720-11eb-8940-7a8f3f87c7d1.png)
Finish dictionary creation by going to the next step, adding a perspective and clicking "Create" button, then go to the new dictionary, and you can see license info in the top right corner:
![image](https://user-images.githubusercontent.com/2802467/109088701-fb144300-7720-11eb-8696-831ffac8b497.png)
![image](https://user-images.githubusercontent.com/2802467/109088726-09625f00-7721-11eb-92d3-faee8131916d.png)
![image](https://user-images.githubusercontent.com/2802467/109088730-0bc4b900-7721-11eb-97d9-c67524c54b61.png)

For Creative Commons licenses, license info is also a link leading to the license text:
![image](https://user-images.githubusercontent.com/2802467/109089137-c8b71580-7721-11eb-970b-ecd38d686779.png)
![image](https://user-images.githubusercontent.com/2802467/109089146-cbb20600-7721-11eb-8f2d-b42de5626031.png)

The same when creating a new corpus (home page -> Dashboard -> Create corpus), at the second step "Corpus names and metadata" a license can be selected:
![image](https://user-images.githubusercontent.com/2802467/109089436-47ac4e00-7722-11eb-8787-810a98f8f7de.png)
Finish corpus creation, open it, license info is displayed in the top right corner:
![image](https://user-images.githubusercontent.com/2802467/109089787-dc16b080-7722-11eb-839d-d5a16340b5b4.png)

### Importing dictionaries

When creating a dictionary by Dialeqt dictionary import, license can be selected at the third step "Dictionary names".

E.g. go to Dialeqt dictionary import (home page -> Dashboard -> Import Dialeqt dictionary), select any available .dialeqt file, select "Create dictionary", next step, select any parent language, e.g. Uralic, next step, license selection:
![image](https://user-images.githubusercontent.com/2802467/109090285-cbb30580-7723-11eb-99b8-f6080f7147b0.png)
Launch dictionary import by clicking "Create dictionary", wait for the conversion to finish, go to home page -> Dashboard -> Dictionaries, open e.g. "Lexical entries" perspective of the new dictionary, license info is in the top right corner:
![image](https://user-images.githubusercontent.com/2802467/109094689-6fec7a80-772b-11eb-951f-44702720e5bb.png)
![image](https://user-images.githubusercontent.com/2802467/109090799-ac68a800-7724-11eb-9e73-30edf4fa4b87.png)
![image](https://user-images.githubusercontent.com/2802467/109090805-af639880-7724-11eb-9f74-77ee8ade11b5.png)
![image](https://user-images.githubusercontent.com/2802467/109090811-b25e8900-7724-11eb-8e3d-a30a314debfb.png)

When creating a dictionary by Starling dictionary import, license can be selected at the third step "Language selection".

E.g. home page -> Dashboard -> Import Starling dictionaries, select any base blob and at least one Startling column as "Keep", next step, select any Lingvodoc field(s) for selected Starling column(s), next step, license selection:
![image](https://user-images.githubusercontent.com/2802467/109091750-66144880-7726-11eb-9d27-566bc323257d.png)
Launch dictionary import by clicking "Submit", wait for the conversion to finish, go to home page -> Dashboard -> Dictionaries, refresh page if the new dictionary is not displayed, open its perspective, license info is in the top right corner:
![image](https://user-images.githubusercontent.com/2802467/109092056-f2bf0680-7726-11eb-9d24-fe88fc47b389.png)
![image](https://user-images.githubusercontent.com/2802467/109092060-f488ca00-7726-11eb-9c7a-a00b600fb788.png)
![image](https://user-images.githubusercontent.com/2802467/109092066-f6eb2400-7726-11eb-94b0-087aee9e2939.png)
![image](https://user-images.githubusercontent.com/2802467/109092071-f94d7e00-7726-11eb-9467-475a067f57d8.png)

### Creating dictionaries from corpora

When creating dictionary from a markup in a corpus, license of the new dictionary is inherited from the markup's corpus.

E.g. open existing or create a new corpus with e.g. CC-BY-4.0 license, see above for instructions, in editing mode, "Add lexical entry", upload a compatible EAF markup, e.g. uncompressed 
[Евангелие от Луки 1889.eaf.zip](https://github.com/ispras/lingvodoc-react/files/6040149/1889.eaf.zip), view it, "Convert to dictionary...", select "Create dictionary", any parent language, e.g. Uralic, "Convert":
![image](https://user-images.githubusercontent.com/2802467/109094775-9a3e3800-772b-11eb-9aa5-2afc7e26b690.png)
![image](https://user-images.githubusercontent.com/2802467/109094783-9ca09200-772b-11eb-98e0-29fde3af2d4e.png)
![image](https://user-images.githubusercontent.com/2802467/109094790-a0341900-772b-11eb-9fd8-cfce4f55c119.png)
![image](https://user-images.githubusercontent.com/2802467/109094800-a1fddc80-772b-11eb-9ee9-da567553f0e4.png)
![image](https://user-images.githubusercontent.com/2802467/109094807-a5916380-772b-11eb-9b2e-2cfad07532be.png)
![image](https://user-images.githubusercontent.com/2802467/109094812-a924ea80-772b-11eb-9cc3-9c1702c87585.png)

Wait for conversion to finish, go to home page -> Dashboard -> Dictionaries, refresh page if the new dictionary is not displayed, open e.g. "Lexical entries" perspective of the new dictionary, the dictionary has the same license as the source corpus, CC-BY-4.0:
![image](https://user-images.githubusercontent.com/2802467/109094821-ab874480-772b-11eb-84eb-796182a71b72.png)
![image](https://user-images.githubusercontent.com/2802467/109094859-b7730680-772b-11eb-971e-f15bd1ac0c04.png)
![image](https://user-images.githubusercontent.com/2802467/109094891-c6f24f80-772b-11eb-8706-f563f2d64fd8.png)
![image](https://user-images.githubusercontent.com/2802467/109094919-d2457b00-772b-11eb-95e2-6dfbdfc6dc5c.png)

**Comment by yesandv** [comment]
Verified.
