### ISSUE TITLE
Implement confirmation before file deletion 

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#409]
Implement confirmation before file deletion.

**Comment by nadezhday** [comment]
It is better to ask twice before we delete something instead of wasting time to recover the deleted items.

**Comment by jandrew44** [comment]
Confirmation dialog has been added.

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/158309489-038235e7-65d2-459a-b17e-f355fa84afbe.png)
Verified

@myrix Is this correct behaviour?
![image](https://user-images.githubusercontent.com/59951991/158309785-713c3a6b-b4e2-49a9-add5-444f2fd13f0c.png)

**Comment by myrix** [comment]
> @myrix Is this correct behaviour?

Source code comments indicate that yes, it is intended behaviour.
