### ISSUE TITLE
Dictionaries & Corpora pages ordering

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#431]
Right now there is no guarantee that dictionaries and corpora on Language databases -> Dictionaries and Language databases -> Language corpora would be ordered inside languages in standard order, which is based on creation time, from newest to oldest.

That should be fixed.

Replaces #330.

**Comment by myrix** [comment]
Now should be alright.

**Comment by nadezhday** [comment]
@myrix could you please help us to verify this case.
What exactly should we see on the page in order to say 'yes' ordering is working.
Probably several screenshot will be enough. )

**Comment by myrix** [comment]
@nadezhday 
Probably enough to verify a subset of the corpora, on Language databases -> Language corpora go to Dolgan,
![image](https://user-images.githubusercontent.com/2802467/111680228-0f84c080-8833-11eb-92e1-7cdd0ec07511.png)
highlighted corpora should go in the current order:
![image](https://user-images.githubusercontent.com/2802467/111680374-3642f700-8833-11eb-84c9-f5904c62425a.png)

If in doubt or need to establish proper order for something else, check dictionary / corpus creation time as specified in #436.

**Comment by yesandv** [comment]
Verified.

**Comment by vmonakhov** [comment]
Covered in tests/test_dictionaries.py
But order is from oldest to newer and not vice versa

**Comment by myrix** [comment]
Fixed.
