### ISSUE TITLE
Handle dictionary / perspective mismatch in URLs

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#433]
Open http://83.149.198.62/dictionary/3781/1/perspective/3782/2/view, note dictionary name in the breadcrumbs:
![image](https://user-images.githubusercontent.com/2802467/109415239-9f6be300-79c8-11eb-93c7-d72a665341f9.png)
Open dictionary menu by clicking on dictionary name, open dictionary properties, note the disparity between initial dictionary name and dictionary name translations in properties:
![image](https://user-images.githubusercontent.com/2802467/109415273-c9bda080-79c8-11eb-8806-afda8aa8c7fa.png)
![image](https://user-images.githubusercontent.com/2802467/109415276-cb876400-79c8-11eb-858f-603659377273.png)

The cause is that dictionary 3781, 1 specified in the URL is not actually parent dictionary of the perspective 3782, 2 specified in the URL.

Such things shouldn't be possible, so in such cases user should be redirected to the correct URL which specifies the perspective's dictionary, in this case to the http://83.149.198.62/dictionary/3782/1/perspective/3782/2/view. (Not the other way around, because in general dictionary can have more than one perspective, while perspective always has one, and only one, parent dictionary.)

**Comment by myrix** [comment]
Implemented, redirects as expected.

**Comment by yesandv** [comment]
Verified.

**Comment by vmonakhov** [comment]
Covered in tests/test_dictionaries.py
