### ISSUE TITLE
Connected lexical entries are not displayed as such

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#434]
Open http://83.149.198.62/dictionary/3151/33643/perspective/3151/33644/edit logged in as julianor, open 'Cognates' of "ćeĺińä",
![image](https://user-images.githubusercontent.com/2802467/109416813-78fe7580-79d1-11eb-941f-fef137b82e79.png)
'Add connection' tab, search for "ćeĺińä", open the first result,
![image](https://user-images.githubusercontent.com/2802467/109416820-887dbe80-79d1-11eb-97f4-4a28b8d33c50.png)
click 'Connect', wait for 'Connected' message in the lower left corner, click 'Cancel',
![image](https://user-images.githubusercontent.com/2802467/109416834-99c6cb00-79d1-11eb-8de2-1322716539e4.png)
return to the 'View' tab, no additional connected lexical entries:
![image](https://user-images.githubusercontent.com/2802467/109416853-b105b880-79d1-11eb-9673-000b357c4be5.png)

Close the dialog with 'Cancel', reload the page, open 'Cognates' of "ćeĺińä" again, still the same, no connections where there should be at least one.

**Comment by myrix** [comment]
Fixed, now created connection is displayed in the 'View' tab as it should be:
![image](https://user-images.githubusercontent.com/2802467/109417080-28881780-79d3-11eb-8123-dd63229dfcf4.png)

**Comment by yesandv** [comment]
Verified.

**Comment by vmonakhov** [comment]
Covered in tests/test_view_lexical_03.py
