### ISSUE TITLE
Transcription, translation in phonology formant tables

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#435]
Open http://83.149.198.62/dictionary/657/3/perspective/657/4/view, Tools -> Phonology, click 'Create' button, wait for the task to finish, look at formant tables at sheets "F-table", "F-table (3d)" in the resulting .xlsx file [Dictionary of Yukonda dialect of Mansi - Lexical Entries - 2021.02.28.xlsx](https://github.com/ispras/lingvodoc-react/files/6058354/Dictionary.of.Yukonda.dialect.of.Mansi.-.Lexical.Entries.-.2021.02.28.xlsx):
![image](https://user-images.githubusercontent.com/2802467/109438184-daf2c580-7a39-11eb-8a60-eeaf9aad00a8.png)
![image](https://user-images.githubusercontent.com/2802467/109438186-dd551f80-7a39-11eb-82c2-f2db36e6313a.png)

Users request that these tables include transcriptions and translations of words the formant values were extracted from.

**Comment by myrix** [comment]
Implemented:
[Dictionary of Yukonda dialect of Mansi - Lexical Entries - 2021.02.28.xlsx](https://github.com/ispras/lingvodoc-react/files/6058443/Dictionary.of.Yukonda.dialect.of.Mansi.-.Lexical.Entries.-.2021.02.28.xlsx)
![image](https://user-images.githubusercontent.com/2802467/109438413-f5796e80-7a3a-11eb-92aa-2fd68a6c879e.png)
![image](https://user-images.githubusercontent.com/2802467/109438414-f7433200-7a3a-11eb-9099-1c942e3c9d10.png)

**Comment by yesandv** [comment]
Verified.
