### ISSUE TITLE
Date of adding a dictionary and a corpus to the database isn't displayed

### ISSUE THREAD

**Issue by yesandv** [ispras/lingvodoc-react#436]
**Precondition**
Found while verifying #431 
Go to http://83.149.198.62/
Login as modis

**Steps**
Go to Dashboard -> Dictionaries -> Available dictionaries
Click on 'Dictionary of Livvik dialect of Karelian language (vil. Ust'e Vidlicy)'
Click on Properties...
Then go to to the main page -> Dashboard -> Corpora -> Available corpora
Click on 'Glossed corpus of the book "Святое Евангелие от Матфея, Марка, Луки и Иоанна", Казань, 1910'
Click on Properties...

**Expected result**
Being able to see the date of adding the dictionary, the corpus to the database (creating) by the user.

**Actual result**
There is no information about the date of adding the dictionary and the corpus.

@nadezhday

**Comment by myrix** [comment]
Open dictionary/perspective properties dialog, now creation and modification data is displayed, e.g. for Yukonda Mansi http://83.149.198.62/dictionary/657/3/perspective/657/4/view:
![image](https://user-images.githubusercontent.com/2802467/111675213-ee6da100-882d-11eb-9275-4197fdabe9d4.png)
![image](https://user-images.githubusercontent.com/2802467/111675231-f299be80-882d-11eb-9565-73dbe8bfa92e.png)

**Comment by yesandv** [comment]
Verified.

![dictionary-properties](https://user-images.githubusercontent.com/73657817/111754629-4695b900-88a9-11eb-8d38-d55b9574be41.png)
![corpora-properties](https://user-images.githubusercontent.com/73657817/111754638-4990a980-88a9-11eb-8083-f7f52bc99073.png)

**Comment by vmonakhov** [comment]
Covered in tests/test_dictionaries.py
