### ISSUE TITLE
Cognate disconnect permission bug

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#437]
Open http://83.149.198.62/dictionary/657/3/perspective/657/4/edit logged in as 'julianor', open cognates of "werpə-", click 'Disconnect' button, result is permission error:
![image](https://user-images.githubusercontent.com/2802467/109578729-c5000600-7b08-11eb-9c0b-d6ec78e55523.png)
![image](https://user-images.githubusercontent.com/2802467/109578767-d2b58b80-7b08-11eb-808d-071e4a14c129.png)

Close cognates dialog, open perspective roles, the user has necessary permission:
![image](https://user-images.githubusercontent.com/2802467/109578834-f5e03b00-7b08-11eb-8452-8fdb2cb2ccb2.png)
![image](https://user-images.githubusercontent.com/2802467/109578839-f8429500-7b08-11eb-9689-5a36573f582a.png)

Operation should succeed.

**Comment by myrix** [comment]
Fixed, works:
![image](https://user-images.githubusercontent.com/2802467/109579762-93883a00-7b0a-11eb-88ac-59e9122d229d.png)

**Comment by yesandv** [comment]
Verified.
