### ISSUE TITLE
Sort by Organizations

### ISSUE THREAD

**Issue by julianor555** [ispras/lingvodoc-react#441]
It is necessary to be able to sort by organizations, as well as by grants.

**Comment by julianor555** [comment]
In the list of organizations, you should also add the ability to delete organizations that were entered incorrectly.

**Comment by myrix** [comment]
Implemented.

Go to /dashboard/dictionaries_all (Language databases -> Dictionaries), select 'Display mode' as "By Organizations":
![image](https://user-images.githubusercontent.com/2802467/110217204-df98fd00-7ec3-11eb-81fb-553b3bdbf3d6.png)

**Comment by yesandv** [comment]
Verified.

**Comment by yesandv** [comment]
Selenium test's written.
