### ISSUE TITLE
Deleting organizations

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#442]
User logged in as administrator should be able to delete organizations.

Non-administrators should not be able to do that.

Rel. https://github.com/ispras/lingvodoc-react/issues/441#issuecomment-790668201.

**Comment by myrix** [comment]
Implemented.

To delete an organization, log in as administrator, go to /organizations page,
![image](https://user-images.githubusercontent.com/2802467/110210501-0135bc80-7ea3-11eb-8064-d92ddd98f19a.png)
click 'Delete' button of the organization that should be deleted,
![image](https://user-images.githubusercontent.com/2802467/110210515-0c88e800-7ea3-11eb-9b64-f01364fbb613.png)
confirm deletion,
![image](https://user-images.githubusercontent.com/2802467/110210522-114d9c00-7ea3-11eb-8214-b1fe1a30847a.png)
organization then will be deleted with appropriate message:
![image](https://user-images.githubusercontent.com/2802467/110210542-2aeee380-7ea3-11eb-9e1b-378f62ef2fe1.png)

If you are logged in as non-administrator user, you don't have access to 'Delete' buttons,
![image](https://user-images.githubusercontent.com/2802467/110210568-4bb73900-7ea3-11eb-9db6-8d0e57d3e75b.png)
and any organization deletion API calls will end with error.

**Comment by yesandv** [comment]
Verified.

**Comment by vmonakhov** [comment]
Covered in tests/test_organizations.py
