### ISSUE TITLE
Sorting by field bug

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#443]
Open http://lingvodoc.ispras.ru/dictionary/3648/23692/perspective/3648/23696/edit, sort by 'Paradigms and Contexts', page fails with error:
![image](https://user-images.githubusercontent.com/2802467/110590360-bceb3a80-8188-11eb-9ede-3444b2b9e057.png)
![image](https://user-images.githubusercontent.com/2802467/110590378-c1175800-8188-11eb-9741-618f3704a42e.png)
Edit: the same e.g. at http://83.149.198.62/dictionary/657/3/perspective/657/4/view.

**Comment by myrix** [comment]
Fixed, now sorts ok.

**Comment by yesandv** [comment]
Verified.

**Comment by vmonakhov** [comment]
Covered in tests/test_dictionaries.py
