### ISSUE TITLE
Etymological distance plot malfunction pt. 2

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#444]
Open http://83.149.198.62/dictionary/3688/1/perspective/3688/2/view logged in as admin, Tools -> Cognate analysis, 'Compute' button, wait for computation to finish and for results to render, 2d and 3d embedding plots are mostly empty and the legends obscure the data.

Just a part of the 2d plot:
![image](https://user-images.githubusercontent.com/2802467/110680142-4b8fa400-81e9-11eb-8807-c65d5c2ab2c0.png)

Probably due to a high number (more than 150) of dictionaries.

**Comment by myrix** [comment]
Failed to fix it directly, it seems this is due to inherent limitations of Plotly.js when working with such a large legend, I don't have enough JavaScript qualifications to investigate further and maybe fix it. Maybe somebody more JS-qualified can do it?

In the meantime, a workaround, when the number of dictionaries is sufficiently high, we'll render a separate legend below:
![image](https://user-images.githubusercontent.com/2802467/110681023-61519900-81ea-11eb-8267-394b2988d622.png)

When the number of dictionaries is sufficiently low, we'll have a plot with a legend as before, e.g. Yukonda Mansi /dictionary/657/3/perspective/657/4/view:
![image](https://user-images.githubusercontent.com/2802467/110681334-c7d6b700-81ea-11eb-8b3f-19fb56fa66f8.png)

**Comment by yesandv** [comment]
Verified.

**Comment by vmonakhov** [comment]
Covered in tests/test_cognate_analysis.py
