### ISSUE TITLE
'Cognate ...' tools accessible to perspective authors

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#445]
Rel. #387 'Cognate ...' tools accessible only to the administrator.

Now we need to allow access to 'Cognate...' tools to perspective authors also.

E.g. if you go to http://83.149.198.62/dictionary/657/3/perspective/657/4/view logged in as 'julianor', you should be able to open 'Cognate...' tools from the 'Tools' menu, whereas now you can't:
![image](https://user-images.githubusercontent.com/2802467/110779598-c782fe00-8274-11eb-939e-9b2bc01b3ee9.png)

**Comment by myrix** [comment]
Implemented.

Open http://83.149.198.62/dictionary/657/3/perspective/657/4/view logged in as 'julianor', 'Cognate...' tools are accessible:
![image](https://user-images.githubusercontent.com/2802467/110781489-01550400-8277-11eb-9ea2-099312d8357b.png)

Select 'Cognate analysis', scroll all the way down, click 'Compute' button, computes ok:
![image](https://user-images.githubusercontent.com/2802467/110781582-247fb380-8277-11eb-860e-3c6a72e8efd3.png)

The same dictionary logged in as 'test', 'Cognate...' tools are not accessible:
![image](https://user-images.githubusercontent.com/2802467/110781780-5e50ba00-8277-11eb-8aa4-94753a6c8562.png)

**Comment by yesandv** [comment]
Verified.

**Comment by yesandv** [comment]
Selenium test's written.

**Comment by myrix** [comment]
Now user that created the perspective can be seen in the perspective properties as specified in #436.
