### ISSUE TITLE
Perspective editing: adding new text entity bug

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#446]
Open http://83.149.198.62/dictionary/3619/96801/perspective/3619/96802/edit logged in as admin, try adding a new entity in the 'Word' column, new entity does not appear:
![image](https://user-images.githubusercontent.com/2802467/110996007-559dd800-838c-11eb-8b8d-053a80bfd6a7.png)
![image](https://user-images.githubusercontent.com/2802467/110996016-57679b80-838c-11eb-9d9f-bd5b8d988083.png)
![image](https://user-images.githubusercontent.com/2802467/110996023-59315f00-838c-11eb-9a00-06d10ca6919c.png)

**Comment by myrix** [comment]
Fixed, now works as expected:
![image](https://user-images.githubusercontent.com/2802467/110996806-892d3200-838d-11eb-863d-e2b834a6e3a4.png)

**Comment by yesandv** [comment]
Verified.

**Comment by vmonakhov** [comment]
Covered in tests/test_dashboard_create_corpus.py
