### ISSUE TITLE
PostgreSQL 13, Ubuntu 20.04 backend environment

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#447]
Some recently implemented features need PostgreSQL 13 to work, and PostgreSQL 13, it appears, won't work in the current Ubuntu 14.04 production environment.

So, we need to upgrade backend environment to the one based on latest long-term support Ubuntu release 20.04.

**Comment by myrix** [comment]
Ok, got a working setup for Ubuntu 20.04 backend environment, tested it, most automatic tests completed ok, and tests that failed seem to fail not because of errors, but due to timeouts and inability to find interface components; maybe caused by the DB state update?

Looks good enough to use in production.

**Comment by nadezhday** [comment]
we can close it.
