### ISSUE TITLE
Distance map: Error message

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#448]
Our test test_tools_distance_map.test_select_1_dictionary_map_admin  FAILed
![image](https://user-images.githubusercontent.com/59951991/111261278-48eedd80-8633-11eb-8ca2-90f42a123f9a.png)

Steps to reproduce:
Login as admin
Tools->distance map
Find 'Dictionary Upper Pelym dialect of Mansi language, author priest K.Slovcov,  1905'
Select dictionary
Uncheck all
Expand Uralic, Mansi, Western dialect
Checkbox ON for 'Dictionary of Mansi language, compiled by archpriest Simeon Cherkalov (Solikamsk city, 1783)'
Next
 Expected: Verify dots on the map
Actual: Error message

**Comment by myrix** [comment]
Fixed, now works as expected.

**Comment by nadezhday** [comment]
Works fine. Thank you, @myrix
