### ISSUE TITLE
Merge frontend/backend error: GraphQL error

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#449]
Test test_view_lexical_merge_suggestions.py:test_merge_on_several_pages - FAIL
![image](https://user-images.githubusercontent.com/59951991/111579112-761fc500-87c6-11eb-8426-4d0a66727468.png)

Steps to reproduce the problem can be found in https://github.com/ispras/lingvodoc-react/issues/229
Merge frontend/backend error

This is a regression.

**Comment by myrix** [comment]
Should be fixed.
![image](https://user-images.githubusercontent.com/2802467/111600721-be4ce080-87e2-11eb-8bcd-0285b27540f8.png)

**Comment by nadezhday** [comment]
Test - Pass
