### ISSUE TITLE
'Save dictionary' with markup

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#450]
User should be able to save dictionary info with attached markup files, just as it is possible to save dictionary with attached sound files (#282); saving with both attached sound and markup should also be possible.

**Comment by myrix** [comment]
Implemented.

Open e.g. "Dictionary of Yukonda dialect of Mansi", http://83.149.198.62/dictionary/657/3/perspective/657/4/view, 'Dictionary of Yukonda dialect of Mansi' drop-down menu, 'Save Dictionary 'Dictionary of Yukonda dialect of Mansi'', 'Save markup' check can be enabled / disabled independent of 'Save sound recordings' check:
![image](https://user-images.githubusercontent.com/2802467/113952413-4ccee380-981e-11eb-8aff-03d7b9fdf470.png)

If checked, saving dictionary would result in an archive containing markup files.

**Comment by nadezhday** [comment]
Verified. 
zip file was generated

**Comment by nadezhday** [comment]
Covered in tests\test_save_dictionary_02.py
