### ISSUE TITLE
Phonology: no results

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#451]
Open http://83.149.198.62/dictionary/2088/4/perspective/2088/7/view logged in as admin, 'Tools' menu, 'Phonology', 'Create' button, wait for task to complete, completed task shows "no results produced":
![image](https://user-images.githubusercontent.com/2802467/114034548-f34ecf00-9886-11eb-9004-a4ac0f0d673c.png)

Expected: a link to .xlsx file with phonology results.

**Comment by myrix** [comment]
Fixed, now computes ok with results.

Requires phonology cache flushing on the server, with `redis-cli --scan --pattern "phonology:*" | xargs redis-cli DEL` if using redis.

**Comment by nadezhday** [comment]
Verified
![image](https://user-images.githubusercontent.com/59951991/114699184-a35d8580-9d28-11eb-9ae3-0a01d2537450.png)

**Comment by nadezhday** [comment]
Covered in selenium test tests\test_phonology.py
