### ISSUE TITLE
Corpus converter bug

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#452]
For some corpora conversion gives some words invalid paradigm links.

E.g. open http://83.149.198.62/dictionary/3596/37747/perspective/3596/37750/view logged in as admin, start conversion to dictionary of the markup 'PKZ_196X_Branch_flk.eaf' (the 10th one):
![image](https://user-images.githubusercontent.com/2802467/114292135-0fc05680-9a95-11eb-95b1-e8a5a827ae92.png)
![image](https://user-images.githubusercontent.com/2802467/114292138-1a7aeb80-9a95-11eb-9fae-6992001246b0.png)
![image](https://user-images.githubusercontent.com/2802467/114292148-28c90780-9a95-11eb-8e10-63323406ba72.png)

Wait for the task to finish, go home page -> Language databases -> Dictionaries, find the new dictionary, open 'Lexical Entries' perspective:
![image](https://user-images.githubusercontent.com/2802467/114292158-35e5f680-9a95-11eb-9e86-6bdc10e1ebe2.png)
![image](https://user-images.githubusercontent.com/2802467/114292171-426a4f00-9a95-11eb-9196-880877002e76.png)

Go to 'Edit' view, search for "кормить", open paradigm links, there is a link to an unrelated "мужчина" entry:
![image](https://user-images.githubusercontent.com/2802467/114292219-92e1ac80-9a95-11eb-8ac2-9fc1ceb5fd16.png)
![image](https://user-images.githubusercontent.com/2802467/114292223-983ef700-9a95-11eb-9764-18eef2bc4412.png)
![image](https://user-images.githubusercontent.com/2802467/114292227-9a08ba80-9a95-11eb-9781-5e6f7ee878f0.png)
![image](https://user-images.githubusercontent.com/2802467/114292228-9bd27e00-9a95-11eb-82cc-2babc85ee2b7.png)
![image](https://user-images.githubusercontent.com/2802467/114292241-a7be4000-9a95-11eb-8760-31b2cb89715c.png)

**Comment by myrix** [comment]
Fixed, the problem was that the converter was not suited to converting corpora with empty phrase-level paradigm text and translation layers.

Now there are no extra paradigm links:
![image](https://user-images.githubusercontent.com/2802467/114292601-49df2780-9a98-11eb-91d9-3d58063d8f4d.png)

**Comment by nadezhday** [comment]
Verified.
Thank you for verification steps.
