### ISSUE TITLE
Showing parser versions

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#453]
At the version page /version_route, home page -> 'Support' -> 'Version', user should be able to see versions of some of the uniparser-* Python packages used by the Lingvodoc backend.

**Comment by myrix** [comment]
Implemented:
![image](https://user-images.githubusercontent.com/2802467/115992707-b9e0c800-a5d7-11eb-8e6b-9b1784f1ac1f.png)

**Comment by nadezhday** [comment]
Verified on http://lingvodoc.ispras.ru/version_route

**Comment by nadezhday** [comment]
Not verified on http://83.149.198.62/version_route
![image](https://user-images.githubusercontent.com/59951991/116030987-7a60bd00-a665-11eb-8842-8e3e8810d6c4.png)

**Comment by nadezhday** [comment]
I have started tests again and let us see how it will go.

**Comment by nadezhday** [comment]
The problem is that we cannot see any plugin info  http://83.149.198.62/version_route
@myrix should we do extra steps in order to see new plugin functionality?

**Comment by myrix** [comment]
> The problem is that we cannot see any plugin info http://83.149.198.62/version_route
> @myrix should we do extra steps in order to see new plugin functionality?

Due to an inaccuracy wasn't working properly in Docker container, pushed fix just now that should make it work ok on http://83.149.198.62/version_route also.

**Comment by nadezhday** [comment]
Thank you @myrix
Verified:
![image](https://user-images.githubusercontent.com/59951991/116069716-61bbcb80-a694-11eb-878c-08d29d082ee8.png)

**Comment by vmonakhov** [comment]
Covered in tests/test_support_version.py
