### ISSUE TITLE
Moving markup elements

### ISSUE THREAD

**Issue by ankan2013** [ispras/lingvodoc-react#455]
A pull request https://github.com/ispras/lingvodoc-react/pull/454 was made to provide a user with the ability to select an element in the parser's result and to change its position in the text. Also, modified code allows a user to remove not only user's markup elements, but any element in the markup.
Steps to reproduce:
1. All steps from here https://github.com/ispras/lingvodoc-react/issues/399
2. Select an element in the markup (1) and press the button (2) (and confirm).
![photo5264903196885758749](https://user-images.githubusercontent.com/45983282/118423995-ef586d00-b6ce-11eb-972d-11f19525f2d4.jpg)
3. The element's highlighting should disappear and a message about moving the element should be listed
![photo5264903196885758750](https://user-images.githubusercontent.com/45983282/118424098-2cbcfa80-b6cf-11eb-8b1c-ad6a85a59e90.jpg)
4. Select an area in the text that doesn't contain any whitespaces and other markup elements in the text (1) and press the button (2)
![photo5264903196885758751](https://user-images.githubusercontent.com/45983282/118424203-6d1c7880-b6cf-11eb-90a0-90c8c6d4aea8.jpg)
![photo5264903196885758752](https://user-images.githubusercontent.com/45983282/118424941-d18c0780-b6d0-11eb-9dd2-caf339639af7.jpg)
The data (variants) of the moved element should be the same as it was on the step 2 (before moving).
Then press the button "Remove from markup" and confirm.
![photo5264903196885758753](https://user-images.githubusercontent.com/45983282/118424572-21b69a00-b6d0-11eb-9559-7dd993bac050.jpg)

**Comment by nadezhday** [comment]
Tested with 'тань'
Works fine.
![image](https://user-images.githubusercontent.com/59951991/119093294-37052e80-ba18-11eb-9166-19a39d291428.png)
