### ISSUE TITLE
Adding new perspectives to existing dictionaries

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#456]
Users should be able to add new perspectives to existing dictionaries, specifying perspectives' names and fields.

**Comment by myrix** [comment]
Implemented.

Open e.g. http://83.149.198.62/dictionary/1574/274855/perspective/1574/274858/view logged in as admin, choose 'Create new perspective' from dictionary menu:
![image](https://user-images.githubusercontent.com/2802467/119059786-aad41680-b9d9-11eb-949b-976d711e8d1c.png)

In the perspective creation dialog add perspective's names and fields, click 'Save' button:
![image](https://user-images.githubusercontent.com/2802467/119059842-c808e500-b9d9-11eb-865b-76cfcc1bc0c2.png)

New perspective is created, can be accessed from current perspective menu:
![image](https://user-images.githubusercontent.com/2802467/119059854-d0f9b680-b9d9-11eb-8c89-6e2b331247d2.png)

**Comment by nadezhday** [comment]
Verified.
![image](https://user-images.githubusercontent.com/59951991/119086191-cb1dc880-ba0d-11eb-8520-e4f31743c94d.png)


Problems found (this is design related problems, defects will not be created):
1) buttons move down is available if you select the last item and there is not place to move it down. Minor issue.
![image](https://user-images.githubusercontent.com/59951991/119085826-1edbe200-ba0d-11eb-84d5-539c9598d0f2.png)

**Comment by nadezhday** [comment]
For testers: should be covered in selenium tests

**Comment by vmonakhov** [comment]
Covered in tests/test_view_lexical_new_perspective.py
