### ISSUE TITLE
Confirmation for deletion of sound, markup and parser results

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#457]
Subset of #416, maybe subset of #409?

When user initiates deletion of sound / markup files and parser results, there should be a confirmation dialog asking the user if the item in question should really be deleted.

**Comment by myrix** [comment]
Implemented.

Testing:

Log in as admin, open e.g. /dictionary/334/3/perspective/334/4/edit dictionary in editing mode, click delete button of a sound file:
![image](https://user-images.githubusercontent.com/2802467/125889191-9e92eccd-6dc7-4235-934d-62d18c4d378a.png)
Confirmation dialog appears:
![image](https://user-images.githubusercontent.com/2802467/125889207-ef00dbf7-e17d-4e6d-8d24-a3ac4de69bf3.png)
Click 'Cancel', nothing happens, click 'OK', sound file is deleted:
![image](https://user-images.githubusercontent.com/2802467/125889309-442c9859-b505-45f3-a99d-46eb8de6d354.png)

The same for markup:
![image](https://user-images.githubusercontent.com/2802467/125889387-76c151c1-7cc4-4de8-927e-a06ad3c9e149.png)
![image](https://user-images.githubusercontent.com/2802467/125889393-9a7d033e-6924-4505-adca-c614b565f053.png)
![image](https://user-images.githubusercontent.com/2802467/125889400-72311e82-8314-4896-ac9e-e39e3048a5a9.png)

Open /dictionary/3648/5/perspective/3648/8/edit dictionary in editing mode, the same for a parser result:
![image](https://user-images.githubusercontent.com/2802467/125889551-fd055af8-d745-42e9-b2e9-d934acac21ad.png)
![image](https://user-images.githubusercontent.com/2802467/125889554-9e35ee02-bb8c-4e1b-84eb-d5e347d9d3e5.png)
![image](https://user-images.githubusercontent.com/2802467/125889556-872c96ca-c782-4c6b-9044-7ee6cb520e2b.png)

**Comment by nadezhday** [comment]
http://83.149.198.62/version_route
Backend:2.1.1+1372-b3bff583-2021.07.16-07:21+modified-2021.07.18-21:46
uniparser-erzya:1.1.2
uniparser-komi-zyrian:1.1.5
uniparser-meadow-mari:1.1.5
uniparser-moksha:1.1.0
uniparser-udmurt:2.1.6
Frontend:e96abfeb-445-staging-server

Problem: Delete confirmation dialog does not appear.
@myrix,  do we have all changes in http://83.149.198.62/ ?

**Comment by myrix** [comment]
> Problem: Delete confirmation dialog does not appear.
> @myrix, do we have all changes in http://83.149.198.62/ ?

It seems the frontend is not up-to-date, and the problem is absense of automatic frontend builds after Travis CI at travis-ci.org no longer works.

@al-indigo Maybe it's possible to do something about it?

**Comment by nadezhday** [comment]
Works fine. Verified.

**Comment by vmonakhov** [comment]
Covered in tests/test_dictionaries.py
