### ISSUE TITLE
Parser results: update, delete permissions

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#458]
Only administrator and users with 'Can edit perspective' permission should be able to update work on parser results.

Only administrator and users with 'Can delete lexical entries and entities' permission should be able to delete parser results.

**Comment by myrix** [comment]
Implemented.

Testing:

Open dictionary /dictionary/3648/5/perspective/3648/8/edit logged in as administrator, changes are saved ok:
![image](https://user-images.githubusercontent.com/2802467/125907491-db2805b7-1ea8-45f3-b08a-1ed3ab8a02de.png)
![image](https://user-images.githubusercontent.com/2802467/125907504-9ddf2cea-1c57-4f3f-b3a7-3507a294991a.png)
![image](https://user-images.githubusercontent.com/2802467/125907510-a8f466c9-ff5a-43b3-b849-87a72ea2dbd5.png)
![image](https://user-images.githubusercontent.com/2802467/125907518-eb087df9-1a56-4e3d-9686-86d7535ac2a8.png)

Parser results are deleted ok:
![image](https://user-images.githubusercontent.com/2802467/125907538-0fed24cf-80df-4964-b27c-5095e9be3231.png)
![image](https://user-images.githubusercontent.com/2802467/125907542-187b94ad-a226-4c21-8825-b20d35c05f59.png)
![image](https://user-images.githubusercontent.com/2802467/125907544-a249e2c9-de5e-4009-9f0d-f1cacbbbe4c3.png)

Open perspective roles, add 'test' user, revoke 'Can edit perspective' and 'Can delete lexical entries and entities' permissions:
![image](https://user-images.githubusercontent.com/2802467/125907690-b119944b-49c9-4265-9998-d2719337d4eb.png)
![image](https://user-images.githubusercontent.com/2802467/125907701-d2247f6e-df19-40ce-b770-fe2fed900856.png)
![image](https://user-images.githubusercontent.com/2802467/125907708-40b9c80b-de82-4c9e-bba3-54a5d271f79f.png)
![image](https://user-images.githubusercontent.com/2802467/125907714-8fc0e76e-0fdb-46a8-868e-4f7f389e110b.png)
![image](https://user-images.githubusercontent.com/2802467/125907718-ecc9e3ac-ea9d-4929-94ba-b61f58f51dca.png)

Ensure 'test' user is active:
![image](https://user-images.githubusercontent.com/2802467/125907745-6257e999-31fd-4323-bcb2-caedb2ccdd2d.png)
![image](https://user-images.githubusercontent.com/2802467/125907806-5724fa98-02c9-45c1-9221-30a082d1e9a5.png)

Log out, log in as 'test', try saving changed parser results and deleting parser results in the same dictionary, does not work:
![image](https://user-images.githubusercontent.com/2802467/125907895-0c1fb9de-9562-4a86-9dc9-fe504ce31846.png)
![image](https://user-images.githubusercontent.com/2802467/125907915-1d7ffa91-275e-4ec4-96ae-0c39bb4dafd2.png)
![image](https://user-images.githubusercontent.com/2802467/125907921-4f35fc96-c54f-49d1-8747-3279fd767fbc.png)
![image](https://user-images.githubusercontent.com/2802467/125907927-837dc860-c4c6-4e48-8fcd-24140364f2df.png)

Log in as admin, in the same dictionary give permissions back:
![image](https://user-images.githubusercontent.com/2802467/125907943-70c2c1cb-41a9-4651-9da7-738a342c1883.png)
![image](https://user-images.githubusercontent.com/2802467/125908012-393b960e-ea7e-4f74-9d2d-8a6213fd2322.png)

Try again saving modified parser results and deleting parser results as 'test', works ok.

**Comment by nadezhday** [comment]
Verified. Everything works fine. Instead of 'test' user 'julia' was used.
