### ISSUE TITLE
Phonology: 'Fast Track' formant computation

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#459]
User should be able to select computation of formant data according to https://github.com/santiagobarreda/FastTrack algorithm.

**Comment by myrix** [comment]
Implemented.

User can select 'Fast Track' formant computation in phonology dialog:
![image](https://user-images.githubusercontent.com/2802467/129345161-241c018a-c203-42a5-b699-277dc22b86d2.png)

NOTE: Can take a really long time.

**Comment by nadezhday** [comment]
Login as admin.
Open /dictionary/4003/17/perspective/4003/21/edit
![image](https://user-images.githubusercontent.com/59951991/132679755-46fb9a8d-f8d7-42b2-b390-bd84a9da740a.png)
Tools->Phonology
checkbox Fast track formant extraction - ON
Create
Result: OK

Verified.

**Comment by nadezhday** [comment]
@myrix could you please help.

Result: (4/4) Finished, no result produced
Should we get any generated files?
![image](https://user-images.githubusercontent.com/59951991/139664936-5bf61868-fae8-4fa2-ad03-de29382266f7.png)

**Comment by nadezhday** [comment]
We will not cover this functionality is selenium test. DB has been changed.
