### ISSUE TITLE
Perspective properties: fields do not unlink

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#460]
Open http://lingvodoc.ispras.ru/dictionary/4003/17/perspective/4003/21/edit, Lexical Entries dropdown menu, 'Lexical Entries' properties..., try to unlink 'Sound' field from the 'Word' field by clearing checkbox:
![image](https://user-images.githubusercontent.com/2802467/130947174-08c464c4-eb9d-428b-8218-c65c043b565b.png)

Close the dialog, open it again, the field is still linked.

**Comment by myrix** [comment]
Fixed, now fields unlink properly.

**Comment by nadezhday** [comment]
Verified.

**Comment by nadezhday** [comment]
Covered in tests\test_perspective_properties.py
