### ISSUE TITLE
Adding cache-through system

### ISSUE THREAD

**Issue by Winking-maniac** [ispras/lingvodoc-react#462]
Remaking cache for only Redis. Also adding some new caching features based on Redis specifity, such as bulk set/get, implementing simple intarface for saving/loading database objects and replacing database queries with cache queries in order to perfomance

**Comment by nadezhday** [comment]
master (634):
https://jenkins.zeus.intra.ispras.ru/job/test_lingvodoc_frontend/test_results_analyzer/ 
specific backend (52): https://jenkins.zeus.intra.ispras.ru/job/test_lingvodoc_specific_backend/test_results_analyzer/ 
[Tests_execution_time_634-52_Jenkins.xlsx](https://github.com/ispras/lingvodoc-react/files/7438933/Tests_execution_time_634-52_Jenkins.xlsx)

Verified.
