### ISSUE TITLE
'Cognate ...' tools accessible to users with perspective editing permissions

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#463]
Rel. #445 'Cognate ...' tools accessible to perspective authors.

Now we need to allow access to 'Cognate...' tools to all users with editing permissions for the perspective.

**Comment by myrix** [comment]
Implemented.

Testing:

Open /dictionary/714/5/perspective/714/6/view logged in as 'test', no 'Cognate...' tools in the menu:
![image](https://user-images.githubusercontent.com/2802467/134114155-f7339a73-613f-409c-9279-ab3d5356fd45.png)

Now log in as admin, go to the same dictionary, open perspective roles dialog ('Lexical Entries' dropdown menu, ''Lexical Entries' roles...' menu entry), add 'test' user, check that it has 'Can edit perspective' role:
![image](https://user-images.githubusercontent.com/2802467/134114544-747191c7-b53c-4ae1-809c-c3a4f96dcf72.png)

Ensure 'test' user is active as per instructions in https://github.com/ispras/lingvodoc-react/issues/458#issuecomment-881234657 (search for "Ensure 'test' user is active:"), again open the dictionary logged in as 'test', 'Cognate...' tools are in the menu, e.g. 'Cognate analysis' opens and computes ok:
![image](https://user-images.githubusercontent.com/2802467/134116136-94142e78-b6d7-4f2f-b7ea-e750e315692e.png)
![image](https://user-images.githubusercontent.com/2802467/134116151-3bd00bf4-4abd-44dd-ab98-afce15d2535c.png)

**Comment by nadezhday** [comment]
Verified. Works as expected.
