### ISSUE TITLE
Cognate Suggestions: Connect ->GraphQL error: No such entry in the system

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#464]
Test failed tests\test_cognate_suggestions.py

Steps to reproduce:

Login as admin
open http://83.149.198.62/dictionary/657/3/perspective/657/4/view
Tools->Cognate Suggestions
Compute
Uncheck option  'один (первый) вариант 1ʼ (Dictionary of Yukonda dialect of Mansi - Lexical Entries)'
Click Connect

Problem:
![image](https://user-images.githubusercontent.com/59951991/135802356-50b6150d-affc-466d-977c-899ea7f34ed4.png)

Query error
Failed to connect selected lexical entries, please contact developers.

**Comment by nadezhday** [comment]
Version
Backend:2.1.1+1400-b36002a3-2021.10.01-18:35+modified-2021.10.04-04:45
uniparser-erzya:1.1.2
uniparser-komi-zyrian:1.1.6
uniparser-meadow-mari:1.1.7
uniparser-moksha:1.1.0
uniparser-udmurt:2.1.6
Frontend:da5e9c5f-448-staging-server

**Comment by Winking-maniac** [comment]
Fixed and need verification on custom repository https://github.com/Winking-maniac/lingvodoc/tree/caching

**Comment by nadezhday** [comment]
The problem is fixed.
![image](https://user-images.githubusercontent.com/59951991/138406076-8cbb0c00-2aec-4ba7-bf2d-aff53a7102c3.png)

Test - PASSed
