### ISSUE TITLE
Organization: Accept Request -> Exception

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#465]
Test tests\test_organizations.py  - Failed

Steps to reproduce:
login as admin

http://83.149.198.62/dashboard/dictionaries
search for: Dictionaryof Sary-Yughur language (Draft)
From drop down menu select  Organizations... command
![image](https://user-images.githubusercontent.com/59951991/135808720-c6f43bcf-c72d-4903-bddd-446f54671671.png)

Click Request Link
![image](https://user-images.githubusercontent.com/59951991/135808813-ba5c3053-fa7b-46dd-9af9-798e559df827.png)

Administrator->Requests menu
Click Accept button/

Problem: 
![image](https://user-images.githubusercontent.com/59951991/135808393-a8fd1807-6d3a-41c0-a2e1-ae4aecc63d39.png)

![image](https://user-images.githubusercontent.com/59951991/135806409-b7eee31f-0af8-4353-8c9c-7af6c5324719.png)

The Exception is reported in Console:
Uncaught (in promise) Error: GraphQL error: 'dict_id'
    e ApolloError.js:37
    next QueryManager.js:186
    d Observable.js:126
    h Observable.js:161
    value Observable.js:215
    next index.js:37
    d Observable.js:126
    h Observable.js:161
    value Observable.js:215
    l index.js:91
    promise callback*l/</< index.js:90
    t Observable.js:179
    value Observable.js:258
    o index.js:19
    t Observable.js:179
    value Observable.js:258
    mutate QueryManager.js:183
    mutate QueryManager.js:124
    mutate ApolloClient.js:98
    dataForChildViaMutation react-apollo.browser.umd.js:544
    a Requests.js:19
    onClick Requests.js:125
    Lodash 4
    e Button.js:103
    React 12
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
    d raven.js:393
    b raven.js:1046
    React 15
    i index.js:66
    1287 index.js:80
    Webpack 5

**Comment by Winking-maniac** [comment]
Fixed and need verification on custom repository https://github.com/Winking-maniac/lingvodoc/tree/caching

**Comment by nadezhday** [comment]
Follow the steps from discription
![image](https://user-images.githubusercontent.com/59951991/137899050-fd55b477-065f-4524-91f8-f165676d9fb9.png)

Exception:
 GraphQL error: get() got an unexpected keyword argument 'objects'
@Winking-maniac, can you reproduce this problem in your env? 

BTW: We have 21 failed selenium tests.

Version
Backend:2.1.1+1409-d34842f8-2021.10.13-14:46+modified-2021.10.19-10:49
uniparser-erzya:1.1.2
uniparser-komi-zyrian:1.1.7
uniparser-meadow-mari:1.1.7
uniparser-moksha:1.1.0
uniparser-udmurt:2.1.6
Frontend:fc7f0822-469-staging-server

**Comment by Winking-maniac** [comment]
Fixed and need verification on custom repository https://github.com/Winking-maniac/lingvodoc/tree/caching

**Comment by nadezhday** [comment]
https://jenkins.zeus.intra.ispras.ru/job/test_lingvodoc_specific_backend/50/
Test tests\test_organizations.py - PASSed
