### ISSUE TITLE
Mobile version: some elements are not available

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#468]
Mobile version
Open Lingvodoc on mobile

![image](https://user-images.githubusercontent.com/59951991/136145524-c25326fa-d7d4-48b4-91f5-8fce070a2bbe.png)
1) Lingvodoc 3.0 is not present in the top menu
2) open Dictionaries-> any view (e.g starling_source)
Problem: Tabs (View contributions ...) cannot be reached

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
We can close with issue. There are other places that can be fixed. But we will create separate defects for found issues.
