### ISSUE TITLE
Scroll to the top by default if a new menu is selected

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#469]
Login as admin
Admin->Organization
scroll down the page
![image](https://user-images.githubusercontent.com/59951991/136146600-24709018-4d2a-47c3-ac30-16b64b376edb.png)
Select Admin -> my Files
Select Admin ->Organizations
Expected: We should be on the top
Actual: We are on the bottom of the page

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Verified
