### ISSUE TITLE
Scrollbar is hidden under the top menu

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#471]
Open http://83.149.198.62/dashboard/dictionaries_all (the same problem with other pages)
Start scrolling.
Problem: Scrollbar is not visible. It appears afterwards.
![image](https://user-images.githubusercontent.com/59951991/136148115-7449e4db-318f-40c4-8d9b-f7fd1af44933.png)
![image](https://user-images.githubusercontent.com/59951991/136148260-fa30fb92-ff7f-4d87-923f-d3c4b5118457.png)

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Verified
