### ISSUE TITLE
Menu Localization 

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#472]
Probably this is a duplicate.
This issue is found by users.
![image](https://user-images.githubusercontent.com/59951991/136149734-e09b6bc6-dda7-4a2c-94f8-d241eff76a2e.png)

![image](https://user-images.githubusercontent.com/59951991/136149802-8a67f67b-9aa5-4446-b752-d787e0f928ca.png)

![image](https://user-images.githubusercontent.com/59951991/136149855-5b1f0978-56aa-4bf7-9776-4b77b82e7176.png)

![image](https://user-images.githubusercontent.com/59951991/136149938-7393c32c-2cab-4940-bbe7-8220fea3fff0.png)

For developers: all menus should be translated

**Comment by nadezhday** [comment]
Test tests\test_language.py failed. This is a regression/

**Comment by al-indigo** [comment]
fixed everything except search (search options won't be fixed in near future)

**Comment by nadezhday** [comment]
This particular case can be verified.

Separate defects will be created for non-localized strings in Lingvodoc.

https://github.com/ispras/lingvodoc-react/issues/479 Non-localized sub menus
https://github.com/ispras/lingvodoc-react/issues/480 Non-localized table header strings for Organizations
https://github.com/ispras/lingvodoc-react/issues/481 Localization problem with "By Organizations" string on 83.149.198.62
https://github.com/ispras/lingvodoc-react/issues/482 Localize "The work is supported by the following grants"
https://github.com/ispras/lingvodoc-react/issues/484 Localization in create/import dictionary pages

**Comment by nadezhday** [comment]
I would close this issue @al-indigo. As soon as this issue is Closed I will add the Verified label.

**Comment by jandrew44** [comment]
Closing.
