### ISSUE TITLE
Update edit_translation page

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#473]
http://83.149.198.62/edit_translations

![image](https://user-images.githubusercontent.com/59951991/136153126-547929b7-e876-4b6a-87c3-e3613617a6dc.png)

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Looks fine. Verified.

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_translations.py
