### ISSUE TITLE
Remove Duplicated login dialog

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#476]
Test failed
Reason:
Look at the screenshot.We have duplicated dialog:
![image](https://user-images.githubusercontent.com/59951991/136509204-0a87af64-a5b4-451d-ae1f-5dc82be0039e.png)

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
@ianlethic  FYI
I still can see duplicated dialog. 
@nataliauvarova could you please check that your changes are in the build? 
The first dialog is for mobile, The second is for computer. Please clearify How this issue was fixed?

**Comment by nataliauvarova** [comment]
> @ianlethic FYI I still can see duplicated dialog. @nataliauvarova could you please check that your changes are in the build? The first dialog is for mobile, The second is for computer. Please clearify How this issue was fixed?

https://github.com/ispras/lingvodoc-react/pull/477/files

**Comment by nadezhday** [comment]
Only one dialog exists. OK
![image](https://user-images.githubusercontent.com/59951991/136957331-9a7effb6-dd9d-4b56-aff5-ec3e21c96822.png)
Verified

**Comment by vmonakhov** [comment]
Covered in selenium tests
