### ISSUE TITLE
Organization users(admins): Exception Uncaught TypeError: d is undefined

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#478]
Login as admin
![изображение](https://user-images.githubusercontent.com/59951991/136908035-b158eecd-c811-44b5-8a94-16d08ffeb1a6.png)
Administrator menu-> Request
Organization users

Problem: Empty screen. Exception

TypeError: d is undefined
    q Requests.js:77
    React 6
    unstable_runWithPriority scheduler.production.min.js:19
    React 5
    d raven.js:393
raven.js:55:31

Uncaught TypeError: d is undefined
    q Requests.js:77
    React 6
    unstable_runWithPriority scheduler.production.min.js:19
    React 5
    d raven.js:393
Requests.js:77:6

The same problem if you invoke 
Organization admins command

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Verified.
Version
Backend:2.1.1+1408-f037bf0e-2021.10.06-12:39+modified-2021.10.13-05:35
uniparser-erzya:1.1.2
uniparser-komi-zyrian:1.1.7
uniparser-meadow-mari:1.1.7
uniparser-moksha:1.1.0
uniparser-udmurt:2.1.6
Frontend:473f7b9c-459-staging-server

**Comment by nadezhday** [comment]
Covered in selenium tests tests\test_organization_users.py
tests\test_organization_admins.py
