### ISSUE TITLE
Non-localized sub menus

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#479]
Login as admin
Non-localized sub menus
1) Organizations
![image](https://user-images.githubusercontent.com/59951991/136945363-b1c6ddec-8faf-4cc3-8abc-aa2f7ad85c25.png)

**Comment by jandrew44** [comment]
Fixed.

**Comment by nadezhday** [comment]
Organization sub menu is localized - OK

**Comment by nadezhday** [comment]
A separate defect will be created for User account activation/deactivation submenu.
![image](https://user-images.githubusercontent.com/59951991/137869640-57020b0f-700d-4986-bf85-331b70cc99ac.png)
https://github.com/ispras/lingvodoc-react/issues/496  User account activation/deactivation submenu needs localization
