### ISSUE TITLE
Non-localized table header strings for Organizatons

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#480]
Login as Admin
Open Organizations
Problem: Header table is not translated into Russian
![image](https://user-images.githubusercontent.com/59951991/136945958-5faab11a-5c74-4de6-9c94-f1e1df1edc92.png)

**Comment by jandrew44** [comment]
Frontend changes has been completed.
Gists should be created/updated.

**Comment by jandrew44** [comment]
Now gists can be created via UI on the /edit_translations page so closing this issue as fixed.

**Comment by nadezhday** [comment]
Verified

![image](https://user-images.githubusercontent.com/59951991/159452993-d535a72c-a153-4b93-b60a-5a8c0250e6f8.png)
