### ISSUE TITLE
Localize "The work is supported by the following grants"

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#482]
Open http://83.149.198.62/dashboard/dictionaries_all 
Problem: "The work is supported by the following grants" is not translated into Russian

**Comment by nadezhday** [comment]
Can we also translate in this case "Project funded by grants"?
http://83.149.198.62/grantsRoute
Project funded by grants

**Comment by jandrew44** [comment]
1) "The work is supported by the following grants" - added on the frontend
Gist/translation should be added now.

2) "Project funded by grants" - no changes are required on the frontend
Gist/translation should be created/updated.

**Comment by nataliauvarova** [comment]
Fixed (in the admin panel on production)

**Comment by nadezhday** [comment]
![изображение](https://user-images.githubusercontent.com/59951991/153538291-02195151-b39a-4a1f-8ee8-a64dbc2b466b.png)
Verified

**Comment by vmonakhov** [comment]
Covered in tests/test_localization.py
