### ISSUE TITLE
Add one more grand in the list /dashboard/dictionaries_all

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#483]
Open http://83.149.198.62/grantsRoute 
Result: there are 9 grands in the list.
![image](https://user-images.githubusercontent.com/59951991/136950101-d060c680-5501-47d2-af11-01e53ef48ed9.png)

Open http://83.149.198.62/dashboard/dictionaries_all
Problem: there are 8 grands in the list.
![image](https://user-images.githubusercontent.com/59951991/136950174-d5a3bdab-9786-470b-bab1-1c00a5e554ae.png)

**Comment by jandrew44** [comment]
Could not reproduce.
I have 8 grants in both lists.

**Comment by nadezhday** [comment]
Expected: We should have 9 grants.  The 9th grand was added not long ago.
Actual: 8 grants on http://83.149.198.62/dashboard/dictionaries_all  - NOK
(RFBR 14-06-00271) Development of a virtual computational laboratory for management and processing data for endangered languages 2014-2016  is missing

On this page http://83.149.198.62/grantsRoute the grand was added: OK  (9 grands)

**Comment by jandrew44** [comment]
"Development of a virtual computational laboratory for management and processing data for endangered languages 2014-2016".
This grant does not have any dictionaries associated, therefore it is not being displayed.
This behavior is correct.

**Comment by nadezhday** [comment]
OK. Works as designed. Verified.
