### ISSUE TITLE
Localization in create/import dictionary pages

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#484]
Localization problem: 
http://83.149.198.62/dashboard/create_dictionary
Dictionary names and metadata Set dictionary name, translations and metadata
![image](https://user-images.githubusercontent.com/59951991/136951952-0a439de6-1021-4538-b546-4a38d52dff23.png)

http://83.149.198.62/dashboard/create_corpus
Corpus names and metadata Set corpus name, translations and metadata
![image](https://user-images.githubusercontent.com/59951991/136952188-cee4a516-ace7-4970-a6b0-0f84e2305cdb.png)

http://83.149.198.62/import_dialeqt
![image](https://user-images.githubusercontent.com/59951991/136952281-e38e7aa2-eb50-4f04-a163-ea4ae3424e5e.png)

http://83.149.198.62/import
![image](https://user-images.githubusercontent.com/59951991/136952340-ed6f790b-3f76-4b7d-8e44-0eedc05b5cdf.png)

**Comment by jandrew44** [comment]
I have added missing strings on the frontend.
Now translations gists should be added/updated.

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Verified: http://83.149.198.62/import_dialeqt

Verified: http://83.149.198.62/import

Verified: http://83.149.198.62/dashboard/create_corpus

Verified: http://83.149.198.62/dashboard/create_dictionary
