### ISSUE TITLE
Chrome: some columns are not visible in the Grant table

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#487]
Chrome specific issue.
This problem was detected by automatic test
screenshot from the test execution shows the following: 
![image](https://user-images.githubusercontent.com/59951991/137070315-efa8ffed-127b-4bda-a71d-0c8ab18743d8.png)
Also can be reproduced manually.
Open http://83.149.198.62/grants
![image](https://user-images.githubusercontent.com/59951991/137070603-6fbdbd62-03b0-490e-b616-217575efcffe.png)
Problem: some columns are not visible.

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Looks fine.
Verified.

**Comment by vmonakhov** [comment]
Covered in tests/test_grants.py
