### ISSUE TITLE
Make the top menu narrower

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#488]
![image](https://user-images.githubusercontent.com/59951991/137077322-6e5361e3-7ad5-461c-967c-461280db5034.png)

Customer asks to make the top menu a little bit narrower.
Can we do this?

**Comment by Dina936** [comment]
Heder reduced

https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=728%3A4842

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Looks fine.
