### ISSUE TITLE
Add illustration 

### ISSUE THREAD

**Issue by Dina936** [ispras/lingvodoc-react#490]
Add illustration for Distance map

<img width="353" alt="Снимок экрана 2021-10-13 в 13 49 02" src="https://user-images.githubusercontent.com/56397844/137119501-d2f9d35c-d187-4dad-bd89-8ee3efd46bd7.png">

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
verified.
![image](https://user-images.githubusercontent.com/59951991/137274075-cec3eca7-c72d-49a3-8281-34aeae574983.png)
