### ISSUE TITLE
Mobile version: some elements are not available (Part 2)

### ISSUE THREAD

**Issue by nataliauvarova** [ispras/lingvodoc-react#495]
Pages:
http://lingvodoc.ru/map_search
http://lingvodoc.ru/authors_route
![Снимок экрана 2021-10-18 в 17 26 15](https://user-images.githubusercontent.com/90451645/137751533-1b1a2932-6963-4dd3-b387-52c046a8430b.png)

![Снимок экрана 2021-10-18 в 17 26 40](https://user-images.githubusercontent.com/90451645/137751550-1c2ba164-2588-4561-beaf-882b47fd5681.png)

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Tested in Chrome with Window resizer plugin.
Both pages look fine. OK
