### ISSUE TITLE
User account activation/deactivation submenu needs localization

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#496]
The problem found during https://github.com/ispras/lingvodoc-react/issues/479 verification
User account activation/deactivation submenu needs localization.
![image](https://user-images.githubusercontent.com/59951991/137869967-e8742650-a939-4130-ae1f-161d2382a4e3.png)

**Comment by jandrew44** [comment]
Translation gist should be created or updated.

**Comment by nataliauvarova** [comment]
fixed

**Comment by nadezhday** [comment]
Verified
![image](https://user-images.githubusercontent.com/59951991/155466423-d94c03cb-29bf-4756-a2f5-77126e2938a4.png)

**Comment by vmonakhov** [comment]
Covered in tests/test_localization.py
