### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by Dina936** [ispras/lingvodoc-react#497]
Change font and alignment in version
<img width="646" alt="Снимок экрана 2021-10-19 в 13 28 43" src="https://user-images.githubusercontent.com/56397844/137892459-a0bcaede-1484-45a9-bfe4-7e2276197201.png">
<img width="574" alt="Снимок экрана 2021-10-19 в 13 28 35" src="https://user-images.githubusercontent.com/56397844/137892462-f87a3e17-c8a1-4fcd-8e87-7a0fac6bcffa.png">
.

**Comment by nataliauvarova** [comment]
Fixed
