### ISSUE TITLE
Change the style of buttons

### ISSUE THREAD

**Issue by Dina936** [ispras/lingvodoc-react#499]
1) Change the style of buttons: Cancel and Save
https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=310%3A818
<img width="514" alt="Снимок экрана 2021-10-19 в 16 21 30" src="https://user-images.githubusercontent.com/56397844/137918380-e601d9d6-c497-4205-ba0f-1901a6f3bb23.png">

2) Remove dashes in a button
<img width="178" alt="Снимок экрана 2021-10-19 в 13 50 48" src="https://user-images.githubusercontent.com/56397844/137918570-cd9e506c-e643-48e2-86a1-c933457669da.png">

**Comment by nataliauvarova** [comment]
Fixed. Changed the styles of buttons: Cancel, Close and Save

**Comment by nadezhday** [comment]
Separate cases were created for further improvements.

This case can be closed.
