### ISSUE TITLE
New design for Tasks bar

### ISSUE THREAD

**Issue by nataliauvarova** [ispras/lingvodoc-react#501]
![Снимок экрана 2021-10-20 в 17 40 29](https://user-images.githubusercontent.com/90451645/138115290-373d69fc-919a-4627-a0a5-00c6b03c9ae6.png

![Снимок экрана 2021-10-20 в 17 41 28](https://user-images.githubusercontent.com/90451645/138115299-83bacb02-c049-4e5e-8b2d-2f08c8a3a649.png)
)

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Backend:2.1.1+1408-f037bf0e-2021.10.06-12:39+modified-2021.10.21-07:08
uniparser-erzya:1.1.2
uniparser-komi-zyrian:1.1.7
uniparser-meadow-mari:1.1.7
uniparser-moksha:1.1.0
uniparser-udmurt:2.1.6
Frontend:49370ee8-475-staging-server

We are missing Close button. 
![image](https://user-images.githubusercontent.com/59951991/138243284-24b2a4e6-f07d-4e42-a3e7-de2d6de06b0e.png)

**Comment by nataliauvarova** [comment]
> Backend:2.1.1+1408-f037bf0e-2021.10.06-12:39+modified-2021.10.21-07:08 uniparser-erzya:1.1.2 uniparser-komi-zyrian:1.1.7 uniparser-meadow-mari:1.1.7 uniparser-moksha:1.1.0 uniparser-udmurt:2.1.6 Frontend:49370ee8-475-staging-server
> 
> We are missing Close button. ![image](https://user-images.githubusercontent.com/59951991/138243284-24b2a4e6-f07d-4e42-a3e7-de2d6de06b0e.png)

The Сlose button should not be on large screens:
https://user-images.githubusercontent.com/90451645/138115290-373d69fc-919a-4627-a0a5-00c6b03c9ae6.png

**Comment by nadezhday** [comment]
Verified
![image](https://user-images.githubusercontent.com/59951991/138408259-3c6f674e-9c73-4a83-8336-6c72ea5b4400.png)

**Comment by nadezhday** [comment]
Covered in tests\test_tasks_mobile.py
