### ISSUE TITLE
Corpus Conversion failed: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#503]
Backend:2.1.1+1411-4b4107d1-2021.10.21-11:24+modified-2021.10.22-05:25
uniparser-erzya:1.1.2
uniparser-komi-zyrian:1.1.7
uniparser-meadow-mari:1.1.7
uniparser-moksha:1.1.0
uniparser-udmurt:2.1.6
Frontend:49370ee8-475-staging-server

Specific_backend https://jenkins.zeus.intra.ispras.ru/job/test_lingvodoc_specific_backend/50/

Selenium test failed tests\test_view_lexical_view_published.py (it covers steps from  https://github.com/ispras/lingvodoc-react/issues/214)
Login as admin

http://83.149.198.62/dictionary/2866/5/perspective/2866/9/view
Click table icon
Click the button "Convert to dictionary"
Select Language, add Translation (Test123_...)
Close dialog
![image](https://user-images.githubusercontent.com/59951991/138399641-63cb9eb0-738b-4cdd-9a39-344ae2e7fc35.png)

Problem:
(2/10) Conversion failed: 'NoneType' object has no attribute 'get'

**Comment by Winking-maniac** [comment]
Fixed in remote repo https://github.com/Winking-maniac/lingvodoc/tree/caching. Needed verifiication

**Comment by nadezhday** [comment]
Verified in 
Backend:2.1.1+1416-523dc13f-2021.10.27-15:54+modified-2021.10.28-04:17
uniparser-erzya:1.1.2
uniparser-komi-zyrian:1.1.7
uniparser-meadow-mari:1.1.7
uniparser-moksha:1.1.0
uniparser-udmurt:2.1.6
Frontend:78cfd82f-479-staging-server

![image](https://user-images.githubusercontent.com/59951991/139188229-8241e6c1-78d4-427a-be70-632c7c09e22a.png)
