### ISSUE TITLE
Undo dictionary does not work

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#504]
https://jenkins.zeus.intra.ispras.ru/job/test_lingvodoc_specific_backend/50/

Selenium test tests\test_dictionaries.py - FAILed

Steps to reproduce can be found here:  https://github.com/ispras/lingvodoc-react/issues/240

The problem: after using curl command for undoing dictionary deletion and refreshing web page dictionary does not appear.

**Comment by Winking-maniac** [comment]
Fixed in remote repo, need verification @nadezhday

**Comment by nadezhday** [comment]
Selenium test tests\test_dictionaries.py - PASS
https://jenkins.zeus.intra.ispras.ru/job/test_lingvodoc_specific_backend/52/
Verified
