### ISSUE TITLE
Kazakh and Tatar parsers added

### ISSUE THREAD

**Issue by ankan2013** [ispras/lingvodoc-react#506]
Parsers for Kazakh and Tatar languages developed by Apertium team were added to the Lingvodoc back-end. The pull-request is https://github.com/ispras/lingvodoc/pull/1322.
Steps for testing are below:
1. Go to http://83.149.198.62/ and authorize as Administrator
2. Open http://83.149.198.62/dictionary/4113/4/perspective/4113/11/edit
3. Create a new lexical entry and add two files available by the links below
[tat.docx](https://github.com/ispras/lingvodoc-react/files/7411809/tat.docx)
[kaz.odt](https://github.com/ispras/lingvodoc-react/files/7411814/kaz.odt)
![parsersadded1](https://user-images.githubusercontent.com/45983282/138730600-03dfa786-3e06-4aad-8ded-e7eafe3bd5c1.png)
4. A parser can be launched with the key:
![parsersadded2](https://user-images.githubusercontent.com/45983282/138731332-e215acf3-4123-42b6-8792-e2964d3fe72d.png)
Press it for each of two files and select the Kazakh parser by Apertium for "kaz.docx" and the Tatar parser by Apertium for "tat.odt":
![parsersadded3](https://user-images.githubusercontent.com/45983282/138731619-8d2f01d1-314b-476a-810b-72a4d149786e.png)
![parsersadded4](https://user-images.githubusercontent.com/45983282/138731623-f2a64195-e03d-4f1d-bddc-a5ad5e366ca4.png)
5. Make sure that both parsers have finished:
![parsersadded5](https://user-images.githubusercontent.com/45983282/138732406-643ef684-918e-4d3f-8e04-ae81b477b1aa.png)
6. Reload the page
7. To open a result, press:
![parsersadded6](https://user-images.githubusercontent.com/45983282/138732806-c4f82529-30ad-485f-a6fd-9fcff1ddafaa.png)
8. Expected result for the Kazakh parser looks like:
![Screenshot from 2021-10-25 19-16-50](https://user-images.githubusercontent.com/45983282/138732918-329c4dab-0efd-4587-a34b-82eb9edb2473.png)
9. Expected result for the Tatar parser looks like:
![Screenshot from 2021-10-25 19-16-35](https://user-images.githubusercontent.com/45983282/138732964-99562c86-ec22-4026-a435-db9d3e841d24.png)

**Comment by nadezhday** [comment]
Version
Backend:2.1.1+1408-f037bf0e-2021.10.06-12:39+modified-2021.10.26-01:00
uniparser-erzya:1.1.2
uniparser-komi-zyrian:1.1.7
uniparser-meadow-mari:1.1.7
uniparser-moksha:1.1.0
uniparser-udmurt:2.1.6
Frontend:e641a841-477-staging-server

1) 
![image](https://user-images.githubusercontent.com/59951991/138822731-35aa0848-1f9d-493b-a08f-74257952990f.png)

2) 
![image](https://user-images.githubusercontent.com/59951991/138822816-62da12d2-9d3e-4da9-9769-d0c854e69b1b.png)

@ankan2013 I am just waiting for you. Please close this issue. And then I will put label Verified.

**Comment by nadezhday** [comment]
Verified.

**Comment by vmonakhov** [comment]
Covered in tests/test_parser_tat.py and tests/test_parser_kaz.py
