### ISSUE TITLE
Parser markup keyboard navigation added

### ISSUE THREAD

**Issue by ankan2013** [ispras/lingvodoc-react#507]
Some improvements to the Lingvodoc front-end were provided with the pull-request https://github.com/ispras/lingvodoc-react/pull/527. The idea is to provide a user with the ability to make some trivial actions to speed up the process of a markup.
The features are below with the steps of reproducing. A short guide about parsers' launching and files uploading was provided in https://github.com/ispras/lingvodoc-react/issues/506.

1. If an element of a parser's markup is selected, pressing "->" (right arrow key) from a keyboard performs the selection of the next element (if exists), as well as pressing "<-" key performs the selection of the next element (if exists):
1) before pressing "->":
![Screenshot from 2021-10-25 19-28-41](https://user-images.githubusercontent.com/45983282/138734715-74bf5ace-d639-46bc-bab8-eeb861085433.png)
2) after pressing "->":
![Screenshot from 2021-10-25 19-29-31](https://user-images.githubusercontent.com/45983282/138734834-82965830-1861-4f83-8bc0-944dc6827cbd.png)
If no element selected, "->" pressing performs the selection of the first element. 

2. If an element of a parser's markup is selected, pressing a number key (from 1 to 9) from a keyboard performs the selection of a variant with the same sequential number in the list of the variants as a correct one and the selection of the next element of the markup (if exists):
1) before pressing "2":
![Screenshot from 2021-10-25 19-29-22](https://user-images.githubusercontent.com/45983282/138735230-519352f0-9417-4e3b-8de9-c0944d526422.png)
2) after pressing "2":
![Screenshot from 2021-10-25 19-29-59](https://user-images.githubusercontent.com/45983282/138735298-cf36f325-b91e-4332-b681-8fa5cda49754.png)
![Screenshot from 2021-10-25 19-30-13](https://user-images.githubusercontent.com/45983282/138735312-236d7d5d-424a-4470-9ccd-b767bfc7676f.png)
If the variant with pressed number has been already selected before, only the selection of the next element is been performed.  

3. If an element of a parser's markup is selected and there is the only variant, pressing "Enter" from a keyboard performs the selection of this variant as correct and the selection of the next element of the markup (if exists) - it's equivalent to pressing "1" in the step 2.

4. If a green highlited ("verified") element of a parser's markup is selected, pressing "Delete" from a keyboard performs cancelling the selection of all results for this element and setting the red highlight ("unverified"):
1) before pressing "Delete":
![Screenshot from 2021-11-09 14-02-25](https://user-images.githubusercontent.com/45983282/140912839-8fd4bd31-66fa-42f2-a24f-2dc128b006b4.png)
2) after pressing "Delete":
![Screenshot from 2021-11-09 14-02-37](https://user-images.githubusercontent.com/45983282/140912848-11ff75df-b082-4782-b28a-22661285d7ea.png)

Features 2-4 work only in 'Edit' mode.

**Comment by nadezhday** [comment]
This case still has status 'Open'.
@ankan2013 Is this task completed? Can we start verification? If so please close it and then we will start testing.

**Comment by nadezhday** [comment]
Testing:
1) Please watch video. It shows that -> and <- work strange.
[Right_Left_inMarkup.zip](https://github.com/ispras/lingvodoc-react/files/7416090/Right_Left_inMarkup.zip)

2) Clicking 1 or 2 is not obvious.

[Pressing_1_and_2.zip](https://github.com/ispras/lingvodoc-react/files/7416127/Pressing_1_and_2.zip)

3) Here is video when Enter does not work as expected (only one variant exists)

[Enter_for_existing1variant.zip](https://github.com/ispras/lingvodoc-react/files/7416171/Enter_for_existing1variant.zip)

@ankan2013 FYI

**Comment by nadezhday** [comment]
One more video: 
[1and2.zip](https://github.com/ispras/lingvodoc-react/files/7416267/1and2.zip)
Very interesting that sometimes buttons Remove from markup not available.

**Comment by nadezhday** [comment]
Instead of creating separate defects we agreed to reopen this one and try to fix found problems.

**Comment by nadezhday** [comment]
1) Problem with -> and <- navigation is fixed. 
2) Pressing Num (1,2 etc) - works fine
3) Enter - works 

Separate defects will be created for found issues.

**Comment by nadezhday** [comment]
Covered in tests\test_kaz_parser.py

**Comment by nadezhday** [comment]
Separate defect is created.
Using numeric keys from a keyboard.
Now it is possible to select a variant that is lower or equal 9.
This functionality does not work if we have more then 10 variants.
https://github.com/ispras/lingvodoc-react/issues/639 Markup: variant selection by pressing a number key (if more then 9 variants available)
