### ISSUE TITLE
Change the buttons style - PART 2

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#509]
The problem found during verification #499

Probably we should change the buttons style in all dialogs. What about style for Create? Compute buttons?
For example:
1) 
![image](https://user-images.githubusercontent.com/59951991/138810865-4b892c81-6326-4888-a7a2-fed2e96ec144.png)
2)
![image](https://user-images.githubusercontent.com/59951991/138811026-24aed773-07ef-415c-b44a-104a61fe6423.png)

Steps to reproduce:
Login as admin.
Open http://83.149.198.62/dictionary/2495/6658/perspective/2495/6662/edit
 Click Tools and any submenu (e.g Phonology)

**Comment by nadezhday** [comment]
What about changing style for all other buttons?
Add, Update etc

![image](https://user-images.githubusercontent.com/59951991/138814605-37a87df9-7a57-4644-b256-deeef7adf307.png)

**Comment by nadezhday** [comment]
More places where we should change button style (steps to reproduce can be taken from https://github.com/ispras/lingvodoc-react/issues/506 )
![image](https://user-images.githubusercontent.com/59951991/138821282-bf0b76bc-aa90-4dcf-ba56-a97f1b10acf3.png)

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/138821463-6f0dfefb-e02c-43aa-b2d9-e158420176ac.png)

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/138821719-2a01a5ba-c5b3-417e-b844-06ee4c505cfc.png)

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/138852446-2b1a9763-bdd2-416c-817f-10ef5a8da8bd.png)

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Verified
![image](https://user-images.githubusercontent.com/59951991/141753003-3b1662c3-b587-4d37-9ada-1ac9468b6918.png)

![image](https://user-images.githubusercontent.com/59951991/141753054-5b1cbebb-4233-4e3f-bf4d-abe166283557.png)

We can close this issue.
