### ISSUE TITLE
Improvements to version dialog (closing dialog)

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#510]
Open Version dialog.

Problem: There is no possibility to close it. 
It should have atleast [x].
Should it have Close button?

After pressing Close button or [x] we should find ourselves on this page
![image](https://user-images.githubusercontent.com/59951991/138813643-39b1344e-f85e-4c2e-9259-87b588791cc9.png)

**Comment by Dina936** [comment]
@nadezhday The version does not open in a modal window. Therefore, there is no close button. We go back in the same way as on all pages.

@nataliauvarova Can I make a "close" or "go back" button?

**Comment by Dina936** [comment]
@nadezhday
I think that you need to close the task and create a new "make buttons back"

**Comment by nadezhday** [comment]
@Dina936 I think we should leave this case opened.
Version page looks like a dialog.
It is not obvious that I need to use Go back button.

It should be fixed.
I do not think that we need to create another case. It can be fixed here.
![image](https://user-images.githubusercontent.com/59951991/158311349-5bcf8439-1c96-4e5a-bcae-d5d4118a58bd.png)

**Comment by Dina936** [comment]
@nadezhday Nadia, see my solution

https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=878%3A4418

**Comment by nadezhday** [comment]
@Dina936, looks fine.

**Comment by Dina936** [comment]
я перевожу на Наталью
https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=878%3A4418

**Comment by nataliauvarova** [comment]
Done

**Comment by nadezhday** [comment]
verified.

Test tests\test_support_version.py - updated
