### ISSUE TITLE
Dublicated [x] [x] buttons in Text markup dialog

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#511]
Step to reproduce can be taken from https://github.com/ispras/lingvodoc-react/issues/506
1)
![image](https://user-images.githubusercontent.com/59951991/138822079-8ab47989-65b4-4585-9424-ef0ecadf3862.png)

2) xpath to the second close icon:
(//i[@class='close icon'])[2]
![image](https://user-images.githubusercontent.com/59951991/138822357-eab29ab4-4cd2-462b-9c99-7833d89e3be8.png)

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Verified.

**Comment by vmonakhov** [comment]
Covered in tests/test_parser_kaz.py
