### ISSUE TITLE
Make links on Lingvodoc creators page more visible

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#513]
http://83.149.198.62/authors_route

There are two links on this page.
Can we make these links more visible to our users? So people can see them immediately.
![image](https://user-images.githubusercontent.com/59951991/138859176-842dc121-c818-43e5-8686-4f6c8bc2637d.png)

**Comment by Dina936** [comment]
<img width="608" alt="Снимок экрана 2021-11-16 в 11 19 20" src="https://user-images.githubusercontent.com/56397844/141947742-7e582d25-4cdc-4f66-83af-4aec18c944eb.png">

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
verified
