### ISSUE TITLE
New desing of Roles dialog

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#515]
http://83.149.198.62/dictionary/3987/4568/perspective/3987/4569/merge
![image](https://user-images.githubusercontent.com/59951991/138873666-51279eb2-793c-4ba9-a540-45f0be0c52cf.png)
Improve Roles dialog:
![image](https://user-images.githubusercontent.com/59951991/138873489-76b1bb7a-47b3-483f-af5c-59246fbe43b6.png)

**Comment by Dina936** [comment]
Dialogue with roles is ready

You can create a new task to change the design "combining lexical inputs"

**Comment by nadezhday** [comment]
A separate enhancement has been created: https://github.com/ispras/lingvodoc-react/issues/643 Improve design for the Merge suggestions functionality

**Comment by nadezhday** [comment]
This case is verified.
