### ISSUE TITLE
Improve Statistics dialog

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#516]
http://83.149.198.62/dictionary/3987/4568/perspective/3987/4569/merge

![image](https://user-images.githubusercontent.com/59951991/138873889-e896eb28-0946-40e8-9f5f-e313d6f1aa24.png)
Show statistics.
Improve Statistics dialog:

**Comment by Dina936** [comment]
https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=988%3A4782

**Comment by nataliauvarova** [comment]
Done

**Comment by nadezhday** [comment]
Two different dialogs:
1) 
![image](https://user-images.githubusercontent.com/59951991/164002281-e84af304-27f1-4b94-a3a2-b7840146b5f8.png)

![image](https://user-images.githubusercontent.com/59951991/164002127-71a8da5d-d418-4610-b2f2-25fb23c998b8.png)

2) 
![image](https://user-images.githubusercontent.com/59951991/164002560-5435089c-6545-4e6e-8679-db5799faa6a2.png)

![image](https://user-images.githubusercontent.com/59951991/164002442-e665e3b5-bbd1-49da-a4f7-7de7886519d2.png)

**Comment by nadezhday** [comment]
Verified.
