### ISSUE TITLE
Add button "Clear completed"

### ISSUE THREAD

**Issue by Dina936** [ispras/lingvodoc-react#517]
<img width="269" alt="Снимок экрана 2021-10-27 в 12 48 14" src="https://user-images.githubusercontent.com/56397844/139042602-52cc7939-0a7f-4e44-90ef-d2a7521bacf7.png">

**Comment by nataliauvarova** [comment]
design here: https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=715%3A6934

**Comment by nataliauvarova** [comment]
Done

**Comment by nadezhday** [comment]
Covered in tests\test_valency.py

**Comment by nadezhday** [comment]
verified

**Comment by nadezhday** [comment]
Covered in tests\test_valency.py
