### ISSUE TITLE
Impossible to work with Cognates functionality

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#518]
Customer reports the following problem:
Open http://lingvodoc.ispras.ru/dictionary/2639/4200/perspective/2639/4204/edit
Search for: два

Cognates

Problem: It takes too long.  Impossible to work with this functionality.

The same problem with 
http://lingvodoc.ispras.ru/dictionary/1393/37604/perspective/1393/37605/edit 
search for: два

**Comment by myrix** [comment]
Now works better, should also be faster.

**Comment by nadezhday** [comment]
Excellent. Works fine.

**Comment by nadezhday** [comment]
Covered in selenium test tests\test_cognate_performance_01.py
