### ISSUE TITLE
Search is slow, hangs up

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#519]
User report:

> Еще поиск, когда запрос из четырех разных слов, которые во многих словарях, он теперь часто просто виснет
> 
> Сейчас не воспроизведу, но неоднократно, если запрос корни четырех-пяти слов, например, два, тян, свет, моч сразу в одном запросе, то срабатывает на моем компе через раз и очень долго

Open http://lingvodoc.ispras.ru/map_search, wait for additional filter data to load, search field "Word" for "два" as "Substring", search takes quite a lot of time, transfers a lot of data.

Looks like most of this data is actually not used, just as was with #518.

**Comment by myrix** [comment]
Removed unnecessary data requests, search takes less time, transfers less data.

**Comment by nadezhday** [comment]
Search works rather fast now. Excellent.
![image](https://user-images.githubusercontent.com/59951991/139813366-7ef8848b-2f5c-4288-a4c5-d70aef21d924.png)

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/139814158-dc7a34f3-e01e-49f6-b7ab-afb415812bff.png)
No problem with the following search request.

**Comment by nadezhday** [comment]
JN:
The following scenario FAILed.
Do not set the first parameter. 
![изображение](https://user-images.githubusercontent.com/59951991/140684127-78240318-e2c2-481d-b22f-ad9315f8e9f9.png)

@myrix we have a separate case for this scenario
https://github.com/ispras/lingvodoc-react/issues/521

**Comment by myrix** [comment]
> JN: The following scenario FAILed. Do not set the first parameter. ![изображение](https://user-images.githubusercontent.com/59951991/140684127-78240318-e2c2-481d-b22f-ad9315f8e9f9.png)
> 
> @myrix Should we reopen this case or should we create a new one?

Works ok for me, would check with JN about her experience separately, in this new issue then.

![image](https://user-images.githubusercontent.com/2802467/140685373-3d94923d-fb21-4176-8d5a-0b5e25c332d8.png)

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_search_03.py
