### ISSUE TITLE
Phonology: .png file is not generated

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#523]
tests\test_phonology.py - FAILed
Steps (covers https://github.com/ispras/lingvodoc-react/issues/451):
Login as admin
Open http://83.149.198.62/dictionary/2088/4/perspective/2088/7/view
Tools->Phonology
Generate.

Expected result: generated .xlsx and .png files
Actual: .png file is not genarated

![image](https://user-images.githubusercontent.com/59951991/140700154-6ec65aa5-4988-415f-a223-6e6bbb494d6b.png)

**Comment by myrix** [comment]
Works as intended, no .png file due to insufficient data.

Reduce threshold, .png is generated:
![image](https://user-images.githubusercontent.com/2802467/140767951-53b80e5d-2dd6-4b98-85cc-61502f43f02d.png)
![image](https://user-images.githubusercontent.com/2802467/140768341-4bfdc704-e110-4ef3-8719-94c7257a8f40.png)

**Comment by nadezhday** [comment]
@myrix I did not have to change any option (formant chart threshold) before.
Why should I do it now? 

By default it (formant chart threshold) is 8 now.
If I change it to 1 then .png is generated.

**Comment by myrix** [comment]
> @myrix I did not have to change any option (formant chart threshold) before. Why should I do it now?

I assume because dictionary data was slightly altered, probably while there are only 7 instances of 'a' phoneme now, there were 8 before.

**Comment by nadezhday** [comment]
Ок, I will modify test.

**Comment by nadezhday** [comment]
Created one more test where png is generated. 
another dictionary is used (/dictionary/3548/1/perspective/3548/2/view)
tests\test_phonology_png.py

**Comment by nadezhday** [comment]
Test tests\test_phonology.py - FAILed

PNG is generated

Version
Backend:2.1.1+1576-2c522292-2022.05.25-08:38+modified-2022.05.26-01:00
uniparser-erzya:1.1.2
uniparser-komi-zyrian:1.1.17
uniparser-meadow-mari:1.1.12
uniparser-moksha:1.1.0
uniparser-udmurt:2.1.13
Frontend:server

@myrix FYI

**Comment by myrix** [comment]
> Test tests\test_phonology.py - FAILed
> 
> PNG is generated
> 
> Version Backend:2.1.1+1576-2c522292-2022.05.25-08:38+modified-2022.05.26-01:00 uniparser-erzya:1.1.2 uniparser-komi-zyrian:1.1.17 uniparser-meadow-mari:1.1.12 uniparser-moksha:1.1.0 uniparser-udmurt:2.1.13 Frontend:server
> 
> @myrix FYI

Checked, works as intended, except it seems there are more results then before. Looks like changes introduced by #796 allow for more meaningful data to be extracted, leading to more results.

So now it should have .png file, the test probably should be modified.

**Comment by nadezhday** [comment]
Test updated. (png should be generated)
