### ISSUE TITLE
New Design for Dictionaries

### ISSUE THREAD

**Issue by nataliauvarova** [ispras/lingvodoc-react#525]
Make pages 
http://lingvodoc.ru/dashboard/dictionaries
http://lingvodoc.ru/dashboard/corpora
with a new design:
https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=988%3A4782

**Comment by nataliauvarova** [comment]
Done

**Comment by nadezhday** [comment]
Verified.
Test were updated. PASSed.
