### ISSUE TITLE
New Design for tasks

### ISSUE THREAD

**Issue by nataliauvarova** [ispras/lingvodoc-react#526]
New design:
https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=715%3A6934

**Comment by nataliauvarova** [comment]
Fixed the tasks list (without the button "Clear completed")

**Comment by nadezhday** [comment]
Updated tests.

**Comment by nadezhday** [comment]
Clear completed will be implemented in https://github.com/ispras/lingvodoc-react/issues/517
