### ISSUE TITLE
Highlighted element shoud have a focus during navigation

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#529]
This  problem is found during verification of https://github.com/ispras/lingvodoc-react/issues/507 Parser markup keyboard navigation added.

Steps how to create a dictionary, a perspective with markup can be found in #507.

Click icon to open Text markup dialog.
![image](https://user-images.githubusercontent.com/59951991/141756414-397798a1-9ba4-4be3-a9ae-5897e469941a.png)

Click the last word that you can see and use -> to move to the next word.
![image](https://user-images.githubusercontent.com/59951991/141757352-ef5385fc-d7c3-4559-9712-c6dbc7166d1c.png)

Expected: we should move to the next word and we should see that next word is highlighted.
Actual: After pressing -> we have lost focus of the selected word.   Look at the screenshot.

![image](https://user-images.githubusercontent.com/59951991/141757494-6830425e-3329-4441-a9aa-038583c53664.png)

This is an important usability issue.

**Comment by jandrew44** [comment]
Added scroll into view when element is not visible.

**Comment by nadezhday** [comment]
[2022-03-09 09-39-43.zip](https://github.com/ispras/lingvodoc-react/files/8212282/2022-03-09.09-39-43.zip)
Watch video.

![изображение](https://user-images.githubusercontent.com/59951991/157386955-963deef5-05d5-425d-8678-5f9201fe0ba6.png)
Click Arrow right
![изображение](https://user-images.githubusercontent.com/59951991/157387260-ec5d9d05-b1bb-4477-932d-51782860a74c.png)

Problem: List of Variants is changed? but I cannot see the next word.
Workaround: you need to press extra Arrow down to see the next word focused.
![изображение](https://user-images.githubusercontent.com/59951991/157387444-f12053f2-aab9-4e2c-8f3e-f34186751904.png)

Should we do anything to fix this problem? @jandrew44

**Comment by jandrew44** [comment]
/dictionary/4739/4/perspective/4739/7/edit

I am getting "perspective not found" error when trying to open this url.
Both in my local environment and on production server.

@nadezhday

**Comment by nadezhday** [comment]
@jandrew44 
You should create a new dictionary (please follow the instruction from https://github.com/ispras/lingvodoc-react/issues/506)

**Comment by jandrew44** [comment]
It is a minor issue in case it is reproducible on one very specific text only.

**Comment by nadezhday** [comment]
Verified.
