### ISSUE TITLE
Disable keyboard navigation if the User defined variant dialog is opened

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#530]
This problem is found during verification of #507 Parser markup keyboard navigation added.

Steps how to create a dictionary, a perspective with markup can be found in #507.

Click icon to open Text markup dialog.
![image](https://user-images.githubusercontent.com/59951991/141758183-b2cb51e8-f41c-4b7c-b826-3831f6294007.png)

Click Язучы. 
![image](https://user-images.githubusercontent.com/59951991/141758893-b33ac48e-4532-4963-9da7-92218c6efad6.png)
Click 2
Verify that the second яз option is selected
![image](https://user-images.githubusercontent.com/59951991/141759150-8f4def3d-621e-4e38-b0b9-f187a619cc86.png)

Click Add variant button.
Add some values (put '1' in all fields )
Click Create.
![image](https://user-images.githubusercontent.com/59951991/141759458-0775d319-b068-4074-8111-b7976787a00e.png)

Problem: 
Look at the screenshot. We have  managed to select variants for the words without intention.
![image](https://user-images.githubusercontent.com/59951991/141760146-d5a30961-e1dc-4231-a864-c959448c1e5d.png)

We need to disable navigation if dialog is opened.

**Comment by jandrew44** [comment]
Could not reproduce the problem.
Perhaps it was fixed already.

**Comment by nadezhday** [comment]
The problem is not reproduced. Fixed indirectly.

**Comment by vmonakhov** [comment]
Covered in tests/test_parser_kaz.py
