### ISSUE TITLE
Buttons move on the bottom of the page and become unavailable in the Text markup dialog

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#531]
This problem is found during verification of #507 Parser markup keyboard navigation added.

Steps how to create a dictionary, a perspective with markup can be found in #507.

[kaz.odt](https://github.com/ispras/lingvodoc-react/files/7537671/kaz.odt)

Click icon to open Text markup dialog.

![image](https://user-images.githubusercontent.com/59951991/141762077-f2e8699a-891e-45e2-a018-d773b0d6227d.png)

Select the first word
![image](https://user-images.githubusercontent.com/59951991/141762401-1ecc7ce4-a926-4fe4-a5e6-4b02d44f41a6.png)
All buttons are visible - OK

Scroll down and select the word with a lot of variants (eg ойлайды)
![image](https://user-images.githubusercontent.com/59951991/141762910-44edd0ec-12d7-4f69-83ed-330c5c1fc698.png)

Problem: All buttons disappear.  

Let us scroll down and find out buttons.

Problem: Text is not visible

![image](https://user-images.githubusercontent.com/59951991/141763177-d8ba36ea-9c87-4da6-ba57-623fe3e345bd.png)

We need to improve usability. Should we move buttons on the top?
@Dina936 what do you think? Please advise how we can improve the design?

**Comment by jandrew44** [comment]
Separate scroll bar for variants has been added.
Bottom buttons are visible always now.

**Comment by nadezhday** [comment]
Verified

![image](https://user-images.githubusercontent.com/59951991/156875319-4f92fc7e-2564-44e6-a2c3-4a775b51e1c9.png)

**Comment by vmonakhov** [comment]
Covered in tests/test_parser_kaz.py
