### ISSUE TITLE
New Design for Main page

### ISSUE THREAD

**Issue by nataliauvarova** [ispras/lingvodoc-react#533]
New Design: 

Desktop:
https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=481%3A3704

Mobile:
https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=1249%3A5101

**Comment by nataliauvarova** [comment]
Done

**Comment by nadezhday** [comment]
Переделать 
![image](https://user-images.githubusercontent.com/59951991/141981537-55247b15-f74d-4e6b-b4d5-757c0e9e9115.png)

Добавить 
![image](https://user-images.githubusercontent.com/59951991/141981651-9d8bf23a-b2a0-41a9-87b6-273ee08cce4c.png)

@Dina936 FYI

**Comment by Dina936** [comment]
<img width="823" alt="Снимок экрана 2021-11-16 в 15 01 15" src="https://user-images.githubusercontent.com/56397844/141981947-1bb1f762-d076-4b68-89d5-ab9644965ba5.png">

**Comment by nataliauvarova** [comment]
text fixed

**Comment by nadezhday** [comment]
verified
