### ISSUE TITLE
Admin page design

### ISSUE THREAD

**Issue by Dina936** [ispras/lingvodoc-react#536]
1. Creating a new TranslationGist inside each category.
https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=1326%3A4887

**Comment by nataliauvarova** [comment]
done

**Comment by nadezhday** [comment]
Created separate defects:

https://github.com/ispras/lingvodoc-react/issues/550 - Make Add new translation gist button more visible

https://github.com/ispras/lingvodoc-react/issues/551 - Edit interface translations: By default the first tab (Perspective) should be active. 

https://github.com/ispras/lingvodoc-react/issues/552 - Edit interface translations: Duplicated gists

https://github.com/ispras/lingvodoc-react/issues/553 - Possibility to delete a gist

https://github.com/ispras/lingvodoc-react/issues/554 - Edit interface translations: Empty fields

https://github.com/ispras/lingvodoc-react/issues/555 - Edit interface translations: Missing information in lingvo-gist__header

https://github.com/ispras/lingvodoc-react/issues/556 - Element cannot be deleted - GraphQL error: Error: no such translationatom in the system

https://github.com/ispras/lingvodoc-react/issues/557 - Edit interface translations: The order of languages

https://github.com/ispras/lingvodoc-react/issues/560 - Edit interface translations: Duplicated entries after deletion

**Comment by nadezhday** [comment]
verified

**Comment by nadezhday** [comment]
https://github.com/ispras/lingvodoc-react/issues/561 - Edit interface translations: multiple identical localizations for the same dictionary

https://github.com/ispras/lingvodoc-react/issues/562 - Edit interface translations: Implement search

https://github.com/ispras/lingvodoc-react/issues/563 - Edit interface translations: Performance problem
