### ISSUE TITLE
Admin page design

### ISSUE THREAD

**Issue by Dina936** [ispras/lingvodoc-react#537]
mobile version
https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=1340%3A5984

**Comment by nataliauvarova** [comment]
done

**Comment by nadezhday** [comment]
Separate defects:

https://github.com/ispras/lingvodoc-react/issues/564 Edit interface translation (Mobile version): The field is not expanded.

**Comment by nadezhday** [comment]
For testers: cover this functionality

**Comment by nadezhday** [comment]
verified
