### ISSUE TITLE
Add button to Tools

### ISSUE THREAD

**Issue by Dina936** [ispras/lingvodoc-react#538]
Add button to Tools
<img width="612" alt="Снимок экрана 2021-11-23 в 17 37 07" src="https://user-images.githubusercontent.com/56397844/143044442-9db65fbb-0bb6-45de-b046-ec5678711d23.png">

**Comment by nataliauvarova** [comment]
Only for Admin.

**Comment by nataliauvarova** [comment]
Done.

**Comment by nadezhday** [comment]
Edit interface translations is added (only for admin) - OK

![image](https://user-images.githubusercontent.com/59951991/145163188-7fdbea54-d0f8-4e2f-95d0-9dd48be7e910.png)

Waiting with testing of Edit interface translations functionality. 
![image](https://user-images.githubusercontent.com/59951991/145163104-49d8055a-e4e1-4907-99d3-8f03eba8cd3a.png)


Separate defects:
https://github.com/ispras/lingvodoc-react/issues/543 Edit interface translations - localization is needed

**Comment by nadezhday** [comment]
Covered in tests\test_tools_translations.py
