### ISSUE TITLE
Cognate suggestions: no results without initial groups

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#540]
Open http://lingvodoc.ispras.ru/dictionary/4196/1/perspective/4196/2/view as admin, Tools -> Cognate suggestions, deselect the last dictionary "Dictionary Russian-Chud' which was complied P.K.Uspenski in 1913", click 'Compute', no results:
![image](https://user-images.githubusercontent.com/2802467/144315211-9ec44bd5-be30-43d6-b68a-1898a30b006f.png)

The problem is that selected dictionaries has no existing cognate groups; preferably, we would like to get cognate suggestions even in that case.

**Comment by myrix** [comment]
Changed, now we have results:
![image](https://user-images.githubusercontent.com/2802467/144316579-3a58318c-25da-4505-9a89-31855a721f39.png)

**Comment by myrix** [comment]
Note to testers: probably impossible to reproduce without this specific DB state or without specially prepared data in a separate non-production DB state.

**Comment by nadezhday** [comment]
Closing without verification. Screenshots from @myrix show that functionality works.
