### ISSUE TITLE
Edit interface translations - localization is needed 

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#543]
http://83.149.198.62/toolsRoute

![image](https://user-images.githubusercontent.com/59951991/145162309-15f7b40f-b048-49e0-8522-4665091aeab9.png)

Localization is missing for Edit interface translations.

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Verified: http://lingvodoc.ispras.ru/toolsRoute
