### ISSUE TITLE
Cognate suggestions: faster selection/deselection

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#544]
Users report that selection and deselection of words suggested to be grouped as cognates takes significant time, such that the interface does not feel sufficiently responsive.

E.g. open http://lingvodoc.ispras.ru/dictionary/4201/1/perspective/4201/2/view as admin, Tools -> Cognate suggestions, click 'Compute' button, wait for suggestions to appear, try toggling first suggestion checkbox back and forth, there is an identifiable pause:
![image](https://user-images.githubusercontent.com/2802467/145572454-5ca063a3-b6be-4d37-ac20-e122ffb4a03c.png)

As reported by users, with other sets of initial dictionaries and larger sets of suggestions the pause is noticeable.

We should try to do something about it.

**Comment by myrix** [comment]
Done something about it.

Local testing, before, min. 1.55 fps, about 600 ms pause:
![image](https://user-images.githubusercontent.com/2802467/145575484-07bae3be-13ab-45aa-b74b-316d3567bab3.png)

Local testing, after, min. 23.71fps, about 100 ms pause:
![image](https://user-images.githubusercontent.com/2802467/145575546-072a6ddc-4dde-462f-92a1-9c553268e5eb.png)

**Comment by nadezhday** [comment]
I was not able to perform this particular scenario.
Free testing:
Testing with  http://83.149.198.62/dictionary/4201/1/perspective/4201/2/view

![image](https://user-images.githubusercontent.com/59951991/147217135-98112f66-8785-4296-aeba-6347fbc1bd54.png)

**Comment by vmonakhov** [comment]
Covered in tests/test_cognate_suggestions.py
