### ISSUE TITLE
Docx -> Eaf corpus conversion

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#545]
Users should be able to convert suitably formatted .docx files to Lingvodoc 5-tier .eaf corpora.

**Comment by myrix** [comment]
Implemented.

To use, open /docx2eaf url. Only signed in users can use the converter.

For files in the standard format, like [Чертыкова_Беседы_14.09.2019.docx](https://github.com/ispras/lingvodoc-react/files/7699137/_._14.09.2019.docx), just select the file via 'Browse...' button, wait for conversion to finish, and you can download the result:
![image](https://user-images.githubusercontent.com/2802467/145721488-53dea9d0-51fc-49a4-a217-690c4134ab51.png)

Some files, like [Маркешта Святой Іôванӷели (2).docx](https://github.com/ispras/lingvodoc-react/files/7699141/o.2.docx), due to a slight format difference require 'All tables' option, enable it, select the file via 'Browse...', wait for conversion to finish, you have the result:
![image](https://user-images.githubusercontent.com/2802467/145721611-ffec4c26-5f84-4b4e-bbd5-f61fc728da0b.png)

Other files, like [Деяния_апостолов_2_часть_Якутский.docx](https://github.com/ispras/lingvodoc-react/files/7699152/_._2_._.docx), due to a different corpus table format require 'Separate by paragraphs' option, enable it, select the file via 'Browse...', wait for conversion to finish, you have the result:
![image](https://user-images.githubusercontent.com/2802467/145721754-e2fbd7bf-8328-4863-a68c-ced40e9fbfc5.png)

**Comment by nadezhday** [comment]
The results:

Files are generated - OK

BUT

I am not sure about the correctness of converted information. A lot of data is missing.

Look at the screenshots:
 
![изображение](https://user-images.githubusercontent.com/59951991/146768305-18c7ccd4-537f-4853-a50f-eb18d7fc0344.png)

Problem: the second and the 3d columns are not present in the generated file.

@myrix could you please explain what we should get? 

And what should I do with this case? Reopen? Or should I create separate defects for the found issues?

BTW: It would be nice to add the Convert button.
Now the conversion starts as soon as you add file. So user will have to set options beforehand. - NOK

**Comment by nadezhday** [comment]
covered in test_docx2eaf.py

**Comment by myrix** [comment]
> @myrix could you please explain what we should get?

We should get the .eaf file, all other files are just for quick checking and general info, they do not have to contain all columns, so working as intended.

> BTW: It would be nice to add the Convert button.
> Now the conversion starts as soon as you add file. So user will have to set options beforehand. - NOK

That is intended, first user sets options, then selects the file. This is reflected in the layout, options first, higher, file selection next, lower. If the convertion was with the wrong options, the user just changes options and converts again.

Perhaps it would be more apparent if the label was "Convert .docx file:" instead of ".docx file for convertion:"? Or do you think it's still better to have an explicit 'Convert' button? If yes, I think it's better to reopen the issue instead of creating a new one.

**Comment by nadezhday** [comment]
1)
@myrix, I suggest to implement additional button: Convert
![image](https://user-images.githubusercontent.com/59951991/146871853-4b1def6f-10bd-452a-9e20-92980a48f287.png)

2)
Then let us rename (as you suggested) '.docx file for convertion':  Select .docx file for conversion (or Browser for .docx file for conversion)

3) Maybe it would be better to have full file names in Converted successfully area?
Right now we have 'check .txt'. Why do we have extra space? What is the meaning?
If we have '.eaf file'  why we do not have 'check.txt file'?
![image](https://user-images.githubusercontent.com/59951991/146872224-4cae79ca-929e-4043-b9a8-6aaef9073c45.png)

4) Will we have a special menu command to invoke this functionality? Right now I have to modify url to get it.

If we fix all these issues then this feature will be perfect.

**Comment by myrix** [comment]
@nadezhday 
Will do 1 and 2.

Regarding 4, at the moment we do not plan on it.

Regarding 3, the links are not file names, they are file descriptions, and "check .txt" means ".txt file for checking". As we have ".eaf file" which is the main result, we have ".txt file" for checking and sometimes some other files.

Do you think it would be better for uniformity for links to look like this?
<result .eaf>
<check .txt>
<check .docx>
<alignment .docx>

The full file names would not add any additional info and would just make result file type dictinction less apparent:
<Чертыкова_Беседы_14.09.2019.eaf>
<Чертыкова_Беседы_14.09.2019 check.txt>
<Чертыкова_Беседы_14.09.2019 check.docx>
<Чертыкова_Беседы_14.09.2019 alignment.docx>

Unless you emphasize this distinction explicitly:
result .eaf: <Чертыкова_Беседы_14.09.2019.eaf>
check .txt: <Чертыкова_Беседы_14.09.2019 check.txt>
check .docx: <Чертыкова_Беседы_14.09.2019 check.docx>
alignment .docx: <Чертыкова_Беседы_14.09.2019 alignment.docx>

But compare it with first minimalistic design, doesn't the first one look better? And given that the user does not need to be shown file names to know them, as they are based on the name of the source file the user just selected (and which will be shown now in the options, as we'll add an explicit 'Convert' button), I believe that the first variant is better overall. What do you think?

**Comment by nadezhday** [comment]
@myrix  1 and 2 is enough.

**Comment by myrix** [comment]
Implemented.

**Comment by nadezhday** [comment]
Verified.

**Comment by nadezhday** [comment]
Are we going to translate this functionality into Russian? Separate enh is created https://github.com/ispras/lingvodoc-react/issues/569
