### ISSUE TITLE
Saving dictionary - Failed

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#546]
Test FAILed

chrome.test_save_dictionary.test_saving_task_zip

Steps to reproduce:
Login as Julia
Open http://83.149.198.62/dictionary/1106/7053/perspective/1106/7054/view
Save dictionary
click Save sound recordings 
Click Save only published
Close
Verify Tasks

Expected: 
(4/4) Finished
.xlsx
.zip

Actual: Saving dictionary has never finished
![image](https://user-images.githubusercontent.com/59951991/146000700-319be37c-92f4-4bd3-b5ab-0231c7585ec0.png)

Regression.

If we open screenshots we will find that task had been completed
 How long should it take to complete this task?
 
 
![image](https://user-images.githubusercontent.com/59951991/146002366-02becd65-288e-4c04-b174-bfeaea79146a.png)

**Comment by nadezhday** [comment]
For testers: find another dictionary for this test

**Comment by nadezhday** [comment]
In order to verify the generated zip we have increased wait In the test.

BUT

 tests\test_save_dictionary.py - FAIL

Steps to reproduce:

http://83.149.198.62/dictionary/1106/7053/perspective/1106/7054/view

open save dictionary dialog

1) Click Save All button

2) Save sound recordings option - ON

3) Click Save only published button

4) Close dialog and verify tasks

![image](https://user-images.githubusercontent.com/59951991/147040406-bd18b85b-121b-4112-b5fd-6d0032d589e6.png)

Wait for  zip file to be generated

![image](https://user-images.githubusercontent.com/59951991/147039508-ddc86823-3d4d-471d-adca-c58783807e4b.png)

Problem:
(4/4) Finished (ERROR), exception: Traceback (most recent call last): File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open h.request(req.get_method(), req.selector, req.data, headers, File "/usr/lib/python3.8/http/client.py", line 1256, in request self._send_request(method, url, body, headers, encode_chunked) File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output self.send(msg) File "/usr/lib/python3.8/http/client.py", line 951, in send self.connect() File "/usr/lib/python3.8/http/client.py", line 922, in connect self.sock = self._create_connection( File "/usr/lib/python3.8/socket.py", line 787, in create_connection for res in getaddrinfo(host, port, 0, SOCK_STREAM): File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags): socket.gaierror: [Errno -3] Temporary failure in name resolution During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/api/lingvodoc/scripts/save_dictionary.py", line 2788, in save_dictionary compile_workbook( File "/api/lingvodoc/scripts/save_dictionary.py", line 2642, in compile_workbook context.save_lexical_entry( File "/api/lingvodoc/scripts/save_dictionary.py", line 2419, in save_lexical_entry f(entity) File "/api/lingvodoc/scripts/save_dictionary.py", line 2322, in f self.get_etymology_info( File "/api/lingvodoc/scripts/save_dictionary.py", line 2216, in get_etymology_info [[self.get_sound_link(*args)] File "/api/lingvodoc/scripts/save_dictionary.py", line 2216, in <listcomp> [[self.get_sound_link(*args)] File "/api/lingvodoc/scripts/save_dictionary.py", line 2527, in get_sound_link with self.storage_f( File "/api/lingvodoc/views/v2/utils.py", line 614, in storage_file return urllib.request.urlopen(urllib.parse.quote(url, safe = '/:')) File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen return opener.open(url, data, timeout) File "/usr/lib/python3.8/urllib/request.py", line 525, in open response = self._open(req, data) File "/usr/lib/python3.8/urllib/request.py", line 542, in _open result = self._call_chain(self.handle_open, protocol, protocol + File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain result = func(*args) File "/usr/lib/python3.8/urllib/request.py", line 1383, in http_open return self.do_open(http.client.HTTPConnection, req) File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open raise URLError(err)

If I try to run these steps again, zip file sometimes is generated.
@myrix could you please help.  Any idea what can be wrong?
![image](https://user-images.githubusercontent.com/59951991/147042743-6d851cdc-50af-4e58-862c-d98d9d46d904.png)

**Comment by myrix** [comment]
@nadezhday 
Key info is "socket.gaierror: [Errno -3] Temporary failure in name resolution", so it is a network error, which seems sometimes appears during download of the files from the production (in this particular case --- download of the sound file), as they are not stored on the testing, so it needs to get them from the production over the net. On production they are just read from the file system.

So nothing we can do about it, unless maybe add a 2-3 retries to the code in such cases? I'll look into it.

**Comment by nadezhday** [comment]
@myrix, @ianlethic  
1) We can redesign test (2-3 retries). But these actions usually take to much time. 
2) We can use a specific user and test it directly on production. It will take less time. 
But what user can be used? 'test' does not have permissions.
![image](https://user-images.githubusercontent.com/59951991/147083448-25ab6377-b1f4-4561-8207-c9bde082cdf7.png)

**Comment by myrix** [comment]
> 1. We can redesign test (2-3 retries). But these actions usually take to much time.

I suggest to find a dictionary with a small number, as small as possible, of sound files, and test on it still on testing; smaller number of sound files will lead to smaller test times.

**Comment by nadezhday** [comment]
Done. 
Test is using Dictionary of Alexandrowo dialect of Khanty language (village Novonikol'skoe)
http://83.149.198.62/dictionary/866/5/perspective/866/6/view 

But it would be nice to use the large dictionary to detect the problems our users can face with.
