### ISSUE TITLE
Cognate tools: select/deselect all dictionaries

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#547]
Users should be able to select and deselect all dictionaries in Cognate analysis, reconstruction and suggestions tools with a single click. The same with all dictionaries of a particular language in Cognate multi-language analysis, reconstruction and suggestions tools.

**Comment by myrix** [comment]
Implemented.
![image](https://user-images.githubusercontent.com/2802467/146177437-8e71ec7a-2f5d-4459-94b7-42e382b3f266.png)
![image](https://user-images.githubusercontent.com/2802467/146177448-4297d2be-ad93-4281-b636-af204e537582.png)

**Comment by nadezhday** [comment]
Options work.

Verified

The main problem: it is difficult to notice them.

**Comment by nadezhday** [comment]
Covered in tests\test_cognate_analysis.py and tests\test_cognate_multi_reconstr.py


Separate defect is created https://github.com/ispras/lingvodoc-react/issues/568 Compute should be disabled if Select/deselect all language's dictionaries option is OFF for the second language

**Comment by nadezhday** [comment]
We can verify this case.
