### ISSUE TITLE
Compute should be unavailable (if Multiple languages required)

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#548]
Test  tests\test_cognate_multi_reconstr.py - FAILed

Steps to reproduce:

Login as admin

Open lexical view for Dictionary of ABC for Moksha language (1892)

http://83.149.198.62/dictionary/1393/19108/perspective/1393/19109/view

Open Tools - Cognate multi-language reconstruction

Result: Multiple languages required Cognate multi-language reconstruction requires dictionaries from at least 2 languages. - ОК

Add language 
Udmurt

Result: Compute  is available

Delete Udmurt

Expected: Compute should become Disabled

Actual: Compute is available - NOK

Regression.

**Comment by myrix** [comment]
Fixed.

**Comment by nadezhday** [comment]
verified.

Test - passed
