### ISSUE TITLE
Make Add new translation gist button more visible

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#550]
Make Add new translation gist button more visible

![image](https://user-images.githubusercontent.com/59951991/146512616-a9958ff9-ce44-4742-b05e-909f929a00ae.png)

**Comment by Dina936** [comment]
Made the button brighter
(поменять в компонентах везде)
<img width="735" alt="Снимок экрана 2021-12-17 в 12 13 09" src="https://user-images.githubusercontent.com/56397844/146519778-ea119465-34c3-46bd-a131-19e0551c22e8.png">
<img width="803" alt="Снимок экрана 2021-12-17 в 12 12 47" src="https://user-images.githubusercontent.com/56397844/146519789-5af6ee9b-b10b-4ad6-8425-e6a224c74769.png">

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/146876260-9f789e31-b07b-4d81-9a1a-7486a3a30011.png)

Verified
