### ISSUE TITLE
Edit interface translations: By default the first tab (Perspective) should be active.

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#551]
Login as admin
Tools > Edit interface translations

Expected: By default the first tab (Perspective) should be active.

Actual: Nothing is selected. No information.

![image](https://user-images.githubusercontent.com/59951991/146515884-39a2f469-a4b7-447d-b1cc-1439fe61b12f.png)

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Verified

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_translations.py
