### ISSUE TITLE
Possibility to delete a gist

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#553]
Login as admin
Tools > Edit interface translations
Perspective

How can I delete a gist?

![image](https://user-images.githubusercontent.com/59951991/146517179-ddc1b632-88c9-4615-ba6f-df868d496271.png)

This functionality should be implemented for all tabs.

**Comment by nataliauvarova** [comment]
Oleg said that he thinks that it is not necessary to delete a gist,
because it can break a lot of other things.
(if I want to delete something from service translations, I just change the contents of some unnecessary gist to the right one)

**Comment by nadezhday** [comment]
I am closing this case as Works as Designed.
BUT
@al-indigo I am not sure that this is a correct decision. 
If you can add a gist It should be possible to delete it (unused). 
We need a check if it is used somewhere then we cannot delete it.
