### ISSUE TITLE
Edit interface translations: Empty fields

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#554]
login as admin

Tools - Edit interface translations

Click Field

Why do we have this empty field?

And it cannot be deleted. 

![image](https://user-images.githubusercontent.com/59951991/146517782-99a96d13-9253-429d-bbbb-e0e49805b048.png)

**Comment by nataliauvarova** [comment]
You can simply change the contents of an unnecessary gist (in this case, this empty gist) to the right one.

**Comment by nadezhday** [comment]
We are always trying to find a workaround for a problem instead of fixing it.
@al-indigo what is the goal? Are we going to make LingvoDoc good?

**Comment by nadezhday** [comment]
The problem is not fixed.

Won't fix and verified without verification.
