### ISSUE TITLE
Edit interface translations: Missing information in lingvo-gist__header

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#555]
login as admin

Tools - Edit interface translations

Click Dictionary

We are missing some information. (Edit interface translations)

![image](https://user-images.githubusercontent.com/59951991/146518427-03169841-a5c6-4da6-9d57-364f5beb2865.png)

Info is present:
![image](https://user-images.githubusercontent.com/59951991/146518961-f5fcfeb6-d1a9-4a3d-9315-73d847a15b54.png)

Info is missing:
![image](https://user-images.githubusercontent.com/59951991/146519227-4fdb3443-f2f9-42f2-a9b4-e77be129ae8c.png)

**Comment by nataliauvarova** [comment]
In order for the title to appear here, you need to add an atom in English

**Comment by nadezhday** [comment]
@myrix Ivan, should this field be mandatory during dictionary creation?

It looks strange when some data is missing.

**Comment by myrix** [comment]
> @myrix Ivan, should this field be mandatory during dictionary creation?
> 
> It looks strange when some data is missing.

It probably shouldn't be mandatory; as far as I remember, it was always possible to set however many dictionary name translations, including just one, only Russian or only English, and users never raised this as an issue.

I wouldn't say that the data is missing, just that it's not set.

**Comment by nadezhday** [comment]
Will we do anything in this case? Or should we close it as Works as Designed?

**Comment by myrix** [comment]
> Will we do anything in this case? Or should we close it as Works as Designed?

Maybe if there is no English atom, set the header from a Russian atom? If there is neither English nor Russian atoms, set from the first available. Or we can just leave it as it is.

**Comment by nataliauvarova** [comment]
Done.
By default, the title is set in the language of the current locale. If such a title is missing or is equal to a void, then set the title in English. If there is no such title either, then in Russian.

**Comment by nadezhday** [comment]
Verified
