### ISSUE TITLE
Element cannot be deleted - GraphQL error: Error: no such translationatom in the system

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#556]
Login as admin
Tools > Edit interface translations
Grant

Add translation

Save

Delete it.
![image](https://user-images.githubusercontent.com/59951991/146519653-8f298f0c-a3a5-44b4-ac19-dc7bfcd6a6a8.png)

Save.

Problem: the element is not deleted. After refresh it appears again.

Uncaught (in promise) Error: GraphQL error: Error: no such translationatom in the system

Exception can be found in Console:

Uncaught (in promise) Error: GraphQL error: Error: no such translationatom in the system
    e ApolloError.js:37
    next QueryManager.js:186
    d Observable.js:126
    h Observable.js:161
    value Observable.js:215
    next index.js:37
    d Observable.js:126
    h Observable.js:161
    value Observable.js:215
    l index.js:91
    promise callback*l/</< index.js:90
    t Observable.js:179
    value Observable.js:258
    o index.js:19
    t Observable.js:179
    value Observable.js:258
    _ QueryManager.js:183
    mutate QueryManager.js:124
    mutate ApolloClient.js:98
    value EditAtoms.js:219
    value EditAtoms.js:263
    value EditAtoms.js:287
    Lodash 4
    M Button.js:103
    React 12
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
    d raven.js:393
    b raven.js:1046
    React 15
    i index.js:66
    1290 index.js:80
    Webpack 5

**Comment by jandrew44** [comment]
@nadezhday I could not reproduce the problem.
Please attach a video.

**Comment by nadezhday** [comment]
The problem is not reproduced anymore. Closing.

**Comment by nadezhday** [comment]
Covered in tests\test_tools_translations.py
