### ISSUE TITLE
Edit interface translations: The order of languages 

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#557]
Login as admin
Tools > Edit interface translations
Services

Problem: The order of languages is different.

![image](https://user-images.githubusercontent.com/59951991/146521950-920d3564-17c4-4da6-9ee2-97e635a2dbc8.png)

Should we do anything about it?

**Comment by nadezhday** [comment]
If this is very difficult to implement we can leave it as it is (Works as design)

**Comment by nataliauvarova** [comment]
Done

**Comment by nadezhday** [comment]
verified

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_translations.py
