### ISSUE TITLE
Import Starling dictionaries: Excel-exported CSV import error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#559]
Error on importing [Хантыйская базисная лексика.csv](https://github.com/ispras/lingvodoc-react/files/7734272/default.csv).

Upload the file by User menu -> My files, Browse... select file, select 'Starling' in dropdown, Upload.

Import the file by Home page -> Dashboard -> Import Starling dictionaries, select the file, clik on field 'берёз.', Keep, Next Step, set field type as 'Word', Next Step, any parent language, any name translation, Submit.

Open tasks, wait for error to appear:
![image](https://user-images.githubusercontent.com/2802467/146529230-4e5f1d2e-3362-4a12-af34-73bab8440209.png)

**Comment by myrix** [comment]
Fixed, work ok.
![image](https://user-images.githubusercontent.com/2802467/146530286-9d8529ae-73c5-4407-a104-815f2284f88e.png)

**Comment by nadezhday** [comment]
Verified.

![image](https://user-images.githubusercontent.com/59951991/146548375-33ebabb4-5efd-40ed-97d4-acce0abf18b9.png)

**Comment by nadezhday** [comment]
Covered in tests\test_import_starling_dict_01.py
