### ISSUE TITLE
Edit interface translations: Duplicated entries after deletion

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#560]
Login as admin
Tools > Edit interface translations
Services

Initial: 

![image](https://user-images.githubusercontent.com/59951991/146524149-cc985a64-b241-439b-944b-8ba7fa41ee0a.png)

Add a new translation (Finnish) and Save

![image](https://user-images.githubusercontent.com/59951991/146529672-c3c7ff48-e668-4fdb-955e-b7acc1c3bc94.png)

Delete Russian version and Save

![image](https://user-images.githubusercontent.com/59951991/146529858-b006f949-b0ac-416b-8c55-fc34d4d45d6f.png)

Refresh page

Problem:  Now we have 2 versions of Finnish  - NOK

![image](https://user-images.githubusercontent.com/59951991/146530115-f8ebabe3-39ea-4f45-9b99-710b80f7b8ed.png)

**Comment by jandrew44** [comment]
I have fixed one problem, there are no more duplicates with the same locale when performing steps for this scenario.
However, there is one problem remaining.
Currently it is impossible to delete translation atoms, I don't know why.
Mutation delete_translationatom has { triumph: true } but atom is not deleted.
@myrix please have a look.

**Comment by myrix** [comment]
Now should work ok.

It looks like all these years backend always returned all atoms, independently of whether they were deleted or not. I surmise it's an artifact of the old approach, where it was assumed that no more than 1 atom per locale would be ever created and we would not need to delete them.

Now it is possible to ask backend for only not deleted atoms.

**Comment by nadezhday** [comment]
1) Initial:
![image](https://user-images.githubusercontent.com/59951991/159473223-9711a476-a845-4c77-b134-98da29bb3168.png)

2) Add the second line
![image](https://user-images.githubusercontent.com/59951991/159473475-978030dc-8582-49d7-8942-63725703ebea.png)

Save

2) Delete it

Save
Result: line disappears OK

![image](https://user-images.githubusercontent.com/59951991/159473916-bc95b923-2a67-4b39-b172-affcae719546.png)

3) Add translation
![image](https://user-images.githubusercontent.com/59951991/159474110-8bec19a5-adf4-4dc8-b2b9-6bd39a4149fa.png)

Save

Uncaught (in promise) Error: GraphQL error: TranslationAtom with this locale already exists

Separate defect has been created:
https://github.com/ispras/lingvodoc-react/issues/658 - Uncaught (in promise) Error: GraphQL error: TranslationAtom with this locale already exists

**Comment by nadezhday** [comment]
In addition https://github.com/ispras/lingvodoc-react/issues/659 
Impossible to add a new translation: Uncaught (in promise) Error: GraphQL error: 'int' object is not subscriptable

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_translations.py
