### ISSUE TITLE
Edit interface translations: Implement search

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#562]
Login as admin
Tools > Edit interface translations
Dictionary (All)

We have so many entries on the page.  
It would be great if we implement Search functionality for this menu

**Comment by jandrew44** [comment]
Need to decide where to place search field and what will be displayed if there are no search results.

**Comment by myrix** [comment]
Implemented backend-side filtering with simple frontend-side pagination, to filter enter a filtering string and click the search icon / press "enter":
![image](https://user-images.githubusercontent.com/2802467/164406402-bc1fd002-f764-4870-846b-9df65d2b8eb7.png)
![image](https://user-images.githubusercontent.com/2802467/164406595-2ab1397d-9048-4509-8787-a1beda93b965.png)

**Comment by Dina936** [comment]
@myrix  I need to redesign search and pagination. I will transfer the task to Natalia.

**Comment by myrix** [comment]
@Dina936 If it's relevant for redesign, search now has case sensitivity setting:
![image](https://user-images.githubusercontent.com/2802467/164618301-c12d2a7e-79e0-48f2-8c6a-434e8db45fc9.png)

**Comment by Dina936** [comment]
Search design, pagination. Sort alphabetically.
https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc? идентификатор узла = 1326%3A4887

**Comment by nataliauvarova** [comment]
Done the redesign of the search, pagination. Sort alphabetically.

**Comment by nadezhday** [comment]
Separate defect is created: https://github.com/ispras/lingvodoc-react/issues/756 Translation: search does not work properly

**Comment by nadezhday** [comment]
tests\test_tools_translations.py test updated

Verified
