### ISSUE TITLE
Edit interface translation (Mobile version): The field is not expanded.

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#564]
Mobile version 
Login as admin
Tools > Edit interface translations
Grant

Click on the field to start editing

Problem: 

![image](https://user-images.githubusercontent.com/59951991/146552471-41a5c01e-a4d0-429a-a676-6cf97a67d5ed.png)

 The field is not expanded.  Cursor should be placed in the end of text.

**Comment by nadezhday** [comment]
1)  In addition we have problem to swipe the text. Should we disable horizontal swipe?

If we fix the problem from the description this problem also will be fixed.

2) Can we remove popover if we start editing.
![image](https://user-images.githubusercontent.com/59951991/146553380-cf2403dc-8eba-4a33-b94c-820d9d66fd2d.png)

**Comment by nataliauvarova** [comment]
Done

**Comment by nadezhday** [comment]
Verified
