### ISSUE TITLE
Adding localization to the Main Page

### ISSUE THREAD

**Issue by nataliauvarova** [ispras/lingvodoc-react#565]

**Comment by nataliauvarova** [comment]
Now Localization is added in the Admin Panel (http://lingvodoc.ru/edit_translations).
 As part of this task, only the frontend is being done.

**Comment by nataliauvarova** [comment]
fixed the main page template

**Comment by nadezhday** [comment]
Not verified.

http://83.149.198.62/edit_translations

![image](https://user-images.githubusercontent.com/59951991/146875803-30ebea82-c725-4094-b01e-75431ad4a51e.png)

Missing:
-Add new translation gist
-Add Translation

**Comment by nataliauvarova** [comment]
@nadezhday Added to the DB on production - you can check.

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/147087837-eb1358b3-fb8a-40cb-ac03-bc4e13c37538.png)

**Comment by nadezhday** [comment]
Separate defect https://github.com/ispras/lingvodoc-react/issues/543 - Edit interface translations - localization is needed
