### ISSUE TITLE
Main page: Russian localization is gone 

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#567]
Russian localization of the first page has disappeared.

![image](https://user-images.githubusercontent.com/59951991/146876848-56bcdcc0-f57b-43fe-8540-d3e444643baa.png)

For testers: Update test_default_page.test_lingvodoc_01

**Comment by nadezhday** [comment]
tests\test_default_page.py updated to should Eng text.

**Comment by nataliauvarova** [comment]
Russian Localization is now added through the Admin Panel. (on the page /edit_translations )

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/146887086-595e8dc9-80f7-42ea-8c19-c15c3b90dea3.png)

On official site http://lingvodoc.ispras.ru/ Only Russian version is present.

**Comment by nadezhday** [comment]
I do not know how this functionality (localization) is implemented
BUT we should have the same functionality both on http://lingvodoc.ispras.ru/
and http://83.149.198.62/

And it looks strange for me that we need to perform localization for test stand separately.

Can we automate it? Should we use the latest DB?

What should we do in this case?  

 @myrix /  @ianlethic

**Comment by myrix** [comment]
Localization is in the DB, if the DB differs, localization can differ. So if we update translations on production, we need to update the DB on testing.

**Comment by nataliauvarova** [comment]
@nadezhday  Added to the DB on production - you can check.

**Comment by nadezhday** [comment]
Production (http://lingvodoc.ispras.ru/version_route)
Backend:2.1.1+1436-92a11fdb-2021.12.17-10:25
uniparser-erzya:1.1.2
uniparser-komi-zyrian:1.1.10
uniparser-meadow-mari:1.1.7
uniparser-moksha:1.1.0
uniparser-udmurt:2.1.9
Frontend:3cb6ceeb-501-staging-server

I cannot verify localization chanпes (screenshot):

![image](https://user-images.githubusercontent.com/59951991/147051981-3af8a9dc-1e45-464d-aebf-6e5d75e15993.png)

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/147052996-4dce3603-144e-48c4-bd2f-5ce585ad7f97.png)

**Comment by nadezhday** [comment]
Waiting with verification.

**Comment by nadezhday** [comment]
Backend:2.1.1+1437-de6bb3b0-2021.12.20-13:58+modified-2021.12.22-10:09
uniparser-erzya:1.1.2
uniparser-komi-zyrian:1.1.10
uniparser-meadow-mari:1.1.7
uniparser-moksha:1.1.0
uniparser-udmurt:2.1.9
Frontend:16e8e179-505-staging-server
+ Updated DB

http://83.149.198.62/ - Verified 
![image](https://user-images.githubusercontent.com/59951991/147081458-5d2c7f42-7991-4533-92ee-3ccc6b29fc38.png)

![image](https://user-images.githubusercontent.com/59951991/147081532-23147ed9-7f66-4b76-a738-6b95ea65079d.png)

**Comment by nadezhday** [comment]
BUT we still have problem with lingvodoc.ispras.ru

![image](https://user-images.githubusercontent.com/59951991/147081872-f6c8dc52-d380-4485-9f81-e241e66d3323.png)

**Comment by nadezhday** [comment]
Verified on lingvodoc.ispras.ru
