### ISSUE TITLE
Compute should be disabled if Select/deselect all language's dictionaries option is OFF for the second language

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#568]
Login as admin

Tools > Cognate multi-language reconstruction

Result: Compute button is disabled - OK (#272)

Add additional language

Result: Compute button is enabled - OK

Set Select/deselect all language's dictionaries option OFF for the second language

Problem: Compute button is still enabled

![image](https://user-images.githubusercontent.com/59951991/146903181-98dbdb14-158b-4573-9fb6-cbe99d5dcb45.png)

http://83.149.198.62/dictionary/2654/9280/perspective/2654/9284/view

For testers: cover this scenario in tests\test_cognate_multi_reconstr.py

**Comment by myrix** [comment]
Fixed.

**Comment by nadezhday** [comment]
Works fine.

Covered in tests\test_cognate_multi_reconstr.py -  PASS
