### ISSUE TITLE
Localization of Docx -> Eaf corpus conversion feature

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#569]
https://github.com/ispras/lingvodoc-react/issues/545 Docx -> Eaf corpus conversion

We need localization.

![image](https://user-images.githubusercontent.com/59951991/147038916-f7036b14-4651-4540-8c47-c6c133bb76d7.png)

**Comment by nataliauvarova** [comment]
Done (http://lingvodoc.ru/docx2eaf)

**Comment by nadezhday** [comment]
Separate defect is created: https://github.com/ispras/lingvodoc-react/issues/769
