### ISSUE TITLE
Not translated into Russian

### ISSUE THREAD

**Issue by Dina936** [ispras/lingvodoc-react#570]
Steps:
1. Dashboard
2. Dictionarie
![IMAGE 2021-12-22 13:17:08](https://user-images.githubusercontent.com/56397844/147077358-c7c4b57c-6716-4e3d-aadf-d53647442d6d.jpg)
s

**Comment by nataliauvarova** [comment]
Fixed (changes in the repository)

**Comment by nadezhday** [comment]
Verified
![image](https://user-images.githubusercontent.com/59951991/152089463-e80eb471-cdce-4e05-b4bc-2e6c4df2be3f.png)

**Comment by vmonakhov** [comment]
Covered in selenium tests
