### ISSUE TITLE
Phonological statistical distance & phonology error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#572]
User reports failure to compute Phonological statistical distance with two dictionaries
http://lingvodoc.ispras.ru/dictionary/1230/570/perspective/1230/571/view,
http://lingvodoc.ispras.ru/dictionary/657/3/perspective/657/4/view:
<img width="640" alt="image" src="https://user-images.githubusercontent.com/2802467/147363782-c2b41088-0fbd-4c2e-94a7-17aeb7236b8d.png">

Additionally, there is no Phonology results for http://lingvodoc.ispras.ru/dictionary/1230/570/perspective/1230/571/view:
![image](https://user-images.githubusercontent.com/2802467/147364028-0210f4bd-5b83-4927-b81e-440cb0e86309.png)

**Comment by myrix** [comment]
Fixed, now statistical distance & phonology computes ok.

For statistical distance, open http://lingvodoc.ispras.ru/dictionary/1230/570/perspective/1230/571/view, Tools -> Phonological statistical distance, add "Uralic › Mansi › Eastern dialect › Dictionary of Yukonda dialect of Mansi (Published) › Lexical Entries (Published)" perspective, Create, wait for the task to complete:
![image](https://user-images.githubusercontent.com/2802467/147366217-a9a5504c-ca87-42ee-87a5-62a94b091d32.png)

Phonology from http://lingvodoc.ispras.ru/dictionary/1230/570/perspective/1230/571/view as usual:
![image](https://user-images.githubusercontent.com/2802467/147366246-0ba963ab-e725-4eda-b8f5-7c05679b53fc.png)

Note to testers: requires flushing redis cache, so probably requires test stand docker restart.

**Comment by nadezhday** [comment]
Covered in tests\test_phonological_statistic_distance_02.py
and in tests\test_phonology_02.py

**Comment by nadezhday** [comment]
Verified
