### ISSUE TITLE
Cognate acoustic analysis error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#573]
Open http://lingvodoc.ispras.ru/dictionary/657/3/perspective/657/4/view, Tools -> Cognate acoustic analysis, click 'Compute' button, task finishes with error:
![image](https://user-images.githubusercontent.com/2802467/147394034-3548e1b8-21f0-4756-a01b-430a2c114335.png)

**Comment by myrix** [comment]
Fixed, computes ok.
![image](https://user-images.githubusercontent.com/2802467/147394251-6b94f452-40da-4320-907c-e258d40f6f48.png)

**Comment by nadezhday** [comment]
Verified.
Covered in tests\test_cognate_acoustic_analysis.py
