### ISSUE TITLE
Language databases -> Dictionaries page error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#574]
Open http://lingvodoc.ispras.ru/dashboard/dictionaries_all, empty page:
![image](https://user-images.githubusercontent.com/2802467/147410129-0ee6e1e3-2252-4c60-a898-bdb6a0183176.png)

Relevant Sentry issue: https://sentry.at.ispras.ru/ispras/lingvodoc-frontend/issues/972/

**Comment by myrix** [comment]
Fixed, page works ok:
![image](https://user-images.githubusercontent.com/2802467/147410334-9c860b3e-6770-4920-9fa9-3e9db1e2558e.png)

**Comment by nadezhday** [comment]
@myrix What was the problem?
Should we do anything to avoid this problem in future?

**Comment by myrix** [comment]
> @myrix What was the problem? Should we do anything to avoid this problem in future?

The problem was some old code which was actually not doing anything; the fix removes the code, so there should be no re-occurrence of this problem in the future.

**Comment by nadezhday** [comment]
Verified (without auto test coverage).
