### ISSUE TITLE
Valency and Statistical distance localization

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#580]
Tools - Valency command should be localized

![image](https://user-images.githubusercontent.com/59951991/148942147-438ecf64-056c-4d1d-97cc-e0286fa00f0e.png)

**Comment by nadezhday** [comment]
from https://github.com/ispras/lingvodoc-react/issues/575

**Comment by myrix** [comment]
Localized, at lingvodoc.ispras.ru:
![image](https://user-images.githubusercontent.com/2802467/149065870-db73dead-6cc3-4fa3-a590-4da7f2477785.png)

**Comment by nadezhday** [comment]
![изображение](https://user-images.githubusercontent.com/59951991/150917072-3752a0ab-b612-47cc-94ab-b2834b8eb89e.png)


![изображение](https://user-images.githubusercontent.com/59951991/150917230-9f626606-1ed4-4e22-8232-d5669cbaf645.png)


@myrix.  Cognate multi-language analysis.  Is it a special one? Why it is not translated?

**Comment by nadezhday** [comment]
https://github.com/ispras/lingvodoc-react/issues/599 - separate defect for Cognate multi-language analysis

This case is verified
