### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by Dina936** [ispras/lingvodoc-react#581]
steps: Dashboard - Dictionaries - Role

![2022-01-13_14-54-56](https://user-images.githubusercontent.com/56397844/149354660-757a6522-58f5-42de-8682-b4c8b932e145.png)
<img width="1440" alt="Roles" src="https://user-images.githubusercontent.com/56397844/149354668-4b978719-ae30-4f23-a3a6-718675161916.png">
s

**Comment by nataliauvarova** [comment]
Done

**Comment by nadezhday** [comment]
Reopened.
[x] is not implemented according to design.
![image](https://user-images.githubusercontent.com/59951991/150723257-cef7636b-7f18-418a-b822-8fce8c016d9a.png)

**Comment by nadezhday** [comment]
Separate defect is created: #591 Localization of Roles dialog

**Comment by nadezhday** [comment]
Closing this issue.

Separate enhancement is created https://github.com/ispras/lingvodoc-react/issues/593 Implement [x] in all dialogs
