### ISSUE TITLE
Improve UI - organizations

### ISSUE THREAD

**Issue by Dina936** [ispras/lingvodoc-react#582]
Steps: Dashboard - Dictionaries - Organizations

https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=988%3A4782
![2](https://user-images.githubusercontent.com/56397844/149355743-e633ad81-3ac2-4fe6-9c57-5c88a67e4507.png)
<img width="1440" alt="Organizations" src="https://user-images.githubusercontent.com/56397844/149355747-c03d7da9-4215-4e61-9335-c2e9d8bf1014.png">

**Comment by nataliauvarova** [comment]
If there are no organizations in the list, put a dash (agreed with the designer)
![Снимок экрана 2022-02-10 в 13 51 23](https://user-images.githubusercontent.com/90451645/153457289-90dff5a5-b8ce-4bcd-ba91-1e89bc9f0c65.png)

**Comment by nataliauvarova** [comment]
Done (https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=988%3A4782)

**Comment by nadezhday** [comment]
http://83.149.198.62/dashboard/dictionaries

![изображение](https://user-images.githubusercontent.com/59951991/153539097-931aea45-b041-4c8d-b172-50f35e3e9a93.png)

![изображение](https://user-images.githubusercontent.com/59951991/153538987-b944e506-3560-4854-853d-aea76d0dca5b.png)


Localization is not complete for this dialog
![изображение](https://user-images.githubusercontent.com/59951991/153539450-fc416076-4e6a-4e03-9321-857eaafb3740.png)

This is an enhancement. So reopening case.

**Comment by nadezhday** [comment]
Updated tests\test_organizations.py test

**Comment by nadezhday** [comment]
Looks fine

![image](https://user-images.githubusercontent.com/59951991/153998842-c1eb628f-db7a-455a-9e1d-c08966ba669d.png)

**Comment by nadezhday** [comment]
Separate defect is created for Organization page

https://github.com/ispras/lingvodoc-react/issues/618 We need localization for Create organization dialog
