### ISSUE TITLE
Improve UI - statistics

### ISSUE THREAD

**Issue by Dina936** [ispras/lingvodoc-react#583]
Steps: Dashboard - Dictionaries - Statistics

https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=988%3A4782
![3](https://user-images.githubusercontent.com/56397844/149356046-7e65c9a4-6482-405c-bf65-fe4052406196.png)
<img width="1440" alt="Statistics" src="https://user-images.githubusercontent.com/56397844/149356055-0bfc83f8-6739-4944-9b2c-e546d723429f.png">

**Comment by nataliauvarova** [comment]
@Dina936 we also need a new design of the statistics table

**Comment by Dina936** [comment]
The table with statistics is ready
https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=988%3A4782

**Comment by nataliauvarova** [comment]
Done by design: https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=988%3A4782

**Comment by nadezhday** [comment]
http://83.149.198.62/dashboard/dictionaries

Localization is needed.
 @nataliauvarova, could you please check that all your changes in the build. 

![image](https://user-images.githubusercontent.com/59951991/164000466-7729821b-c996-480c-afd1-f9c21909279a.png)

Figma:
![image](https://user-images.githubusercontent.com/59951991/164000967-74c9d6b9-9e9b-43b6-b880-54e5ade26f62.png)

**Comment by nataliauvarova** [comment]
> could you please check that all your changes in the build.

This Localization has been added to the admin panel on production:
![Снимок экрана 2022-04-19 в 15 20 48](https://user-images.githubusercontent.com/90451645/164002581-7adf3c69-17dc-4ff9-a51b-d8f74406d78e.png)

After updating the production, you will be able to see it.

**Comment by nadezhday** [comment]
Verified http://83.149.198.62/dashboard/dictionaries

![image](https://user-images.githubusercontent.com/59951991/164173196-04c7db3c-77e9-43dd-9080-90351865660c.png)

**Comment by nadezhday** [comment]
Covered in tests\test_view_lexical_statist.py
