### ISSUE TITLE
Improve UI - save dictionary

### ISSUE THREAD

**Issue by Dina936** [ispras/lingvodoc-react#584]
https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=988%3A4782
![2022-01-13_15-41-04 1](https://user-images.githubusercontent.com/56397844/149792477-48e66336-87d1-4263-8d64-5862670dd860.png)

<img width="808" alt="Снимок экрана 2022-01-17 в 17 59 40" src="https://user-images.githubusercontent.com/56397844/149792851-fccc6905-3a58-4a76-8c89-d0a17c52b224.png">

**Comment by nataliauvarova** [comment]
Done

**Comment by nadezhday** [comment]
Separate defect is created: https://github.com/ispras/lingvodoc-react/issues/591 Localization of Roles dialog

**Comment by nadezhday** [comment]
1) We have problem with [x]
![image](https://user-images.githubusercontent.com/59951991/150724238-fd9f378f-7717-40e7-97bc-5a1c22d0d22c.png)

Separate enhancement is created #593 Implement [x] in all dialogs
2) Localization is missing
![image](https://user-images.githubusercontent.com/59951991/150724383-21d08a4b-55af-476a-a1b0-965d914f8d26.png)
Separate defect is created: https://github.com/ispras/lingvodoc-react/issues/592 Localization is missing for Save dictionary dialog

**Comment by nadezhday** [comment]
@nataliauvarova  What was implemented in this case?
I cannot see your changes.

**Comment by nadezhday** [comment]
Reloaded new DB. Nothing.
![image](https://user-images.githubusercontent.com/59951991/150734181-76db79bb-1282-41da-884f-bee0f68f7f99.png)

**Comment by nataliauvarova** [comment]
> @nataliauvarova What was implemented in this case? I cannot see your changes.

Edits have been made to the styles of various elements of this modal window

**Comment by nataliauvarova** [comment]
Fixed a problem with [x]

**Comment by nadezhday** [comment]
Verified.
