### ISSUE TITLE
Composite words parsing fixed

### ISSUE THREAD

**Issue by ankan2013** [ispras/lingvodoc-react#587]
A pull requests https://github.com/ispras/lingvodoc/pull/1338 and fix (https://github.com/ispras/lingvodoc/pull/1339) were made to allow the analysis of composite words like aaa-bbb by morphological analyzers. The idea is that both cases should work: 1) a morphological analyzer has a result for aaa-bbb 2) a morphological analyzer has not result for aaa-bbb, but it has a result for aaa or(and) bbb.
Steps to reproduce:
1) Authorize at http://lingvodoc.ispras.ru/, update the page and select "Dashboard" from below:
![Screenshot from 2022-01-19 15-43-36](https://user-images.githubusercontent.com/45983282/150281812-d26ed3bc-443a-4628-a21a-0e65ed80591e.png)
2) Press "Create a dictionary":
![Screenshot from 2022-01-19 15-43-53](https://user-images.githubusercontent.com/45983282/150282014-7afb90fa-ed7f-41a8-9c57-265986482695.png)
3) Select any language and press "Next step":
![Screenshot from 2022-01-19 15-44-16](https://user-images.githubusercontent.com/45983282/150282198-2a903094-55fb-4289-854b-b71d119a5d43.png)
4) Press "Add" button at menu "Add one or more translations" and give any name to the dictionary:
![Screenshot from 2022-01-19 15-44-36](https://user-images.githubusercontent.com/45983282/150282342-0d783087-b3d4-45c7-ae40-b080e5aae063.png)
5) Press "Next step" at the bottom of this dialog:
![Screenshot from 2022-01-19 15-44-44](https://user-images.githubusercontent.com/45983282/150282458-bd5bcac8-8710-4f85-b42d-e17b00651b7a.png)
6) Press "Add" button at menu "Add one or more perspectives" and give any name a new perspective, then press "Add new column" in the Field menu and select "Markup" in the droplist:
![Screenshot from 2022-01-19 15-45-29](https://user-images.githubusercontent.com/45983282/150282517-17e7fd6a-8914-4d1d-a123-dd579d135f0a.png)
Then press "Create" button at the bottom of the dialog.
7) Click to view the dictionary:
![Screenshot from 2022-01-20 09-06-39](https://user-images.githubusercontent.com/45983282/150283052-4f53b7f4-397d-4d50-82ff-d9d52470ea67.png)
8) Add a document:
Press "+":
![Screenshot from 2022-01-20 09-06-39](https://user-images.githubusercontent.com/45983282/150283404-c10c86be-2075-4c2b-b6dd-17e1c3b5f58f.png)
Press "Browse files":
![Screenshot from 2022-01-20 09-08-39](https://user-images.githubusercontent.com/45983282/150283433-5889ef52-96c1-44c2-b9b9-6333f0291697.png)
and select this file:
[pochelamut.docx](https://github.com/ispras/lingvodoc-react/files/7902733/pochelamut.docx)
9) Press the "Power" button below:
![Screenshot from 2022-01-20 09-09-12](https://user-images.githubusercontent.com/45983282/150283663-08af5609-3e7e-4c03-b8c9-1da701366e49.png)
select "Парсер марийского лугового языка Т. А. Архангельского" and press "Execute":
![Screenshot from 2022-01-19 15-46-12](https://user-images.githubusercontent.com/45983282/150283807-575dec98-3294-43fb-92f4-ec7b96223824.png)
10) Wait until the task is finished:
![Screenshot from 2022-01-19 15-46-21](https://user-images.githubusercontent.com/45983282/150283887-a87598cf-44ea-4cd9-8826-7a4282c61239.png)
(to get the taskbar, you should press the icon looking like a folder (it is with number 7 below at my picture)
This is the finished task:
![Screenshot from 2022-01-19 15-49-58](https://user-images.githubusercontent.com/45983282/150284040-5a9f7618-12ab-4379-a882-9f5af7f35109.png)
11) Update the page and open 
the markup by pressing the "Table" button:
![Screenshot from 2022-01-19 15-50-11](https://user-images.githubusercontent.com/45983282/150284213-5424a427-7f3f-4f8c-bb99-dd2bf0f26265.png)
12) "мастарна-влак" (a plural form in Meadow Mari language) is successfully analysed as a composite word:
![Screenshot from 2022-01-19 15-50-21](https://user-images.githubusercontent.com/45983282/150284379-e47f40a4-8b4a-4fbb-b92e-39cbc9fbfaa1.png)
13) "эр-эрдене" where the analyzer has not a variant for a composite word, but has both for "эр" and "эрдене" should be analysed like this:
![Screenshot from 2022-01-19 15-51-06](https://user-images.githubusercontent.com/45983282/150284604-43d0bcfa-affd-4bae-b715-15054bb42f85.png)

**Comment by nadezhday** [comment]
https://jenkins.zeus.intra.ispras.ru/job/test_lingvodoc_frontend/824/
Tests PASSed

**Comment by nadezhday** [comment]
Covered in tests\test_parser_pochelamut.py

**Comment by nadezhday** [comment]
Verified
