### ISSUE TITLE
Can't see notification

### ISSUE THREAD

**Issue by Dina936** [ispras/lingvodoc-react#588]
When we change the settings, a message appears that we cannot see. Is there any way to bring it to the fore?
<img width="674" alt="Снимок экрана 2022-01-20 в 13 38 48" src="https://user-images.githubusercontent.com/56397844/150323720-6f59c42b-fe6f-4224-978e-3606ad1c136c.png">

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Verified.
Error message is visible now/
