### ISSUE TITLE
Localization of Roles dialog

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#591]
https://github.com/ispras/lingvodoc-react/issues/581 Improve UI

We still do not have localization for Roles dialog.

@al-indigo FYI

**Comment by nadezhday** [comment]
In addition it would be nice to add localization for the following context commands
![image](https://user-images.githubusercontent.com/59951991/150734558-1436d8c1-ab62-401e-9e39-30c083b6ae72.png)

**Comment by nadezhday** [comment]
+Localize button title Remove user
![image](https://user-images.githubusercontent.com/59951991/150735110-6e484941-25d9-47ea-9367-9637059bb5a0.png)

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Verified.
