### ISSUE TITLE
Localization is missing for Save dictionary dialog

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#592]
https://github.com/ispras/lingvodoc-react/issues/584 - Improve UI - save dictionary

Localization is missing

![image](https://user-images.githubusercontent.com/59951991/150724480-168f056e-6960-42e7-aaae-91e0ffe18a0c.png)

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Verified
![image](https://user-images.githubusercontent.com/59951991/152088702-eabd8914-72a9-43d0-aebf-d44cd04a871f.png)
