### ISSUE TITLE
Implement [x] in all dialogs

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#593]
The left issue from https://github.com/ispras/lingvodoc-react/issues/584
The left issue from https://github.com/ispras/lingvodoc-react/issues/581

![image](https://user-images.githubusercontent.com/59951991/150726618-8a8184e2-8ef2-4daa-85a6-e8849af7c853.png)

![image](https://user-images.githubusercontent.com/59951991/150726681-3c4ccd45-8841-4b10-8f26-63abfaa88eeb.png)

We need to implement [x] as designer wants. @Dina936

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Verified

![изображение](https://user-images.githubusercontent.com/59951991/150915818-3a5ae4a9-7dad-40e1-b8ff-509bc568d5c4.png)

![изображение](https://user-images.githubusercontent.com/59951991/150915884-206ddb03-67c5-47f9-a09a-504363ec6a69.png)
