### ISSUE TITLE
Apertium Sah parser language

### ISSUE THREAD

**Issue by ankan2013** [ispras/lingvodoc-react#595]
A pull request https://github.com/ispras/lingvodoc/pull/1341 was made to add a new parser to the system.
Steps to reproduce a common use case:
Steps 1-11 from https://github.com/ispras/lingvodoc-react/issues/587, on step 8 another file should be uploaded:
[sah.odt](https://github.com/ispras/lingvodoc-react/files/7925062/sah.odt)
and on step 9 the new parser "Парсер якутского языка Apertium (моноязыковой)" should be selected:
![Screenshot from 2022-01-24 13-59-45](https://user-images.githubusercontent.com/45983282/150772836-e793a6ac-b39a-43c8-965f-a0751e45c968.png)
Expected result looks like:
![Screenshot from 2022-01-24 14-00-22](https://user-images.githubusercontent.com/45983282/150772903-0ef81797-c160-4ad5-84d5-a9817f1da293.png)

**Comment by nadezhday** [comment]
Not verified

Error occurred during parser process.
![изображение](https://user-images.githubusercontent.com/59951991/150926205-f89a2d9d-ff87-4ef1-9075-a4ba3214f06a.png)


(1/2) Parsing of file sah.odt failed: An error occured during Apertium parser process running

**Comment by nadezhday** [comment]
Parser has been installed on test env.

Works. 
![изображение](https://user-images.githubusercontent.com/59951991/150968792-e69bfdbd-17d5-41bb-a157-595e1696fe48.png)

**Comment by nadezhday** [comment]
Covered in  tests\test_parser_sah.py

**Comment by nadezhday** [comment]
verified
