### ISSUE TITLE
Menu modification and its localization 

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#600]
Menu modification and its localization:

YNormanskaya:
1. Карта языков и диалектов
Map of the languages and dialects

2. Поиск и построение карт
Search and map’s creating

3. Библиотека лингвистических карт
Library of linguistic maps

4. Карта близости языков и диалектов
Language genetic proximity map

5. Редактировать классификацию диалектов
Edit of the dialects classification

6. Редактировать переводы
Edit translations

In addition:

Import Starling dictionaries надо заменить на Import Excel and Starling dictionaries

**Comment by Dina936** [comment]
https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=481%3A3704

1) Change text
2) Move arrows down

**Comment by nataliauvarova** [comment]
Done

**Comment by nadezhday** [comment]
Verified
