### ISSUE TITLE
Wrong localization for 'Search'

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#601]
![image](https://user-images.githubusercontent.com/59951991/151109144-d6f40a69-fdc1-4513-8755-3146c8559db1.png)

'Search'

Select Rus localization

![image](https://user-images.githubusercontent.com/59951991/151109219-cf135be9-221b-4b90-9774-8e3ae6602dda.png)

Поиск и построение карт

This is incorrect translation.

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/151109828-270411cd-1f72-4216-9cc5-5bd66d70dba9.png)

**Comment by nadezhday** [comment]
This is a regression.

![image](https://user-images.githubusercontent.com/59951991/151151082-a49ffef5-b02a-443a-877d-056868f72907.png)

**Comment by nataliauvarova** [comment]
Fixed (fixed in the admin panel on production)

**Comment by nadezhday** [comment]
Verified
