### ISSUE TITLE
Impossible to use digits, ARROW RIGHT and ARROW LEFT in User defined variant dialog

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#602]
Problem is found during verification of https://github.com/ispras/lingvodoc-react/issues/596 Parser variants edition allowed

Follow the steps from #596 to open User defined variant dialog

1) Initial
![image](https://user-images.githubusercontent.com/59951991/151136279-d31f0a79-935e-4cc3-8e83-986e490214c5.png)

2) in the dialog click on 'c' of caxa and use ARROW_right
![image](https://user-images.githubusercontent.com/59951991/151136977-3f897a08-4fd5-4383-8830-2e9b75a2601c.png)

Problem: Next word becomes selected on the Text markup dialog.
If you accidentally press digit 1 or 2. Variant 'тыл' will be selected. 
This is critical problem.
![image](https://user-images.githubusercontent.com/59951991/151137467-6a721781-beda-4b63-893a-8a7a6e1c4cb1.png)

@ankan2013 
@myrix FYI

**Comment by ankan2013** [comment]
Fix: https://github.com/ispras/lingvodoc-react/pull/606

**Comment by ankan2013** [comment]
An error detected in previous fix, new fix: https://github.com/ispras/lingvodoc-react/pull/608

**Comment by nadezhday** [comment]
Verified

**Comment by vmonakhov** [comment]
Covered in tests/test_parser_kaz.py
