### ISSUE TITLE
Localization Cognate commands (disabled, perspective is not published)

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#605]
http://83.149.198.62/dictionary/4467/4/perspective/4467/7/edit
![image](https://user-images.githubusercontent.com/59951991/151291891-e5588486-d63c-4140-9d0c-f8e79272aa3a.png)

Cognate suggestions (disabled, perspective is not published)
Cognate multi-language suggestions (disabled, perspective is not published)

**Comment by nataliauvarova** [comment]
Done.

Added:

1) Cognate suggestions (disabled, perspective is not published)
Поиск когнатов в разных диалектах (отключено, нет прав)

2) Cognate multi-language suggestions (disabled, perspective is not published)
Поиск когнатов в разных языках (отключено, нет прав)

**Comment by nadezhday** [comment]
Login as admin
http://lingvodoc.ispras.ru/dictionary/3787/16/perspective/3787/19/view
![image](https://user-images.githubusercontent.com/59951991/154626440-2252d55c-f724-45bb-971b-e14820f3a1bb.png)
