### ISSUE TITLE
Apertium Bashkir language parsers

### ISSUE THREAD

**Issue by ankan2013** [ispras/lingvodoc-react#609]
A pull request [ispras/lingvodoc#1341](https://github.com/ispras/lingvodoc/pull/1343) was made to add two parsers for Bashkir language to the system.
Steps to reproduce a common use case:
Steps 1-11 from #587, on step 8 another file should be uploaded:
[bak.odt](https://github.com/ispras/lingvodoc-react/files/7967874/bak.odt)

and on step 9 the new parser "Парсер башкирского языка Apertium (моноязыковой)" should be selected.

The expected result looks like:
![image](https://user-images.githubusercontent.com/45983282/151735509-3cf9ccb1-afe7-4631-a789-49b2ca8e09aa.png)

Repeat from the step 9 with "Парсер башкирского языка Apertium (c переводом на татарский)"

The expected result looks like:
![image](https://user-images.githubusercontent.com/45983282/151735628-c3828e61-fff1-481e-bb07-d67321aa1302.png)

**Comment by nadezhday** [comment]
It does not work.

![image](https://user-images.githubusercontent.com/59951991/152292867-1e28c074-9ec5-4d02-95e9-778b81419859.png)


Reopen.

**Comment by nadezhday** [comment]
For tester: cover tests\test_parser_bashkir.py

**Comment by nadezhday** [comment]
@myrix thanks for installing missing files on our test env.
@ankan2013 FYI
It would be nice to perform such steps every time we implement any functionality for parsers.

**Comment by nadezhday** [comment]
Verified

**Comment by vmonakhov** [comment]
Covered in tests/test_parser_bash1.py and tests/test_parser_bash2.py
