### ISSUE TITLE
Save markup dilaog: "GraphQL error: local variable 'perspective_id' referenced before assignment"

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#611]
Follow the steps from https://github.com/ispras/lingvodoc-react/issues/595

In the opened Text markup dialog  select Саха
Edit values
Click Save in User defined dialog
Click Save in Text markup dialog
![image](https://user-images.githubusercontent.com/59951991/152094038-3a06d9e9-0ace-4538-a4a4-75d1e43980eb.png)

Error: GraphQL error: local variable 'perspective_id' referenced before assignment

![image](https://user-images.githubusercontent.com/59951991/152094069-159a5e95-3cd6-498e-b696-58a2dc09c119.png)

**Comment by nadezhday** [comment]
Covered in tests\test_parser_sah.py
For testers: Remove SkipTest as soon as this case is fixed.

**Comment by ankan2013** [comment]
Fixed

**Comment by nadezhday** [comment]
Verified.
Covered intests\test_parser_sah.py - PASS
