### ISSUE TITLE
Distance map: localization 

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#616]
Select Russian

Open http://lingvodoc.ispras.ru/distance_map/selected_languages

Localization is needed for buttons

No data found for analysis, please select another dictionary

![image](https://user-images.githubusercontent.com/59951991/153997700-f0491157-cf6b-4315-8cfb-53ea1a03e241.png)

Click Next

![image](https://user-images.githubusercontent.com/59951991/153997774-549a55be-5528-4296-b191-08878f3ab40a.png)

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/154201769-5b482011-1d57-4853-b3fc-2cbe71120379.png)

![image](https://user-images.githubusercontent.com/59951991/154201832-eb3b8e21-60ab-462a-a18a-22370876a1ff.png)


Verified
