### ISSUE TITLE
Localization for Organizations page 

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#617]
Login as admin

![image](https://user-images.githubusercontent.com/59951991/153999490-c3d12690-7fb6-4199-ad94-7e2931ad0d32.png)

![image](https://user-images.githubusercontent.com/59951991/153999524-cf195c50-6ba2-457d-9f9c-f8717a3c3787.png)

We need to complete localize  

![image](https://user-images.githubusercontent.com/59951991/153999452-60e92823-1327-416b-8a65-ba2986e76fc5.png)

**Comment by nataliauvarova** [comment]
Done

**Comment by nadezhday** [comment]
Verified
![image](https://user-images.githubusercontent.com/59951991/156872846-7324995d-a556-4878-95b2-28fef696d6f4.png)
