### ISSUE TITLE
'Create organization' dialog and its localization

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#618]
Login as admin

![image](https://user-images.githubusercontent.com/59951991/153999920-1b4ab17c-1f37-495c-b7cb-791e1208d9b4.png)

We need localization for Create organization dialog

@Dina do we need to do anything for this dialog or just localization
Click Create organization...

![image](https://user-images.githubusercontent.com/59951991/153999681-8bf54c16-e1bd-47da-a9a9-bc7fd4de0e9d.png)

**Comment by Dina936** [comment]
ok

**Comment by Dina936** [comment]
Ready https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=1927%3A7720

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/156768533-891d34f0-ca10-480e-a6d5-366ef5118444.png)

Add buttons are missing in Russian version

**Comment by nadezhday** [comment]
Add organization dialog:
https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=1927%3A7720

Do not forget to localize it.

**Comment by nataliauvarova** [comment]
Done according to the design.

**Comment by nadezhday** [comment]
Verified on http://83.149.198.62/organizations
OK.
![image](https://user-images.githubusercontent.com/59951991/158366636-c0e1356c-1570-4066-af71-a21c6a76bf44.png)

'Add translation' localization can be tested later/

**Comment by nadezhday** [comment]
Covered in tests\test_organization_admins.py
