### ISSUE TITLE
Reparsing feature fixed

### ISSUE THREAD

**Issue by ankan2013** [ispras/lingvodoc-react#620]
https://github.com/ispras/lingvodoc/pull/1345 -
A bug about re-parsing of a parser's markup was fixed when some of 'green' words had become broken.
Steps to reproduce a re-parsing:

1) Open http://83.149.198.62/dictionary/4351/15/perspective/4351/18/edit
2) Press 'Table' icon to open markup
![Screenshot from 2022-02-17 01-55-55](https://user-images.githubusercontent.com/45983282/154371555-8c5e311b-bba5-4761-9c5c-6358cadd580e.png)
3) Select some 'red' words by clicking on them and remove them from markup bu klicking orange button 'Remove from markup'
![Screenshot from 2022-02-17 01-58-10](https://user-images.githubusercontent.com/45983282/154372788-29e277f6-f8d1-4cb7-adfe-9da82ec60c26.png)
![Screenshot from 2022-02-17 01-58-56](https://user-images.githubusercontent.com/45983282/154372808-c2a0a8eb-a737-46be-8791-6cf0525ac8a6.png)
4) Press 'Save' and then 'Close'
![Screenshot from 2022-02-17 01-59-04](https://user-images.githubusercontent.com/45983282/154372921-0358578d-ae8b-4bd8-9fce-a684360d6c9c.png)
5) Press 'Update' icon to re-execute parser
![Screenshot from 2022-02-17 01-59-25](https://user-images.githubusercontent.com/45983282/154373029-f7ba9fe5-237b-49ac-8f3d-30a8ddea8b00.png)
6) Wait for task bar completed on the right side of the page  
![Screenshot from 2022-02-17 01-59-42](https://user-images.githubusercontent.com/45983282/154373362-0260b96d-c1a9-4560-8b06-6ae24749d283.png)
7) Reload page
8) Open markup again as on step 2
'Red' words appeared again and 'green' words stayed untouched with all their variants 
![Screenshot from 2022-02-17 02-00-39](https://user-images.githubusercontent.com/45983282/154373592-09cfbb41-a5ca-44d0-895e-2531275aac08.png)

**Comment by nadezhday** [comment]
Screenshot that show the problem from the user^
![image](https://user-images.githubusercontent.com/59951991/154419127-97cc7b78-7ccf-4148-83e5-637a6b92579b.png)




Open http://83.149.198.62/dictionary/3428/6/perspective/3428/9/edit
Click table icon for 
 Торопов Олӧм...
![image](https://user-images.githubusercontent.com/59951991/154417722-6ce2e7e6-4945-4f37-ad3b-f6f75c1009a9.png)

The problem:
![image](https://user-images.githubusercontent.com/59951991/154417826-42b3de88-c76c-4d5e-8fae-50a2dbb1b715.png)

After Reparsing 
100%
(2/2) Reparsing of file Торопов Олӧм вӧсна мунiс тыш.odt finished

![image](https://user-images.githubusercontent.com/59951991/154417997-d5d9ef6d-1fc4-443f-a7f4-0bfb8f169771.png)



Куратова Вӧр...
![image](https://user-images.githubusercontent.com/59951991/154418154-d990072d-555c-4a68-81c5-7b77b9168718.png)

100%
(2/2) Reparsing of file Куратова Вӧр гормӧг.odt finished

@ankan2013, From the user's screenshot we cannot see  data-type="trSpan" data-value
Is this a regression? Can we fix it?
@myrix FYI 
![image](https://user-images.githubusercontent.com/59951991/154418526-e731ccbe-7cb3-409b-a9f1-33160586f387.png)

Да-в-а-й" data-type="trSpan" data-value="Да-в-а-й">Да-в-а-й! 

 Тю, лешак, мыйсӧбара-й " data-type="trSpan" data-value=" бара-й "> бара-й он вӧтав! 

 Ок-ок-ок! " data-type="trSpan" data-value="Ок-ок-ок! ">Ок-ок-ок! Унаысь жӧ эськӧ шуліс

**Comment by nadezhday** [comment]
Here is the initial text :
![image](https://user-images.githubusercontent.com/59951991/154419923-aff0fb68-1e00-4381-ab53-11b40eaad76a.png)

**Comment by nadezhday** [comment]
The problem with data-type="trSpan" data-value="Ок-ок-ок! "> is fixed by @ankan2013

Verified.

**Comment by nadezhday** [comment]
Covered in tests\test_parser_reparsing.py
