### ISSUE TITLE
Markup: problem with buttons layout

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#621]
Login as admin 
Open

http://83.149.198.62/dictionary/3428/6/perspective/3428/9/edit

We have problem with buttons layout. If needed resize window.

![image](https://user-images.githubusercontent.com/59951991/154416171-a875b481-29ca-4e2d-839d-3fd23a60010a.png)

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Looks fine.
![image](https://user-images.githubusercontent.com/59951991/159876950-9ab823a2-ab56-459f-bddd-46f9535676a7.png)

**Comment by vmonakhov** [comment]
Covered in tests/test_db_corpora_all.py
