### ISSUE TITLE
Reparsing entity: text gets out of the task 

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#622]
Steps can be taken from https://github.com/ispras/lingvodoc-react/issues/620

![image](https://user-images.githubusercontent.com/59951991/154618464-f37ce236-9251-4425-808a-2d9873203f32.png)

Problem 
Reparsing entity: text gets out of the task 

Can we fix the message in tasks?

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/159877665-c89ed2a9-4908-485b-972d-772afddd52d1.png)

Verified
