### ISSUE TITLE
Add Mikhail Oslon, Pavel Grashchenkov to authors

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#625]
Subj.

**Comment by myrix** [comment]
Implemented.

**Comment by nadezhday** [comment]
Verified

![image](https://user-images.githubusercontent.com/59951991/155465882-ad81c0b9-06f7-45b7-a707-63132498e740.png)

**Comment by nadezhday** [comment]
Do not forget: That we have a lot of problems with Mikhail Oslon library.
