### ISSUE TITLE
English version of the 'Lingvodoc creators' page

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#626]
We should have an English version of the 'Lingvodoc creators' page http://lingvodoc.ispras.ru/authors_route.

**Comment by nadezhday** [comment]
Lingvodoc creators page localization  - 
https://github.com/ispras/lingvodoc-react/issues/628

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/155463282-bcb4c597-20bd-49b6-93a6-11d1ba7fd1f7.png)

**Comment by nadezhday** [comment]
Waiting with verification.
![image](https://user-images.githubusercontent.com/59951991/155463849-0695a160-dc97-4a9d-9400-41cc7df149fc.png)

**Comment by nataliauvarova** [comment]
Done

**Comment by nadezhday** [comment]
Verified.
Tests should be updated.

**Comment by vmonakhov** [comment]
Covered in tests/test_localization.py
