### ISSUE TITLE
Docx -> Eaf: no header, no parsing options

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#632]
We need a no header, no parsing options for Docx -> Eaf converter to convert files like
[Сказки_Рамстетд Г.Й..docx](https://github.com/ispras/lingvodoc-react/files/8164747/_.docx).

**Comment by myrix** [comment]
Implemented.

Open http://lingvodoc.ispras.ru/docx2eaf, check 'All tables', 'No header' and 'No parsing' flags, select the file, converts successfully.

**Comment by nadezhday** [comment]
However, Converted successfully.

Click txt link

Error message is reported: 
Could not get tasks

![image](https://user-images.githubusercontent.com/59951991/156869908-00a63174-13ba-40ee-be55-979ff6be5787.png)


![image](https://user-images.githubusercontent.com/59951991/156869850-01fc310c-4549-45c0-8330-6ad9c6a24668.png)
Separate defect is created: https://github.com/ispras/lingvodoc-react/issues/636 Docx->eaf: clicking the converted file Error 'could not get tasks' appears

**Comment by nadezhday** [comment]
Files are generated. Case is verified. Covered in tests\test_docx2eaf.py
