### ISSUE TITLE
Valency Corpus of Udmurt texts: Failed with Exception

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#635]
Test failed
tests\test_valency.py

Steps to reproduce:
Login as Julia
Open http://83.149.198.62/dictionary/3648/5/perspective/3648/8/view
Tools - >valency
Problem: 
(1/1) ERROR, exception: Traceback (most recent call last): File "/api/lingvodoc/schema/query.py", line 9505, in async_valency_compute Valency.compute( File "/api/lingvodoc/schema/query.py", line 9761, in compute json.dumps( File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps return cls( File "/usr/lib/python3.8/json/encoder.py", line 201, in encode chunks = list(chunks) File "/usr/lib/python3.8/json/encoder.py", line 429, in _iterencode yield from _iterencode_list(o, _current_indent_level) File "/usr/lib/python3.8/json/encoder.py", line 325, in _iterencode_list yield from chunks File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict yield from chunks File "/usr/lib/python3.8/json/encoder.py", line 438, in _iterencode o = _default(o) File "/usr/lib/python3.8/json/encoder.py", line 179, in default raise TypeError(f'Object of type {o.__class__.__name__} ' TypeError: Object of type bytes is not JSON serializable

Exception
![image](https://user-images.githubusercontent.com/59951991/156764548-93752fb0-52e6-44d6-bddd-983dc02a4fbb.png)

**Comment by nadezhday** [comment]
@ianlethic FYI

**Comment by myrix** [comment]
Fixed, now finishes ok.

**Comment by nadezhday** [comment]
Test PASSed.
