### ISSUE TITLE
Regression: css is changed for text (impossible to see it)

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#641]
Open http://83.149.198.62/dictionary/719/5/perspective/719/6/view
It looks like that css is changed for these elements:
![image](https://user-images.githubusercontent.com/59951991/158310160-dcebe922-6fb3-4042-a25d-8cd6ba179536.png)

Regression

@jandrew44 FYI

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Verified

![image](https://user-images.githubusercontent.com/59951991/158365047-ea909ec7-957d-4f1b-ab1c-ff8ae33d90e3.png)
