### ISSUE TITLE
Uploaded file is not availble in Import Excel and Starling dictionaries

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#645]
Test tests\test_import_starling_dict_01.py - FAILed
Steps to reproduce the problem:
Login as Julia

My files

Upload Starling
[Хантыйская базисная лексика.csv](https://github.com/ispras/lingvodoc-react/files/8260171/default.csv)

Click Lingvodoc 3.0

 Dashboard - > Import Excel and Starling dictionaries
![изображение](https://user-images.githubusercontent.com/59951991/158547967-860183f0-bd83-4ede-a9bc-0f64fd9d7636.png)

Click dropdown icon

Expected: Uploaded file should be available
Actual: No results found. Regression.

Workaround: Additionally click f5 to see the list of file.

**Comment by jandrew44** [comment]
Fixed.

**Comment by nadezhday** [comment]
test PASSed  - OK
