### ISSUE TITLE
F5 is needed to see the created corpus (Exception) - empty screen

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#647]
Problem: tests\test_dashboard_create_corpus.py - FAILed (After fixed #351 several steps have been just uncommented in the test.)
Probably this is a regression.

Steps to reproduce:  
Follow steps from #351 (it is important to fill all fields)

Problem: After clicking Create we will get a white empty screen.
![изображение](https://user-images.githubusercontent.com/59951991/158575059-2d0deb7d-ad84-4ea4-8035-8b35e993eb21.png)

Workaround: F5 is needed.
Exception:
TypeError: this.createdDictionary is undefined
    value index.js:178
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    unlisten Router.js:70
    n createTransitionManager.js:54
    notifyListeners createTransitionManager.js:73
    notifyListeners createTransitionManager.js:72
    k createBrowserHistory.js:95
    A createBrowserHistory.js:120
    n createTransitionManager.js:44
    A createBrowserHistory.js:118
    M createBrowserHistory.js:102
    d raven.js:393
raven.js:55:31
    2]</d/a[b raven.js:55
    React 5
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    unlisten Router.js:70
    n createTransitionManager.js:54
    notifyListeners createTransitionManager.js:73
    notifyListeners createTransitionManager.js:72
    k createBrowserHistory.js:95
    A createBrowserHistory.js:120
    n createTransitionManager.js:44
    A createBrowserHistory.js:118
    M createBrowserHistory.js:102
    d raven.js:393

**Comment by jandrew44** [comment]
@nadezhday I could not reproduce the problem.
Please attach a video.

**Comment by nadezhday** [comment]
tests\test_dashboard_create_corpus.py Test - PASSed both on Firefox and Chrome

Closing as fixed indirectly.

**Comment by nadezhday** [comment]
verified
