### ISSUE TITLE
More permissive .eaf corpus validation

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#649]
Create a new corpus via Dashboard -> Create corpus with standard corpus structure, open created corpus, add lexical entry, unzip and upload markup file [избранные_слова_из_Писания_Господа_ЮН_2.eaf.zip](https://github.com/ispras/lingvodoc-react/files/8296089/_._._._._._2.eaf.zip) into Markup column, open markup viewer by clilcking on the 'window' icon, there is no 'Convert to dictionary...' button, .eaf corpus file is not considered a valid Lingvodoc .eaf corpus:
![image](https://user-images.githubusercontent.com/2802467/158916987-9420f38e-ac12-491e-a340-843bd19f8308.png)

It should be.

**Comment by myrix** [comment]
Implemented, now it validates ok:
![image](https://user-images.githubusercontent.com/2802467/158917478-b5e306b6-41a6-4568-bd5d-c9303511e78a.png)

**Comment by nadezhday** [comment]
Looks OK.
![image](https://user-images.githubusercontent.com/59951991/159853174-a598e957-8534-4bc9-bb50-c9551644a3e2.png)


More testing - OK
![image](https://user-images.githubusercontent.com/59951991/159853263-46bff0db-4796-45b2-a9da-aa7807262c33.png)

Verified

**Comment by nadezhday** [comment]
Covered in tests\test_eaf_corpus_conversion.py
