### ISSUE TITLE
Valency data annotation

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#650]
Users should be able to accept or reject valency annotations produced by Pavel Grashchenkov's algorithms.

**Comment by myrix** [comment]
Implemented.

Go to /valency relative URL path, choose perspective; as usual the choice can be filtered by a partial name:
![image](https://user-images.githubusercontent.com/2802467/159177099-6228ada6-aafc-4f8d-b094-64b437218dad.png)

If the perspective doesn't have annotation data, generate the data by clicking on the 'Create valency data' button:
![image](https://user-images.githubusercontent.com/2802467/159178947-c23f1616-ea64-46b0-91b9-a174f541d52b.png)

After generation is complete, the annotation data will be shown:
![image](https://user-images.githubusercontent.com/2802467/159179450-ca5cbc43-6489-419d-b903-9b68564cac95.png)

If the chosen perspective already has annotation data, it will be shown upon perspective's selection.

In each proposed annotation, the verb is highlighted with bluish color, and the dependent word is highlighted with greenish color and has its grammatical case displayed next to it.

If you hover the mouse pointer over any word, its parser data would be displayed:
![image](https://user-images.githubusercontent.com/2802467/159179676-11417da1-bcb2-4e73-b3ad-e8262bf4f2e8.png)

To accept proposed annotation as valid, click 'Accept' button:
![image](https://user-images.githubusercontent.com/2802467/159179738-dfe38aad-5feb-4be8-a7b0-96fbce390dd6.png)
![image](https://user-images.githubusercontent.com/2802467/159179766-e4256888-f789-4727-b0c7-a159d058b8b7.png)

Acceptances from different users are tracked separately and are displayed together, e.g. after logging in as Administrator and accepting the first annotation:
![image](https://user-images.githubusercontent.com/2802467/159179871-e1dd1663-7c65-45fd-b942-c533bd8a40b9.png)

Annotations can be selected/deselected via checkboxes, and at the bottom of the page there is an 'Accept all selected' button, which will accept all selected and not yet accepted annotations:
![image](https://user-images.githubusercontent.com/2802467/159180096-953b0aa1-eec8-4c87-9748-d309863fd5f5.png)

You can navigate through proposed annotations via pagination interface.

Proposed annotations can be sorted by verb and/or by case:
![image](https://user-images.githubusercontent.com/2802467/159181179-30af9917-45b7-4e5b-b663-116c86e5aafd.png)
![image](https://user-images.githubusercontent.com/2802467/159181218-9fb71390-3d0d-4d29-aaca-b2446586da7e.png)
![image](https://user-images.githubusercontent.com/2802467/159181262-c05d97a1-6d00-44a7-a655-16a14a08530d.png)

When annotations are sorted by verbs, it is possible to filter them by verb prefixes.

Verb prefix to be filtered on can be set by clicking on any of the displayed verbs or single-letter prefixes or can be typed in in the input field:
![image](https://user-images.githubusercontent.com/2802467/159183349-8aaa6a23-2874-4ff1-8d51-83740a6711d1.png)

When a prefix is set, single-letter prefixes are updated and verbs filtered by the prefix are displayed:
![image](https://user-images.githubusercontent.com/2802467/159183656-4c9bb550-6183-4d5b-9a55-dad84b38a69a.png)
Current prefix can be cleared by clicking on the cross icon in the input field.

To filter annotation data according to the verb prefix, click 'Apply filter' button:
![image](https://user-images.githubusercontent.com/2802467/159183834-965b22b9-a7da-4030-8c5e-6231f219b4d0.png)

**Comment by nadezhday** [comment]
Covered in tests\test_tools_valency_01.py

**Comment by nadezhday** [comment]
+Covered in tests\test_tools_valency_03.py
