### ISSUE TITLE
More permissive .eaf corpus convertion

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#651]
When converting [избранные_слова_из_Писания_Господа_ЮН_2.eaf.zip](https://github.com/ispras/lingvodoc-react/files/8296089/_._._._._._2.eaf.zip) .eaf corpus file into a dictionary (to convert, see #649 how to upload and view the file, then click 'Convert to dictionary...' button and proceed), we have missing transcriptions:
![image](https://user-images.githubusercontent.com/2802467/159105832-ac6912bc-bb50-4e3e-90ca-ded4601d694f.png)

The problem is a variant tier structure, with transcription sub-tier having type 'Included In' instead of 'Symbolic Association'.

If possible, we should be able to convert such files properly regardless.

**Comment by myrix** [comment]
Implemented, now converts with transcriptions:
![image](https://user-images.githubusercontent.com/2802467/159106058-cfa250f2-1c64-4921-9365-6aef0f1de482.png)

**Comment by nadezhday** [comment]
Works fine
![image](https://user-images.githubusercontent.com/59951991/161917688-dd1a865d-7b3f-4678-9a38-68f2fefbe0db.png)

**Comment by nadezhday** [comment]
Covered in tests\test_eaf_corpus_conversion.py
