### ISSUE TITLE
Valency annotation: choose default selection state

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#654]
Users should be able to choose default selection state, selected or not selected, of proposed annotations; users request initial default selection state to be not selected.

**Comment by myrix** [comment]
Implemented:
![image](https://user-images.githubusercontent.com/2802467/159384078-dd2c92d5-f430-42db-becc-963931ff15c6.png)
![image](https://user-images.githubusercontent.com/2802467/159384082-dc95216a-4c1d-40c6-b4fb-1b47a0a9d129.png)

**Comment by nadezhday** [comment]
This option is created. We can verify this case.

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_valency_06.py
