### ISSUE TITLE
Valency annotation: more convenient pagination

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#655]
Users request more convenient pagination to more easily navigate to any page.

**Comment by myrix** [comment]
Implemented.

Now user can go forward/backward by two pages instead of one, can go to an arbitrary page via a page number and can select number items displayed per page:
![image](https://user-images.githubusercontent.com/2802467/159400450-f14fc781-f620-490b-ad75-c09a98b71b7c.png)

**Comment by nadezhday** [comment]
The separate defects:
https://github.com/ispras/lingvodoc-react/issues/675 Valency: We have problem with pagination on the bottom of the page
https://github.com/ispras/lingvodoc-react/issues/676 Valency: use ENTER to navigate to any page

**Comment by nadezhday** [comment]
We can verify this case

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_valency_06.py
