### ISSUE TITLE
Add new card

### ISSUE THREAD

**Issue by Dina936** [ispras/lingvodoc-react#656]
<img width="1440" alt="eng - администратор" src="https://user-images.githubusercontent.com/56397844/159447815-02a2d561-a19b-4ccc-8373-f7fb36ecc2d6.png">

go to this page http://lingvodoc.ispras.ru/valency

**Comment by Dina936** [comment]
link to layout
https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=481%3A3704

**Comment by nataliauvarova** [comment]
Done, except localization: "Verb valency", because of this error: https://github.com/ispras/lingvodoc-react/issues/659

**Comment by nataliauvarova** [comment]
added localization

**Comment by nadezhday** [comment]
1) card added - OK
2) Localization - OK

**Comment by nadezhday** [comment]
Covered in  tests\test_tools_valency_02.py, tests\test_tools_valency_01.py
