### ISSUE TITLE
Uncaught (in promise) Error: GraphQL error: TranslationAtom with this locale already exists

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#658]
The problem found during https://github.com/ispras/lingvodoc-react/issues/560 verification 
1) Initial:
![image](https://user-images.githubusercontent.com/59951991/159473223-9711a476-a845-4c77-b134-98da29bb3168.png)

2) Add the second line
![image](https://user-images.githubusercontent.com/59951991/159473475-978030dc-8582-49d7-8942-63725703ebea.png)

Save

2) Delete it

Save
Result: line disappears OK

![image](https://user-images.githubusercontent.com/59951991/159473916-bc95b923-2a67-4b39-b172-affcae719546.png)

3) Add translation
![image](https://user-images.githubusercontent.com/59951991/159474110-8bec19a5-adf4-4dc8-b2b9-6bd39a4149fa.png)

Save

Uncaught (in promise) Error: GraphQL error: TranslationAtom with this locale already exists
    e ApolloError.js:37
    next QueryManager.js:186
    d Observable.js:126
    h Observable.js:161
    value Observable.js:215
    next index.js:37
    d Observable.js:126
    h Observable.js:161
    value Observable.js:215
    l index.js:91
    promise callback*l/</< index.js:90
    t Observable.js:179
    value Observable.js:258
    a index.js:19
    t Observable.js:179
    value Observable.js:258
    _ QueryManager.js:183
    mutate QueryManager.js:124
    mutate ApolloClient.js:98
    value EditAtoms.js:219
    value EditAtoms.js:256
    value EditAtoms.js:277
    Lodash 4
    handleClick Button.js:85
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    d raven.js:393
    b raven.js:1046
    React 8
    a index.js:66
    1235 index.js:80
    Webpack 5

Press F5
![image](https://user-images.githubusercontent.com/59951991/159474856-741c6daa-ec78-4713-8b6d-1f7488f33a08.png)

Problem: a translation cannot be added/edited if it was once deleted 

@jandrew44 FYI

**Comment by myrix** [comment]
Fixed.

**Comment by nadezhday** [comment]
Verified

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_translations.py
