### ISSUE TITLE
Impossible to add a new translation:  Uncaught (in promise) Error: GraphQL error: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#659]
http://83.149.198.62/edit_translations
Click Add new translation gist
Enter text and click Save
![image](https://user-images.githubusercontent.com/59951991/159475851-90ab7483-7f80-4286-b1b3-c0d1b354dbfc.png)

Uncaught (in promise) Error: GraphQL error: 'int' object is not subscriptable

Problem: 
Uncaught (in promise) Error: GraphQL error: 'int' object is not subscriptable
    e ApolloError.js:37
    next QueryManager.js:186
    d Observable.js:126
    h Observable.js:161
    value Observable.js:215
    next index.js:37
    d Observable.js:126
    h Observable.js:161
    value Observable.js:215
    l index.js:91
    promise callback*l/</< index.js:90
    t Observable.js:179
    value Observable.js:258
    a index.js:19
    t Observable.js:179
    value Observable.js:258
    _ QueryManager.js:183
    mutate QueryManager.js:124
    mutate ApolloClient.js:98
    value EditAtoms.js:219
    value EditAtoms.js:256
    value EditAtoms.js:273
    promise callback*value EditAtoms.js:267
    Lodash 4
    handleClick Button.js:85
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    d raven.js:393
    b raven.js:1046
    React 8
    a index.js:66
    1235 index.js:80
    Webpack 5

**Comment by nadezhday** [comment]
Probably regression introduced in https://github.com/ispras/lingvodoc-react/issues/560

**Comment by jandrew44** [comment]
Error is produced by the "updateAtom" mutation.
@myrix please have a look.

**Comment by myrix** [comment]
Fixed.

**Comment by nadezhday** [comment]
Verified

New Element can be added.

**Comment by nadezhday** [comment]
Covered in tests\test_tools_translations.py
