### ISSUE TITLE
Improve Build+ Run test functionality

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#660]
Very often we have a problem with starting tests for Lingvodoc.
https://jenkins.zeus.intra.ispras.ru/job/test_lingvodoc_frontend/1009/console

00:56:29.743 ++ basename https://github.com/ispras/lingvodoc-react/releases/download/untagged-e26deeac79e18f69f41b/lingvodoc-react-server-build-584-staging.tar.gz
00:56:29.744 + build=lingvodoc-react-server-build-584-staging.tar.gz
00:56:29.745 ++ cat /home/centos/jenkins/static/frontend_latest_build.txt
00:56:29.746 + [[ lingvodoc-react-server-build-584-staging.tar.gz == lingvodoc-react-server-build-584-staging.tar.gz ]]
00:56:29.746 + let wait_time=wait_time-1
00:56:29.747 + echo 'build not found yet, will run tests on previous build within 64 minutes'
00:56:29.747 build not found yet, will run tests on previous build within 64 minutes
00:56:29.747 + sleep 60

Can we do anything to make it more stable?

**Comment by academic-sakharov** [comment]
That's weird, but variables in jenkins shell script are keeping old values, even though they should get new values from the github API. Solved by restarting whole jenkins runner session (not only a job) for lingvodoc test machine. Now works fine, but I'll keep an eye on it at least today and close it later.

**Comment by academic-sakharov** [comment]
Now it should be fixed. I've changed API request to get only the latest build.

**Comment by nadezhday** [comment]
It looks like that the problem is fixed.
