### ISSUE TITLE
Impossible to delete file

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#662]
Login as admin

Upload file

Remove file. Click OK in Confirmation dialog

![image](https://user-images.githubusercontent.com/59951991/159673243-e7893b8c-6323-404e-9a5f-5b0ca1944064.png)

![image](https://user-images.githubusercontent.com/59951991/159673332-fbaca711-ae66-41e8-b674-2dde47c7e43d.png)

Problem: File is not removed.
This is a rgression.
GraphQL error: File can not be deleted physically; deleting from DMBS only.

@jandrew44 FYI

**Comment by nadezhday** [comment]
tests\test_my_files.py  - FAIL

**Comment by jandrew44** [comment]
It works fine in my development environment.

**Comment by nadezhday** [comment]
It does not work on http://83.149.198.62/

**Comment by myrix** [comment]
Tested locally and then on http://83.149.198.62/, upload file and then deleted uploaded file, works fine. Need more precise steps to reproduce.

**Comment by nadezhday** [comment]
test PASSed
The problem is not reproduced.
