### ISSUE TITLE
Valency: GraphQL error: Dictionary 'name'  is deleted.

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#663]
Login as admin
Tools valency

Problem: it takes some time the Perspective choice to appear. Is it OK?

select Uralic › Erzya › Glossed corpus Test › Тест
Click Create valency data

Problem: 
It takes about 20 sec to get error message 'Dictionary is deleted'
![image](https://user-images.githubusercontent.com/59951991/159695691-19b2af1d-a950-4122-85ce-d73a2550b4bf.png)

What is the problem?
Should we allow to select only existing dictionaries?  

@myrix @jandrew44 FYI

**Comment by myrix** [comment]
Now also checking if any of the dictionary and parent languages are deleted, in addition to perspective's deletion check; shouldn't get this error anymore.

**Comment by nadezhday** [comment]
1) It takes about 1 sec to get error message - OK
![image](https://user-images.githubusercontent.com/59951991/159847856-71cd878e-da0c-42ca-a584-5244180fe030.png)

2) Still I get this error.
@myrix should I reopen this case?

**Comment by nadezhday** [comment]
Backend:2.1.1+1493-4c39c0bc-2022.03.24-04:06+modified-2022.03.24-08:21
uniparser-erzya:1.1.2
uniparser-komi-zyrian:1.1.14
uniparser-meadow-mari:1.1.9
uniparser-moksha:1.1.0
uniparser-udmurt:2.1.11
Frontend:f3cf3ee5-590-staging-server

**Comment by nadezhday** [comment]
@myrix  pleases check that all your changes are in the build.

**Comment by myrix** [comment]
@nadezhday changes are in the latest build 593, this is build 590.

**Comment by nadezhday** [comment]
Verified: we filter out dictionaries from the list - OK

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_valency_07_update.py
