### ISSUE TITLE
Valency: GraphQL error: Exception: Traceback (most recent call last)

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#664]
Login as admin
Tools valency

select Altaic languages › Turkic languages › Bashkir › Southern dialectal group › Dim Baškir › Әкиəт (vil. Klyashevo) › Әкиəт 
Click Create valency data

Problem: 
GraphQL error: Exception: Traceback (most recent call last): File "/api/lingvodoc/schema/query.py", line 10300, in mutate Valency.get_parser_result_data( File "/api/lingvodoc/schema/query.py", line 9937, in get_parser_result_data export_parser_result.process_parser_result( File "/api/lingvodoc/scripts/export_parser_result.py", line 252, in process_parser_result root = ElementTree.fromstring(content) File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML parser.feed(text) xml.etree.ElementTree.ParseError: undefined entity: line 1, column 41

![image](https://user-images.githubusercontent.com/59951991/159697732-e32b04d5-862a-45f2-b00f-dac3b76e2b42.png)

@myrix @jandrew44 FYI

**Comment by nadezhday** [comment]
No results after clicking Create valency data for this dictionary
![image](https://user-images.githubusercontent.com/59951991/159699629-4e4b5d9a-b912-4d99-a094-da73d5095b0e.png)

**Comment by myrix** [comment]
Fixed, now computes ok.

**Comment by nadezhday** [comment]
1) 
![image](https://user-images.githubusercontent.com/59951991/160779770-487f5d58-c4b6-48e9-a242-885588082362.png)

**Comment by nadezhday** [comment]
Separate defect is created 
 Create valency data: Exception (Марийский корпус) #684

**Comment by nadezhday** [comment]
Covered in tests\test_tools_valency_04.py
