### ISSUE TITLE
Add checkboxes

### ISSUE THREAD

**Issue by Dina936** [ispras/lingvodoc-react#667]
Add checkboxes 1) select all 2) to select a row 3) to select a column

https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=2203%3A6773

**Comment by nataliauvarova** [comment]
Done 
(Added these checkboxes, 
only for this table: http://lingvodoc.ru/dictionary/4839/1/perspective/4839/2/publish)

P.S. The page design is still old

**Comment by nadezhday** [comment]
1) Login as admin
2) http://lingvodoc.ispras.ru/dictionary/4839/1/perspective/4839/2/publish
Result: there are a lot of checkboxes in the table.

Problems: During Sorting checkbox becomes selected automatically. Separate defect is created:
https://github.com/ispras/lingvodoc-react/issues/689 Checkbox becomes selected after clicking on the sorting icon

**Comment by nadezhday** [comment]
Covered in tests\test_revital_01.py
