### ISSUE TITLE
Valency: GraphQL error: not implemented

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#668]
/valency, select 'Altaic languages › Turkic languages › Yakut › Glossed corpus "Tubelteler" on Sakha language › Khalandaar tubeltelere (calendar of events)', 'Create valency data':
![image](https://user-images.githubusercontent.com/2802467/159804857-df6010e3-9cd3-4247-8e4b-21ed32652457.png)

**Comment by myrix** [comment]
Fixed, now computes successfully.

**Comment by nadezhday** [comment]
Verified
![image](https://user-images.githubusercontent.com/59951991/159879340-09ca8c0a-3889-4c4a-85e2-75009a364aea.png)

**Comment by nadezhday** [comment]
covered in tests\test_tools_valency_04.py
