### ISSUE TITLE
Localization for Valency page

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#669]
We need localization for http://83.149.198.62/valency

![image](https://user-images.githubusercontent.com/59951991/159847579-ef5df99f-c495-4740-8932-1eacc21f3330.png)

![image](https://user-images.githubusercontent.com/59951991/159847508-47c2718f-6415-412f-a16b-4c3dcf9e289a.png)

**Comment by nataliauvarova** [comment]
Done

**Comment by nadezhday** [comment]
Separate defect is created: https://github.com/ispras/lingvodoc-react/issues/715
