### ISSUE TITLE
Improve Valency functionality: option selection

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#671]
The problem found during testing https://github.com/ispras/lingvodoc-react/issues/668 Valency: GraphQL error: not implemented

login as admin
Tools Valency

/valency, select 'Altaic languages › Turkic languages › Yakut › Glossed corpus "Tubelteler" on Sakha language › Khalandaar tubeltelere (calendar of events)'

![image](https://user-images.githubusercontent.com/59951991/159880613-1a097ae9-e38c-4d09-a5e4-4ba7bba1e184.png)

1) click Sort by verbs option

Problem: Loading valency data process is started. NOK (I want to select another option Sort by cases and only after the second option is ON to start loading valency data)
![image](https://user-images.githubusercontent.com/59951991/159881370-6d842057-6f45-4f83-a7aa-8de0e58fc9b5.png)

2) I have to wait for loading data finishes and only after this process is finished I can turn ON the second option
![image](https://user-images.githubusercontent.com/59951991/159881897-a3ca4154-ef86-47bb-b680-f8df041e90fb.png)

leds to Loading valency data...

**Comment by myrix** [comment]
Now can change options even during loading.

**Comment by nadezhday** [comment]
Verified.
Separate defect is created: https://github.com/ispras/lingvodoc-react/issues/686 Valency: clean Verb prefix filter field

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_valency_01.py
