### ISSUE TITLE
Valency-> Apply filter: White screen + exception

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#672]
The problem found during testing https://github.com/ispras/lingvodoc-react/issues/668 Valency: GraphQL error: not implemented

login as admin
Tools Valency

/valency, select 'Altaic languages › Turkic languages › Yakut › Glossed corpus "Tubelteler" on Sakha language › Khalandaar tubeltelere (calendar of events)'

1) click Sort by verbs option

Enter DAT 

Click Apply filter

![image](https://user-images.githubusercontent.com/59951991/159882735-4efabb47-2da3-4acc-a687-f7d2dacf164c.png)

Problem: white screen /+Exception/

TypeError: this.state.instance_list[0] is undefined
    value index.js:723
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    value index.js:262
raven.js:55:31
    2]</d/a[b raven.js:55
    React 5
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    value index.js:262

**Comment by myrix** [comment]
Fixed, now correctly displays no data in such cases.

**Comment by nadezhday** [comment]
Verified

![image](https://user-images.githubusercontent.com/59951991/160062702-81b12b61-9e42-47e1-9387-5eaee8e77124.png)

**Comment by vmonakhov** [comment]
Covered tests/test_tools_valency_06.py (#672 and #762))
