### ISSUE TITLE
Valency: Accept all selected button is located on the bottom of the page. You need to scroll to see it. 

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#673]
The problem found during testing https://github.com/ispras/lingvodoc-react/issues/668 Valency: GraphQL error: not implemented

login as admin
Tools Valency

/valency, select 'Altaic languages › Turkic languages › Yakut › Glossed corpus "Tubelteler" on Sakha language › Khalandaar tubeltelere (calendar of events)'

Click Select by default: off

![image](https://user-images.githubusercontent.com/59951991/159883524-0150f859-cf6e-42a6-9e7d-78fb902a6b34.png)

Problem: Accept all selected button is located on the bottom of the page. You need to scroll the page to see it. NOK

Should we ask @Dina how should we implement this page?

**Comment by myrix** [comment]
@nadezhday @jandrew44

The rationale for the button to be on the bottom is that a significant part of valency instance suggestions, and sometimes most suggestions, are invalid and should not be accepted, and the placement of the button on the bottom encourages user to look through all suggestions before accepting them all.

Julia Normanskaya, the customer for the feature, agrees with the reasoning, so when deciding whether to redesign or not, please consider this.

**Comment by jandrew44** [comment]
I agree with the reasons, closing.

**Comment by nadezhday** [comment]
WAD. Verified
