### ISSUE TITLE
Valency: Reject all selected button

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#674]
The problem found during testing https://github.com/ispras/lingvodoc-react/issues/668 Valency: GraphQL error: not implemented

login as admin
Tools Valency

/valency, select 'Altaic languages › Turkic languages › Yakut › Glossed corpus "Tubelteler" on Sakha language › Khalandaar tubeltelere (calendar of events)'

Click Select by default: off

Click Accept all selected

![image](https://user-images.githubusercontent.com/59951991/159884412-5f2e25a3-d291-4bcc-8f8f-e566d493361f.png)

Problem: How can I make all this option Rejected?

Should we have Reject all selected button?

**Comment by myrix** [comment]
Implemented.

**Comment by nadezhday** [comment]
As far as I can see these changes should be available.
![image](https://user-images.githubusercontent.com/59951991/160061985-be172d68-8d1d-4dd8-9cc8-8a1e430b1825.png)

Waiting with verification.

**Comment by nadezhday** [comment]
Verified

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_valency_0{1,6}.py
