### ISSUE TITLE
Valency:  We have problem with pagination on the bottom of the page

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#675]
The problem found during testing https://github.com/ispras/lingvodoc-react/issues/668 Valency: GraphQL error: not implemented

login as admin
Tools Valency

/valency, select 'Altaic languages › Turkic languages › Yakut › Glossed corpus "Tubelteler" on Sakha language › Khalandaar tubeltelere (calendar of events)'

We have problem with pagination on the bottom of the page
Look at the screenshot:

![image](https://user-images.githubusercontent.com/59951991/159885411-9b70a6d2-5fc4-479a-8ef0-1ef84037edd6.png)

**Comment by jandrew44** [comment]
Tried both Chrome and Firefox.
Could not reproduce, probably was fixed already.

**Comment by nadezhday** [comment]
Verified.

The problem is not reproduced anymore
