### ISSUE TITLE
Valency: use ENTER to navigate to any page

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#676]
The problem found during testing https://github.com/ispras/lingvodoc-react/issues/668 Valency: GraphQL error: not implemented

login as admin
Tools Valency

/valency, select 'Altaic languages › Turkic languages › Yakut › Glossed corpus "Tubelteler" on Sakha language › Khalandaar tubeltelere (calendar of events)'

Now you have to use Go button. 
But it would be good if we could use ENTER to initiate page navigation
![image](https://user-images.githubusercontent.com/59951991/159888729-7499531d-4bd8-451b-8c40-1e1ff5795d99.png)

**Comment by myrix** [comment]
Implemented.

**Comment by nadezhday** [comment]
Not verified.

Waiting with verification.

**Comment by nadezhday** [comment]
Verified

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_valency_06.py
