### ISSUE TITLE
Valency: Not all instances are present after setting option Off

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#678]
Admin
Tools - Valency
select perspective
![image](https://user-images.githubusercontent.com/59951991/159894741-93e3c16a-a529-4d2d-903d-2fa1097ecaef.png)

Result: Instances (1-25/44170) - OK

click Sort by verbs

Click any word

![image](https://user-images.githubusercontent.com/59951991/159895115-c26ab367-c6fb-49ff-b888-f90b6cb13b76.png)

Result: a few instances are listed - OK

Unselect Sort by verbs option

Expected: if option is unselected, we should see all instances - Instances (1-25/44170) 
Actual: only a few instances are listed.

**Comment by myrix** [comment]
Fixed, now correctly loads all instances after deselecting the option.

**Comment by nadezhday** [comment]
Verified

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_valency_06.py
