### ISSUE TITLE
Valency: User sign-in error and its localization

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#679]
Do not login
Tools - Valency
Problem: User sign-in error 

![image](https://user-images.githubusercontent.com/59951991/160107189-8535e23f-f7f3-4668-a690-2fd42c33ed90.png)

1) if Valency functionality is not available for unauthorized users then we should hide menu from Tools
2) Do not forget to localize this error

**Comment by myrix** [comment]
Tools -> Valency is hidden when there is no user signed in, shown when there is a signed in user:
![image](https://user-images.githubusercontent.com/2802467/160229972-c5d17f97-bcf5-4898-aa09-87b63c29083a.png)
![image](https://user-images.githubusercontent.com/2802467/160229980-0bf369c8-31f7-469e-aa25-ef96b236bd4b.png)

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/160336971-fd0a785f-48c8-408a-b9bc-2fca71e3b96d.png)

**Comment by nadezhday** [comment]
Covered in tests\test_tools_valency_02.py
