### ISSUE TITLE
Add server timings to GraphQL API responses

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#680]
HTTP responses to GraphQL API requests should contain timings of the requests' execution.

**Comment by myrix** [comment]
Implemented.

Elapsed real time and server's process time of the GraphQL request execution is now in the Server-Timing HTTP header and response JSON data:
![image](https://user-images.githubusercontent.com/2802467/160227702-d8894895-dc48-4a4b-930d-b59c4fb27587.png)
![image](https://user-images.githubusercontent.com/2802467/160227711-113e8236-d6b2-435d-a801-42f82ea4a664.png)

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/160780935-9c62750c-9ccc-44b9-b9ed-2f3a2727a58d.png)
