### ISSUE TITLE
Localization of Индивидуальная работа

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#681]
Open http://lingvodoc.ispras.ru/dashboard/dictionaries_all
Click By Organization

![image](https://user-images.githubusercontent.com/59951991/160331018-ad8fbac2-8501-4115-b4db-941cdfd2ebcf.png)

**Comment by nataliauvarova** [comment]
Done

**Comment by nadezhday** [comment]
Verified on Test env. (http://83.149.198.62)  - OK
Not verified on http://lingvodoc.ispras.ru/ -  NOK

I cannot see this translation in /edit_translations page? Should it be? 
@nataliauvarova 
@jandrew44

**Comment by nataliauvarova** [comment]
> /edit_translations



> Verified on Test env. (http://83.149.198.62) - OK Not verified on http://lingvodoc.ispras.ru/ - NOK
> 
> I cannot see this translation in /edit_translations page? Should it be? @nataliauvarova @jandrew44

If the database is not from production, then yes!

In production:
![Снимок экрана 2022-04-11 в 11 59 40](https://user-images.githubusercontent.com/90451645/162702325-20521894-1238-4fd9-a437-88e501f3db78.png)

**Comment by nadezhday** [comment]
Not verified

![image](https://user-images.githubusercontent.com/59951991/163519048-22313ffb-d6b9-4533-9842-ccb6d53b1fdb.png)

**Comment by nadezhday** [comment]
http://lingvodoc.ispras.ru/dashboard/dictionaries_all  - NOK
![image](https://user-images.githubusercontent.com/59951991/163519398-ebb0cec6-02bf-4d93-82c8-858233aed90a.png)


@nataliauvarova please check that all your changes are in the build.


Note: http://83.149.198.62/dashboard/dictionaries_all - OK

**Comment by nataliauvarova** [comment]
Updated on production

**Comment by nadezhday** [comment]
http://lingvodoc.ispras.ru/dashboard/dictionaries_all

Eng:
![image](https://user-images.githubusercontent.com/59951991/163777236-0e6a162a-c5e9-4503-8733-9667eb79c1dd.png)

Rus:
![image](https://user-images.githubusercontent.com/59951991/163777401-7c6cec65-4321-4642-8efd-47a6f655dba6.png)

Verified
