### ISSUE TITLE
If a dictionary cannot be opened we should inform our user

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#683]
This problem found during https://github.com/ispras/lingvodoc-react/issues/142 verification

Try to open /dictionary/2929/12/perspective/2929/16/publish

Problem: It the dictionary cannot be opened we should inform our user that it was deleted.
![image](https://user-images.githubusercontent.com/59951991/160754636-0e0c83f4-a41a-4110-961e-59eed9dfcc71.png)

Exception 

uncaught at l Error: b is undefined
re@http://83.149.198.62/assets/client.3d8e0023.js:1:610010
Dn@http://83.149.198.62/assets/vendor.daac830d.js:1:1220983
cr@http://83.149.198.62/assets/vendor.daac830d.js:1:1227821
Xl@http://83.149.198.62/assets/vendor.daac830d.js:1:1289485
ui@http://83.149.198.62/assets/vendor.daac830d.js:1:1255305
si@http://83.149.198.62/assets/vendor.daac830d.js:1:1255233
oi@http://83.149.198.62/assets/vendor.daac830d.js:1:1255094
$r@http://83.149.198.62/assets/vendor.daac830d.js:1:1251957
Ze/<@http://83.149.198.62/assets/vendor.daac830d.js:1:1207639
e.unstable_runWithPriority@http://83.149.198.62/assets/vendor.daac830d.js:1:1299035
We@http://83.149.198.62/assets/vendor.daac830d.js:1:1207417
Ze@http://83.149.198.62/assets/vendor.daac830d.js:1:1207587
Ke@http://83.149.198.62/assets/vendor.daac830d.js:1:1207520
Wr@http://83.149.198.62/assets/vendor.daac830d.js:1:1249537
enqueueSetState@http://83.149.198.62/assets/vendor.daac830d.js:1:1282169
a.prototype.setState@http://83.149.198.62/assets/vendor.daac830d.js:1:1174066
u/</c.prototype.onStateChange@http://83.149.198.62/assets/vendor.daac830d.js:1:686191
notify@http://83.149.198.62/assets/vendor.daac830d.js:1:1303752
t.prototype.notifyNestedSubs@http://83.149.198.62/assets/vendor.daac830d.js:1:1304280
u/</c.prototype.onStateChange@http://83.149.198.62/assets/vendor.daac830d.js:1:686209
notify@http://83.149.198.62/assets/vendor.daac830d.js:1:1303752
t.prototype.notifyNestedSubs@http://83.149.198.62/assets/vendor.daac830d.js:1:1304280
u/</c.prototype.onStateChange@http://83.149.198.62/assets/vendor.daac830d.js:1:686209
c@http://83.149.198.62/assets/vendor.daac830d.js:1:687897
i/t/</<@http://83.149.198.62/assets/vendor.daac830d.js:1:1321126
r/</</<@http://83.149.198.62/assets/vendor.daac830d.js:1:1320591
dispatch@http://83.149.198.62/assets/vendor.daac830d.js:1:1310444
I/<@http://83.149.198.62/assets/vendor.daac830d.js:1:226122
s/M/<@http://83.149.198.62/assets/vendor.daac830d.js:1:713665
r@http://83.149.198.62/assets/vendor.daac830d.js:1:709145
s@http://83.149.198.62/assets/vendor.daac830d.js:1:709296
i@http://83.149.198.62/assets/vendor.daac830d.js:1:709194
M@http://83.149.198.62/assets/vendor.daac830d.js:1:713623
b@http://83.149.198.62/assets/vendor.daac830d.js:1:712818
p@http://83.149.198.62/assets/vendor.daac830d.js:1:711757
n@http://83.149.198.62/assets/vendor.daac830d.js:1:712365
promise callback*x@http://83.149.198.62/assets/vendor.daac830d.js:1:713279
T@http://83.149.198.62/assets/vendor.daac830d.js:1:713874
b@http://83.149.198.62/assets/vendor.daac830d.js:1:712890
p@http://83.149.198.62/assets/vendor.daac830d.js:1:711757
n@http://83.149.198.62/assets/vendor.daac830d.js:1:712365
s/M/<@http://83.149.198.62/assets/vendor.daac830d.js:1:713736
r@http://83.149.198.62/assets/vendor.daac830d.js:1:709145
s@http://83.149.198.62/assets/vendor.daac830d.js:1:709296
A@http://83.149.198.62/assets/vendor.daac830d.js:1:714367
b@http://83.149.198.62/assets/vendor.daac830d.js:1:712937
p@http://83.149.198.62/assets/vendor.daac830d.js:1:711757
s@http://83.149.198.62/assets/vendor.daac830d.js:1:717399
r@http://83.149.198.62/assets/vendor.daac830d.js:1:710000
1237@http://83.149.198.62/assets/client.3d8e0023.js:1:44786
n@http://83.149.198.62/assets/manifest.99cf26d5.js:1:101
1037@http://83.149.198.62/assets/client.3d8e0023.js:1:43280
n@http://83.149.198.62/assets/manifest.99cf26d5.js:1:101
window.webpackJsonp@http://83.149.198.62/assets/manifest.99cf26d5.js:1:418
@http://83.149.198.62/assets/client.3d8e0023.js:1:13
[raven.js:55:31](https://cdn.ravenjs.com/3.18.1/raven.js)
    2]</d/a[b raven.js:55
    Redux 23
    1237 index.js:38
    Webpack 5

**Comment by jandrew44** [comment]
Could not reproduce exception.
The following error message is reported - "GraphQL error: DictionaryPerspective was not found".

**Comment by nadezhday** [comment]
Let us leave it as it is.
![image](https://user-images.githubusercontent.com/59951991/169961149-3b132134-d29f-4da1-a02a-b5ad850e64f8.png)
