### ISSUE TITLE
Create valency data: Exception (Марийский корпус)

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#684]
Create valency date for the following perspective:
![image](https://user-images.githubusercontent.com/59951991/160781679-dfb9569f-af81-42bd-b811-d9880d44e51a.png)

Problem: Exception
GraphQL error: Exception: Traceback (most recent call last): File "/api/lingvodoc/schema/query.py", line 10307, in mutate Valency.get_parser_result_data( File "/api/lingvodoc/schema/query.py", line 9944, in get_parser_result_data export_parser_result.process_parser_result( File "/api/lingvodoc/scripts/export_parser_result.py", line 562, in process_parser_result process_content( File "/api/lingvodoc/scripts/export_parser_result.py", line 430, in process_content for ( File "/api/lingvodoc/scripts/export_parser_result.py", line 416, in iterate_beautiful_soup process_paragraph_bs( File "/api/lingvodoc/scripts/export_parser_result.py", line 354, in process_paragraph_bs f(paragraph_html) File "/api/lingvodoc/scripts/export_parser_result.py", line 350, in f f(content) File "/api/lingvodoc/scripts/export_parser_result.py", line 312, in f raise NotImplementedError NotImplementedError

**Comment by myrix** [comment]
Fixed, now computes ok.

**Comment by nadezhday** [comment]
Covered in tests\test_tools_valency_04.py
