### ISSUE TITLE
Valency: F5 is needed to see Perspective selection field

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#685]
Very often I can see the following problem:
Login as admin
Tools-Verb Valency
Problem: Select perspective is not available
You can see Loading process 
![image](https://user-images.githubusercontent.com/59951991/160784222-7f69fa97-b402-45f7-8c36-abcf3309786e.png)

Workaround:
Click F5 to see Perspective selection field
![image](https://user-images.githubusercontent.com/59951991/160784367-0901a6a4-a8c1-4333-bd8b-d24c47bcc73b.png)

**Comment by nadezhday** [comment]
Here is the error message you get during the first attempt to open Verb Valency.   
![image](https://user-images.githubusercontent.com/59951991/161473945-6f91cfc8-0c2d-4805-bbac-2bad34b69e91.png)

**Comment by myrix** [comment]
> Here is the error message you get during the first attempt to open Verb Valency. ![image](https://user-images.githubusercontent.com/59951991/161473945-6f91cfc8-0c2d-4805-bbac-2bad34b69e91.png)

In general, this error message is supposed to appear only after DB reset, when user login info in the browser no longer corresponds to user info in the DB. If you encounter this error in other circumstances, please notify me.

Fixed error reporting, now after successful logging in and loading of the user info the message goes away as it supposed to.

Go to /valency after DB reset:
![image](https://user-images.githubusercontent.com/2802467/161502759-215edb27-de4c-4641-ab46-2980faa32208.png)

Log in, wait for info to load:
![image](https://user-images.githubusercontent.com/2802467/161502888-bf87d9ee-1ef8-4192-99e5-5c029ef4f22d.png)

**Comment by myrix** [comment]
Should be fixed by https://github.com/ispras/lingvodoc-react/commit/57f32256bea952400d0f89f649c97249c4091377.

**Comment by nadezhday** [comment]
Tests: Removed config.driver.refresh() steps

**Comment by nadezhday** [comment]
Verified.

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_valency_04.py
