### ISSUE TITLE
Valency: clean Verb prefix filter field

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#686]
Follow the steps from screenshot

![image](https://user-images.githubusercontent.com/59951991/161239531-06491a90-9d43-4f30-a5c8-e0e3d874df05.png)

We have two scenario: 
1) Select a new perspective.

2) Deselect and then select Sort by verbs option again

Expected: In both cases field should be empty.
![image](https://user-images.githubusercontent.com/59951991/161240092-5df3a493-b766-41eb-8159-acc66fede5bd.png)

Actual: field still has word selected in step 1 from the screenshot.

**Comment by myrix** [comment]
Fixed for both deselecting/selecting 'Sort by verbs' option and selecting a new perspective, the prefix is reset to empty.

**Comment by nadezhday** [comment]
Scenario from description works.
However, it would be good if we return all options to initial state after selecting a new perspective.


![image](https://user-images.githubusercontent.com/59951991/161481434-3c266eb7-bbb3-4844-a1c8-4b10ff054f27.png)

**Comment by myrix** [comment]
Now sorting by verbs, by cases and by acceptance are all reset when perspective is changed.

Selection by default and items per page are intentionally not reset.

**Comment by nadezhday** [comment]
verified

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_valency_06.py
