### ISSUE TITLE
Valency: sort by acceptance

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#688]
Users should be able to sort valency data by acceptance, so that all accepted valency data instances are shown before unaccepted ones.

**Comment by myrix** [comment]
Implemented, users can enable sorting by acceptance:
![image](https://user-images.githubusercontent.com/2802467/161668374-c92968a6-1ddb-4423-bf1c-c6ed1aa84365.png)
![image](https://user-images.githubusercontent.com/2802467/161668409-5f66e75b-dffb-47d3-82d7-4bc9005b4f08.png)

Sorting can be switched between accepted first / accepted last by clicking on the arrow icon:
![image](https://user-images.githubusercontent.com/2802467/161668535-bd39ae46-1c59-4ad4-bd43-dffbc15477bd.png)

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/161744510-8f9d4442-7555-4689-a6f0-ff1735dd5b7f.png)

Problem: Refresh icon is used for accepted first/ accepted last ordering.
It is not obvious.

@Dina936, please help us. What icon can be used instead Refresh?

**Comment by nadezhday** [comment]
@myrix something is wrong.
If we select Sort by verbs option in addition to Sort by acceptance.
The ordering does not work correctly
![image](https://user-images.githubusercontent.com/59951991/161745836-154b0c65-f3eb-4715-bfcf-686c8ef9172b.png)

**Comment by nadezhday** [comment]
1)activate the option the first time
![image](https://user-images.githubusercontent.com/59951991/161746669-8d1fba41-607d-4672-8100-14c71d924bf1.png)
2) Click alternate button
![image](https://user-images.githubusercontent.com/59951991/161746819-bcdfb863-5b67-4d09-bb38-f70345b7566a.png)

3) deactivate the option 
![image](https://user-images.githubusercontent.com/59951991/161746919-5f9265c7-86a3-4b0c-b251-6eb608b6e87f.png)

4) activate it again
Problem: we expect to see (accepted first) 
![image](https://user-images.githubusercontent.com/59951991/161747038-3fae57dc-8ab6-4879-b2bb-1927503a80eb.png)

**Comment by nadezhday** [comment]
Covered in tests\test_tools_valency_03.py  and tests\test_tools_valency_05.py

**Comment by myrix** [comment]
Fixed sorting issue.

First/last not resetting on option on/off for now stays as it is as it seems more convenient this way, would change later if users would request it.

**Comment by nadezhday** [comment]
Separate defect is created

https://github.com/ispras/lingvodoc-react/issues/692 Valency: Sort by cases + Sort by acceptance

This case can be verified.
