### ISSUE TITLE
Checkbox becomes selected after clicking on the sorting icon

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#689]
The problem is found during testing https://github.com/ispras/lingvodoc-react/issues/667

1) Login as admin
2) http://lingvodoc.ispras.ru/dictionary/4839/1/perspective/4839/2/publish
Result: there are a lot of checkboxes in the table.
3) click checkbox in the header of the first column
![image](https://user-images.githubusercontent.com/59951991/161692150-ca399129-a8b0-401f-b00c-dd6c32e4addf.png)

4) try to click Sorting icon in the second column.
![image](https://user-images.githubusercontent.com/59951991/161692207-f383d625-1e85-48e8-b72b-f209fd8cf0e1.png)

Problem:  Checkbox becomes selected after clicking on the sorting icon.
Video:
[2022-04-05 09-27-38.zip](https://github.com/ispras/lingvodoc-react/files/8415506/2022-04-05.09-27-38.zip)

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Verified.

**Comment by vmonakhov** [comment]
Covered in tests/test_publish.py
