### ISSUE TITLE
Valency: Sort by cases + Sort by acceptance

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#692]
The problem found during https://github.com/ispras/lingvodoc-react/issues/688 verification

![image](https://user-images.githubusercontent.com/59951991/161904769-42e6d07e-899c-483e-9b52-0d6a72fb035f.png)

Steps to reproduce

select Uralic › Udmurt › Corpus of Udmurt texts › удмуртские тексты

Sort by verbs -ON
азьмыныны
Result: Instances 1-6/6

Sort by cases - ON

Sort by acceptance - ON 

If needed accept any element

Click  alternate icon to see the changed order first/last

Problem: sorting by acceptance does not work if Sort by cases is ON

**Comment by nadezhday** [comment]
Should be covered in tests\test_tools_valency_05.py (remove raise SkipTest)

**Comment by myrix** [comment]
That's expected sorting order, first by cases, then by acceptance:
![image](https://user-images.githubusercontent.com/2802467/161911273-b35134ca-2631-43fb-9871-7aa1f1606d74.png)

Works as expected.
