### ISSUE TITLE
List of dictionaries - empty (Exception  t.get is not a function)

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#693]
https://jenkins.zeus.intra.ispras.ru/job/test_lingvodoc_frontend/1082/

Tests - FAIL

![image](https://user-images.githubusercontent.com/59951991/162121914-f9bf6b1a-5294-4035-8041-1f517e4ce11c.png)

Steps to reproduce:
http://83.149.198.62/dashboard/dictionaries_all

Problem: White screen.

TypeError: t.get is not a function
    e treeBuilder.js:57
    Immutable 16
    e treeBuilder.js:62
    Immutable 5
    e treeBuilder.js:62
    Immutable 16
    e treeBuilder.js:62
    Immutable 5
    e treeBuilder.js:62
    Immutable 16
    LS treeBuilder.js:68
    UH AllDicts.js:15
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    updateCurrentData react-apollo.esm.js:189
    next react-apollo.esm.js:169
    p Observable.js:126
    m Observable.js:161
    value Observable.js:215
    next ObservableQuery.js:328
    next ObservableQuery.js:328
    yf QueryManager.js:419
    broadcastQueries QueryManager.js:710
    broadcastQueries QueryManager.js:709
    broadcastQueries QueryManager.js:704
    next QueryManager.js:761
    p Observable.js:126
    m Observable.js:161
    value Observable.js:215
    next dedupLink.js:60
    next dedupLink.js:60
    p Observable.js:126
    m Observable.js:161
    value Observable.js:215
    next index.js:37
    p Observable.js:126
    m Observable.js:161
    value Observable.js:215
    Yf index.js:91

**Comment by nadezhday** [comment]
One more scenario:
Login as Julia
My files
Import as starling
[Хантыйская базисная лексика.csv](https://github.com/ispras/lingvodoc-react/files/8439867/default.csv)

Dashboard->Import Excel and Starling dictionaries
select the uploaded file

Problem: white screen + Exception
TypeError: t.get is not a function
    VC dictImport.js:192
    VC dictImport.js:192
    VL index.js:286
    Redux 12
    value index.js:114
    onChange Linker.js:114
    Lodash 4
    handleChange Dropdown.js:92
    handleItemClick Dropdown.js:397
    onClick Dropdown.js:936
    Lodash 4
    <anonymous> DropdownItem.js:30
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    d raven.js:393

**Comment by jandrew44** [comment]
Fixed.

**Comment by nadezhday** [comment]
Verified
