### ISSUE TITLE
 Apertium Sah parser improvement

### ISSUE THREAD

**Issue by ankan2013** [ispras/lingvodoc-react#694]
A modification was made to Apertium Sah language parser in https://github.com/ispras/lingvodoc/pull/1363.
It uses a new mode of Apertium parsing process that provides the result with some additional grammatic characteristics.
The execution of the parser stays the same as was described in https://github.com/ispras/lingvodoc-react/issues/595.
Each markup element now gets the only variant of markup due to that mode features.
Some words though get additional data, for example, in element 
![screen](https://user-images.githubusercontent.com/45983282/162129830-5c99f425-3813-4606-8b39-e11d90cb3851.png)
'abl' characteristic now presents that was absent in the previous version.

**Comment by nadezhday** [comment]
Verified.
![image](https://user-images.githubusercontent.com/59951991/162132602-06ef508c-f226-4707-9e61-3e42e365d844.png)

**Comment by nadezhday** [comment]
Covered in tests\test_parser_sah.py
