### ISSUE TITLE
Parsing of file sah.odt failed: An error occured during Apertium parser process running

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#696]
Test tests\test_parser_sah.py - FAIL

Follow the steps from https://github.com/ispras/lingvodoc-react/issues/595

![image](https://user-images.githubusercontent.com/59951991/162358393-7bf82cc5-8613-453d-9ff9-a6dc8f49b079.png)

![image](https://user-images.githubusercontent.com/59951991/162357820-e1ab6b28-9a4b-4035-87a0-171277ec2e3b.png)

Problem:
(1/2) Parsing of file sah.odt failed: An error occured during Apertium parser process running

**Comment by myrix** [comment]
Looks like now it computes ok.

**Comment by nadezhday** [comment]
Works fine. Verified
