### ISSUE TITLE
Import Excel and Starling dictionaries: CSV import problem

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#699]
User reports a problem with importing of [Казымский хантыйский.csv](https://github.com/ispras/lingvodoc-react/files/8501063/default.csv), the data is placed in the wrong columns:
![image](https://user-images.githubusercontent.com/2802467/163702265-7bf7510f-df09-47fc-86a7-5084a8e61a59.png)

**Comment by myrix** [comment]
Fixed, the problem, it seems, was faulty handling of the columns with the same name.

Testing:

Upload, if required, the file in the user menu -> 'My files'.

Open 'Import Excel and Starling dictionaries', select the file, keep all the columns:
![image](https://user-images.githubusercontent.com/2802467/163703574-23d5f034-734f-4f3d-a4ba-dba132ba8112.png)

Select the fields:
![image](https://user-images.githubusercontent.com/2802467/163703703-18464e21-05a7-4607-a298-1dd533562778.png)

Select parent language, specify dictionary name:
![image](https://user-images.githubusercontent.com/2802467/163703729-2d41a314-addb-4268-bde3-3d8cc24ead65.png)

Submit, wait for the task to finish, go to home page -> Language databases -> Dictionaries, open the created dictionary, all data from all five columns is here:
![image](https://user-images.githubusercontent.com/2802467/163703845-16612a7e-60cc-443b-b23b-5514ca7f85e1.png)

**Comment by nadezhday** [comment]
Scenario works.

**Comment by nadezhday** [comment]
Covered in tests\test_import_starling_dict_02.py
