### ISSUE TITLE
Import Excel and Starling dictionaries: choose fields via search

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#700]
In 'Import Excel and Starling dictionaries' Lingvodoc field selection is rather inconvenient, we have many fields and we have to scroll to choose one for each of the columns:
![image](https://user-images.githubusercontent.com/2802467/163702711-20fa97ae-c6a3-472a-ad18-dbd7b6ebd413.png)

We should be able to select fields via a search, a standard dropdown with a search probably would do.

While we are at it, we should also exclude erroneous fields with empty names, no point in showing them.

**Comment by myrix** [comment]
Implemented.

Selection with search:
![image](https://user-images.githubusercontent.com/2802467/163703959-7c8ff61c-d838-4869-95a2-05a10c125c6e.png)

No fields with empty names:
![image](https://user-images.githubusercontent.com/2802467/163703966-1ff81d3c-aaa6-4fa0-9edd-b31d67e1982f.png)

**Comment by nadezhday** [comment]
Verified

**Comment by nadezhday** [comment]
Covered in tests\test_import_starling_dict_02.py
