### ISSUE TITLE
Remove unnecessary user role info

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#701]
When we load Lingvodoc page for a logged in user, we get quite user info, quite a sizeable one for some users, most of the size coming from the roles info which right now is not used by anything.

E.g. logged in as admin, production and local development:
![image](https://user-images.githubusercontent.com/2802467/163704816-0b94fe98-908e-4908-b553-6709e14b7804.png)
![image](https://user-images.githubusercontent.com/2802467/163704820-0eed2c18-429d-477b-a96d-fbe5f5c09eb8.png)

If it's not used by anything, we should not load it.

**Comment by myrix** [comment]
Implemented, locally we have quite an improvement, from 1.99 MB to 299 B and from 5.02 s to 49 ms:
![image](https://user-images.githubusercontent.com/2802467/163705010-ca2b6dbc-209a-470f-86ad-d2d66a455a64.png)

**Comment by nadezhday** [comment]
Verified
![image](https://user-images.githubusercontent.com/59951991/163781834-3170089a-37f1-46b8-96bd-98bcb70731e3.png)
