### ISSUE TITLE
Disallow file uploading and file deletion for inactive users

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#702]
Currently inactive users can upload files and can delete uploaded files, they should not be able to do that.

**Comment by myrix** [comment]
Implemented.

Testing:

1. Choose a user, e.g. 'test'.

2. Sign in as administrator, user menu -> User account activation/deactivation, ensure that the user is active.

3. Sign out, sign in as the user, user menu -> My files.

4. Upload a file, upload successful.

5. Remove a file, remove successful.

6. Upload another file.

7. Sign out, sign in as administrator, deactive the user.

8. Sign out, sign in as the user, user menu -> My files.

9. Can't upload files, can't remove files.

**Comment by nadezhday** [comment]
Scenario from description works as expected.

@myrix 

Ivan, should we also disable Become a member, Become an administrator  buttons for inactive users?
![image](https://user-images.githubusercontent.com/59951991/163783022-d7755c5b-194b-40b5-865f-d87b3fc44a8c.png)
I can create a separate enhancement. 


Join in http://83.149.198.62/grants
![image](https://user-images.githubusercontent.com/59951991/163783599-eb4e5765-d5f1-4902-b5a2-e6177778572d.png)

**Comment by myrix** [comment]
> @myrix
> 
> Ivan, should we also disable Become a member, Become an administrator buttons for inactive users? I can create a separate enhancement.
> 
> Join in http://83.149.198.62/grants

Yeah, we probably should, separate enhancement ok.

**Comment by nadezhday** [comment]
Separate case is created: 
![image](https://user-images.githubusercontent.com/59951991/163949369-0a114dc4-398f-4964-b96d-7fb4e2adda1a.png)

**Comment by nadezhday** [comment]
Covered in tests\test_user_sign.py
