### ISSUE TITLE
Pagination: Possibility to open a specific page

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#703]
Open http://lingvodoc.ispras.ru/dictionary/4860/190/perspective/4860/191/view

Result: there are 195 pages

Just imagine, a user would like to open the100th page. How can the user do this? 

Implement: field to enter the page number

![image](https://user-images.githubusercontent.com/59951991/163754932-110f5cc4-5ca2-4908-a86f-1207146b25b3.png)

**Comment by jandrew44** [comment]
Done.
I have implemented a new pagination component based on Dina's design for the "edit translations" page.
This component can be used in other places where pagination is required.

**Comment by nadezhday** [comment]
Not verified.
Waiting for a new build.
![image](https://user-images.githubusercontent.com/59951991/171333632-d781e0de-a5ed-402b-92ec-ad97d1e5645b.png)

**Comment by jandrew44** [comment]
@nadezhday changes were included in the build 1299.
You can look through its regression tests results.
Here is the screenshot from the failed pagination test(most likely it should be updated for the new UI).

![image](https://user-images.githubusercontent.com/43956090/171376944-fe2bc6a7-1916-4aa3-99f5-c51ccca9309f.png)

**Comment by nadezhday** [comment]
Works fine.

Verified.

**Comment by nadezhday** [comment]
Covered in tests\test_view_lexical.py
