### ISSUE TITLE
My files: table does not appear. Loading... 

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#704]
Login as Julia

My files

Expected: The table with files appears.

Actual: Loading... The table does not appear. 

![image](https://user-images.githubusercontent.com/59951991/163758238-19afc0cb-2602-4e83-ac26-e5bc0ae71236.png)

Workaround: you need to press F5.

**Comment by nadezhday** [comment]
test my_files - FAILed
tests\test_import_starling_dict_01.py - FAILed

**Comment by nadezhday** [comment]
The same problem with page Tools->Valency
The list of dictionaries does not appear.

**Comment by myrix** [comment]
Should be fixed by https://github.com/ispras/lingvodoc-react/commit/57f32256bea952400d0f89f649c97249c4091377.

**Comment by nadezhday** [comment]
Tests - PASSed.

Verified
