### ISSUE TITLE
Edit profile: proper email conflict handling

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#706]
As reported by Andrey Zharov, right now if we try to edit in already existing email in Edit profile, we'll get a 500 with an internal html error page:
![image](https://user-images.githubusercontent.com/2802467/163912099-9793fc54-d42c-42fc-8337-61d28ef35c73.png)

In such cases we should get a 409 with a {"status": "409 Conflict", "error": "'The user with this email is already registered'"} response, like in analogous situation with Sign Up:
![image](https://user-images.githubusercontent.com/2802467/163912398-3088adb7-6595-4a93-8af2-44bb117bba54.png)

**Comment by myrix** [comment]
Implemented, we now get a 409 with a {"status": "409 Conflict", "error": "The user with this email is already registered"} response:
![image](https://user-images.githubusercontent.com/2802467/163912904-a6ac0dbb-1869-4133-9a06-f281199a8152.png)

**Comment by nadezhday** [comment]
Sign Up:
1) 'The user with this login is already registered'  - OK
2) 'The user with this email is already registered'  - OK

Edit profile:
The user with this email is already registered - OK

**Comment by nadezhday** [comment]
Covered in tests\test_user_edit_profile.py
