### ISSUE TITLE
Modify error message: Password do not match

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#708]
We have: Passwords does not match

Should it be: Passwords do not match
![image](https://user-images.githubusercontent.com/59951991/163930960-98b08b8e-cda0-426e-861e-f0d2fc61a54d.png)

**Comment by jandrew44** [comment]
Fixed.

**Comment by nadezhday** [comment]
Verified
![image](https://user-images.githubusercontent.com/59951991/164169902-ab4de5b8-1a79-4a28-832d-233dfbc9f8e4.png)

**Comment by nadezhday** [comment]
covered in tests\test_user_sign.py
