### ISSUE TITLE
Sign In: Localization

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#709]
Sign In:
Enter incorrect Password 

![image](https://user-images.githubusercontent.com/59951991/163936220-018c90b2-4322-457d-bfe1-87d17f253e32.png)

Localization is needed
Signin failure. Either no such login/password combination exists, or this user account has been deactivated.

**Comment by nataliauvarova** [comment]
Done

**Comment by nadezhday** [comment]
It looks like that we introduced the regression.


The area with error text becomes hidden on the bottom. 

![image](https://user-images.githubusercontent.com/59951991/164691580-2d78570a-cc24-4f01-bb6e-8642d8f00c04.png)

Reopening. @nataliauvarova FYI

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Verified
![image](https://user-images.githubusercontent.com/59951991/165026659-deaf6911-d13f-4ac4-b995-a0ccb28d35c6.png)
