### ISSUE TITLE
Sign Up: Localization

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#710]
Sign Up (Регистрация): 
![image](https://user-images.githubusercontent.com/59951991/163935354-12f8c08f-3ce8-43d4-98a8-15fe4be75917.png)

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Verified  (http://lingvodoc.ispras.ru/)
![image](https://user-images.githubusercontent.com/59951991/164689593-19d087ab-b659-4865-b1d4-79dbc659d1a5.png)
