### ISSUE TITLE
Modify 'Set valency annotation' message

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#714]
It seems that this message is not fully correct:
Set valency annotation.
![image](https://user-images.githubusercontent.com/59951991/164171846-002f0fbd-8b1c-4cf9-a89c-f2da7eb705c9.png)

![image](https://user-images.githubusercontent.com/59951991/164171670-6ac7ae84-2c83-414b-aef4-f439938e9c56.png)
Установите аннотацию валентности.

This message tells us that valency annotation has been set. 
Now it gives an instruction to set valency annotation.

**Comment by myrix** [comment]
Changed to "Аннотация валентности выставлена.".
![image](https://user-images.githubusercontent.com/2802467/164972381-7f4aa37c-9b15-4fa1-abdd-6f51db4eb21b.png)

**Comment by nadezhday** [comment]
Verified on http://lingvodoc.ispras.ru/
