### ISSUE TITLE
Valency: Localization left issues 'Go to page'

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#715]
![image](https://user-images.githubusercontent.com/59951991/164171240-16eb92f1-c06c-4018-ba5d-6abb9574b4f0.png)

I suggest to rename the following text:

На страницу: ___1___ [Перейти]

**Comment by nataliauvarova** [comment]
Fixed: http://lingvodoc.ru/valency

**Comment by nadezhday** [comment]
Looks fine.
