### ISSUE TITLE
Update Content table with new added dictionary

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#716]
Normanskaya:
/dashboard/dictionaries_all

When a new dictionary is created it should appear in the top table

![image](https://user-images.githubusercontent.com/59951991/164214375-177494da-58c8-41d7-9178-2e7b2137f007.png)

![image](https://user-images.githubusercontent.com/59951991/164214586-75152c35-e1da-45b1-9a38-4226de8c1342.png)

It is very important to implement this functionality!

**Comment by nadezhday** [comment]
@Dina936 FYI

**Comment by jandrew44** [comment]
Solved by #718.

**Comment by nadezhday** [comment]
Verified in #718
