### ISSUE TITLE
User account activation/deactivation: Dialog does not appear

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#717]
Login as admin

User account activation/deactivation

![image](https://user-images.githubusercontent.com/59951991/164230516-6a79153f-fe8e-4e12-92b4-8be2f77c03cb.png)

Expected: dialog with users' logins should appear.

Actual: Nothing

**Comment by jandrew44** [comment]
Fixed.

**Comment by nadezhday** [comment]
Verified.

**Comment by nadezhday** [comment]
covered in tests\test_user_sign.py
