### ISSUE TITLE
Adding/removing languages in the TOC

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#718]
We need to be able to add/remove languages in the TOC:
![image](https://user-images.githubusercontent.com/59951991/164214586-75152c35-e1da-45b1-9a38-4226de8c1342.png)

**Comment by myrix** [comment]
Implemented.

Sign in as administrator, go to Tools -> Edit of the dialects classification, you can add a language to the TOC by clicking on 'Add to TOC' button:
![image](https://user-images.githubusercontent.com/2802467/164361838-d2696849-5727-4f40-8a9a-4949ebb7b6fb.png)

Language then would appear in the dictionary (Language databases -> Dictionaries) / corpora (Language databases -> Language corpora) TOC if it has any dictionaries / corpora:
![image](https://user-images.githubusercontent.com/2802467/164364061-e0a6762b-3130-4591-a0f7-44b30bf3db99.png)

Languages that were added to the TOC can be removed from it by clicking the 'Remove from TOC' button:
![image](https://user-images.githubusercontent.com/2802467/164364371-9833bf00-e2b5-46a5-9f29-65b7f2b3660f.png)

Languages that were added to the TOC manually through direct id checking can't be removed from the TOC and have disabled 'Remove from TOC' buttons.

**Comment by nadezhday** [comment]
Verified

**Comment by nadezhday** [comment]
Covered in tests\test_tools_classification.py
