### ISSUE TITLE
Submit button is cut if alert messages are present in the dialog

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#719]
Enter invalid data in Sign Up dialog

![image](https://user-images.githubusercontent.com/59951991/164413493-93abd2f9-2870-4030-ab0d-7f6a31b4a94d.png)

Problem: Submit button us not fully visible.

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Looks fine:

![image](https://user-images.githubusercontent.com/59951991/165221036-02489cdd-0006-4218-a09c-1449efe4cebf.png)

![image](https://user-images.githubusercontent.com/59951991/165221084-4a4263eb-c10c-4749-b4ec-2a31043e28fe.png)

**Comment by vmonakhov** [comment]
Covered in tests/test_user_sign.py
