### ISSUE TITLE
Faster locale interface translation data loading

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#723]
Currently locale interface translation data loading takes quite a bit of time, e.g. 862 ms on production and 1620 ms on local development: 
![image](https://user-images.githubusercontent.com/2802467/164448716-566834e7-fb04-4267-9685-499373062bb6.png)
![image](https://user-images.githubusercontent.com/2802467/164448722-6a73387c-25c6-45b9-abcf-bda0bbb9ff13.png)

We should try to make it faster.

**Comment by myrix** [comment]
Implemented some optimizations, now it's quite faster at 153 ms on local development:
![image](https://user-images.githubusercontent.com/2802467/164455703-5bad3a65-f478-480a-9081-598d2531f407.png)

**Comment by nadezhday** [comment]
Verified.

Works faster.

**Comment by vmonakhov** [comment]
Covered in tests/test_localization.py
