### ISSUE TITLE
Make the Filter... field wider

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#726]
Can we make Filter... field wider?

![image](https://user-images.githubusercontent.com/59951991/164608257-e2546bac-4005-4210-a09e-da041ea32779.png)
Usually Dictionary names are too long.

**Comment by Dina936** [comment]
@nadezhday
В новом дизайне это поле шире. Проблема https://github.com/ispras/lingvodoc-react/issues/562

https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc? идентификатор узла = 1326%3A4887
