### ISSUE TITLE
Search in translations should be case insensitive

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#727]
Filter in translations should be case insensitive

![image](https://user-images.githubusercontent.com/59951991/164610864-e755e9cf-861a-4c51-a4cf-404860b46867.png)

**Comment by myrix** [comment]
Implemented, with an option to make the search case-sensitive if required.

**Comment by nadezhday** [comment]
Verified

**Comment by vmonakhov** [comment]
Already covered in tests/test_tools_translations.py
