### ISSUE TITLE
Localization Case-sensitivу option in translation

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#728]
Translations:
1) Case-sensitive
![image](https://user-images.githubusercontent.com/59951991/164627163-429e518e-e05f-4e3a-b8c6-8f65c9c48a8b.png)

2) No translations.
![image](https://user-images.githubusercontent.com/59951991/164647830-91ac6548-33d0-40bf-8f36-5bdf704b25c7.png)

Localization is needed.

**Comment by nataliauvarova** [comment]
Done

**Comment by nadezhday** [comment]
Verified 
http://lingvodoc.ispras.ru/
