### ISSUE TITLE
Spurious user info request

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#732]
Sign out, refresh page, we have a getting user info error while we are not in a signed in state:
![image](https://user-images.githubusercontent.com/2802467/164865522-42de1a6d-7ca7-427f-a048-90b5afe2b0b0.png)
![image](https://user-images.githubusercontent.com/2802467/164865526-58bc6f00-d858-4646-91c5-a572261efafa.png)

We should not try to get user info if we are not signed in.

**Comment by myrix** [comment]
Fixed, no more spurious user info request on page opening when signed out.

**Comment by nadezhday** [comment]
The problem is not reproduced.

**Comment by vmonakhov** [comment]
Covered in tests/test_user_sign.py
