### ISSUE TITLE
Better perspective fields info loading

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#733]
Open any perspective, e.g. /dictionary/4830/23/perspective/4830/27/edit, we have a slow request which contains info of all fields defined in the system, which we don't actually need, as it is used only to manually match it to perspective's columns.

829 ms on local development:
![image](https://user-images.githubusercontent.com/2802467/164873592-7aa5c4f1-59fd-4256-a9d4-8b12d3328fe1.png)
554 ms on production:
![image](https://user-images.githubusercontent.com/2802467/164873603-0a744822-d430-4988-8c58-950735382441.png)

We should be able to just request the field info corresponding to perspective's columns directly.

**Comment by myrix** [comment]
Implemented, now it's slightly faster, at e.g. 223 ms on local development:
![image](https://user-images.githubusercontent.com/2802467/164874600-27a00756-ec6a-4298-b577-86b937c0bb35.png)

**Comment by nadezhday** [comment]
Verified.

**Comment by vmonakhov** [comment]
Covered in tests/test_view_lexical_03.py
