### ISSUE TITLE
More responsive metadata editing in corpus / dictionary creation and properties

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#734]
Home page -> Dashboard -> Create dictionary / corpus -> go to 2nd step, try to type something into 'Informant' metadata field, there is noticeable stuttering.

Open any dictionary, e.g. /dictionary/657/3/perspective/657/4/view, open dictionary properties through upper breadcrumb dropdown menu, there is the same problem.

**Comment by myrix** [comment]
Now it's better, less stuttering.

**Comment by nadezhday** [comment]
Test (config.py) - updated by @myrix

**Comment by nadezhday** [comment]
Verified
