### ISSUE TITLE
Edit translations: add new when no results, regular expression search

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#735]
We should be able to add a new translation even when the current search yields no results, currently we can not do that:
![image](https://user-images.githubusercontent.com/2802467/165003323-86438503-6b5c-4395-9ebc-6770ed0963cf.png)

We also should allow searching with regular expressions, it would allow us to search for an exact string, currently we have no means of doing so:
![image](https://user-images.githubusercontent.com/2802467/165003363-02fd9f73-7242-4866-80d6-6b686529630b.png)

**Comment by myrix** [comment]
Implemented.

Can add new translations when the search yields no results:
![image](https://user-images.githubusercontent.com/2802467/165004147-025a7f20-8228-427e-a854-f6c683ba6743.png)

Can search with regular expressions, allowing searching for exact match:
![image](https://user-images.githubusercontent.com/2802467/165004165-c1c519d7-687c-4faf-a95e-d927b4a07da7.png)

**Comment by nadezhday** [comment]
Verified
![image](https://user-images.githubusercontent.com/59951991/165033785-939a03fb-7ae7-498d-b4fc-4e3cf5e8981a.png)

**Comment by nadezhday** [comment]
Localization is needed for 'Regular expression'
https://github.com/ispras/lingvodoc-react/issues/736

**Comment by nadezhday** [comment]
Regular expressions functionality works incorrectly:  https://github.com/ispras/lingvodoc-react/issues/737

**Comment by nadezhday** [comment]
Covered in tests\test_tools_translations.py
