### ISSUE TITLE
Localization is needed for 'Regular expression'

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#736]
![image](https://user-images.githubusercontent.com/59951991/165037181-7b1598f5-afd2-474e-9956-928bbbd775c2.png)

**Comment by myrix** [comment]
Added translation on [lingvodoc.ispras.ru/edit_translations](http://lingvodoc.ispras.ru/edit_translations):
![image](https://user-images.githubusercontent.com/2802467/165042000-570c0481-997f-4927-a9ec-0af49d3d1542.png)

**Comment by nadezhday** [comment]
Verified
![image](https://user-images.githubusercontent.com/59951991/165087903-7bc7ed35-cbc6-49cf-835f-04c5a559b17b.png)
