### ISSUE TITLE
Locale switching with no reload

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#738]
Open any dictionary, e.g. /dictionary/657/3/perspective/657/4/view, wait for it to load, then switch locale via top-right menu, the page is now reloading.

The same is true almost everywhere, if not everywhere, switching locales leads to page reload.

If would be better if we could switch locales of both the interface and the data without reloading.

**Comment by myrix** [comment]
Implemented, now can switch both interface and data locale without page reload.

**Comment by nadezhday** [comment]
Verified

**Comment by vmonakhov** [comment]
Selenium tests were updated for this
