### ISSUE TITLE
Deselecting search field

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#739]
Go to /map_search, you can search with field not selected,
![image](https://user-images.githubusercontent.com/2802467/165360604-12becdc5-8ff4-4898-85ee-3f203aa943d0.png)
such search searches all the fields.

The problem is, if you select a field, you can't unselect it,
![image](https://user-images.githubusercontent.com/2802467/165360801-ebc42417-6d52-471e-b500-fd82d23cd53e.png)
and the only way is to delete the whole AND condition with the search string and match type, and add a new, empty one, and fill it out again.

There should be an easier way to deselect a field.

**Comment by myrix** [comment]
Implemented, you can clear the selected field by clicking the delete icon:
![image](https://user-images.githubusercontent.com/2802467/165361873-4f845867-d9b7-41ab-89a5-bc9a2f15cd16.png)
![image](https://user-images.githubusercontent.com/2802467/165361972-c811724c-1f6b-4139-9dda-f1d36dc191d9.png)

The field selection is now also searchable.

**Comment by myrix** [comment]
@nadezhday 
Tests (config/config.py, tests/test_tools_search.py) updated.

**Comment by myrix** [comment]
Localization on lingvodoc.ispras.ru:
![image](https://user-images.githubusercontent.com/2802467/165444414-d40dde1b-0c9b-4380-ace5-70b440c46300.png)

**Comment by nadezhday** [comment]
Functionality works fine.

**Comment by nadezhday** [comment]
Covered in tests\test_tools_search_02.py
