### ISSUE TITLE
Exception occurs after clicking the Edit tab in Local Entries dialog

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#740]
Login as admin
Open http://83.149.198.62/map_search

Type: мама
Search
![image](https://user-images.githubusercontent.com/59951991/165444846-4c5d8fc4-a0b2-4a23-980f-af9c6b0518d1.png)

Expand the following languages
Click 1 result link
![image](https://user-images.githubusercontent.com/59951991/165444948-c74e71ca-4c40-487a-8d79-c04605e55976.png)

Click Edit tab
![image](https://user-images.githubusercontent.com/59951991/165445021-76b83746-b163-4548-af55-eae577c2a83c.png)

Exception: TypeError: oS is undefined

TypeError: oS is undefined
    mS index.js:370
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    d raven.js:393
[raven.js:55:31](https://cdn.ravenjs.com/3.18.1/raven.js)
    2]</d/a[b raven.js:55
    React 5
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    d raven.js:393

Note: Publish (1) opens without any problem.

**Comment by myrix** [comment]
Fixed, works ok, all tabs, including 'Edit', open as expected.

**Comment by nadezhday** [comment]
Covered in tests\test_tools_search_02.py

**Comment by nadezhday** [comment]
Verified
