### ISSUE TITLE
Dictionary properties exception

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#741]
Open /dictionary/502/3/perspective/502/4/view, wait for the dictionary to load, open in the upper breadcrumb menu 'Dictionary of Kildin Saami language (village Voronino)' -> 'Dictionary of Kildin Saami language (village Voronino) properties...', exception:

![image](https://user-images.githubusercontent.com/2802467/165449796-fbc6a265-ba8f-4e9c-ba47-d226be7941bb.png)

Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    React 4
        checkForNestedUpdates
        scheduleUpdateOnFiber
        enqueueSetState
        setState
    check_init index.js:175
    componentDidUpdate index.js:203
    React 3
        commitLifeCycles
        commitLayoutEffects
        callCallback
[react-dom.development.js:23803](webpack://lingvodoc/node_modules/react-dom/cjs/react-dom.development.js?61bb)
The above error occurred in the <Properties> component:

Properties@webpack-internal:///./src/components/DictionaryPropertiesModal/index.js:143:5
ApolloConsumer
WithApollo@webpack-internal:///./node_modules/@apollo/client/react/hoc/withApollo.js:24:32
ShouldUpdate@webpack-internal:///./node_modules/recompose/dist/Recompose.esm.js:616:27
Mutation@webpack-internal:///./node_modules/@apollo/client/react/components/Mutation.js:10:17
GraphQL@webpack-internal:///./node_modules/@apollo/client/react/hoc/mutation-hoc.js:29:50
Mutation@webpack-internal:///./node_modules/@apollo/client/react/components/Mutation.js:10:17
GraphQL@webpack-internal:///./node_modules/@apollo/client/react/hoc/mutation-hoc.js:29:50
Query@webpack-internal:///./node_modules/@apollo/client/react/components/Query.js:12:20
GraphQL@webpack-internal:///./node_modules/@apollo/client/react/hoc/query-hoc.js:35:50
Branch@webpack-internal:///./node_modules/recompose/dist/Recompose.esm.js:551:15
ConnectFunction@webpack-internal:///./node_modules/react-redux/es/components/connect.js:234:114
div
Layout@webpack-internal:///./src/Layout/index.js:81:5
ConnectFunction@webpack-internal:///./node_modules/react-redux/es/components/connect.js:234:114
Router@webpack-internal:///./node_modules/react-router/index.js:859:7
BrowserRouter@webpack-internal:///./node_modules/react-router-dom/index.js:121:7
ApolloProvider@webpack-internal:///./node_modules/@apollo/client/react/context/ApolloProvider.js:12:18
Provider@webpack-internal:///./node_modules/react-redux/es/components/Provider.js:14:18

**Comment by myrix** [comment]
Fixed, works ok, dictionary properties modal opens as expected.

**Comment by nadezhday** [comment]
Covered in tests\test_view_lexical_properties.py
