### ISSUE TITLE
During search: strange error message 'param_46913': 4200, 'param_46914': 662

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#742]
Login as julia

http://83.149.198.62/map_search

Sub string
type in Russian: ам
Click Search
![image](https://user-images.githubusercontent.com/59951991/165458072-4050f547-3418-4ac2-84b9-767a265d1ebf.png)

Problem: nothing is found
We get strange error message.
It would be nice to ask user to use another search parameters.

'param_46913': 4200, 'param_46914': 662, 'param_46915': 3151, 'param_46916': 63853, 'param_46917': 4387, 'param_46918': 488, 'param_46919': 3151, 'param_46920': 35745, 'param_46921': 3172, 'param_46922': 13402, 'param_46923': 731, 'param_46924': 5510, 'param_46925': 586, 'param_46926': 12703, 'param_46927': 775, 'param_46928': 6748, 'param_46929': 3532, 'param_46930': 17128, 'param_46931': 339, 'param_46932': 933, 'param_46933': 4860, 'param_46934': 208925, 'param_46935': 2482, 'param_46936': 1062, 'param_46937': 126, 'param_46938': 825, 'param_46939': 2639, 'param_46940': 4429, 'param_46941': 731, 'param_46942': 3416, 'param_46943': 3148, 'param_46944': 4306, 'param_46945': 2654, 'param_46946': 765, 'param_46947': 3080, 'param_46948': 9275, 'param_46949': 694, 'param_46950': 32773, 'param_46951': 4860, 'param_46952': 97998, 'param_46953': 586, 'param_46954': 17964, 'param_46955': 139, 'param_46956': 6887, 'param_46957': 4860, 'param_46958': 94965, 'param_46959': 1230, 'param_46960': 4645, 'param_46961': 586, 'param_46962': 8515, 'param_46963': 840, 'param_46964': 6153, 'param_46965': 775, 'param_46966': 27635, 'param_46967': 586, 'param_46968': 18314, 'param_46969': 1443, 'param_46970': 13047, 'param_46971': 3113, 'param_46972': 124, 'param_46973': 4179, 'param_46974': 858, 'param_46975': 3914, 'param_46976': 1341, 'param_46977': 4860, 'param_46978': 71179, 'param_46979': 704, 'param_46980': 4198, 'param_46981': 4860, 'param_46982': 100226, 'param_46983': 2059, 'param_46984': 8418, 'param_46985': 1858, 'param_46986': 26, 'param_46987': 3148, 'param_46988': 468, 'param_46989': 522, 'param_46990': 9038, 'param_46991': 776, 'param_46992': 55163, 'param_46993': 2871, 'param_46994': 2819, 'param_46995': 4860, 'param_46996': 194133, 'param_46997': 1574, 'param_46998': 129452, 'param_46999': 1674, 'param_47000': 2541, 'param_47001': 1733, 'param_47002': 9537, 'param_47003': 731, 'param_47004': 7283, 'param_47005': 3602, 'param_47006': 85685, 'param_47007': 3527, 'param_47008': 12141, 'param_47009': 776, 'param_47010': 47592, 'param_47011': 3648, 'param_47012': 26431, 'param_47013': 3148, 'param_47014': 9112, 'param_47015': 1574, 'param_47016': 156405, 'param_47017': 1359, 'param_47018': 28170, 'param_47019': 747, 'param_47020': 996, 'param_47021': 296, 'param_47022': 5261, 'param_47023': 731, 'param_47024': 5189, 'param_47025': 3527, 'param_47026': 6664, 'param_47027': 1574, 'param_47028': 71142, 'param_47029': 743, 'param_47030': 144584, 'param_47031': 4860, 'param_47032': 106187, 'param_47033': 133, 'param_47034': 544, 'param_47035': 1726, 'param_47036': 11375, 'param_47037': 3596, 'param_47038': 1516, 'param_47039': 4860, 'param_47040': 141650, 'param_47041': 731, 'param_47042': 6128, 'param_47043': 657, 'param_47044': 3173, 'param_47045': 1393, 'param_47046': 8691, 'param_47047': 638, 'param_47048': 2931, 'param_47049': 1752, 'param_47050': 12007, 'param_47051': 743, 'param_47052': 139107, 'param_47053': 776, 'param_47054': 33605, 'param_47055': 1493, 'param_47056': 412, 'param_47057': 4860, 'param_47058': 196711, 'param_47059': 4168, 'param_47060': 402, 'param_47061': 4755, 'param_47062': 428139, 'param_47063': 776, 'param_47064': 49820, 'param_47065': 475, 'param_47066': 2351, 'param_47067': 2872, 'param_47068': 9944, 'param_47069': 4860, 'param_47070': 136523, 'param_47071': 2872, 'param_47072': 1084, 'param_47073': 1447, 'param_47074': 417, 'param_47075': 3648, 'param_47076': 12794, 'param_47077': 1389, 'param_47078': 6074, 'param_47079': 107, 'param_47080': 1551, 'param_47081': 775, 'param_47082': 12038, 'param_47083': 4755, 'param_47084': 356058, 'param_47085': 1393, 'param_47086': 39966, 'param_47087': 1733, 'param_47088': 7577, 'param_47089': 694, 'param_47090': 31297}]

![image](https://user-images.githubusercontent.com/59951991/165458410-3c2ba545-1131-4d50-a712-b741bfc4e1e9.png)

**Comment by myrix** [comment]
Fixed, now this search computes ok.

**Comment by nadezhday** [comment]
Works fine. Verified

**Comment by nadezhday** [comment]
Covered in tests\test_tools_search_03.py
