### ISSUE TITLE
New translations of existing concepts are not accessible immediately 

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#744]
For example, you have a missing Russian translation for a language name at Language databases -> Dictionaries:
![image](https://user-images.githubusercontent.com/2802467/165673680-9f627343-7326-460d-ab62-03cbe89fe2ff.png)

Go to Tools -> Edit translations, search for the name in English, locale translation gist with a missing Russian translation:
![image](https://user-images.githubusercontent.com/2802467/165674081-68eadaf0-95f5-4c91-875f-e1d5c5dca547.png)
![image](https://user-images.githubusercontent.com/2802467/165674088-65a4e98f-8fb9-4c3f-af06-ac2380d43045.png)

Add missing translation "Хантыйский" for 'Russian (Русский)', save, go back to Language databases -> Dictionaries, switch to Russian locale, there's still a Khanty entry as if the newly added Russian translation does not exists.

**Comment by myrix** [comment]
Fixed, the problem was not clearing translationgist translation cache on addition of new atoms.

**Comment by nadezhday** [comment]
Follow the steps in description (using Russian locale)

In order to see the Russian translation in dictionaries list I have to press F5.

Waiting with verification. @myrix FYI

**Comment by nadezhday** [comment]
[2022-04-28 11-52-41.zip](https://github.com/ispras/lingvodoc-react/files/8581191/2022-04-28.11-52-41.zip)

Video 

Separate defect created: https://github.com/ispras/lingvodoc-react/issues/746 Extra F5 is needed to see a new translation

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_translations.py
