### ISSUE TITLE
Searching in a field error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#745]
Search in any field, e.g. 'Word', for something, e.g. substring 'ab', an error:
![image](https://user-images.githubusercontent.com/2802467/165677326-d592a04e-39b8-4803-a775-d7cd84605e8f.png)

Caused by changes fixing #742.

**Comment by myrix** [comment]
Fixed, now the search works.

**Comment by nadezhday** [comment]
works OK.
