### ISSUE TITLE
Extra F5 is needed to see a new translation

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#746]
Problem found during https://github.com/ispras/lingvodoc-react/issues/744 testing

Follow the steps in description (using Russian locale)

In order to see the Russian translation in dictionaries list I have to press F5.

Video:
[2022-04-28 11-52-41.zip](https://github.com/ispras/lingvodoc-react/files/8581493/2022-04-28.11-52-41.zip)

**Comment by jandrew44** [comment]
Fixed indirectly by the #720 changes.

**Comment by nadezhday** [comment]
Verified/
The problem is fixed

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_translations.py
