### ISSUE TITLE
Corpus creation metadata editing error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#748]
Open /dashboard/create_corpus, go to 2nd step 'Corpus names and metadata', type "123" Enter into 'Authors' metadata field, adding "123" to it, go back to the 1st step and then to the 2nd step, an error:
![image](https://user-images.githubusercontent.com/2802467/165909683-1b6ed0a8-16a1-4c4d-99c5-bd1edcc83f24.png)

**Comment by myrix** [comment]
Fixed, now works ok.

Looks like the error was introduced by https://github.com/ispras/lingvodoc-react/commit/392d6636082b1c5e7b40cb4cc04fb77e219fd8ae of https://github.com/ispras/lingvodoc-react/issues/734.

**Comment by nadezhday** [comment]
Verified

**Comment by vmonakhov** [comment]
Covered in tests/test_dashboard_create_corpus.py
