### ISSUE TITLE
Valency create data error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#749]
Go to Tools -> Verb valency, pick any perspective without valency data, e.g. "Altaic languages › Turkic languages › Yakut › Glossed corpus "Tubelteler" on Sakha language › Khalandaar tubeltelere (calendar of events" (search for it by typing "tubelteler"), click 'Create valency data' button, an error:
![image](https://user-images.githubusercontent.com/2802467/166082405-3fda0314-589d-4d32-9e6c-03a07cf9ba0f.png)

Valency data is actually created, which is apparent after reloading the page and picking the perspective again, the error gives impression that it is not so.

**Comment by myrix** [comment]
Fixed, now loads and shows created valency data without error.

**Comment by nadezhday** [comment]
Verified on http://83.149.198.62/valency

**Comment by nadezhday** [comment]
Covered in tests\test_tools_valency_04.py
