### ISSUE TITLE
Valency data annotation with .EAF corpora

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#750]
Users should be able to extract and work with valency annotations from .EAF corpora, just as #650 allows users to do that with valency annotations from annotated parser results.

**Comment by myrix** [comment]
Implemented.

Note: requires `alembic upgrade head` on DB to work.

Testing:

Go to /valency path (or Tools -> Verb valency), select "Uralic › Udmurt › Букварь для вотяцких детей Сарапульского уезда (1882) › Глоссированный текст" perspective, click 'Create valency data' button, wait for data to be created, created valency annotation data is displayed.

**Comment by myrix** [comment]
Temporary disabled until we'll have more clarity on details of valency instance extraction from .EAF corpora.

**Comment by myrix** [comment]
Implemented with additional merging of verbs by translations for verbs with equal 2-character prefixes, not counting diacritics.

Note: requires `alembic upgrade head` on DB to work.

**Comment by nadezhday** [comment]
Verified. Covered in tests\test_tools_valency_04.py
