### ISSUE TITLE
Dictionary properties: can't edit location

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#752]
Open /dictionary/3648/5/perspective/3648/8/view signed in as admin, wait for the dictionary to load, open in the upper breadcrumb menu 'Corpus of Udmurt texts' -> ''Corpus of Udmurt texts' properties...', scroll down to the location map, click on the map, location fields stays empty instead of displaying selected location like it's supposed to:
![image](https://user-images.githubusercontent.com/2802467/167151277-e0803f0d-2d7b-49c2-a38d-c98f78746eab.png)

**Comment by myrix** [comment]
Fixed, now can select locations alright:
![image](https://user-images.githubusercontent.com/2802467/167152207-a2d8a64a-fc98-4537-8fb7-6a588a58e177.png)

Was introduced by #734.

**Comment by nadezhday** [comment]
Covered in tests\test_view_lexical_properties.py

**Comment by nadezhday** [comment]
Test tests\test_view_lexical_properties.py - FAILed 
Problem: Sometimes we can see that after reopening dialog location ("lng" value) differs from the initial value.

1) NOK
 File "D:\ispras\modis\lingvodoc\frontend\tests\test_view_lexical_properties.py", line 91, in test_properties_location
AssertionError: '{"lat":61.32958673568789,"lng":59.85351562500001}' != '{"lat":61.32958673568789,"lng":60.02929687500001}'
- {"lat":61.32958673568789,"lng":59.85351562500001}
?                                ^ ^ ^^^^^^^
+ {"lat":61.32958673568789,"lng":60.02929687500001}
?                                ^^^^^ ^^^ ^

2) NOK
- {"lat":61.32958673568789,"lng":59.67773437500001}
?                                    ^^^^^^^
+ {"lat":61.32958673568789,"lng":59.85351562500001}
?                                   ++++++ ^

3) OK
test_view_lexical_properties.test_properties_location ... ok

Steps: Follow the steps from discription, Close dialog, then open it again. Compare location values.

**Comment by myrix** [comment]
Checked, the location changes in the DB as expected, after reopening of the dialog changed location is displayed as expected.

Added some waiting for save confirmation to the test tests\test_view_lexical_properties.py, the test is now OK.

We should probably investigate more deeply how exactly this works and if we should do something to make dictionary properties interface more robust against such quick action sequences, but right now we have other priorities.

@nadezhday 
Modified tests\test_view_lexical_properties.py by adding some waiting.
