### ISSUE TITLE
Add lexical entry: upload file -> Exception

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#757]
Test test_eaf_corpus_conversion - FAILed

Login as Julia
Create corpus (parent_language = 'Altaic languages, add perspective name, corpus name)
Click 'here'
Add lexical entry
click +
add file 

![image](https://user-images.githubusercontent.com/59951991/168020508-a941d77a-e962-491a-9170-4814324c5c43.png)

Problem: Exception
Uncaught (in promise) Error: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /objects/entity/graphql_files/5142/13/%D0%B8%D0%B7%D0%B1%D1%80%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5_%D1%81%D0%BB%D0%BE%D0%B2%D0%B0_%D0%B8%D0%B7_%D0%9F%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D1%8F_%D0%93%D0%BE%D1%81%D0%BF%D0%BE%D0%B4%D0%B0_%D0%AE%D0%9D_2.eaf (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f5c8c090b20>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by nadezhday** [comment]
Problem appears https://jenkins.zeus.intra.ispras.ru/job/test_lingvodoc_frontend/1215/

**Comment by nadezhday** [comment]
test_parser_bashkir.py test:

![image](https://user-images.githubusercontent.com/59951991/168023867-edd2a042-572f-4e79-9121-f2781f1b0b40.png)

**Comment by myrix** [comment]
With proper test server configuration now works as expected.

**Comment by nadezhday** [comment]
Verified.
Tests - PASSed
