### ISSUE TITLE
Roles modal user search: show logins in addition to names

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#759]
Login as admin, open any dictionary, e.g. /dictionary/3648/5/perspective/3648/8/view, open dictionary roles dialog from the dictionary dropdown menu from the breadcrumbs header, you can search users only by user's names:
![image](https://user-images.githubusercontent.com/2802467/168338439-6d2d9bbe-73ed-47fb-bb1f-103faf10efae.png)
![image](https://user-images.githubusercontent.com/2802467/168338447-926ce7c9-3b0d-40b4-a916-43841352f0f2.png)

We should add user logins to user names to 1) make searching for user more convenient and faster in case relevant search info is in user's login, and to 2) make disambiguating users easier, in particular in a possible case of users specifying identical names.

**Comment by myrix** [comment]
Implemented:
![image](https://user-images.githubusercontent.com/2802467/168342403-d50a58a1-013e-4fd4-b4ad-01a3207073c6.png)
![image](https://user-images.githubusercontent.com/2802467/168342414-3944a127-3c58-42e6-aaea-1ea0e6e472e7.png)

**Comment by nadezhday** [comment]
Verified

**Comment by nadezhday** [comment]
Covered in tests\test_view_lexical_roles.py
