### ISSUE TITLE
Create corpus error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#760]
Dashboard -> Create corpus, pick any parent language, next step, input any translation, next step, add perspective, input any name, create, an error:
![image](https://user-images.githubusercontent.com/2802467/168405137-92b112db-4108-4590-8bbf-a0f59390357e.png)
![image](https://user-images.githubusercontent.com/2802467/168405116-7462a669-7e61-4937-b6bb-ddbb1b0cda3b.png)

**Comment by myrix** [comment]
Fixed, now corpus is created successfully.

**Comment by nadezhday** [comment]
Verified (test - PASSed)
