### ISSUE TITLE
Languages page: edit language error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#761]
Open /languages (Tools -> Edit of the dialects classification) logged as admin, click 'Edit' on any language, an error:
![image](https://user-images.githubusercontent.com/2802467/168438294-fbc42bbb-c70c-4b33-9ad4-c84f285cceb4.png)

**Comment by myrix** [comment]
Fixed, now after clicking on 'Edit' language edit dialog opens as expected.

**Comment by nadezhday** [comment]
Already covered in tests\test_tools_translations.py

Verified
