### ISSUE TITLE
Valency non-existent verb prefix filter error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#762]
Open /valency, select "Uralic › Udmurt › Corpus of Udmurt texts › удмуртские тексты" perspective, click 'Create valency data' if there is not data, enable 'Sort by verbs', input "1" as verb prefix filter, click 'Apply filter (prefix "1")' button, an error:
![image](https://user-images.githubusercontent.com/2802467/168440573-01c8ecce-33ea-45d7-a034-94ac9d7b3da5.png)

**Comment by myrix** [comment]
Fixed, now correctly shows no instances:
![image](https://user-images.githubusercontent.com/2802467/168440736-25d5a309-a16c-41ae-91ad-dd4a1c6a9484.png)

**Comment by nadezhday** [comment]
Separate defect created: 
https://github.com/ispras/lingvodoc-react/issues/783 Valency: Options become overlapped

**Comment by nadezhday** [comment]
Verified. Covered in tests\test_tools_valency_06.py
