### ISSUE TITLE
Cognate analysis computation error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#763]
Open /dictionary/656/2/perspective/656/3/view logged in as admin, Tools -> Cognate analysis, click 'Compute' button, wait for computation to finish, an error:
![image](https://user-images.githubusercontent.com/2802467/168444700-795ac895-1a7e-4eb6-be7d-93fc5bcfcb82.png)

**Comment by myrix** [comment]
Fixed, now computes ok.

**Comment by nadezhday** [comment]
Verified.

Covered in tests\test_cognate_analysis_02.py
