### ISSUE TITLE
Language databases -> Dictionaries error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#764]
Sometimes, depending on query duration times it seems, when logged as admin Language databases -> Dictionaries (/dashboard/dictionaries_all) page does not open, instead giving an error:
![image](https://user-images.githubusercontent.com/2802467/168449108-14cb3071-ed48-414a-a367-35e7e882e91c.png)

**Comment by myrix** [comment]
Should be fixed now.

Looks like it was introduced by https://github.com/ispras/lingvodoc-react/commit/bb5ad12d2a742e91ec47677cbc2c77c34f9c03c1.

**Comment by nadezhday** [comment]
Free testing. I am not able to reproduce the problem. Verified.

**Comment by nadezhday** [comment]
Steps: 
Open http://83.149.198.62/dashboard/dictionaries_all
Try to refresh this page a few times by pressing F5.

Sometimes you can see the following error message:
Dictionary data loading error, please contact administrators.
Then dictionaries are loaded.
I cannot see any exceptions in the Console window.

@myrix any comments? Why do we have this 'Dictionary data loading error, please contact administrators' message? Should we reopen this defect?

![image](https://user-images.githubusercontent.com/59951991/168578459-e04b8b39-abf2-44f0-908d-1ddd5f19cfc0.png)

**Comment by myrix** [comment]
> Steps: Open http://83.149.198.62/dashboard/dictionaries_all Try to refresh this page a few times by pressing F5.
> 
> Sometimes you can see the following error message: Dictionary data loading error, please contact administrators. Then dictionaries are loaded. I cannot see any exceptions in the Console window.
> 
> @myrix any comments? Why do we have this 'Dictionary data loading error, please contact administrators' message? Should we reopen this defect?
> 
> ![image](https://user-images.githubusercontent.com/59951991/168578459-e04b8b39-abf2-44f0-908d-1ddd5f19cfc0.png)

It looks like that's what's happening:
1. Page starts to load, dictionary data query starts to load.
2. F5 is pressed, dictionary data query is aborted immediately and terminated with error; the current page is still showing for a few moments, and shows this error.
3. The page starts to reload, previous page with the error goes away.

So it's working as expected.

Unfortunately, there is no possibility to differentiate between an error from page reload and error from network / server problems, so the message stays. Maybe there should be a better message?

**Comment by nadezhday** [comment]
Verified.
If we should to rephrase this error message then a separate defect can be created.
