### ISSUE TITLE
Edit translations: 'Add new translation gist' at All

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#765]
Open /edit_translations (Tools -> Edit translations) signed in as admin, search for "abc", select 'All' gist type tab, we have an 'Add new translation gist' button which should not be here:
![image](https://user-images.githubusercontent.com/2802467/168456633-44636b5a-87c4-4dde-be37-7db62b8766c2.png)

Looks like it was introduced by https://github.com/ispras/lingvodoc-react/commit/0339ac2f0b022475a4af5388d01283d1750092c7 of https://github.com/ispras/lingvodoc-react/issues/756.

**Comment by myrix** [comment]
Fixed, no more 'Add new translation gist' button at 'All' gist type tab:
![image](https://user-images.githubusercontent.com/2802467/168456714-847f2639-5d74-40a6-b3d1-4b4c6663a65d.png)

**Comment by nadezhday** [comment]
Covered in tests\test_tools_translations.py
