### ISSUE TITLE
Merge suggestions error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#766]
Open /dictionary/2969/4/perspective/2969/5/merge signed in as admin, click 'View suggestions' button as soon as it is visible, an error:
![image](https://user-images.githubusercontent.com/2802467/168456779-72db991e-dc7d-4e7c-9df0-2c8bc596e330.png)

The problem is trying to get suggestions when the lexical entries and entities of the perspective are still not loaded; we should not allow getting suggestions until all required data is fully loaded.

**Comment by myrix** [comment]
Fixed, until all required data is fully loaded, it's impossible to try to get merge suggestions:
![image](https://user-images.githubusercontent.com/2802467/168457277-c3d08c05-efe8-4741-bafa-c3df869b1ea9.png)

**Comment by nadezhday** [comment]
Verified.
Covered in tests\test_view_lexical_merge_suggestions.py
