### ISSUE TITLE
Organization page: deletion inconsistency

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#768]
As automated tests test_organization_admins.py show, sometimes organization remains in the table after being successfully deleted:
![organization_table_deleted_still_shows](https://user-images.githubusercontent.com/2802467/168490224-1ef3d169-4727-44cd-b86d-e92216ed1e54.png)

Obviously it should not be so.

**Comment by myrix** [comment]
Alright, can't reproduce it, organization deletes and disappears fine, can only reproduce it with autotest, so probably a quirk of a too quick automated testing sequence.

Looks like with added waiting in test_organization_admins.py:test_delete_org() it at least tests fine, @nadezhday FYI.

**Comment by nadezhday** [comment]
Test - PASSed
