### ISSUE TITLE
Localization of Docx -> Eaf corpus conversion feature (error messages)

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#769]
Found during verification https://github.com/ispras/lingvodoc-react/issues/569

Translate the following:

1) input file is not a .docx format file

![image](https://user-images.githubusercontent.com/59951991/168527506-8d48c0c9-fd5e-4628-9594-fd296bccdc2c.png)

2) .docx file does not have any tables

![image](https://user-images.githubusercontent.com/59951991/168527597-7d9924de-5522-432e-8160-bb7d968607ff.png)

**Comment by nadezhday** [comment]
3. Please contact developers.....
![image](https://user-images.githubusercontent.com/59951991/168527850-46fddda1-ffca-4773-9e7e-5320f9c8f42c.png)

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Verified in http://lingvodoc.ispras.ru/docx2eaf
