### ISSUE TITLE
Mobile version: Loader is superimposed on other elements of the page /edit_translations

### ISSUE THREAD

**Issue by nataliauvarova** [ispras/lingvodoc-react#772]
![Снимок экрана 2022-05-16 в 16 31 28](https://user-images.githubusercontent.com/90451645/168608606-1e757f3f-bade-4d29-902b-d8cc31a2aa67.png)

**Comment by nataliauvarova** [comment]
Fixed

**Comment by nadezhday** [comment]
Verified
![image](https://user-images.githubusercontent.com/59951991/169287534-7661c1eb-2306-4e98-931c-3e768deaf2de.png)
