### ISSUE TITLE
 Import Excel and Starling dictionaries: better perspective names

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#780]
Right now, when importing Excel and Starling CSV dictionaries, perspective names are set to "starling_source". We should change it to "CSV (Excel) data" (en) / "CSV (Excel) данные" (ru) and "CSV (Starling) data" (en) / "CSV (Starling) данные" (ru) for Excel and Starling CSV dictionaries respectively.

**Comment by myrix** [comment]
Implemented.

Testing:

Open /import (Dashboard -> Import Excel and Starling dictionaries) signed in as admin, choose Test.csv, choose any number of CSV fields, map them to any Lingvodoc fields, choose any language and any dictionary name, 'Submit', open created dictionary, perspective name is as expected:
![image](https://user-images.githubusercontent.com/2802467/169176562-7ad17348-0112-455b-946f-e6c29b0afc46.png)
![image](https://user-images.githubusercontent.com/2802467/169176577-2532a7d9-a6d2-4d99-96a2-e1f4b69eadd2.png)

Go to user menu -> My files, upload [Test_Starling.csv](https://github.com/ispras/lingvodoc-react/files/8721715/Test_Starling.csv) as 'Starling/CSV' file:
![image](https://user-images.githubusercontent.com/2802467/169176712-afd65231-cbec-4aea-9e2d-19ddb1403447.png)

@nadezhday
Modified tests/test_my_files.py, tests/test_import_starling_dict_01.py, tests/test_import_starling_dict_02.py as required due to file type names uniformity changes.

Go to Dashboard -> Import Excel and Starling dictionaries, choose Test_Starling.csv, proceed choosing any fields, any language, any name, create dictionary, open it, perspective name is as expected:
![image](https://user-images.githubusercontent.com/2802467/169177594-23559a31-01fc-4360-a21e-9511584cfcd5.png)
![image](https://user-images.githubusercontent.com/2802467/169177599-a2375103-836d-4011-8a48-8fd3427c3a1f.png)

**Comment by nadezhday** [comment]
Verified
