### ISSUE TITLE
Create new 'name' perspective: white screen + Exception

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#782]
Open any dictionary (eg: http://83.149.198.62/dictionary/4995/1/perspective/4995/2/edit)
Invoke Create new 'name' perspective... menu command

![image](https://user-images.githubusercontent.com/59951991/169235237-94449749-36c3-48c5-895d-f387a5c649d9.png)

Exception:
TypeError: e.perspective is undefined
    r Fields.js:190
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    t useQuery.js:125
    _ module.js:132
    b module.js:176
    next module.js:225
    r iteration.js:4
    r iteration.js:4
    reportResult ObservableQuery.js:400
    next ObservableQuery.js:375
    r iteration.js:4
    r iteration.js:4
    next Concast.js:25
    _ module.js:132
    b module.js:176
    next module.js:225
    c asyncMap.js:19
    promise callback*5614/h/</u/< asyncMap.js:17
    _ module.js:132
    b module.js:176
    next module.js:225
    r iteration.js:4
    r iteration.js:4
    next Concast.js:25
    _ module.js:132
    b module.js:176
    next module.js:225
    next index.js:29
    _ module.js:132
    b module.js:176
    next module.js:225
    exports createUploadLink.js:216
    promise callback*89776/e.exports/</< createUploadLink.js:215
    e module.js:190
    subscribe module.js:264
    zn index.js:11
    e module.js:190
    subscribe module.js:264
    complete Concast.js:57
    start Concast.js:83
    t Concast.js:75
    getObservableFromLink QueryManager.js:549
    getResultsFromLink QueryManager.js:588
    _ QueryManager.js:753
    fetchQueryByPolicy QueryManager.js:780
    y QueryManager.js:636
    fetchQueryObservable QueryManager.js:643
    fetch ObservableQuery.js:295
    reobserve ObservableQuery.js:372
    a ObservableQuery.js:30
    e module.js:190
    subscribe module.js:264
    Ef useQuery.js:111
    Rl React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    Zi React
[raven.js:55:31](https://cdn.ravenjs.com/3.18.1/raven.js)
    2]</d/a[b raven.js:55
    React 5
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    t useQuery.js:125
    _ module.js:132
    b module.js:176
    next module.js:225
    r iteration.js:4
    r iteration.js:4
    reportResult ObservableQuery.js:400
    next ObservableQuery.js:375
    r iteration.js:4
    r iteration.js:4
    next Concast.js:25
    _ module.js:132
    b module.js:176
    next module.js:225
    c asyncMap.js:19
    (Async: promise callback)
    u asyncMap.js:17
    _ module.js:132
    b module.js:176
    next module.js:225
    r iteration.js:4
    r iteration.js:4
    next Concast.js:25
    _ module.js:132
    b module.js:176
    next module.js:225
    next index.js:29
    _ module.js:132
    b module.js:176
    next module.js:225
    exports createUploadLink.js:216
    (Async: promise callback)
    exports createUploadLink.js:215
    e module.js:190
    subscribe module.js:264
    zn index.js:11
    e module.js:190
    subscribe module.js:264
    complete Concast.js:57
    start Concast.js:83
    t Concast.js:75
    getObservableFromLink QueryManager.js:549
    getResultsFromLink QueryManager.js:588
    _ QueryManager.js:753
    fetchQueryByPolicy QueryManager.js:780
    y QueryManager.js:636
    fetchQueryObservable QueryManager.js:643
    fetch ObservableQuery.js:295
    reobserve ObservableQuery.js:372
    a ObservableQuery.js:30
    e module.js:190
    subscribe module.js:264
    Ef useQuery.js:111
    Rl React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    Zi React

**Comment by jandrew44** [comment]
Fixed.

**Comment by nadezhday** [comment]
Verified
Covered in tests\test_view_lexical_new_perspective.py
