### ISSUE TITLE
Valency: Options become overlapped

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#783]
Found during https://github.com/ispras/lingvodoc-react/issues/762 verification
Steps to reproduce:
Login as admin
Valency
select  Uralic › Udmurt › Corpus of Udmurt texts › удмуртские тексты
Sort by verbs - ON
In Verb prefix filter type: 1
Click Apply filter (prefix "1") button
Sort by verbs - OFF

Video: 

[2022-05-19 13-16-10.zip](https://github.com/ispras/lingvodoc-react/files/8728200/2022-05-19.13-16-10.zip)

Problem: Options become overlappted
![image](https://user-images.githubusercontent.com/59951991/169269605-3fc45564-d0f7-46bd-b88f-b34876afa097.png)

![image](https://user-images.githubusercontent.com/59951991/169269643-f06bf375-e14c-42bb-809e-5b3c8cfcaf67.png)

**Comment by jandrew44** [comment]
Fixed.

**Comment by nadezhday** [comment]
The problem is reproduced
![image](https://user-images.githubusercontent.com/59951991/169464474-493bec0c-8c2a-4665-a37f-4eaa23f90246.png)

**Comment by nadezhday** [comment]
Video:
[2022-05-20 09-14-16.zip](https://github.com/ispras/lingvodoc-react/files/8736849/2022-05-20.09-14-16.zip)

**Comment by jandrew44** [comment]
Tried to use steps from the last video.
Could not reproduce.

**Comment by nadezhday** [comment]
The problem is not reproduced.
