### ISSUE TITLE
Corpus converter enhancement

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#785]
Users report that current corpus converter behaviour, specifically, merging of different lexical entries related to changes introduced by #258, is unsatisfactory.

We should enhance corpus converter by making this merging feature optional and introducing other customization as appropriate.

**Comment by myrix** [comment]
Implemented.

Added an option to convert more than one markup simultaneously.

In the corpus conversion dialog, enable 'Convert additional markup.' option, now you can select additional markup to be included in conversion:
![image](https://user-images.githubusercontent.com/2802467/169700010-8417b472-8e7e-4445-ba90-4fe624f84402.png)
![image](https://user-images.githubusercontent.com/2802467/169700016-8f3e3f33-6719-45dd-afcf-1c1a807873c6.png)

Merging of lexical entries is controlled by the 'Merge lexical entries by meaning.' option and its suboptions, addition of words and transcriptions from paradigms is controlled by the 'Add words and transcriptions from paradigms to lexical entries' option and its suboptions.

The same when updating a dictionary:
![image](https://user-images.githubusercontent.com/2802467/169700108-41962019-92d5-4417-a27e-c1aaf39f946d.png)
![image](https://user-images.githubusercontent.com/2802467/169700113-bfb45519-a601-4d00-ba61-11d177fc56dc.png)

Tested in various combinations on /dictionary/4084/5404/perspective/4084/5407/view.

**Comment by nadezhday** [comment]
Covered in tests\test_corpus_convertion.py (partly)

**Comment by nadezhday** [comment]
Separate defect is created:
https://github.com/ispras/lingvodoc-react/issues/799
