### ISSUE TITLE
Dictionary / perspective properties error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#786]
Open /dictionary/4084/5404/perspective/4084/5407/view, view any markup by clicking on its table icon, 'Convert to dictionary...', select any name, select any language, 'Convert', wait for convertion to finish, go to /dashboard/dictionaries (Home page -> Dashboard -> Dictionaries), try to open properties of the created dictionary, an error:
![image](https://user-images.githubusercontent.com/2802467/169700298-b7a5eab6-13e5-453b-9b62-c452d4b566ab.png)
![image](https://user-images.githubusercontent.com/2802467/169700301-25019c7a-116b-43b2-b2d7-2dfedd563f6d.png)

The same when trying to open properties of its perspective:
![image](https://user-images.githubusercontent.com/2802467/169700318-7e57eb3e-96fb-42c4-983c-715b77f93442.png)
![image](https://user-images.githubusercontent.com/2802467/169700322-1d9cbe04-b95a-4d4e-b982-9f35890ca70f.png)

**Comment by myrix** [comment]
Fixed, now dictionary and perspective properties open alright.

Introduced by #785.

**Comment by nadezhday** [comment]
This particular scenario works fine.  Verified.

Covered (using another dictionary) in tests\test_view_published_convertion.py

Separate defect is created: https://github.com/ispras/lingvodoc-react/issues/793

**Comment by nadezhday** [comment]
This case can be verified
