### ISSUE TITLE
Undelete translationgist GraphQL mutation API

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#788]
We need a GraphQL API for undeleting translationgists, something like `undelete_translationgist` like `undelete_dictionary` and `undelete_perspective` we already have.

We need such an API when we need to undelete just the translationgist, e.g. in a situation when we need to undelete deleted translationgist (217, 2) of a non-deleted dictionary (630, 2), as the translationgist was shared between 3 dictionaries (217, 4), (620, 2), (630, 2) and, it seems, was deleted when dictionary (620, 2) was deleted, leaving dictionary (630, 2) without proper names.

**Comment by vmonakhov** [comment]
Related issue: https://github.com/ispras/lingvodoc-react/issues/1103

**Comment by vmonakhov** [comment]
Resolved, described in #1103, can be closed.
