### ISSUE TITLE
Impossible to select All entries option

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#792]
Found during verification https://github.com/ispras/lingvodoc-react/issues/786

Login as admin
http://83.149.198.62/dictionary/4084/5404/perspective/4084/5407/view

Click table icon

![image](https://user-images.githubusercontent.com/59951991/170011507-b312a185-ee5e-400d-b0cf-a1951789370b.png)

Convert to dictionary

Result: All entries option is ON

![image](https://user-images.githubusercontent.com/59951991/170011656-65ff882c-69f5-4582-aacf-9d77412c5db3.png)

Click Only entries of paradigmatic annotated forms option

Try to select All entries option again
![image](https://user-images.githubusercontent.com/59951991/170012504-1b354f04-67a2-473d-8b29-b785d3a3d8be.png)

Problem: it is not possible

**Comment by myrix** [comment]
Fixed, can now select 'All entries.'.

**Comment by nadezhday** [comment]
Verified

**Comment by vmonakhov** [comment]
Covered in tests/test_corpus_convertion.py
