### ISSUE TITLE
Title for properties dialog does not have name of the dictionary

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#793]
Follow the steps from https://github.com/ispras/lingvodoc-react/issues/786

Open properties dialog for converted dictionary

Problem: Title for properties dialog does not have name of the dictionary
![image](https://user-images.githubusercontent.com/59951991/170038205-07de049e-6fed-461a-9fc5-9ec44060b240.png)

**Comment by myrix** [comment]
Implemented more uniform properties dialog titles, "Dictionary '...' properties" and "Perspective '...' properties" for dictionaries and perspectives respectively.

**Comment by nadezhday** [comment]
Verified
![image](https://user-images.githubusercontent.com/59951991/170245551-b83bb509-c37d-4ef6-b748-8ba167f353ab.png)

**Comment by nadezhday** [comment]
Covered in tests\test_view_published_convertion.py
