### ISSUE TITLE
Phonology: no results

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#796]
Open /dictionary/296/4/perspective/296/5/view, Tools -> Phonology, click 'Create', wait for task to complete, no results.

**Comment by myrix** [comment]
Fixed, now computes with results.

Introduced by #790, specifically by cchardet changes.

**Comment by nadezhday** [comment]
Formant chart threshold 8
Or we can set it to 1

![image](https://user-images.githubusercontent.com/59951991/170227659-41d8a41e-32dd-4257-b5ec-fc53ee2ab45b.png)

![image](https://user-images.githubusercontent.com/59951991/170227522-c9ae73ac-ae01-4186-afd2-d88b71192aaa.png)

Result: (4/4) Finished, no results produced

Waiting for a new build.

**Comment by myrix** [comment]
> Formant chart threshold 8 Or we can set it to 1
> 
> ![image](https://user-images.githubusercontent.com/59951991/170227659-41d8a41e-32dd-4257-b5ec-fc53ee2ab45b.png)
> 
> ![image](https://user-images.githubusercontent.com/59951991/170227522-c9ae73ac-ae01-4186-afd2-d88b71192aaa.png)
> 
> Result: (4/4) Finished, no results produced
> 
> Waiting for a new build.

It should have results on 8. The fix wouldn't be in until the new build, so definitely should wait for it.

**Comment by nadezhday** [comment]
Verified
![image](https://user-images.githubusercontent.com/59951991/170436624-e0af79ac-e324-452d-adda-06db594d4e4a.png)

**Comment by vmonakhov** [comment]
Covered in tests/test_phonology.py
