### ISSUE TITLE
Convert to dictionary: Dictionary is not present in My dictionaries list

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#799]
Locale Eng
login as admin
/dictionary/4084/5404/perspective/4084/5407/view

click table icon
![image](https://user-images.githubusercontent.com/59951991/170460966-26bffbf1-ca0e-4e61-872e-53fc01321763.png)

Covert to dictionary...
Add Russian text
Convert

Open http://83.149.198.62/dashboard/dictionaries

Dictionary is not in the list

Convert to dictionary + Update dictionary option

Problem: dictionary is not in the list

**Comment by nadezhday** [comment]
[2022-05-26 12-52-14.zip](https://github.com/ispras/lingvodoc-react/files/8778107/2022-05-26.12-52-14.zip)
Video

**Comment by nadezhday** [comment]
[2022-05-26 12-55-29_работает.zip](https://github.com/ispras/lingvodoc-react/files/8778128/2022-05-26.12-55-29_.zip)

**Comment by myrix** [comment]
The dictionary is in the 'My dictionaries' list.

Implemented updating the list of dictionaries for update, start conversion, wait for the task to finish, open conversion dialog again, select 'Update dictionary', the new dictionary is here.

Updating list of available dictionaries in the currently opened dialog as soon as the task is finished is currently impossible, will require major rework of the task system and should be a separate issue.

**Comment by nadezhday** [comment]
Update dictionary 

Result: dictionary is found 
![image](https://user-images.githubusercontent.com/59951991/171138758-5e00a557-3a2b-4f27-b1e9-7e77925748d1.png)

@myrix  
But why I can not find it in the list http://83.149.198.62/dashboard/dictionaries


![image](https://user-images.githubusercontent.com/59951991/171138216-922d2056-7760-4d16-9c21-aa8e9d4db669.png)

Workaround: F5. 
Separate defect is created: https://github.com/ispras/lingvodoc-react/issues/801

**Comment by nadezhday** [comment]
Scenario from description is covered in tests\test_corpus_convertion.py
