### ISSUE TITLE
New design for the table: http://lingvodoc.ru/dictionary/4839/1/perspective/4839/2/publish and other similar tables

### ISSUE THREAD

**Issue by nataliauvarova** [ispras/lingvodoc-react#804]
New design for the table: http://lingvodoc.ru/dictionary/4839/1/perspective/4839/2/publish and other similar tables.

Make according to the layout: https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=2203%3A6773

In addition to the green and red buttons above the table (there will be changes in the design)

**Comment by nataliauvarova** [comment]
Done (according to the new design, except for the buttons above the table)

**Comment by nadezhday** [comment]
Minor issue:
![image](https://user-images.githubusercontent.com/59951991/173032956-04ece378-1332-4574-b312-ba279b9cb4df.png)

I will not create any defects for this.
