### ISSUE TITLE
Get tasks error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#806]
Getting tasks fails on the test stand:
![image](https://user-images.githubusercontent.com/2802467/171854937-8150c9d4-c916-43a9-8666-7ce01f8db388.png)

Looks like some kind of redis problem, gunicorn log in the backend container:

> redis.exceptions.ResponseError: DENIED Redis is running in protected mode because protected mode is enabled and no password is set for the default user. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a an authentication password for the default user. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside.

**Comment by myrix** [comment]
Fixed.

Looks like it was problem with the redis image 'bitnami/redis:latest' in the not up-to-date docker/docker-compose-proxy.yml, changed it to 'redis:latest' as it is in docker/docker-compose.yml.

**Comment by nadezhday** [comment]
Verified
