### ISSUE TITLE
Create dictionary: Impossible to select the parent language

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#807]
Login as admin
Create dictionary
Problem: this is no list of languages on the page

![image](https://user-images.githubusercontent.com/59951991/172098640-6f26e025-e478-4e4c-8ad8-effa62b42b8d.png)

**Comment by nadezhday** [comment]
Exception:
Uncaught TypeError: e is undefined
    n_ treeBuilder.js:6
    I index.js:67
    onCompleted index.js:86
    t useQuery.js:127
    _ module.js:132
    b module.js:176
    next module.js:225
    r iteration.js:4
    r iteration.js:4
    reportResult ObservableQuery.js:400
    next ObservableQuery.js:375
    r iteration.js:4
    r iteration.js:4
    next Concast.js:25
    _ module.js:132
    b module.js:176
    next module.js:225
    c asyncMap.js:19
    promise callback*5614/h/</u/< asyncMap.js:17
    _ module.js:132
    b module.js:176
    next module.js:225
    r iteration.js:4
    r iteration.js:4
    next Concast.js:25
    _ module.js:132
    b module.js:176
    next module.js:225
    next index.js:29
    _ module.js:132
    b module.js:176
    next module.js:225
    exports createUploadLink.js:216
    promise callback*89776/e.exports/</< createUploadLink.js:215
    e module.js:190
    subscribe module.js:264
    Fn index.js:11
    e module.js:190
    subscribe module.js:264
    complete Concast.js:57
    start Concast.js:83
    t Concast.js:75
    getObservableFromLink QueryManager.js:549
    getResultsFromLink QueryManager.js:588
    _ QueryManager.js:753
    fetchQueryByPolicy QueryManager.js:780
    y QueryManager.js:636
    fetchQueryObservable QueryManager.js:643
    fetch ObservableQuery.js:295
    reobserve ObservableQuery.js:372
    a ObservableQuery.js:30
    e module.js:190
    subscribe module.js:264
    Lf useQuery.js:111
    Rl React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    <anonymous> index.js:45
    <anonymous> index.js:53
    <anonymous> index.js:53

**Comment by myrix** [comment]
Fixed by the latest update https://github.com/ispras/lingvodoc-react/commit/e3769ae8e96cfd49f00a03fd3254a93a676c20df to #720.

**Comment by nadezhday** [comment]
Verified.

**Comment by vmonakhov** [comment]
Covered in tests/test_dictionaries.py
