### ISSUE TITLE
Merge suggestions error when not signed in

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#811]
Open /dictionary/2969/4/perspective/2969/5/merge when not signed in, wait for perspective data to load, click 'View suggestions' button, an error:
![image](https://user-images.githubusercontent.com/2802467/172107476-8b34e4aa-b463-4184-b2bd-35effcfb8c54.png)
Backend traceback:
```
Traceback (most recent call last):
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/graphql/execution/executor.py", line 311, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/root/lingvodoc-extra/virtualenv/lib/python3.8/site-packages/graphql/execution/executors/sync.py", line 7, in execute
    return fn(*args, **kwargs)
  File "/root/lingvodoc/lingvodoc/schema/query.py", line 5215, in resolve_merge_suggestions
    result = merge_suggestions(request=request,
  File "/root/lingvodoc/lingvodoc/utils/merge.py", line 94, in merge_suggestions
    entry_data_list, match_result_list, user_has_permissions = merge_suggestions_compute(
  File "/root/lingvodoc/lingvodoc/views/v2/merge.py", line 1022, in merge_suggestions_compute
    user_has_permissions = check_user_merge_permissions(
  File "/root/lingvodoc/lingvodoc/views/v2/merge.py", line 486, in check_user_merge_permissions
    if user.id == 1:
AttributeError: 'NoneType' object has no attribute 'id'
```

While merging is accessible only to signed-in users with required permissions, current policy is that anybody can view merge suggesions. So not signed in guests should also be able to view them.

**Comment by myrix** [comment]
Fixed, now suggestions compute ok when not signed in.

**Comment by nadezhday** [comment]
@myrix 
![image](https://user-images.githubusercontent.com/59951991/172855596-df0f9f70-1b46-413d-a46e-ea3ff89bd4c9.png)

![image](https://user-images.githubusercontent.com/59951991/172855808-9b3be9b2-c6d5-4c9e-8da5-8ff5438f5e47.png)


Is this the expected result?

**Comment by myrix** [comment]
> @myrix ![image](https://user-images.githubusercontent.com/59951991/172855596-df0f9f70-1b46-413d-a46e-ea3ff89bd4c9.png)
> 
> ![image](https://user-images.githubusercontent.com/59951991/172855808-9b3be9b2-c6d5-4c9e-8da5-8ff5438f5e47.png)
> 
> Is this the expected result?

For the current DB at the testing stand, yeah. If you'll update the DB to the current from the production, there should be one 1 suggestion.

In general, if there are suggestions or not does not matter for this issue, if suggestions compute at all, everything is good.

**Comment by nadezhday** [comment]
Verified.

**Comment by nadezhday** [comment]
Should be covered in selenium

**Comment by vmonakhov** [comment]
Covered in tests/test_view_lexical_merge_suggestions.py
