### ISSUE TITLE
Checkboxes - Part 2

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#812]
The left issues from https://github.com/ispras/lingvodoc-react/issues/667

Compare figma and the page that we have now.

![image](https://user-images.githubusercontent.com/59951991/172123104-ad011bb0-569c-4ab8-9500-6488db5429df.png)

![image](https://user-images.githubusercontent.com/59951991/172123274-1417d6c5-7636-4f4b-9148-2c1c3ffee98b.png)

Problem: checkboxes are missing.
We should make it as designer says.

@Dina936

**Comment by nataliauvarova** [comment]
In task 667 we are talking only about the page: http://lingvodoc.ru/dictionary/4839/1/perspective/4839/2/publish

There is no need to add new checkboxes on the other pages.

**Comment by Dina936** [comment]
@nadezhday This is a different page. the customer asked to make checkboxes for only one table, which is at the address  http://lingvodoc.ispras.ru/dictionary/4839/1/perspective/4839/2/publish

**Comment by nadezhday** [comment]
http://83.149.198.62/dictionary/4839/1/perspective/4839/2/publish

![image](https://user-images.githubusercontent.com/59951991/172133103-6079989d-4ad1-4426-8b52-7046dbd4a47c.png)
