### ISSUE TITLE
Language databases -> Dictionaries: blank page bug

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#813]
User reports an error at Language databases -> Dictionaries, the page becomes blank.

Looks like https://sentry.at.ispras.ru/ispras/lingvodoc-frontend/issues/1132/, TypeError: undefined is not an object (evaluating 'c.translation[0].toLocaleUpperCase'), and https://sentry.at.ispras.ru/ispras/lingvodoc-frontend/issues/1133/, TypeError: Cannot read properties of undefined (reading 'toLocaleUpperCase') may be about it.

**Comment by myrix** [comment]
Couldn't reproduce, added additional translation checks, it shouldn't be undefined anymore.

**Comment by nadezhday** [comment]
@myrix can you please provide steps for verification.

**Comment by myrix** [comment]
> @myrix can you please provide steps for verification.

Don't know exact steps, couldn't reproduce, just that after using the page Languge databases -> Dictionaries (/dictionaries_all) for a while it does not become blank and there are no errors.

**Comment by nadezhday** [comment]
closing without verification

**Comment by vmonakhov** [comment]
Covered in many tests
