### ISSUE TITLE
Duplicated views

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#816]
Looks at the screenshots:

![image](https://user-images.githubusercontent.com/59951991/172851230-eba56d9e-cb5d-4671-94fa-75c442fbdb69.png)

![image](https://user-images.githubusercontent.com/59951991/172851269-8b8d69b3-9a34-48d1-9e32-79a586aa5daf.png)

Problem: duplicated view

**Comment by nadezhday** [comment]
A 110-Swadesh list for the Nurlat variety of Chuvash (Anatri dialect) (4)
(А.В. Савельев, В.К. Савельев (информант))

![image](https://user-images.githubusercontent.com/59951991/172858521-0d9818bc-9160-4390-b586-8bcd7587e690.png)

**Comment by myrix** [comment]
Fixed.

**Comment by nadezhday** [comment]
Verified

**Comment by vmonakhov** [comment]
Covered in tests/test_dictionaries.py
