### ISSUE TITLE
Create dictionary: Next Step bug

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#817]
Dashboard -> Create dictionary, select "Uralic" as parent language, can't click on the 'Next Step' button, it's behind the language tree:
![image](https://user-images.githubusercontent.com/2802467/172932147-935282b7-23fc-4175-bea3-717e65e9e9ed.png)

Looks like it was introduced by #122.

**Comment by nadezhday** [comment]
test test_dashboard_create_corpus - FAILed

**Comment by jandrew44** [comment]
Fixed.

**Comment by vmonakhov** [comment]
Covered in tests/test_dashboard_create_corpus.py
