### ISSUE TITLE
Created at field bug

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#822]
Open properties of any dictionary or perspective, e.g. /dictionary/4084/5404/perspective/4084/5407/view, 'Глоссированный текст' dropdown menu, ''Глоссированный текст' properties...', 'Created at' date is a default zero Unix time value instead of a proper one:
![image](https://user-images.githubusercontent.com/2802467/173489835-50e4c41a-28a2-459e-8477-20257453e04f.png)

Was introduced by commit https://github.com/ispras/lingvodoc/commit/9afd5604aa7f4e6b086f85f2b1b000ca222b6978 of #720.

**Comment by myrix** [comment]
Fixed, now the proper value is displayed, and not a default one:
![image](https://user-images.githubusercontent.com/2802467/173490545-7ef12885-9a77-49fe-bc89-5b3ac393602c.png)

**Comment by vmonakhov** [comment]
Covered at tests/test_dictionaries.py
