### ISSUE TITLE
Image entity deletion

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#823]
As reported by users, open /dictionary/5329/1/perspective/5329/2/edit logged in as admin, sort by 'Pitch' column descending, there is no way to delete image entities in the 'Pitch' column.

We should add a way to do it.

**Comment by myrix** [comment]
Implemented, can now delete image entities just as sound and markup entities, by clicking on the cross icon and confirming deletion in the confirmation dialog:
![image](https://user-images.githubusercontent.com/2802467/173754073-c8a11018-2216-45ce-b5d1-a565cf9c082f.png)

**Comment by vmonakhov** [comment]
Covered in tests/test_dictionaries.py
