### ISSUE TITLE
Search: show grammar selection error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#824]
Open /map_search (Home page -> Tools -> Search and map's creating), wait for additional filter data to load, click 'Grammar' button, select 'affirmative' under 'Mood / Form', click 'Close' button, click 'Show' button, an error:
![image](https://user-images.githubusercontent.com/2802467/174222669-a859d3cc-f6d7-448c-bda3-674d15d0e5e8.png)

Sentry report [1141](https://sentry.at.ispras.ru/ispras/lingvodoc-frontend/issues/1141/), introduced by commit https://github.com/ispras/lingvodoc-react/commit/68dcdfe5858a7568ba049901a38029a2085cc857 of #738.

**Comment by myrix** [comment]
Fixed, now shows grammar selection ok:
![image](https://user-images.githubusercontent.com/2802467/174222960-5ca266a3-c91d-4454-ad90-bb51a1170e1b.png)

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_search_03.py
