### ISSUE TITLE
Search: empty conditions checking

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#826]
There is a suspicion that some search queries may be responsible for total DB hangup which happened on 14th of June. In theory, it may have happend because of an overly permissive search query, such as one having an empty substring condition, which would require going through almost all entities in the DB.

We should ensure that there are checks for such overly permissive queries both on the frontend and the backend, hopefully preventing such DB locks in the future.

We should also ensure that the search queries are reflected in the logs, so that if such DB lock happens again, we would be able to determine if it was really because of the search query, and if yes, because of which.

**Comment by myrix** [comment]
Ensured, as much as currently possible, that there are checks for overly permissive queries on the frontend and implemented such checks at the backend.

The frontend actually had some form of such checks, though it was somewhat counter-intuitive, if after accounting for the grammar checks there was any search condition with an empty string, the search transitioned to a special mode in which it only returned dictionaries and perspectives, which made sense if we selected dictionaries and perspectives based on metadata. Made this search mode explicit and enabled display of a dictionary/perspective search tree in such a mode.

Also now relevant search queries info should be shown in the server logs.

Overall, functionality is as follows:

Searches with empty full string conditions are allowed:
![image](https://user-images.githubusercontent.com/2802467/174796025-4b5342ca-d457-4939-a493-62836e6188c7.png)

Searches with empty substring or regexp conditions are not allowed if there are no grammar modifiers:
![image](https://user-images.githubusercontent.com/2802467/174796171-9c72fe96-e9ff-4cd8-959b-eb67750ac7c2.png)
![image](https://user-images.githubusercontent.com/2802467/174796178-b01225b0-6570-4b1d-ad30-def5489d2ebd.png)

If some grammar modifiers are enabled (click button 'Grammar', select anything, close the dialog) substring and regexp conditions are allowed:
![image](https://user-images.githubusercontent.com/2802467/174798258-7c9da743-6c68-496e-9305-5882958e87e0.png)
![image](https://user-images.githubusercontent.com/2802467/174798283-1bc902b4-b13c-4c51-8869-9ef4a9990705.png)

To search only for dictionaries and perspectives, delete all search conditions:
![image](https://user-images.githubusercontent.com/2802467/174798977-35daf5a3-c418-467b-b9dd-d4906f57566e.png)

E.g. select year tag "2021" (click button 'Select tags', select year tag "2021", close the dialog), click 'Search' button, we have results with dictionaries / perspectives tree shown:
![image](https://user-images.githubusercontent.com/2802467/174801074-ce3fc10d-961a-4aa3-8176-d637d74ceb91.png)
Perspective links in this tree are actually links to perspectives' pages and do not bring up partial perspectives dialog as for the usual search.

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_search_03.py
