### ISSUE TITLE
Create corpus: linked field bug

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#831]
Open home page -> Dashboard -> Create corpus (/create_corpus) logged in as admin, choose any parent language, next step, choose any corpus name, next step, add a perspective, deselect 'has linked field' checkbox, the linked field does not become unlinked and does not appear in the list of top-level fields how it should:
![image](https://user-images.githubusercontent.com/2802467/175309753-a0a8c3e5-f23c-4726-840a-c730d4fb5b16.png)
![image](https://user-images.githubusercontent.com/2802467/175309767-2a1f0317-88fe-428c-954e-2ebe69507013.png)

**Comment by myrix** [comment]
Fixed, now the linked field is being unlinked as it should be:
![image](https://user-images.githubusercontent.com/2802467/175320230-249a69f9-d963-4b40-8b74-e59c31ba0190.png)

**Comment by vmonakhov** [comment]
Covered in tests/test_dashboard_create_corpus.py
