### ISSUE TITLE
Search from link: source link is not shown

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#841]
Open /map_search/UxBPQ, wait for the search results to load, expected result: search results with a link to these search results, ending in /map_search/UxBPQ.

Instead we are shown search results without a link:
![image](https://user-images.githubusercontent.com/2802467/178079201-c90693b7-77a7-4133-952b-53bd74b1b97f.png)

tests/test_tools_storage.py failed

Looks like it was introduced by commit https://github.com/ispras/lingvodoc-react/commit/7b9f623b9e5d682a68d719471f86cd098b16120d of #826.

**Comment by myrix** [comment]
Fixed, link is shown as expected.

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_storage.py
