### ISSUE TITLE
New design of the message "No statistics for the selected period" in the modal statistics window.

### ISSUE THREAD

**Issue by nataliauvarova** [ispras/lingvodoc-react#852]
https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=2447%3A7340
![Снимок экрана 2022-07-25 в 17 14 15](https://user-images.githubusercontent.com/90451645/180754236-6b1f745c-2314-4522-a738-2fe9043b6e87.png)

**Comment by nataliauvarova** [comment]
Done

**Comment by vmonakhov** [comment]
Looks good. Verified.
