### ISSUE TITLE
New design for the modal window "Phonology"

### ISSUE THREAD

**Issue by nataliauvarova** [ispras/lingvodoc-react#865]
New design for the modal window "Phonology":
![Снимок экрана 2022-08-08 в 16 02 11](https://user-images.githubusercontent.com/90451645/183427390-f1bb0a30-f358-4ff3-80ae-04a62b7d64e1.png)

https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=2203%3A6773

**Comment by nataliauvarova** [comment]
Done

**Comment by vmonakhov** [comment]
Verified but the separate issue was created #949
