### ISSUE TITLE
Localization for modal windows

### ISSUE THREAD

**Issue by nataliauvarova** [ispras/lingvodoc-react#871]
Localization for modal windows "Cognate acoustic analysis", "Cognate analysis", "Cognate multi-language analysis", "Cognate multi-language reconstruction", "Cognate multi-language suggestions", "Cognate reconstruction", "Cognate suggestions":
![Снимок экрана 2022-08-24 в 15 43 32](https://user-images.githubusercontent.com/90451645/186421369-a21621cc-8b5e-4a06-bfe1-ccadbd605e89.png)

**Comment by nataliauvarova** [comment]
Done

**Comment by vmonakhov** [comment]
Covered in tests/test_localization.py
