### ISSUE TITLE
Not completely clear map search results indication

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#892]
When search returns lexical entries of dictionaries without metadata location, e.g. when searching for "сабельник" from http://lingvodoc.ispras.ru/dictionary/5645/1/perspective/5645/2/view, the search reports "Found 0 results on map":
![image](https://user-images.githubusercontent.com/2802467/196616113-eb149a85-8ac6-4044-83c3-e063c893eb7a.png)

While this is technically true, it may be misleading, leading to misunderstanding that there are actually no results at all.

We should make a more clear search results indication, so that even when we don't have any results on the map, it's immediately obvious that we still have results in such cases.

**Comment by myrix** [comment]
Implemented, we now indicate both how many results were found in total and how many are displayed in locations on the map:
![image](https://user-images.githubusercontent.com/2802467/196620526-40db6d87-8690-48de-b9b7-c2886f7e7e9f.png)

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_search.py
