### ISSUE TITLE
The text goes to the borders of the block

### ISSUE THREAD

**Issue by nataliauvarova** [ispras/lingvodoc-react#893]
The text goes to the borders of the block:

<img width="584" alt="Снимок экрана 2022-10-18 в 13 11 10" src="https://user-images.githubusercontent.com/90451645/196749615-46d0d2f1-be2f-4941-aeef-b76cb5ac1a8c.png">

http://lingvodoc.ru/dictionary/284/4/perspective/284/5/publish

**Comment by nataliauvarova** [comment]
Done

**Comment by vmonakhov** [comment]
Verified. Now text in tooltips is multiline.
