### ISSUE TITLE
Parsing of file кэпсээн, 2 угуу.odt failed: An error occured during Apertium parser process running

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#901]
Upload [кэпсээн, 2 угуу.odt](https://github.com/ispras/lingvodoc-react/files/10050563/2.odt) file to a corpus, try to parse it with a "Парсер якутского языка Apertium (моноязыковой)" parser, an error:
![image](https://user-images.githubusercontent.com/2802467/202922992-dabe9b03-3538-48d1-82d6-54ea43bd15a2.png)

**Comment by myrix** [comment]
Fixed.

The problem, as Andrey Klochko helpfully suggested, was because of a quote `"` in the file, which tripped up the parsing process due to the way processed file contents are supplied to the parser, via the `echo "<contents>" | apertium ...` pipe.

Changed it to supply the processed contents via an intermediate file, as `cat "<contents_file_path>" | apertium ...`, and now it works ok.

**Comment by vmonakhov** [comment]
Covered in tests/test_parser_reparsing.py (upload_and_apply_parser)
FAILED

**Comment by vmonakhov** [comment]
The same issue is for bashkirian parser [bak.odt](https://github.com/ispras/lingvodoc-react/files/10518538/bak.odt)

**Comment by myrix** [comment]
Failed to reproduce, both [кэпсээн, 2 угуу.odt](https://github.com/ispras/lingvodoc-react/files/10050563/2.odt) and [bak.odt](https://github.com/ispras/lingvodoc-react/files/10518538/bak.odt) parse ok, both locally and on http://10.100.198.233:
![image](https://user-images.githubusercontent.com/2802467/215085738-500f0a47-014e-4933-a6fd-8c96a6ccc985.png)
![image](https://user-images.githubusercontent.com/2802467/215085752-455193a8-a13a-46b6-b6ea-bbbd55a56444.png)

@vmonakhov Please supply instructions to reproduce, or, better, a video recording.

**Comment by vmonakhov** [comment]
Actually, external data for parsers must be placed in /opt/apertium/ and mounted to the docker container.
But I had no this data in the right place. The issue is not reproduced and should be closed.

![2023-01-27_15-44-05](https://user-images.githubusercontent.com/18721530/215090597-39de394b-9a4b-4a0d-ac8f-0c94cda2b4b3.png)
