### ISSUE TITLE
Update valency data error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#904]
Open valency (/valency), choose 'Uralic › Komi › Komi-Zyryan › Corpus of Standard Komi › Литературный коми' perspective, Update valency data, an error:
![image](https://user-images.githubusercontent.com/2802467/204195972-270ff324-06b6-45bf-bf27-d25333eb2c86.png)

**Comment by myrix** [comment]
Fixed.

The problem is 4 instances of malformed (somehow shifted in the middle?) markup:
```
STEM-PRS.3SG", "trans_ru": "печь"}{"lex": "пӧжавны", "gr":" V ,pass, pass_ysj, prs, 3, sg","детали":" пӧжа <с> ь-ӧ", "глянец":"
STEM-PRS.3SG", "trans_ru": "убить"}{"lex": "вины", "gr": "V,pass,prs,3,sg", "parts": "ви<с>ь-ӧ", "gloss": "
STEM-PRS.3PL", "trans_ru": "окликнуть"}{"lex": "корны", "gr": "V,tr,intr,pass,prs,3,pl", "parts": "кор<с>ь-ӧны", "gloss": "
STEM-PRS.3SG", "trans_ru": "ждать"}{"lex": "виччыны", "gr": "V,pass,pass_ysj,prs,3,sg", "parts": "вичч<ыс>ь-ӧ", "gloss": "
```
For now we just skip such cases, through probably the right thing is to report them to the user.

We should also look into overhauling parser markup dialog and related functionality, so that it doesn't just grab the current HTML element tree which has no guarantees of being well-formed and whose unexpected transformations is one of the possible sources of such errors.

**Comment by vmonakhov** [comment]
Covered in tests/test_parser_reparsing.py (test_update_valency_data)
