### ISSUE TITLE
Showing field names along with their types

### ISSUE THREAD

**Issue by nataliauvarova** [ispras/lingvodoc-react#905]
Add display of field types on pages:

![2022-11-30 14 53 45](https://user-images.githubusercontent.com/90451645/204789949-f8c69643-4977-4eda-9eb2-3d05047e1964.jpg)

![2022-11-30 14 53 55](https://user-images.githubusercontent.com/90451645/204789962-9be6a984-15be-4aa8-878f-5a5e5da86ea2.jpg)

![2022-11-30 14 54 01](https://user-images.githubusercontent.com/90451645/204789980-dd5f39dd-8cae-4d4c-90ad-cfc39133650b.jpg)

![2022-11-30 14 54 09](https://user-images.githubusercontent.com/90451645/204790007-a530360d-28cd-4487-abae-ff23a1a5f3b2.jpg)

![2022-11-30 14 54 40](https://user-images.githubusercontent.com/90451645/204790024-cfc66b3f-51dd-4288-93fe-79dec2e26694.jpg)

![2022-11-30 14 54 45](https://user-images.githubusercontent.com/90451645/204790062-778bc5d1-2534-4999-8336-e69c2d0c4738.jpg)

**Comment by myrix** [comment]
Implemented.

**Comment by vmonakhov** [comment]
Covered in tests/test_dictionaries.py
