### ISSUE TITLE
New panel "For grantees and commercial use"

### ISSUE THREAD

**Issue by nataliauvarova** [ispras/lingvodoc-react#910]
New panel "For grantees and commercial use":

![Снимок экрана 2022-12-05 в 17 13 35](https://user-images.githubusercontent.com/90451645/205658526-43f67e06-35aa-4aa2-8d35-34725cb7d407.png)

![Снимок экрана 2022-12-05 в 17 13 46](https://user-images.githubusercontent.com/90451645/205658566-f159fab1-e287-480c-bcd0-acbd00dc9cef.png)

![Снимок экрана 2022-12-05 в 17 13 58](https://user-images.githubusercontent.com/90451645/205658440-8fbff43e-ef0d-40ce-bfd5-8646baac4da3.png)

![Снимок экрана 2022-12-05 в 17 14 28](https://user-images.githubusercontent.com/90451645/205658465-ec0e8652-6af8-4554-a576-7b088f81371d.png)

https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=5017%3A16568&t=mxdx0pVYqsEym78j-0

**Comment by nataliauvarova** [comment]
Done

**Comment by vmonakhov** [comment]
Covered in tests/test_user_sign.py
