### ISSUE TITLE
New link from the panel "For grantees and commercial use"

### ISSUE THREAD

**Issue by nataliauvarova** [ispras/lingvodoc-react#917]
Replace the link with:
https://docs.google.com/forms/d/e/1FAIpQLSd-h0GFww61WmQgJBRYf72s1eFfNPYjx7-ZF0PcCK4cquZ-QQ/viewform

**Comment by nataliauvarova** [comment]
done

**Comment by vmonakhov** [comment]
Covered in tests/test_user_sign.py
