### ISSUE TITLE
Map search: .xslx link bug

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#922]
User reports that with a search for "^\wā" regular expression you can't download search results as .xlsx file.

Open http://lingvodoc.ispras.ru/map_search/b4fvy, click 'XLSX-exported search results' link, 404 Not Found error.

**Comment by myrix** [comment]
Fixed.

The problem was that due to absent filename sanitization regexp was included in the name of the .xlsx file, and consequently in its URL, as is, and the backward slash was causing problems.

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_search.py
