### ISSUE TITLE
Import Starling dictionary: empty dictionary bug

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#923]
Try importing Starling dictionary from [nsamoyedmerged4.csv](https://github.com/ispras/lingvodoc-react/files/10370031/nsamoyedmerged4.csv) in a standard way (User menu -> My files, upload as Starling/CSV, then Home page -> Dashboard -> Import Excel and Starling dictionaries and so on), the resulting dictionary is empty, while the source dictionary is not empty.

**Comment by myrix** [comment]
Fixed, now should work ok.

The problem is that the Lingvodoc Starling converter expects the Starling dictionary to have a NUMBER column, while the aforementioned [nsamoyedmerged4.csv](https://github.com/ispras/lingvodoc-react/files/10370031/nsamoyedmerged4.csv) doesn't have it.

**Comment by vmonakhov** [comment]
Covered in tests/test_dictionaries.py
