### ISSUE TITLE
Parsing documents uploaded to localhost Docker error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#930]
Reported by Vladimir Monakhov.

Start Lingvodoc in a localhost Docker instance, upload a document for parsing (by e.g. opening /dictionary/3648/5/perspective/3648/8/edit corpus, downloading an existing document and re-uploading it in the same corpus), try to parse it, an error:
![photo_2023-01-20_19-24-11](https://user-images.githubusercontent.com/2802467/213847883-bf213808-394a-427b-bcfe-1671e8f09b57.jpg)

Looks like the problem is caused by the backend failing to download a localhost link of the form "http://localhost/objects/entity/graphql_files/5296/2/Данилов Г. Гурт пумын.odt" inside the backend container, and simple switching from localhost to 127.0.0.1 does not help.

IIRC there were some similar problems reported by Andrey Klochko some time ago.

The proper way to resolve the problem would probably to switch Lingvodoc docker-compose to host networking (see https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach, https://docs.docker.com/network/host/, https://docs.docker.com/compose/networking/), but it would be a rather drastic change giving all this isolation away, so I'm not sure we should go for it.

**Comment by myrix** [comment]
Fixed by implementing a workaround, by making the parsing part check in a standard way if it can read a locally-uploaded file from the disk instead of downloading it from the network.

The issue of localhost Docker file downloads from inside the backend container per se remains unresolved for now.

**Comment by vmonakhov** [comment]
Covered in tests/test_parser_reparsing.py (upload_and_apply_parser)
