### ISSUE TITLE
/map_search: Result tree is not updated immediately

### ISSUE THREAD

**Issue by vmonakhov** [ispras/lingvodoc-react#931]
/map_search
- type "ромашка" for search. Result: "Found 3 results, 3 on map"; tree is proper (ok)
- in the same window type "ромашки", press Search. Result: (0); no tree (ok)
- type "ромашка"again, press Search. Result: Found 3 but no any tree to navigate (not ok)

![2023-01-24_13-30-37](https://user-images.githubusercontent.com/18721530/214270807-273eb882-94ef-4948-8d4a-bf53cb60b758.png)

- press 'Get link to search result', click the link. The tree has appeared (seems good)
- type "ромашки". Result: (0) but the tree is stil visible (not ok)

![2023-01-24_13-32-11](https://user-images.githubusercontent.com/18721530/214270814-965c1b6f-cc07-46bb-8c06-291cc69ba33e.png)

**Comment by vmonakhov** [comment]
Related with #892

**Comment by nataliauvarova** [comment]
fixed

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_search_03.py
