### ISSUE TITLE
/map_search: Results for empty string search 

### ISSUE THREAD

**Issue by vmonakhov** [ispras/lingvodoc-react#932]
/map_search
It's possible to search for an empty string, many entries were found.
I think it's better to disable Search button if the input string is empty.  

![2023-01-24_15-12-31](https://user-images.githubusercontent.com/18721530/214288821-b7406eb1-6f57-4876-a904-5a471b326ae8.png)

**Comment by myrix** [comment]
@vmonakhov

See #826, currently full string search with an empty string is allowed, it can be used to search for exactly empty entities, which can make sense with additional filters or just to locate empty entities for e.g. deletion.

Open empty searches, like search for an empty substring or for an empty regular expressions, are disallowed.

So not a issue.
