### ISSUE TITLE
Cognate multi-language analysis dialog bug

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#933]
Open /dictionary/524/4/perspective/524/5/view, Tools -> Cognate multi-language analysis, the dialog gets an error during initialization and hangs:
![image](https://user-images.githubusercontent.com/2802467/214933598-51092790-12af-46f7-b8a7-15c6a230ffe3.png)
![image](https://user-images.githubusercontent.com/2802467/214933608-d8b6ecca-db2a-48d8-82b1-4e7a6a133b17.png)

**Comment by myrix** [comment]
Fixed, now opens ok.

**Comment by vmonakhov** [comment]
Covered in tests/test_cognate_multi_analysis.py
