### ISSUE TITLE
/map_search: AND mode, field type = empty -> GraphQL error

### ISSUE THREAD

**Issue by vmonakhov** [ispras/lingvodoc-react#939]
/map_search: 
select AND mode, field type = empty, type some word to search, click Search
-> GraphQL error (the same with Production version)

![2023-02-08_14-29-32 (2)](https://user-images.githubusercontent.com/18721530/217522762-f159aa59-4aad-4b98-bb53-9dcf4611be4a.png)

**Comment by myrix** [comment]
Fixed.
