### ISSUE TITLE
New design for the modal window "Create language"

### ISSUE THREAD

**Issue by nataliauvarova** [ispras/lingvodoc-react#942]
New design for the modal window "Create language" 
on the page /languages

https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=5575%3A12915&t=RyuYytS0Wpat7weN-0

![Снимок экрана 2023-02-08 в 17 41 47](https://user-images.githubusercontent.com/90451645/217562271-6a015476-0488-4c79-ab91-193ed5a1f012.png)

**Comment by HavreLoic** [comment]
Hi @nataliauvarova is this issue still open? 
I will like to help if necessary

**Comment by nataliauvarova** [comment]
done
