### ISSUE TITLE
Cognate analysis/reconstruction/suggestions scrollbar

### ISSUE THREAD

**Issue by vmonakhov** [ispras/lingvodoc-react#947]
Not obvious scrolling of the modal window for 'Cognate analysis/reconstruction/suggestions' if mouse **wheel does not work**. The scrollbar is placed somewhere outside the window. But the result of the procedure is scrolled by another scrollbar inside the same window. It sounds like something not serious, but I myself met this and it's confusing.

- open /dictionary/2059/5674/perspective/2059/5675/view
- click Tools->Cognate analysis, Compute

![2023-02-20_16-40-26](https://user-images.githubusercontent.com/18721530/222416344-92a55387-50d9-4874-aad7-1210101601aa.png)
![2023-03-02_14-45-52](https://user-images.githubusercontent.com/18721530/222419972-442ae140-8218-4180-a4a0-654fe1a72a04.png)

**Comment by nataliauvarova** [comment]
Fixed
