### ISSUE TITLE
All Cognates and Phonologies modal windows are too wide 

### ISSUE THREAD

**Issue by vmonakhov** [ispras/lingvodoc-react#949]
- Open some dictionary
- Click Tools -> Cognate analysis (or any other Cognate-). 
Note that the modal window fills about 90% of the main window width. The same is for Tools -> Phonology.

![2023-03-09_13-54-41](https://user-images.githubusercontent.com/18721530/224006420-008d558a-2c8f-47e1-ba58-d7386b944915.png)

The different (correct?) design is for Tools -> Phonemic analysis

![2023-03-09_13-58-48](https://user-images.githubusercontent.com/18721530/224006900-46d48a8a-cafc-469a-9cf3-16f9e04424be.png)

**Comment by myrix** [comment]
@nataliauvarova 

For various Cognate... tools this is as expected, as they require selection of frequently many dictionaries with sometimes quite long names, and cognate analysis results may show etymological distance graphs which are better shown in full page width.

So better to leave Cognate... dialogs as full-width.

Though perhaps there is merit in discussing if various Cognate... tools should actually be displayed in separate pages and not just modal dialogs.

Phonology on the other hand, yeah, would probably be better with less width.

**Comment by nataliauvarova** [comment]
> So better to leave Cognate... dialogs as full-width.

agree

**Comment by nataliauvarova** [comment]
> Phonology on the other hand, yeah, would probably be better with less width.

agree

**Comment by nataliauvarova** [comment]
Done
