### ISSUE TITLE
Memory leak after multiple search

### ISSUE THREAD

**Issue by vmonakhov** [ispras/lingvodoc-react#950]
- Run search for some word using the test 'test_memory_heapsize' from tests/test_tools_search_03.py (100 iterations)
- Stop the test just before the end (e.g. using breakpoint)
- Open 'Memory' dialog for the working web page, press 'Trash can' button to invoke GC and remember the heap size value

![2023-03-10_17-21-21](https://user-images.githubusercontent.com/18721530/224340502-7aac4028-d026-40dd-a109-70c94554e5f8.png)

- Leave the page opened without activity for an hour or longer.
- Again press 'Trash can' and note that the heap size increased notedly after the last manual GC.

Note: After the page reloading memory leak stops. So the regular requests for tasks are not the cause.
Listeners amount is not the cause too.

**Comment by myrix** [comment]
Possible duplicate: #154

**Comment by nataliauvarova** [comment]
Done
