### ISSUE TITLE
Merge suggestions: 'Select all' and 'Merge selected' don't work

### ISSUE THREAD

**Issue by vmonakhov** [ispras/lingvodoc-react#951]
- Open /dictionary/5546/2725/perspective/5546/2726/merge
- Press View Suggestions
- Try to press 'Select all on current page' and 'Merge selected on current page'
Nothing happened, the green button just became white.

![2023-03-12_20-27-48 (2)](https://user-images.githubusercontent.com/18721530/224561967-22c6aacb-0100-485e-b413-0469467f1af7.png)

UPD: It works for several groups, but not for single group

**Comment by nataliauvarova** [comment]
Done

**Comment by vmonakhov** [comment]
Verified, works good. Can't be covered because such test is reproducible for certain perspective only once.
