### ISSUE TITLE
/map_search: search tabs strange behaviour

### ISSUE THREAD

**Issue by vmonakhov** [ispras/lingvodoc-react#972]
/map_search
Press [+] button many times to add search tabs
Note that search tabs placed outside main form and even outside the page without any horizontal scroll bar.
  
![2023-04-07_17-25-35](https://user-images.githubusercontent.com/18721530/230626133-e7622f3f-76ed-44ab-947d-d4e0cb1088ce.png)

**Comment by nataliauvarova** [comment]
Done

**Comment by vmonakhov** [comment]
Verified.
Covered in tests/test_tools_search_03.py
